// Verilated -*- C++ -*-
// DESCRIPTION: Verilator output: Symbol table implementation internals

#include "Vtop__Syms.h"
#include "Vtop.h"
#include "Vtop___024root.h"

// FUNCTIONS
Vtop__Syms::~Vtop__Syms()
{

    // Tear down scope hierarchy
    __Vhier.remove(0, &__Vscope_fetch_unit);
    __Vhier.remove(&__Vscope_fetch_unit, &__Vscope_fetch_unit__addressFifo);
    __Vhier.remove(&__Vscope_fetch_unit, &__Vscope_fetch_unit__instrFifo);
    __Vhier.remove(&__Vscope_fetch_unit, &__Vscope_fetch_unit__instr_pop_valid_popc);
    __Vhier.remove(&__Vscope_fetch_unit, &__Vscope_fetch_unit__instr_push_valid_vec_popc);
    __Vhier.remove(&__Vscope_fetch_unit, &__Vscope_fetch_unit__rvcDecompressor_2);
    __Vhier.remove(&__Vscope_fetch_unit, &__Vscope_fetch_unit__rvcDecompressor_3);
    __Vhier.remove(&__Vscope_fetch_unit, &__Vscope_fetch_unit__trailone_index_0);
    __Vhier.remove(&__Vscope_fetch_unit, &__Vscope_fetch_unit__trailone_index_1);
    __Vhier.remove(&__Vscope_fetch_unit, &__Vscope_fetch_unit__trailone_index_2);
    __Vhier.remove(&__Vscope_fetch_unit, &__Vscope_fetch_unit__trailone_index_3);
    __Vhier.remove(&__Vscope_fetch_unit, &__Vscope_fetch_unit__validNumFifo);

}

Vtop__Syms::Vtop__Syms(VerilatedContext* contextp, const char* namep, Vtop* modelp)
    : VerilatedSyms{contextp}
    // Setup internal state of the Syms class
    , __Vm_modelp{modelp}
    // Setup module instances
    , TOP{this, namep}
{
    // Configure time unit / time precision
    _vm_contextp__->timeunit(-9);
    _vm_contextp__->timeprecision(-12);
    // Setup each module's pointers to their submodules
    // Setup each module's pointer back to symbol table (for public functions)
    TOP.__Vconfigure(true);
    // Setup scopes
    __Vscope_TOP.configure(this, name(), "TOP", "TOP", 0, VerilatedScope::SCOPE_OTHER);
    __Vscope_fetch_unit.configure(this, name(), "fetch_unit", "fetch_unit", -9, VerilatedScope::SCOPE_MODULE);
    __Vscope_fetch_unit__addressFifo.configure(this, name(), "fetch_unit.addressFifo", "addressFifo", -9, VerilatedScope::SCOPE_MODULE);
    __Vscope_fetch_unit__instrFifo.configure(this, name(), "fetch_unit.instrFifo", "instrFifo", -9, VerilatedScope::SCOPE_MODULE);
    __Vscope_fetch_unit__instr_pop_valid_popc.configure(this, name(), "fetch_unit.instr_pop_valid_popc", "instr_pop_valid_popc", -9, VerilatedScope::SCOPE_MODULE);
    __Vscope_fetch_unit__instr_push_valid_vec_popc.configure(this, name(), "fetch_unit.instr_push_valid_vec_popc", "instr_push_valid_vec_popc", -9, VerilatedScope::SCOPE_MODULE);
    __Vscope_fetch_unit__rvcDecompressor_2.configure(this, name(), "fetch_unit.rvcDecompressor_2", "rvcDecompressor_2", -9, VerilatedScope::SCOPE_MODULE);
    __Vscope_fetch_unit__rvcDecompressor_3.configure(this, name(), "fetch_unit.rvcDecompressor_3", "rvcDecompressor_3", -9, VerilatedScope::SCOPE_MODULE);
    __Vscope_fetch_unit__trailone_index_0.configure(this, name(), "fetch_unit.trailone_index_0", "trailone_index_0", -9, VerilatedScope::SCOPE_MODULE);
    __Vscope_fetch_unit__trailone_index_1.configure(this, name(), "fetch_unit.trailone_index_1", "trailone_index_1", -9, VerilatedScope::SCOPE_MODULE);
    __Vscope_fetch_unit__trailone_index_2.configure(this, name(), "fetch_unit.trailone_index_2", "trailone_index_2", -9, VerilatedScope::SCOPE_MODULE);
    __Vscope_fetch_unit__trailone_index_3.configure(this, name(), "fetch_unit.trailone_index_3", "trailone_index_3", -9, VerilatedScope::SCOPE_MODULE);
    __Vscope_fetch_unit__validNumFifo.configure(this, name(), "fetch_unit.validNumFifo", "validNumFifo", -9, VerilatedScope::SCOPE_MODULE);

    // Set up scope hierarchy
    __Vhier.add(0, &__Vscope_fetch_unit);
    __Vhier.add(&__Vscope_fetch_unit, &__Vscope_fetch_unit__addressFifo);
    __Vhier.add(&__Vscope_fetch_unit, &__Vscope_fetch_unit__instrFifo);
    __Vhier.add(&__Vscope_fetch_unit, &__Vscope_fetch_unit__instr_pop_valid_popc);
    __Vhier.add(&__Vscope_fetch_unit, &__Vscope_fetch_unit__instr_push_valid_vec_popc);
    __Vhier.add(&__Vscope_fetch_unit, &__Vscope_fetch_unit__rvcDecompressor_2);
    __Vhier.add(&__Vscope_fetch_unit, &__Vscope_fetch_unit__rvcDecompressor_3);
    __Vhier.add(&__Vscope_fetch_unit, &__Vscope_fetch_unit__trailone_index_0);
    __Vhier.add(&__Vscope_fetch_unit, &__Vscope_fetch_unit__trailone_index_1);
    __Vhier.add(&__Vscope_fetch_unit, &__Vscope_fetch_unit__trailone_index_2);
    __Vhier.add(&__Vscope_fetch_unit, &__Vscope_fetch_unit__trailone_index_3);
    __Vhier.add(&__Vscope_fetch_unit, &__Vscope_fetch_unit__validNumFifo);

    // Setup export functions
    for (int __Vfinal = 0; __Vfinal < 2; ++__Vfinal) {
        __Vscope_TOP.varInsert(__Vfinal,"clk", &(TOP.clk), false, VLVT_UINT8,VLVD_IN|VLVF_PUB_RW,0);
        __Vscope_TOP.varInsert(__Vfinal,"core_en", &(TOP.core_en), false, VLVT_UINT8,VLVD_IN|VLVF_PUB_RW,0);
        __Vscope_TOP.varInsert(__Vfinal,"fetchStage_flush", &(TOP.fetchStage_flush), false, VLVT_UINT8,VLVD_IN|VLVF_PUB_RW,0);
        __Vscope_TOP.varInsert(__Vfinal,"fetchStage_isDone", &(TOP.fetchStage_isDone), false, VLVT_UINT8,VLVD_IN|VLVF_PUB_RW,0);
        __Vscope_TOP.varInsert(__Vfinal,"fetchStage_isReady", &(TOP.fetchStage_isReady), false, VLVT_UINT8,VLVD_OUT|VLVF_PUB_RW,0);
        __Vscope_TOP.varInsert(__Vfinal,"ibus_cmd_payload_address", &(TOP.ibus_cmd_payload_address), false, VLVT_UINT32,VLVD_OUT|VLVF_PUB_RW,1 ,31,0);
        __Vscope_TOP.varInsert(__Vfinal,"ibus_cmd_ready", &(TOP.ibus_cmd_ready), false, VLVT_UINT8,VLVD_IN|VLVF_PUB_RW,0);
        __Vscope_TOP.varInsert(__Vfinal,"ibus_cmd_valid", &(TOP.ibus_cmd_valid), false, VLVT_UINT8,VLVD_OUT|VLVF_PUB_RW,0);
        __Vscope_TOP.varInsert(__Vfinal,"ibus_rsp_payload_rdata", &(TOP.ibus_rsp_payload_rdata), false, VLVT_UINT64,VLVD_IN|VLVF_PUB_RW,1 ,63,0);
        __Vscope_TOP.varInsert(__Vfinal,"ibus_rsp_ready", &(TOP.ibus_rsp_ready), false, VLVT_UINT8,VLVD_OUT|VLVF_PUB_RW,0);
        __Vscope_TOP.varInsert(__Vfinal,"ibus_rsp_valid", &(TOP.ibus_rsp_valid), false, VLVT_UINT8,VLVD_IN|VLVF_PUB_RW,0);
        __Vscope_TOP.varInsert(__Vfinal,"if2id_itf_0_instr_data", &(TOP.if2id_itf_0_instr_data), false, VLVT_UINT32,VLVD_OUT|VLVF_PUB_RW,1 ,31,0);
        __Vscope_TOP.varInsert(__Vfinal,"if2id_itf_0_instr_pc", &(TOP.if2id_itf_0_instr_pc), false, VLVT_UINT32,VLVD_OUT|VLVF_PUB_RW,1 ,31,0);
        __Vscope_TOP.varInsert(__Vfinal,"if2id_itf_0_valid", &(TOP.if2id_itf_0_valid), false, VLVT_UINT8,VLVD_OUT|VLVF_PUB_RW,0);
        __Vscope_TOP.varInsert(__Vfinal,"if2id_itf_1_instr_data", &(TOP.if2id_itf_1_instr_data), false, VLVT_UINT32,VLVD_OUT|VLVF_PUB_RW,1 ,31,0);
        __Vscope_TOP.varInsert(__Vfinal,"if2id_itf_1_instr_pc", &(TOP.if2id_itf_1_instr_pc), false, VLVT_UINT32,VLVD_OUT|VLVF_PUB_RW,1 ,31,0);
        __Vscope_TOP.varInsert(__Vfinal,"if2id_itf_1_valid", &(TOP.if2id_itf_1_valid), false, VLVT_UINT8,VLVD_OUT|VLVF_PUB_RW,0);
        __Vscope_TOP.varInsert(__Vfinal,"pcJumpTarget_payload", &(TOP.pcJumpTarget_payload), false, VLVT_UINT32,VLVD_IN|VLVF_PUB_RW,1 ,31,0);
        __Vscope_TOP.varInsert(__Vfinal,"pcJumpTarget_valid", &(TOP.pcJumpTarget_valid), false, VLVT_UINT8,VLVD_IN|VLVF_PUB_RW,0);
        __Vscope_TOP.varInsert(__Vfinal,"pcPredicted_payload", &(TOP.pcPredicted_payload), false, VLVT_UINT32,VLVD_IN|VLVF_PUB_RW,1 ,31,0);
        __Vscope_TOP.varInsert(__Vfinal,"pcPredicted_valid", &(TOP.pcPredicted_valid), false, VLVT_UINT8,VLVD_IN|VLVF_PUB_RW,0);
        __Vscope_TOP.varInsert(__Vfinal,"resetn", &(TOP.resetn), false, VLVT_UINT8,VLVD_IN|VLVF_PUB_RW,0);
        __Vscope_fetch_unit.varInsert(__Vfinal,"INVALID", const_cast<void*>(static_cast<const void*>(&(TOP.fetch_unit__DOT__INVALID))), true, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,1,0);
        __Vscope_fetch_unit.varInsert(__Vfinal,"RVC", const_cast<void*>(static_cast<const void*>(&(TOP.fetch_unit__DOT__RVC))), true, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,1,0);
        __Vscope_fetch_unit.varInsert(__Vfinal,"RVH", const_cast<void*>(static_cast<const void*>(&(TOP.fetch_unit__DOT__RVH))), true, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,1,0);
        __Vscope_fetch_unit.varInsert(__Vfinal,"RVL", const_cast<void*>(static_cast<const void*>(&(TOP.fetch_unit__DOT__RVL))), true, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,1,0);
        __Vscope_fetch_unit.varInsert(__Vfinal,"addressFifo_io_flush", &(TOP.fetch_unit__DOT__addressFifo_io_flush), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_fetch_unit.varInsert(__Vfinal,"addressFifo_io_head", &(TOP.fetch_unit__DOT__addressFifo_io_head), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,1 ,31,0);
        __Vscope_fetch_unit.varInsert(__Vfinal,"addressFifo_io_occupancy", &(TOP.fetch_unit__DOT__addressFifo_io_occupancy), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,2,0);
        __Vscope_fetch_unit.varInsert(__Vfinal,"addressFifo_io_pop_payload", &(TOP.fetch_unit__DOT__addressFifo_io_pop_payload), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,1 ,31,0);
        __Vscope_fetch_unit.varInsert(__Vfinal,"addressFifo_io_pop_ready", &(TOP.fetch_unit__DOT__addressFifo_io_pop_ready), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_fetch_unit.varInsert(__Vfinal,"addressFifo_io_pop_valid", &(TOP.fetch_unit__DOT__addressFifo_io_pop_valid), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_fetch_unit.varInsert(__Vfinal,"addressFifo_io_push_ready", &(TOP.fetch_unit__DOT__addressFifo_io_push_ready), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_fetch_unit.varInsert(__Vfinal,"addressFifo_io_push_valid", &(TOP.fetch_unit__DOT__addressFifo_io_push_valid), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_fetch_unit.varInsert(__Vfinal,"addressOffset", &(TOP.fetch_unit__DOT__addressOffset), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,1,0);
        __Vscope_fetch_unit.varInsert(__Vfinal,"clk", &(TOP.fetch_unit__DOT__clk), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_fetch_unit.varInsert(__Vfinal,"core_en", &(TOP.fetch_unit__DOT__core_en), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_fetch_unit.varInsert(__Vfinal,"default_next_pc", &(TOP.fetch_unit__DOT__default_next_pc), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,1 ,31,0);
        __Vscope_fetch_unit.varInsert(__Vfinal,"fetchStage_flush", &(TOP.fetch_unit__DOT__fetchStage_flush), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_fetch_unit.varInsert(__Vfinal,"fetchStage_isDone", &(TOP.fetch_unit__DOT__fetchStage_isDone), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_fetch_unit.varInsert(__Vfinal,"fetchStage_isReady", &(TOP.fetch_unit__DOT__fetchStage_isReady), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_fetch_unit.varInsert(__Vfinal,"fetch_pending", &(TOP.fetch_unit__DOT__fetch_pending), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_fetch_unit.varInsert(__Vfinal,"ibus_cmd_fire", &(TOP.fetch_unit__DOT__ibus_cmd_fire), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_fetch_unit.varInsert(__Vfinal,"ibus_cmd_payload_address", &(TOP.fetch_unit__DOT__ibus_cmd_payload_address), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,1 ,31,0);
        __Vscope_fetch_unit.varInsert(__Vfinal,"ibus_cmd_ready", &(TOP.fetch_unit__DOT__ibus_cmd_ready), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_fetch_unit.varInsert(__Vfinal,"ibus_cmd_valid", &(TOP.fetch_unit__DOT__ibus_cmd_valid), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_fetch_unit.varInsert(__Vfinal,"ibus_rsp_fire", &(TOP.fetch_unit__DOT__ibus_rsp_fire), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_fetch_unit.varInsert(__Vfinal,"ibus_rsp_payload_rdata", &(TOP.fetch_unit__DOT__ibus_rsp_payload_rdata), false, VLVT_UINT64,VLVD_NODIR|VLVF_PUB_RW,1 ,63,0);
        __Vscope_fetch_unit.varInsert(__Vfinal,"ibus_rsp_ready", &(TOP.fetch_unit__DOT__ibus_rsp_ready), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_fetch_unit.varInsert(__Vfinal,"ibus_rsp_valid", &(TOP.fetch_unit__DOT__ibus_rsp_valid), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_fetch_unit.varInsert(__Vfinal,"if2id_itf_0_instr_data", &(TOP.fetch_unit__DOT__if2id_itf_0_instr_data), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,1 ,31,0);
        __Vscope_fetch_unit.varInsert(__Vfinal,"if2id_itf_0_instr_pc", &(TOP.fetch_unit__DOT__if2id_itf_0_instr_pc), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,1 ,31,0);
        __Vscope_fetch_unit.varInsert(__Vfinal,"if2id_itf_0_valid", &(TOP.fetch_unit__DOT__if2id_itf_0_valid), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_fetch_unit.varInsert(__Vfinal,"if2id_itf_1_instr_data", &(TOP.fetch_unit__DOT__if2id_itf_1_instr_data), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,1 ,31,0);
        __Vscope_fetch_unit.varInsert(__Vfinal,"if2id_itf_1_instr_pc", &(TOP.fetch_unit__DOT__if2id_itf_1_instr_pc), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,1 ,31,0);
        __Vscope_fetch_unit.varInsert(__Vfinal,"if2id_itf_1_valid", &(TOP.fetch_unit__DOT__if2id_itf_1_valid), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_fetch_unit.varInsert(__Vfinal,"instrFifo_io_flush", &(TOP.fetch_unit__DOT__instrFifo_io_flush), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_fetch_unit.varInsert(__Vfinal,"instrFifo_io_occupancy", &(TOP.fetch_unit__DOT__instrFifo_io_occupancy), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,3,0);
        __Vscope_fetch_unit.varInsert(__Vfinal,"instrFifo_io_ov_waterline", &(TOP.fetch_unit__DOT__instrFifo_io_ov_waterline), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_fetch_unit.varInsert(__Vfinal,"instrFifo_io_pop_0_payload", &(TOP.fetch_unit__DOT__instrFifo_io_pop_0_payload), false, VLVT_UINT64,VLVD_NODIR|VLVF_PUB_RW,1 ,32,0);
        __Vscope_fetch_unit.varInsert(__Vfinal,"instrFifo_io_pop_0_valid", &(TOP.fetch_unit__DOT__instrFifo_io_pop_0_valid), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_fetch_unit.varInsert(__Vfinal,"instrFifo_io_pop_1_payload", &(TOP.fetch_unit__DOT__instrFifo_io_pop_1_payload), false, VLVT_UINT64,VLVD_NODIR|VLVF_PUB_RW,1 ,32,0);
        __Vscope_fetch_unit.varInsert(__Vfinal,"instrFifo_io_pop_1_valid", &(TOP.fetch_unit__DOT__instrFifo_io_pop_1_valid), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_fetch_unit.varInsert(__Vfinal,"instrFifo_io_push_0_payload", &(TOP.fetch_unit__DOT__instrFifo_io_push_0_payload), false, VLVT_UINT64,VLVD_NODIR|VLVF_PUB_RW,1 ,32,0);
        __Vscope_fetch_unit.varInsert(__Vfinal,"instrFifo_io_push_0_ready", &(TOP.fetch_unit__DOT__instrFifo_io_push_0_ready), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_fetch_unit.varInsert(__Vfinal,"instrFifo_io_push_0_valid", &(TOP.fetch_unit__DOT__instrFifo_io_push_0_valid), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_fetch_unit.varInsert(__Vfinal,"instrFifo_io_push_1_payload", &(TOP.fetch_unit__DOT__instrFifo_io_push_1_payload), false, VLVT_UINT64,VLVD_NODIR|VLVF_PUB_RW,1 ,32,0);
        __Vscope_fetch_unit.varInsert(__Vfinal,"instrFifo_io_push_1_ready", &(TOP.fetch_unit__DOT__instrFifo_io_push_1_ready), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_fetch_unit.varInsert(__Vfinal,"instrFifo_io_push_1_valid", &(TOP.fetch_unit__DOT__instrFifo_io_push_1_valid), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_fetch_unit.varInsert(__Vfinal,"instrFifo_io_push_2_payload", &(TOP.fetch_unit__DOT__instrFifo_io_push_2_payload), false, VLVT_UINT64,VLVD_NODIR|VLVF_PUB_RW,1 ,32,0);
        __Vscope_fetch_unit.varInsert(__Vfinal,"instrFifo_io_push_2_ready", &(TOP.fetch_unit__DOT__instrFifo_io_push_2_ready), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_fetch_unit.varInsert(__Vfinal,"instrFifo_io_push_2_valid", &(TOP.fetch_unit__DOT__instrFifo_io_push_2_valid), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_fetch_unit.varInsert(__Vfinal,"instrFifo_io_push_3_payload", &(TOP.fetch_unit__DOT__instrFifo_io_push_3_payload), false, VLVT_UINT64,VLVD_NODIR|VLVF_PUB_RW,1 ,32,0);
        __Vscope_fetch_unit.varInsert(__Vfinal,"instrFifo_io_push_3_ready", &(TOP.fetch_unit__DOT__instrFifo_io_push_3_ready), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_fetch_unit.varInsert(__Vfinal,"instrFifo_io_push_3_valid", &(TOP.fetch_unit__DOT__instrFifo_io_push_3_valid), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_fetch_unit.varInsert(__Vfinal,"instr_pop_valid", &(TOP.fetch_unit__DOT__instr_pop_valid), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,1,0);
        __Vscope_fetch_unit.varInsert(__Vfinal,"instr_pop_valid_popc_cnt_out", &(TOP.fetch_unit__DOT__instr_pop_valid_popc_cnt_out), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,1,0);
        __Vscope_fetch_unit.varInsert(__Vfinal,"instr_push_valid_vec", &(TOP.fetch_unit__DOT__instr_push_valid_vec), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,3,0);
        __Vscope_fetch_unit.varInsert(__Vfinal,"instr_push_valid_vec_popc_cnt_out", &(TOP.fetch_unit__DOT__instr_push_valid_vec_popc_cnt_out), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,2,0);
        __Vscope_fetch_unit.varInsert(__Vfinal,"instr_slices_0_payload", &(TOP.fetch_unit__DOT__instr_slices_0_payload), false, VLVT_UINT64,VLVD_NODIR|VLVF_PUB_RW,1 ,32,0);
        __Vscope_fetch_unit.varInsert(__Vfinal,"instr_slices_0_valid", &(TOP.fetch_unit__DOT__instr_slices_0_valid), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_fetch_unit.varInsert(__Vfinal,"instr_slices_1_payload", &(TOP.fetch_unit__DOT__instr_slices_1_payload), false, VLVT_UINT64,VLVD_NODIR|VLVF_PUB_RW,1 ,32,0);
        __Vscope_fetch_unit.varInsert(__Vfinal,"instr_slices_1_valid", &(TOP.fetch_unit__DOT__instr_slices_1_valid), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_fetch_unit.varInsert(__Vfinal,"instr_slices_2_payload", &(TOP.fetch_unit__DOT__instr_slices_2_payload), false, VLVT_UINT64,VLVD_NODIR|VLVF_PUB_RW,1 ,32,0);
        __Vscope_fetch_unit.varInsert(__Vfinal,"instr_slices_2_valid", &(TOP.fetch_unit__DOT__instr_slices_2_valid), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_fetch_unit.varInsert(__Vfinal,"instr_slices_3_payload", &(TOP.fetch_unit__DOT__instr_slices_3_payload), false, VLVT_UINT64,VLVD_NODIR|VLVF_PUB_RW,1 ,32,0);
        __Vscope_fetch_unit.varInsert(__Vfinal,"instr_slices_3_valid", &(TOP.fetch_unit__DOT__instr_slices_3_valid), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_fetch_unit.varInsert(__Vfinal,"pc", &(TOP.fetch_unit__DOT__pc), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,1 ,31,0);
        __Vscope_fetch_unit.varInsert(__Vfinal,"pcJumpTarget_payload", &(TOP.fetch_unit__DOT__pcJumpTarget_payload), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,1 ,31,0);
        __Vscope_fetch_unit.varInsert(__Vfinal,"pcJumpTarget_valid", &(TOP.fetch_unit__DOT__pcJumpTarget_valid), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_fetch_unit.varInsert(__Vfinal,"pcPredicted_payload", &(TOP.fetch_unit__DOT__pcPredicted_payload), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,1 ,31,0);
        __Vscope_fetch_unit.varInsert(__Vfinal,"pcPredicted_valid", &(TOP.fetch_unit__DOT__pcPredicted_valid), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_fetch_unit.varInsert(__Vfinal,"pc_pop_offset", &(TOP.fetch_unit__DOT__pc_pop_offset), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,2,0);
        __Vscope_fetch_unit.varInsert(__Vfinal,"pc_step_all_1", &(TOP.fetch_unit__DOT__pc_step_all_1), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,2,0);
        __Vscope_fetch_unit.varInsert(__Vfinal,"pc_step_all_2", &(TOP.fetch_unit__DOT__pc_step_all_2), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,2,0);
        __Vscope_fetch_unit.varInsert(__Vfinal,"real_instr_0", &(TOP.fetch_unit__DOT__real_instr_0), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,1 ,31,0);
        __Vscope_fetch_unit.varInsert(__Vfinal,"real_instr_1", &(TOP.fetch_unit__DOT__real_instr_1), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,1 ,31,0);
        __Vscope_fetch_unit.varInsert(__Vfinal,"resetn", &(TOP.fetch_unit__DOT__resetn), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_fetch_unit.varInsert(__Vfinal,"rvcDecompressor_2_decompInstr_illegal", &(TOP.fetch_unit__DOT__rvcDecompressor_2_decompInstr_illegal), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_fetch_unit.varInsert(__Vfinal,"rvcDecompressor_2_decompInstr_inst", &(TOP.fetch_unit__DOT__rvcDecompressor_2_decompInstr_inst), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,1 ,31,0);
        __Vscope_fetch_unit.varInsert(__Vfinal,"rvcDecompressor_2_i", &(TOP.fetch_unit__DOT__rvcDecompressor_2_i), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,1 ,31,0);
        __Vscope_fetch_unit.varInsert(__Vfinal,"rvcDecompressor_3_decompInstr_illegal", &(TOP.fetch_unit__DOT__rvcDecompressor_3_decompInstr_illegal), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_fetch_unit.varInsert(__Vfinal,"rvcDecompressor_3_decompInstr_inst", &(TOP.fetch_unit__DOT__rvcDecompressor_3_decompInstr_inst), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,1 ,31,0);
        __Vscope_fetch_unit.varInsert(__Vfinal,"rvcDecompressor_3_i", &(TOP.fetch_unit__DOT__rvcDecompressor_3_i), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,1 ,31,0);
        __Vscope_fetch_unit.varInsert(__Vfinal,"slice_valid_vec_0", &(TOP.fetch_unit__DOT__slice_valid_vec_0), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,0,0);
        __Vscope_fetch_unit.varInsert(__Vfinal,"slice_valid_vec_1", &(TOP.fetch_unit__DOT__slice_valid_vec_1), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,0,0);
        __Vscope_fetch_unit.varInsert(__Vfinal,"slice_valid_vec_2", &(TOP.fetch_unit__DOT__slice_valid_vec_2), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,0,0);
        __Vscope_fetch_unit.varInsert(__Vfinal,"slice_valid_vec_3", &(TOP.fetch_unit__DOT__slice_valid_vec_3), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,0,0);
        __Vscope_fetch_unit.varInsert(__Vfinal,"tail_one_index_vec_0", &(TOP.fetch_unit__DOT__tail_one_index_vec_0), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,1,0);
        __Vscope_fetch_unit.varInsert(__Vfinal,"tail_one_index_vec_1", &(TOP.fetch_unit__DOT__tail_one_index_vec_1), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,1,0);
        __Vscope_fetch_unit.varInsert(__Vfinal,"tail_one_index_vec_2", &(TOP.fetch_unit__DOT__tail_one_index_vec_2), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,1,0);
        __Vscope_fetch_unit.varInsert(__Vfinal,"tail_one_index_vec_3", &(TOP.fetch_unit__DOT__tail_one_index_vec_3), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,1,0);
        __Vscope_fetch_unit.varInsert(__Vfinal,"tail_one_matrix_0", &(TOP.fetch_unit__DOT__tail_one_matrix_0), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,3,0);
        __Vscope_fetch_unit.varInsert(__Vfinal,"tail_one_matrix_1", &(TOP.fetch_unit__DOT__tail_one_matrix_1), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,3,0);
        __Vscope_fetch_unit.varInsert(__Vfinal,"tail_one_matrix_2", &(TOP.fetch_unit__DOT__tail_one_matrix_2), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,3,0);
        __Vscope_fetch_unit.varInsert(__Vfinal,"tail_one_matrix_3", &(TOP.fetch_unit__DOT__tail_one_matrix_3), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,3,0);
        __Vscope_fetch_unit.varInsert(__Vfinal,"tail_one_valid_vec_0", &(TOP.fetch_unit__DOT__tail_one_valid_vec_0), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_fetch_unit.varInsert(__Vfinal,"tail_one_valid_vec_1", &(TOP.fetch_unit__DOT__tail_one_valid_vec_1), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_fetch_unit.varInsert(__Vfinal,"tail_one_valid_vec_2", &(TOP.fetch_unit__DOT__tail_one_valid_vec_2), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_fetch_unit.varInsert(__Vfinal,"tail_one_valid_vec_3", &(TOP.fetch_unit__DOT__tail_one_valid_vec_3), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_fetch_unit.varInsert(__Vfinal,"tmp_1", &(TOP.fetch_unit__DOT__tmp_1), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_fetch_unit.varInsert(__Vfinal,"tmp_2", &(TOP.fetch_unit__DOT__tmp_2), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,1,0);
        __Vscope_fetch_unit.varInsert(__Vfinal,"tmp_2_string", &(TOP.fetch_unit__DOT__tmp_2_string), false, VLVT_UINT64,VLVD_NODIR|VLVF_PUB_RW,1 ,55,0);
        __Vscope_fetch_unit.varInsert(__Vfinal,"tmp_3", &(TOP.fetch_unit__DOT__tmp_3), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,1,0);
        __Vscope_fetch_unit.varInsert(__Vfinal,"tmp_3_string", &(TOP.fetch_unit__DOT__tmp_3_string), false, VLVT_UINT64,VLVD_NODIR|VLVF_PUB_RW,1 ,55,0);
        __Vscope_fetch_unit.varInsert(__Vfinal,"tmp_4", &(TOP.fetch_unit__DOT__tmp_4), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,1,0);
        __Vscope_fetch_unit.varInsert(__Vfinal,"tmp_4_string", &(TOP.fetch_unit__DOT__tmp_4_string), false, VLVT_UINT64,VLVD_NODIR|VLVF_PUB_RW,1 ,55,0);
        __Vscope_fetch_unit.varInsert(__Vfinal,"tmp_5", &(TOP.fetch_unit__DOT__tmp_5), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,1,0);
        __Vscope_fetch_unit.varInsert(__Vfinal,"tmp_5_string", &(TOP.fetch_unit__DOT__tmp_5_string), false, VLVT_UINT64,VLVD_NODIR|VLVF_PUB_RW,1 ,55,0);
        __Vscope_fetch_unit.varInsert(__Vfinal,"tmp_if2id_itf_0_instr_pc", &(TOP.fetch_unit__DOT__tmp_if2id_itf_0_instr_pc), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,1 ,31,0);
        __Vscope_fetch_unit.varInsert(__Vfinal,"tmp_if2id_itf_0_instr_pc_1", &(TOP.fetch_unit__DOT__tmp_if2id_itf_0_instr_pc_1), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,1 ,31,0);
        __Vscope_fetch_unit.varInsert(__Vfinal,"tmp_if2id_itf_1_instr_pc", &(TOP.fetch_unit__DOT__tmp_if2id_itf_1_instr_pc), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,1 ,31,0);
        __Vscope_fetch_unit.varInsert(__Vfinal,"tmp_if2id_itf_1_instr_pc_1", &(TOP.fetch_unit__DOT__tmp_if2id_itf_1_instr_pc_1), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,1 ,31,0);
        __Vscope_fetch_unit.varInsert(__Vfinal,"tmp_if2id_itf_1_instr_pc_2", &(TOP.fetch_unit__DOT__tmp_if2id_itf_1_instr_pc_2), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,1 ,31,0);
        __Vscope_fetch_unit.varInsert(__Vfinal,"tmp_instr_slices_0_payload", &(TOP.fetch_unit__DOT__tmp_instr_slices_0_payload), false, VLVT_UINT16,VLVD_NODIR|VLVF_PUB_RW,1 ,15,0);
        __Vscope_fetch_unit.varInsert(__Vfinal,"tmp_io_push_0_payload", &(TOP.fetch_unit__DOT__tmp_io_push_0_payload), false, VLVT_UINT64,VLVD_NODIR|VLVF_PUB_RW,1 ,32,0);
        __Vscope_fetch_unit.varInsert(__Vfinal,"tmp_io_push_0_valid", &(TOP.fetch_unit__DOT__tmp_io_push_0_valid), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_fetch_unit.varInsert(__Vfinal,"tmp_io_push_1_payload", &(TOP.fetch_unit__DOT__tmp_io_push_1_payload), false, VLVT_UINT64,VLVD_NODIR|VLVF_PUB_RW,1 ,32,0);
        __Vscope_fetch_unit.varInsert(__Vfinal,"tmp_io_push_1_valid", &(TOP.fetch_unit__DOT__tmp_io_push_1_valid), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_fetch_unit.varInsert(__Vfinal,"tmp_io_push_2_payload", &(TOP.fetch_unit__DOT__tmp_io_push_2_payload), false, VLVT_UINT64,VLVD_NODIR|VLVF_PUB_RW,1 ,32,0);
        __Vscope_fetch_unit.varInsert(__Vfinal,"tmp_io_push_2_valid", &(TOP.fetch_unit__DOT__tmp_io_push_2_valid), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_fetch_unit.varInsert(__Vfinal,"tmp_io_push_3_payload", &(TOP.fetch_unit__DOT__tmp_io_push_3_payload), false, VLVT_UINT64,VLVD_NODIR|VLVF_PUB_RW,1 ,32,0);
        __Vscope_fetch_unit.varInsert(__Vfinal,"tmp_io_push_3_valid", &(TOP.fetch_unit__DOT__tmp_io_push_3_valid), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_fetch_unit.varInsert(__Vfinal,"tmp_pc_step_all_1", &(TOP.fetch_unit__DOT__tmp_pc_step_all_1), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_fetch_unit.varInsert(__Vfinal,"tmp_pc_step_all_2", &(TOP.fetch_unit__DOT__tmp_pc_step_all_2), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_fetch_unit.varInsert(__Vfinal,"toplevel_instrFifo_io_pop_0_fire", &(TOP.fetch_unit__DOT__toplevel_instrFifo_io_pop_0_fire), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_fetch_unit.varInsert(__Vfinal,"toplevel_instrFifo_io_pop_1_fire", &(TOP.fetch_unit__DOT__toplevel_instrFifo_io_pop_1_fire), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_fetch_unit.varInsert(__Vfinal,"toplevel_instrFifo_io_push_0_fire", &(TOP.fetch_unit__DOT__toplevel_instrFifo_io_push_0_fire), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_fetch_unit.varInsert(__Vfinal,"trailone_index_0_cnt_out", &(TOP.fetch_unit__DOT__trailone_index_0_cnt_out), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,2,0);
        __Vscope_fetch_unit.varInsert(__Vfinal,"trailone_index_1_cnt_out", &(TOP.fetch_unit__DOT__trailone_index_1_cnt_out), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,2,0);
        __Vscope_fetch_unit.varInsert(__Vfinal,"trailone_index_2_cnt_out", &(TOP.fetch_unit__DOT__trailone_index_2_cnt_out), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,2,0);
        __Vscope_fetch_unit.varInsert(__Vfinal,"trailone_index_3_cnt_out", &(TOP.fetch_unit__DOT__trailone_index_3_cnt_out), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,2,0);
        __Vscope_fetch_unit.varInsert(__Vfinal,"validNumFifo_flush", &(TOP.fetch_unit__DOT__validNumFifo_flush), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_fetch_unit.varInsert(__Vfinal,"validNumFifo_head", &(TOP.fetch_unit__DOT__validNumFifo_head), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,2,0);
        __Vscope_fetch_unit.varInsert(__Vfinal,"validNumFifo_occupancy", &(TOP.fetch_unit__DOT__validNumFifo_occupancy), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,2,0);
        __Vscope_fetch_unit.varInsert(__Vfinal,"validNumFifo_pop_pop_out_data", &(TOP.fetch_unit__DOT__validNumFifo_pop_pop_out_data), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,2,0);
        __Vscope_fetch_unit.varInsert(__Vfinal,"validNumFifo_pop_pop_real", &(TOP.fetch_unit__DOT__validNumFifo_pop_pop_real), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_fetch_unit.varInsert(__Vfinal,"validNumFifo_pop_pop_req_num", &(TOP.fetch_unit__DOT__validNumFifo_pop_pop_req_num), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,2,0);
        __Vscope_fetch_unit.varInsert(__Vfinal,"validNumFifo_pop_ready", &(TOP.fetch_unit__DOT__validNumFifo_pop_ready), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_fetch_unit.varInsert(__Vfinal,"validNumFifo_pop_valid", &(TOP.fetch_unit__DOT__validNumFifo_pop_valid), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_fetch_unit.varInsert(__Vfinal,"validNumFifo_push_payload", &(TOP.fetch_unit__DOT__validNumFifo_push_payload), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,2,0);
        __Vscope_fetch_unit.varInsert(__Vfinal,"validNumFifo_push_ready", &(TOP.fetch_unit__DOT__validNumFifo_push_ready), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_fetch_unit.varInsert(__Vfinal,"validNumFifo_push_valid", &(TOP.fetch_unit__DOT__validNumFifo_push_valid), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_fetch_unit.varInsert(__Vfinal,"valid_instr_slice_0", &(TOP.fetch_unit__DOT__valid_instr_slice_0), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_fetch_unit.varInsert(__Vfinal,"valid_instr_slice_1", &(TOP.fetch_unit__DOT__valid_instr_slice_1), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_fetch_unit.varInsert(__Vfinal,"valid_instr_slice_2", &(TOP.fetch_unit__DOT__valid_instr_slice_2), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_fetch_unit.varInsert(__Vfinal,"valid_instr_slice_3", &(TOP.fetch_unit__DOT__valid_instr_slice_3), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_fetch_unit__addressFifo.varInsert(__Vfinal,"clk", &(TOP.fetch_unit__DOT__addressFifo__DOT__clk), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_fetch_unit__addressFifo.varInsert(__Vfinal,"empty", &(TOP.fetch_unit__DOT__addressFifo__DOT__empty), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_fetch_unit__addressFifo.varInsert(__Vfinal,"full", &(TOP.fetch_unit__DOT__addressFifo__DOT__full), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_fetch_unit__addressFifo.varInsert(__Vfinal,"io_flush", &(TOP.fetch_unit__DOT__addressFifo__DOT__io_flush), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_fetch_unit__addressFifo.varInsert(__Vfinal,"io_head", &(TOP.fetch_unit__DOT__addressFifo__DOT__io_head), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,1 ,31,0);
        __Vscope_fetch_unit__addressFifo.varInsert(__Vfinal,"io_occupancy", &(TOP.fetch_unit__DOT__addressFifo__DOT__io_occupancy), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,2,0);
        __Vscope_fetch_unit__addressFifo.varInsert(__Vfinal,"io_pop_payload", &(TOP.fetch_unit__DOT__addressFifo__DOT__io_pop_payload), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,1 ,31,0);
        __Vscope_fetch_unit__addressFifo.varInsert(__Vfinal,"io_pop_ready", &(TOP.fetch_unit__DOT__addressFifo__DOT__io_pop_ready), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_fetch_unit__addressFifo.varInsert(__Vfinal,"io_pop_valid", &(TOP.fetch_unit__DOT__addressFifo__DOT__io_pop_valid), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_fetch_unit__addressFifo.varInsert(__Vfinal,"io_push_payload", &(TOP.fetch_unit__DOT__addressFifo__DOT__io_push_payload), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,1 ,31,0);
        __Vscope_fetch_unit__addressFifo.varInsert(__Vfinal,"io_push_ready", &(TOP.fetch_unit__DOT__addressFifo__DOT__io_push_ready), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_fetch_unit__addressFifo.varInsert(__Vfinal,"io_push_valid", &(TOP.fetch_unit__DOT__addressFifo__DOT__io_push_valid), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_fetch_unit__addressFifo.varInsert(__Vfinal,"popPtr_value", &(TOP.fetch_unit__DOT__addressFifo__DOT__popPtr_value), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,1,0);
        __Vscope_fetch_unit__addressFifo.varInsert(__Vfinal,"popPtr_valueNext", &(TOP.fetch_unit__DOT__addressFifo__DOT__popPtr_valueNext), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,1,0);
        __Vscope_fetch_unit__addressFifo.varInsert(__Vfinal,"popPtr_willClear", &(TOP.fetch_unit__DOT__addressFifo__DOT__popPtr_willClear), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_fetch_unit__addressFifo.varInsert(__Vfinal,"popPtr_willIncrement", &(TOP.fetch_unit__DOT__addressFifo__DOT__popPtr_willIncrement), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_fetch_unit__addressFifo.varInsert(__Vfinal,"popPtr_willOverflow", &(TOP.fetch_unit__DOT__addressFifo__DOT__popPtr_willOverflow), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_fetch_unit__addressFifo.varInsert(__Vfinal,"popPtr_willOverflowIfInc", &(TOP.fetch_unit__DOT__addressFifo__DOT__popPtr_willOverflowIfInc), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_fetch_unit__addressFifo.varInsert(__Vfinal,"popping", &(TOP.fetch_unit__DOT__addressFifo__DOT__popping), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_fetch_unit__addressFifo.varInsert(__Vfinal,"ptrDif", &(TOP.fetch_unit__DOT__addressFifo__DOT__ptrDif), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,1,0);
        __Vscope_fetch_unit__addressFifo.varInsert(__Vfinal,"ptrMatch", &(TOP.fetch_unit__DOT__addressFifo__DOT__ptrMatch), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_fetch_unit__addressFifo.varInsert(__Vfinal,"pushPtr_value", &(TOP.fetch_unit__DOT__addressFifo__DOT__pushPtr_value), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,1,0);
        __Vscope_fetch_unit__addressFifo.varInsert(__Vfinal,"pushPtr_valueNext", &(TOP.fetch_unit__DOT__addressFifo__DOT__pushPtr_valueNext), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,1,0);
        __Vscope_fetch_unit__addressFifo.varInsert(__Vfinal,"pushPtr_willClear", &(TOP.fetch_unit__DOT__addressFifo__DOT__pushPtr_willClear), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_fetch_unit__addressFifo.varInsert(__Vfinal,"pushPtr_willIncrement", &(TOP.fetch_unit__DOT__addressFifo__DOT__pushPtr_willIncrement), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_fetch_unit__addressFifo.varInsert(__Vfinal,"pushPtr_willOverflow", &(TOP.fetch_unit__DOT__addressFifo__DOT__pushPtr_willOverflow), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_fetch_unit__addressFifo.varInsert(__Vfinal,"pushPtr_willOverflowIfInc", &(TOP.fetch_unit__DOT__addressFifo__DOT__pushPtr_willOverflowIfInc), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_fetch_unit__addressFifo.varInsert(__Vfinal,"pushing", &(TOP.fetch_unit__DOT__addressFifo__DOT__pushing), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_fetch_unit__addressFifo.varInsert(__Vfinal,"readed", &(TOP.fetch_unit__DOT__addressFifo__DOT__readed), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,1 ,31,0);
        __Vscope_fetch_unit__addressFifo.varInsert(__Vfinal,"resetn", &(TOP.fetch_unit__DOT__addressFifo__DOT__resetn), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_fetch_unit__addressFifo.varInsert(__Vfinal,"risingOccupancy", &(TOP.fetch_unit__DOT__addressFifo__DOT__risingOccupancy), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_fetch_unit__addressFifo.varInsert(__Vfinal,"tmp_1", &(TOP.fetch_unit__DOT__addressFifo__DOT__tmp_1), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,3,0);
        __Vscope_fetch_unit__addressFifo.varInsert(__Vfinal,"tmp_popPtr_valueNext", &(TOP.fetch_unit__DOT__addressFifo__DOT__tmp_popPtr_valueNext), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,1,0);
        __Vscope_fetch_unit__addressFifo.varInsert(__Vfinal,"tmp_popPtr_valueNext_1", &(TOP.fetch_unit__DOT__addressFifo__DOT__tmp_popPtr_valueNext_1), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,0,0);
        __Vscope_fetch_unit__addressFifo.varInsert(__Vfinal,"tmp_pushPtr_valueNext", &(TOP.fetch_unit__DOT__addressFifo__DOT__tmp_pushPtr_valueNext), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,1,0);
        __Vscope_fetch_unit__addressFifo.varInsert(__Vfinal,"tmp_pushPtr_valueNext_1", &(TOP.fetch_unit__DOT__addressFifo__DOT__tmp_pushPtr_valueNext_1), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,0,0);
        __Vscope_fetch_unit__addressFifo.varInsert(__Vfinal,"tmp_readed", &(TOP.fetch_unit__DOT__addressFifo__DOT__tmp_readed), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,1 ,31,0);
        __Vscope_fetch_unit__addressFifo.varInsert(__Vfinal,"vec_0", &(TOP.fetch_unit__DOT__addressFifo__DOT__vec_0), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,1 ,31,0);
        __Vscope_fetch_unit__addressFifo.varInsert(__Vfinal,"vec_1", &(TOP.fetch_unit__DOT__addressFifo__DOT__vec_1), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,1 ,31,0);
        __Vscope_fetch_unit__addressFifo.varInsert(__Vfinal,"vec_2", &(TOP.fetch_unit__DOT__addressFifo__DOT__vec_2), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,1 ,31,0);
        __Vscope_fetch_unit__addressFifo.varInsert(__Vfinal,"vec_3", &(TOP.fetch_unit__DOT__addressFifo__DOT__vec_3), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,1 ,31,0);
        __Vscope_fetch_unit__instrFifo.varInsert(__Vfinal,"clk", &(TOP.fetch_unit__DOT__instrFifo__DOT__clk), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_fetch_unit__instrFifo.varInsert(__Vfinal,"dec_num", &(TOP.fetch_unit__DOT__instrFifo__DOT__dec_num), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,1,0);
        __Vscope_fetch_unit__instrFifo.varInsert(__Vfinal,"empty", &(TOP.fetch_unit__DOT__instrFifo__DOT__empty), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_fetch_unit__instrFifo.varInsert(__Vfinal,"full", &(TOP.fetch_unit__DOT__instrFifo__DOT__full), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_fetch_unit__instrFifo.varInsert(__Vfinal,"inc_num", &(TOP.fetch_unit__DOT__instrFifo__DOT__inc_num), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,2,0);
        __Vscope_fetch_unit__instrFifo.varInsert(__Vfinal,"io_flush", &(TOP.fetch_unit__DOT__instrFifo__DOT__io_flush), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_fetch_unit__instrFifo.varInsert(__Vfinal,"io_occupancy", &(TOP.fetch_unit__DOT__instrFifo__DOT__io_occupancy), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,3,0);
        __Vscope_fetch_unit__instrFifo.varInsert(__Vfinal,"io_ov_waterline", &(TOP.fetch_unit__DOT__instrFifo__DOT__io_ov_waterline), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_fetch_unit__instrFifo.varInsert(__Vfinal,"io_pop_0_payload", &(TOP.fetch_unit__DOT__instrFifo__DOT__io_pop_0_payload), false, VLVT_UINT64,VLVD_NODIR|VLVF_PUB_RW,1 ,32,0);
        __Vscope_fetch_unit__instrFifo.varInsert(__Vfinal,"io_pop_0_ready", &(TOP.fetch_unit__DOT__instrFifo__DOT__io_pop_0_ready), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_fetch_unit__instrFifo.varInsert(__Vfinal,"io_pop_0_valid", &(TOP.fetch_unit__DOT__instrFifo__DOT__io_pop_0_valid), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_fetch_unit__instrFifo.varInsert(__Vfinal,"io_pop_1_payload", &(TOP.fetch_unit__DOT__instrFifo__DOT__io_pop_1_payload), false, VLVT_UINT64,VLVD_NODIR|VLVF_PUB_RW,1 ,32,0);
        __Vscope_fetch_unit__instrFifo.varInsert(__Vfinal,"io_pop_1_ready", &(TOP.fetch_unit__DOT__instrFifo__DOT__io_pop_1_ready), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_fetch_unit__instrFifo.varInsert(__Vfinal,"io_pop_1_valid", &(TOP.fetch_unit__DOT__instrFifo__DOT__io_pop_1_valid), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_fetch_unit__instrFifo.varInsert(__Vfinal,"io_push_0_payload", &(TOP.fetch_unit__DOT__instrFifo__DOT__io_push_0_payload), false, VLVT_UINT64,VLVD_NODIR|VLVF_PUB_RW,1 ,32,0);
        __Vscope_fetch_unit__instrFifo.varInsert(__Vfinal,"io_push_0_ready", &(TOP.fetch_unit__DOT__instrFifo__DOT__io_push_0_ready), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_fetch_unit__instrFifo.varInsert(__Vfinal,"io_push_0_valid", &(TOP.fetch_unit__DOT__instrFifo__DOT__io_push_0_valid), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_fetch_unit__instrFifo.varInsert(__Vfinal,"io_push_1_payload", &(TOP.fetch_unit__DOT__instrFifo__DOT__io_push_1_payload), false, VLVT_UINT64,VLVD_NODIR|VLVF_PUB_RW,1 ,32,0);
        __Vscope_fetch_unit__instrFifo.varInsert(__Vfinal,"io_push_1_ready", &(TOP.fetch_unit__DOT__instrFifo__DOT__io_push_1_ready), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_fetch_unit__instrFifo.varInsert(__Vfinal,"io_push_1_valid", &(TOP.fetch_unit__DOT__instrFifo__DOT__io_push_1_valid), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_fetch_unit__instrFifo.varInsert(__Vfinal,"io_push_2_payload", &(TOP.fetch_unit__DOT__instrFifo__DOT__io_push_2_payload), false, VLVT_UINT64,VLVD_NODIR|VLVF_PUB_RW,1 ,32,0);
        __Vscope_fetch_unit__instrFifo.varInsert(__Vfinal,"io_push_2_ready", &(TOP.fetch_unit__DOT__instrFifo__DOT__io_push_2_ready), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_fetch_unit__instrFifo.varInsert(__Vfinal,"io_push_2_valid", &(TOP.fetch_unit__DOT__instrFifo__DOT__io_push_2_valid), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_fetch_unit__instrFifo.varInsert(__Vfinal,"io_push_3_payload", &(TOP.fetch_unit__DOT__instrFifo__DOT__io_push_3_payload), false, VLVT_UINT64,VLVD_NODIR|VLVF_PUB_RW,1 ,32,0);
        __Vscope_fetch_unit__instrFifo.varInsert(__Vfinal,"io_push_3_ready", &(TOP.fetch_unit__DOT__instrFifo__DOT__io_push_3_ready), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_fetch_unit__instrFifo.varInsert(__Vfinal,"io_push_3_valid", &(TOP.fetch_unit__DOT__instrFifo__DOT__io_push_3_valid), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_fetch_unit__instrFifo.varInsert(__Vfinal,"popPtrGlobal", &(TOP.fetch_unit__DOT__instrFifo__DOT__popPtrGlobal), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,3,0);
        __Vscope_fetch_unit__instrFifo.varInsert(__Vfinal,"popPtrGlobalInc", &(TOP.fetch_unit__DOT__instrFifo__DOT__popPtrGlobalInc), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,3,0);
        __Vscope_fetch_unit__instrFifo.varInsert(__Vfinal,"popPtrs_0", &(TOP.fetch_unit__DOT__instrFifo__DOT__popPtrs_0), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,3,0);
        __Vscope_fetch_unit__instrFifo.varInsert(__Vfinal,"popPtrs_1", &(TOP.fetch_unit__DOT__instrFifo__DOT__popPtrs_1), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,3,0);
        __Vscope_fetch_unit__instrFifo.varInsert(__Vfinal,"popping_vec_0", &(TOP.fetch_unit__DOT__instrFifo__DOT__popping_vec_0), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_fetch_unit__instrFifo.varInsert(__Vfinal,"popping_vec_1", &(TOP.fetch_unit__DOT__instrFifo__DOT__popping_vec_1), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_fetch_unit__instrFifo.varInsert(__Vfinal,"ptrDif", &(TOP.fetch_unit__DOT__instrFifo__DOT__ptrDif), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,3,0);
        __Vscope_fetch_unit__instrFifo.varInsert(__Vfinal,"ptrMatch", &(TOP.fetch_unit__DOT__instrFifo__DOT__ptrMatch), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_fetch_unit__instrFifo.varInsert(__Vfinal,"pushPtrGlobal", &(TOP.fetch_unit__DOT__instrFifo__DOT__pushPtrGlobal), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,3,0);
        __Vscope_fetch_unit__instrFifo.varInsert(__Vfinal,"pushPtrGlobalInc", &(TOP.fetch_unit__DOT__instrFifo__DOT__pushPtrGlobalInc), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,3,0);
        __Vscope_fetch_unit__instrFifo.varInsert(__Vfinal,"pushPtrs_0", &(TOP.fetch_unit__DOT__instrFifo__DOT__pushPtrs_0), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,3,0);
        __Vscope_fetch_unit__instrFifo.varInsert(__Vfinal,"pushPtrs_1", &(TOP.fetch_unit__DOT__instrFifo__DOT__pushPtrs_1), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,3,0);
        __Vscope_fetch_unit__instrFifo.varInsert(__Vfinal,"pushPtrs_2", &(TOP.fetch_unit__DOT__instrFifo__DOT__pushPtrs_2), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,3,0);
        __Vscope_fetch_unit__instrFifo.varInsert(__Vfinal,"pushPtrs_3", &(TOP.fetch_unit__DOT__instrFifo__DOT__pushPtrs_3), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,3,0);
        __Vscope_fetch_unit__instrFifo.varInsert(__Vfinal,"pushing_vec_0", &(TOP.fetch_unit__DOT__instrFifo__DOT__pushing_vec_0), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_fetch_unit__instrFifo.varInsert(__Vfinal,"pushing_vec_1", &(TOP.fetch_unit__DOT__instrFifo__DOT__pushing_vec_1), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_fetch_unit__instrFifo.varInsert(__Vfinal,"pushing_vec_2", &(TOP.fetch_unit__DOT__instrFifo__DOT__pushing_vec_2), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_fetch_unit__instrFifo.varInsert(__Vfinal,"pushing_vec_3", &(TOP.fetch_unit__DOT__instrFifo__DOT__pushing_vec_3), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_fetch_unit__instrFifo.varInsert(__Vfinal,"readedVec_0", &(TOP.fetch_unit__DOT__instrFifo__DOT__readedVec_0), false, VLVT_UINT64,VLVD_NODIR|VLVF_PUB_RW,1 ,32,0);
        __Vscope_fetch_unit__instrFifo.varInsert(__Vfinal,"readedVec_1", &(TOP.fetch_unit__DOT__instrFifo__DOT__readedVec_1), false, VLVT_UINT64,VLVD_NODIR|VLVF_PUB_RW,1 ,32,0);
        __Vscope_fetch_unit__instrFifo.varInsert(__Vfinal,"resetn", &(TOP.fetch_unit__DOT__instrFifo__DOT__resetn), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_fetch_unit__instrFifo.varInsert(__Vfinal,"risingOccupancy", &(TOP.fetch_unit__DOT__instrFifo__DOT__risingOccupancy), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_fetch_unit__instrFifo.varInsert(__Vfinal,"tmp_1", &(TOP.fetch_unit__DOT__instrFifo__DOT__tmp_1), false, VLVT_UINT16,VLVD_NODIR|VLVF_PUB_RW,1 ,15,0);
        __Vscope_fetch_unit__instrFifo.varInsert(__Vfinal,"tmp_2", &(TOP.fetch_unit__DOT__instrFifo__DOT__tmp_2), false, VLVT_UINT16,VLVD_NODIR|VLVF_PUB_RW,1 ,15,0);
        __Vscope_fetch_unit__instrFifo.varInsert(__Vfinal,"tmp_3", &(TOP.fetch_unit__DOT__instrFifo__DOT__tmp_3), false, VLVT_UINT16,VLVD_NODIR|VLVF_PUB_RW,1 ,15,0);
        __Vscope_fetch_unit__instrFifo.varInsert(__Vfinal,"tmp_4", &(TOP.fetch_unit__DOT__instrFifo__DOT__tmp_4), false, VLVT_UINT16,VLVD_NODIR|VLVF_PUB_RW,1 ,15,0);
        __Vscope_fetch_unit__instrFifo.varInsert(__Vfinal,"tmp_dec_num", &(TOP.fetch_unit__DOT__instrFifo__DOT__tmp_dec_num), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_fetch_unit__instrFifo.varInsert(__Vfinal,"tmp_dec_num_1", &(TOP.fetch_unit__DOT__instrFifo__DOT__tmp_dec_num_1), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,1,0);
        __Vscope_fetch_unit__instrFifo.varInsert(__Vfinal,"tmp_dec_num_2", &(TOP.fetch_unit__DOT__instrFifo__DOT__tmp_dec_num_2), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,0,0);
        __Vscope_fetch_unit__instrFifo.varInsert(__Vfinal,"tmp_inc_num", &(TOP.fetch_unit__DOT__instrFifo__DOT__tmp_inc_num), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_fetch_unit__instrFifo.varInsert(__Vfinal,"tmp_inc_num_1", &(TOP.fetch_unit__DOT__instrFifo__DOT__tmp_inc_num_1), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,1,0);
        __Vscope_fetch_unit__instrFifo.varInsert(__Vfinal,"tmp_inc_num_2", &(TOP.fetch_unit__DOT__instrFifo__DOT__tmp_inc_num_2), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,1,0);
        __Vscope_fetch_unit__instrFifo.varInsert(__Vfinal,"tmp_inc_num_3", &(TOP.fetch_unit__DOT__instrFifo__DOT__tmp_inc_num_3), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,0,0);
        __Vscope_fetch_unit__instrFifo.varInsert(__Vfinal,"tmp_inc_num_4", &(TOP.fetch_unit__DOT__instrFifo__DOT__tmp_inc_num_4), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,2,0);
        __Vscope_fetch_unit__instrFifo.varInsert(__Vfinal,"tmp_inc_num_5", &(TOP.fetch_unit__DOT__instrFifo__DOT__tmp_inc_num_5), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,1,0);
        __Vscope_fetch_unit__instrFifo.varInsert(__Vfinal,"tmp_inc_num_6", &(TOP.fetch_unit__DOT__instrFifo__DOT__tmp_inc_num_6), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,1,0);
        __Vscope_fetch_unit__instrFifo.varInsert(__Vfinal,"tmp_inc_num_7", &(TOP.fetch_unit__DOT__instrFifo__DOT__tmp_inc_num_7), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,0,0);
        __Vscope_fetch_unit__instrFifo.varInsert(__Vfinal,"tmp_io_occupancy", &(TOP.fetch_unit__DOT__instrFifo__DOT__tmp_io_occupancy), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,3,0);
        __Vscope_fetch_unit__instrFifo.varInsert(__Vfinal,"tmp_io_push_0_ready", &(TOP.fetch_unit__DOT__instrFifo__DOT__tmp_io_push_0_ready), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,3,0);
        __Vscope_fetch_unit__instrFifo.varInsert(__Vfinal,"tmp_io_push_1_ready", &(TOP.fetch_unit__DOT__instrFifo__DOT__tmp_io_push_1_ready), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,3,0);
        __Vscope_fetch_unit__instrFifo.varInsert(__Vfinal,"tmp_io_push_2_ready", &(TOP.fetch_unit__DOT__instrFifo__DOT__tmp_io_push_2_ready), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,3,0);
        __Vscope_fetch_unit__instrFifo.varInsert(__Vfinal,"tmp_io_push_3_ready", &(TOP.fetch_unit__DOT__instrFifo__DOT__tmp_io_push_3_ready), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,3,0);
        __Vscope_fetch_unit__instrFifo.varInsert(__Vfinal,"tmp_popPtrGlobalInc", &(TOP.fetch_unit__DOT__instrFifo__DOT__tmp_popPtrGlobalInc), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,3,0);
        __Vscope_fetch_unit__instrFifo.varInsert(__Vfinal,"tmp_pushPtrGlobalInc", &(TOP.fetch_unit__DOT__instrFifo__DOT__tmp_pushPtrGlobalInc), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,3,0);
        __Vscope_fetch_unit__instrFifo.varInsert(__Vfinal,"tmp_readedVec_0", &(TOP.fetch_unit__DOT__instrFifo__DOT__tmp_readedVec_0), false, VLVT_UINT64,VLVD_NODIR|VLVF_PUB_RW,1 ,32,0);
        __Vscope_fetch_unit__instrFifo.varInsert(__Vfinal,"tmp_readedVec_0_1", &(TOP.fetch_unit__DOT__instrFifo__DOT__tmp_readedVec_0_1), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,3,0);
        __Vscope_fetch_unit__instrFifo.varInsert(__Vfinal,"tmp_readedVec_1", &(TOP.fetch_unit__DOT__instrFifo__DOT__tmp_readedVec_1), false, VLVT_UINT64,VLVD_NODIR|VLVF_PUB_RW,1 ,32,0);
        __Vscope_fetch_unit__instrFifo.varInsert(__Vfinal,"tmp_readedVec_1_1", &(TOP.fetch_unit__DOT__instrFifo__DOT__tmp_readedVec_1_1), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,3,0);
        __Vscope_fetch_unit__instrFifo.varInsert(__Vfinal,"tmp_when", &(TOP.fetch_unit__DOT__instrFifo__DOT__tmp_when), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,3,0);
        __Vscope_fetch_unit__instrFifo.varInsert(__Vfinal,"tmp_when_1", &(TOP.fetch_unit__DOT__instrFifo__DOT__tmp_when_1), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,3,0);
        __Vscope_fetch_unit__instrFifo.varInsert(__Vfinal,"tmp_when_2", &(TOP.fetch_unit__DOT__instrFifo__DOT__tmp_when_2), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,3,0);
        __Vscope_fetch_unit__instrFifo.varInsert(__Vfinal,"tmp_when_3", &(TOP.fetch_unit__DOT__instrFifo__DOT__tmp_when_3), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,3,0);
        __Vscope_fetch_unit__instrFifo.varInsert(__Vfinal,"tmp_when_4", &(TOP.fetch_unit__DOT__instrFifo__DOT__tmp_when_4), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,3,0);
        __Vscope_fetch_unit__instrFifo.varInsert(__Vfinal,"tmp_when_5", &(TOP.fetch_unit__DOT__instrFifo__DOT__tmp_when_5), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,3,0);
        __Vscope_fetch_unit__instrFifo.varInsert(__Vfinal,"tmp_when_6", &(TOP.fetch_unit__DOT__instrFifo__DOT__tmp_when_6), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,2,0);
        __Vscope_fetch_unit__instrFifo.varInsert(__Vfinal,"vec_0", &(TOP.fetch_unit__DOT__instrFifo__DOT__vec_0), false, VLVT_UINT64,VLVD_NODIR|VLVF_PUB_RW,1 ,32,0);
        __Vscope_fetch_unit__instrFifo.varInsert(__Vfinal,"vec_1", &(TOP.fetch_unit__DOT__instrFifo__DOT__vec_1), false, VLVT_UINT64,VLVD_NODIR|VLVF_PUB_RW,1 ,32,0);
        __Vscope_fetch_unit__instrFifo.varInsert(__Vfinal,"vec_10", &(TOP.fetch_unit__DOT__instrFifo__DOT__vec_10), false, VLVT_UINT64,VLVD_NODIR|VLVF_PUB_RW,1 ,32,0);
        __Vscope_fetch_unit__instrFifo.varInsert(__Vfinal,"vec_11", &(TOP.fetch_unit__DOT__instrFifo__DOT__vec_11), false, VLVT_UINT64,VLVD_NODIR|VLVF_PUB_RW,1 ,32,0);
        __Vscope_fetch_unit__instrFifo.varInsert(__Vfinal,"vec_2", &(TOP.fetch_unit__DOT__instrFifo__DOT__vec_2), false, VLVT_UINT64,VLVD_NODIR|VLVF_PUB_RW,1 ,32,0);
        __Vscope_fetch_unit__instrFifo.varInsert(__Vfinal,"vec_3", &(TOP.fetch_unit__DOT__instrFifo__DOT__vec_3), false, VLVT_UINT64,VLVD_NODIR|VLVF_PUB_RW,1 ,32,0);
        __Vscope_fetch_unit__instrFifo.varInsert(__Vfinal,"vec_4", &(TOP.fetch_unit__DOT__instrFifo__DOT__vec_4), false, VLVT_UINT64,VLVD_NODIR|VLVF_PUB_RW,1 ,32,0);
        __Vscope_fetch_unit__instrFifo.varInsert(__Vfinal,"vec_5", &(TOP.fetch_unit__DOT__instrFifo__DOT__vec_5), false, VLVT_UINT64,VLVD_NODIR|VLVF_PUB_RW,1 ,32,0);
        __Vscope_fetch_unit__instrFifo.varInsert(__Vfinal,"vec_6", &(TOP.fetch_unit__DOT__instrFifo__DOT__vec_6), false, VLVT_UINT64,VLVD_NODIR|VLVF_PUB_RW,1 ,32,0);
        __Vscope_fetch_unit__instrFifo.varInsert(__Vfinal,"vec_7", &(TOP.fetch_unit__DOT__instrFifo__DOT__vec_7), false, VLVT_UINT64,VLVD_NODIR|VLVF_PUB_RW,1 ,32,0);
        __Vscope_fetch_unit__instrFifo.varInsert(__Vfinal,"vec_8", &(TOP.fetch_unit__DOT__instrFifo__DOT__vec_8), false, VLVT_UINT64,VLVD_NODIR|VLVF_PUB_RW,1 ,32,0);
        __Vscope_fetch_unit__instrFifo.varInsert(__Vfinal,"vec_9", &(TOP.fetch_unit__DOT__instrFifo__DOT__vec_9), false, VLVT_UINT64,VLVD_NODIR|VLVF_PUB_RW,1 ,32,0);
        __Vscope_fetch_unit__instr_pop_valid_popc.varInsert(__Vfinal,"cnt_out", &(TOP.fetch_unit__DOT__instr_pop_valid_popc__DOT__cnt_out), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,1,0);
        __Vscope_fetch_unit__instr_pop_valid_popc.varInsert(__Vfinal,"data_in", &(TOP.fetch_unit__DOT__instr_pop_valid_popc__DOT__data_in), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,1,0);
        __Vscope_fetch_unit__instr_pop_valid_popc.varInsert(__Vfinal,"din_vld", &(TOP.fetch_unit__DOT__instr_pop_valid_popc__DOT__din_vld), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_fetch_unit__instr_pop_valid_popc.varInsert(__Vfinal,"popsum_init_0", &(TOP.fetch_unit__DOT__instr_pop_valid_popc__DOT__popsum_init_0), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,0,0);
        __Vscope_fetch_unit__instr_pop_valid_popc.varInsert(__Vfinal,"popsum_init_1", &(TOP.fetch_unit__DOT__instr_pop_valid_popc__DOT__popsum_init_1), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,0,0);
        __Vscope_fetch_unit__instr_pop_valid_popc.varInsert(__Vfinal,"popsum_stage1_ele0", &(TOP.fetch_unit__DOT__instr_pop_valid_popc__DOT__popsum_stage1_ele0), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,1,0);
        __Vscope_fetch_unit__instr_push_valid_vec_popc.varInsert(__Vfinal,"cnt_out", &(TOP.fetch_unit__DOT__instr_push_valid_vec_popc__DOT__cnt_out), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,2,0);
        __Vscope_fetch_unit__instr_push_valid_vec_popc.varInsert(__Vfinal,"data_in", &(TOP.fetch_unit__DOT__instr_push_valid_vec_popc__DOT__data_in), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,3,0);
        __Vscope_fetch_unit__instr_push_valid_vec_popc.varInsert(__Vfinal,"din_vld", &(TOP.fetch_unit__DOT__instr_push_valid_vec_popc__DOT__din_vld), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_fetch_unit__instr_push_valid_vec_popc.varInsert(__Vfinal,"popsum_init_0", &(TOP.fetch_unit__DOT__instr_push_valid_vec_popc__DOT__popsum_init_0), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,0,0);
        __Vscope_fetch_unit__instr_push_valid_vec_popc.varInsert(__Vfinal,"popsum_init_1", &(TOP.fetch_unit__DOT__instr_push_valid_vec_popc__DOT__popsum_init_1), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,0,0);
        __Vscope_fetch_unit__instr_push_valid_vec_popc.varInsert(__Vfinal,"popsum_init_2", &(TOP.fetch_unit__DOT__instr_push_valid_vec_popc__DOT__popsum_init_2), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,0,0);
        __Vscope_fetch_unit__instr_push_valid_vec_popc.varInsert(__Vfinal,"popsum_init_3", &(TOP.fetch_unit__DOT__instr_push_valid_vec_popc__DOT__popsum_init_3), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,0,0);
        __Vscope_fetch_unit__instr_push_valid_vec_popc.varInsert(__Vfinal,"popsum_stage1_ele0", &(TOP.fetch_unit__DOT__instr_push_valid_vec_popc__DOT__popsum_stage1_ele0), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,1,0);
        __Vscope_fetch_unit__instr_push_valid_vec_popc.varInsert(__Vfinal,"popsum_stage1_ele1", &(TOP.fetch_unit__DOT__instr_push_valid_vec_popc__DOT__popsum_stage1_ele1), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,1,0);
        __Vscope_fetch_unit__instr_push_valid_vec_popc.varInsert(__Vfinal,"popsum_stage2_ele0", &(TOP.fetch_unit__DOT__instr_push_valid_vec_popc__DOT__popsum_stage2_ele0), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,2,0);
        __Vscope_fetch_unit__rvcDecompressor_2.varInsert(__Vfinal,"addImm", &(TOP.fetch_unit__DOT__rvcDecompressor_2__DOT__addImm), false, VLVT_UINT16,VLVD_NODIR|VLVF_PUB_RW,1 ,11,0);
        __Vscope_fetch_unit__rvcDecompressor_2.varInsert(__Vfinal,"addi16spImm", &(TOP.fetch_unit__DOT__rvcDecompressor_2__DOT__addi16spImm), false, VLVT_UINT16,VLVD_NODIR|VLVF_PUB_RW,1 ,11,0);
        __Vscope_fetch_unit__rvcDecompressor_2.varInsert(__Vfinal,"addi5spnImm", &(TOP.fetch_unit__DOT__rvcDecompressor_2__DOT__addi5spnImm), false, VLVT_UINT16,VLVD_NODIR|VLVF_PUB_RW,1 ,11,0);
        __Vscope_fetch_unit__rvcDecompressor_2.varInsert(__Vfinal,"bImm", &(TOP.fetch_unit__DOT__rvcDecompressor_2__DOT__bImm), false, VLVT_UINT16,VLVD_NODIR|VLVF_PUB_RW,1 ,12,0);
        __Vscope_fetch_unit__rvcDecompressor_2.varInsert(__Vfinal,"decompInstr_illegal", &(TOP.fetch_unit__DOT__rvcDecompressor_2__DOT__decompInstr_illegal), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_fetch_unit__rvcDecompressor_2.varInsert(__Vfinal,"decompInstr_inst", &(TOP.fetch_unit__DOT__rvcDecompressor_2__DOT__decompInstr_inst), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,1 ,31,0);
        __Vscope_fetch_unit__rvcDecompressor_2.varInsert(__Vfinal,"i", &(TOP.fetch_unit__DOT__rvcDecompressor_2__DOT__i), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,1 ,31,0);
        __Vscope_fetch_unit__rvcDecompressor_2.varInsert(__Vfinal,"jImm", &(TOP.fetch_unit__DOT__rvcDecompressor_2__DOT__jImm), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,1 ,20,0);
        __Vscope_fetch_unit__rvcDecompressor_2.varInsert(__Vfinal,"jalImm", &(TOP.fetch_unit__DOT__rvcDecompressor_2__DOT__jalImm), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,1 ,20,0);
        __Vscope_fetch_unit__rvcDecompressor_2.varInsert(__Vfinal,"ldImm", &(TOP.fetch_unit__DOT__rvcDecompressor_2__DOT__ldImm), false, VLVT_UINT16,VLVD_NODIR|VLVF_PUB_RW,1 ,11,0);
        __Vscope_fetch_unit__rvcDecompressor_2.varInsert(__Vfinal,"luiImm", &(TOP.fetch_unit__DOT__rvcDecompressor_2__DOT__luiImm), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,1 ,31,0);
        __Vscope_fetch_unit__rvcDecompressor_2.varInsert(__Vfinal,"lwImm", &(TOP.fetch_unit__DOT__rvcDecompressor_2__DOT__lwImm), false, VLVT_UINT16,VLVD_NODIR|VLVF_PUB_RW,1 ,11,0);
        __Vscope_fetch_unit__rvcDecompressor_2.varInsert(__Vfinal,"rch", &(TOP.fetch_unit__DOT__rvcDecompressor_2__DOT__rch), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,4,0);
        __Vscope_fetch_unit__rvcDecompressor_2.varInsert(__Vfinal,"rcl", &(TOP.fetch_unit__DOT__rvcDecompressor_2__DOT__rcl), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,4,0);
        __Vscope_fetch_unit__rvcDecompressor_2.varInsert(__Vfinal,"ret_illegal", &(TOP.fetch_unit__DOT__rvcDecompressor_2__DOT__ret_illegal), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_fetch_unit__rvcDecompressor_2.varInsert(__Vfinal,"ret_inst", &(TOP.fetch_unit__DOT__rvcDecompressor_2__DOT__ret_inst), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,1 ,31,0);
        __Vscope_fetch_unit__rvcDecompressor_2.varInsert(__Vfinal,"shiftImm", &(TOP.fetch_unit__DOT__rvcDecompressor_2__DOT__shiftImm), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,4,0);
        __Vscope_fetch_unit__rvcDecompressor_2.varInsert(__Vfinal,"tmp_addImm", &(TOP.fetch_unit__DOT__rvcDecompressor_2__DOT__tmp_addImm), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_fetch_unit__rvcDecompressor_2.varInsert(__Vfinal,"tmp_addi16spImm", &(TOP.fetch_unit__DOT__rvcDecompressor_2__DOT__tmp_addi16spImm), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_fetch_unit__rvcDecompressor_2.varInsert(__Vfinal,"tmp_addi16spImm_1", &(TOP.fetch_unit__DOT__rvcDecompressor_2__DOT__tmp_addi16spImm_1), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,2,0);
        __Vscope_fetch_unit__rvcDecompressor_2.varInsert(__Vfinal,"tmp_bImm", &(TOP.fetch_unit__DOT__rvcDecompressor_2__DOT__tmp_bImm), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_fetch_unit__rvcDecompressor_2.varInsert(__Vfinal,"tmp_bImm_1", &(TOP.fetch_unit__DOT__rvcDecompressor_2__DOT__tmp_bImm_1), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,4,0);
        __Vscope_fetch_unit__rvcDecompressor_2.varInsert(__Vfinal,"tmp_jImm", &(TOP.fetch_unit__DOT__rvcDecompressor_2__DOT__tmp_jImm), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_fetch_unit__rvcDecompressor_2.varInsert(__Vfinal,"tmp_jImm_1", &(TOP.fetch_unit__DOT__rvcDecompressor_2__DOT__tmp_jImm_1), false, VLVT_UINT16,VLVD_NODIR|VLVF_PUB_RW,1 ,9,0);
        __Vscope_fetch_unit__rvcDecompressor_2.varInsert(__Vfinal,"tmp_jalImm", &(TOP.fetch_unit__DOT__rvcDecompressor_2__DOT__tmp_jalImm), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_fetch_unit__rvcDecompressor_2.varInsert(__Vfinal,"tmp_jalImm_1", &(TOP.fetch_unit__DOT__rvcDecompressor_2__DOT__tmp_jalImm_1), false, VLVT_UINT16,VLVD_NODIR|VLVF_PUB_RW,1 ,9,0);
        __Vscope_fetch_unit__rvcDecompressor_2.varInsert(__Vfinal,"tmp_luiImm", &(TOP.fetch_unit__DOT__rvcDecompressor_2__DOT__tmp_luiImm), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_fetch_unit__rvcDecompressor_2.varInsert(__Vfinal,"tmp_luiImm_1", &(TOP.fetch_unit__DOT__rvcDecompressor_2__DOT__tmp_luiImm_1), false, VLVT_UINT16,VLVD_NODIR|VLVF_PUB_RW,1 ,14,0);
        __Vscope_fetch_unit__rvcDecompressor_2.varInsert(__Vfinal,"tmp_ret_inst", &(TOP.fetch_unit__DOT__rvcDecompressor_2__DOT__tmp_ret_inst), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,1 ,31,0);
        __Vscope_fetch_unit__rvcDecompressor_2.varInsert(__Vfinal,"tmp_ret_inst_1", &(TOP.fetch_unit__DOT__rvcDecompressor_2__DOT__tmp_ret_inst_1), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,1 ,31,0);
        __Vscope_fetch_unit__rvcDecompressor_2.varInsert(__Vfinal,"tmp_ret_inst_10", &(TOP.fetch_unit__DOT__rvcDecompressor_2__DOT__tmp_ret_inst_10), false, VLVT_UINT16,VLVD_NODIR|VLVF_PUB_RW,1 ,11,0);
        __Vscope_fetch_unit__rvcDecompressor_2.varInsert(__Vfinal,"tmp_ret_inst_2", &(TOP.fetch_unit__DOT__rvcDecompressor_2__DOT__tmp_ret_inst_2), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,1,0);
        __Vscope_fetch_unit__rvcDecompressor_2.varInsert(__Vfinal,"tmp_ret_inst_3", &(TOP.fetch_unit__DOT__rvcDecompressor_2__DOT__tmp_ret_inst_3), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,2,0);
        __Vscope_fetch_unit__rvcDecompressor_2.varInsert(__Vfinal,"tmp_ret_inst_4", &(TOP.fetch_unit__DOT__rvcDecompressor_2__DOT__tmp_ret_inst_4), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,2,0);
        __Vscope_fetch_unit__rvcDecompressor_2.varInsert(__Vfinal,"tmp_ret_inst_5", &(TOP.fetch_unit__DOT__rvcDecompressor_2__DOT__tmp_ret_inst_5), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,6,0);
        __Vscope_fetch_unit__rvcDecompressor_2.varInsert(__Vfinal,"tmp_ret_inst_6", &(TOP.fetch_unit__DOT__rvcDecompressor_2__DOT__tmp_ret_inst_6), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,4,0);
        __Vscope_fetch_unit__rvcDecompressor_2.varInsert(__Vfinal,"tmp_ret_inst_7", &(TOP.fetch_unit__DOT__rvcDecompressor_2__DOT__tmp_ret_inst_7), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_fetch_unit__rvcDecompressor_2.varInsert(__Vfinal,"tmp_ret_inst_8", &(TOP.fetch_unit__DOT__rvcDecompressor_2__DOT__tmp_ret_inst_8), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,4,0);
        __Vscope_fetch_unit__rvcDecompressor_2.varInsert(__Vfinal,"tmp_ret_inst_9", &(TOP.fetch_unit__DOT__rvcDecompressor_2__DOT__tmp_ret_inst_9), false, VLVT_UINT16,VLVD_NODIR|VLVF_PUB_RW,1 ,11,0);
        __Vscope_fetch_unit__rvcDecompressor_2.varInsert(__Vfinal,"tmp_tmp_ret_inst", &(TOP.fetch_unit__DOT__rvcDecompressor_2__DOT__tmp_tmp_ret_inst), false, VLVT_UINT16,VLVD_NODIR|VLVF_PUB_RW,1 ,11,0);
        __Vscope_fetch_unit__rvcDecompressor_2.varInsert(__Vfinal,"tmp_tmp_ret_inst_1", &(TOP.fetch_unit__DOT__rvcDecompressor_2__DOT__tmp_tmp_ret_inst_1), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,5,0);
        __Vscope_fetch_unit__rvcDecompressor_2.varInsert(__Vfinal,"x0", &(TOP.fetch_unit__DOT__rvcDecompressor_2__DOT__x0), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,4,0);
        __Vscope_fetch_unit__rvcDecompressor_2.varInsert(__Vfinal,"x1", &(TOP.fetch_unit__DOT__rvcDecompressor_2__DOT__x1), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,4,0);
        __Vscope_fetch_unit__rvcDecompressor_2.varInsert(__Vfinal,"x2", &(TOP.fetch_unit__DOT__rvcDecompressor_2__DOT__x2), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,4,0);
        __Vscope_fetch_unit__rvcDecompressor_3.varInsert(__Vfinal,"addImm", &(TOP.fetch_unit__DOT__rvcDecompressor_3__DOT__addImm), false, VLVT_UINT16,VLVD_NODIR|VLVF_PUB_RW,1 ,11,0);
        __Vscope_fetch_unit__rvcDecompressor_3.varInsert(__Vfinal,"addi16spImm", &(TOP.fetch_unit__DOT__rvcDecompressor_3__DOT__addi16spImm), false, VLVT_UINT16,VLVD_NODIR|VLVF_PUB_RW,1 ,11,0);
        __Vscope_fetch_unit__rvcDecompressor_3.varInsert(__Vfinal,"addi5spnImm", &(TOP.fetch_unit__DOT__rvcDecompressor_3__DOT__addi5spnImm), false, VLVT_UINT16,VLVD_NODIR|VLVF_PUB_RW,1 ,11,0);
        __Vscope_fetch_unit__rvcDecompressor_3.varInsert(__Vfinal,"bImm", &(TOP.fetch_unit__DOT__rvcDecompressor_3__DOT__bImm), false, VLVT_UINT16,VLVD_NODIR|VLVF_PUB_RW,1 ,12,0);
        __Vscope_fetch_unit__rvcDecompressor_3.varInsert(__Vfinal,"decompInstr_illegal", &(TOP.fetch_unit__DOT__rvcDecompressor_3__DOT__decompInstr_illegal), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_fetch_unit__rvcDecompressor_3.varInsert(__Vfinal,"decompInstr_inst", &(TOP.fetch_unit__DOT__rvcDecompressor_3__DOT__decompInstr_inst), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,1 ,31,0);
        __Vscope_fetch_unit__rvcDecompressor_3.varInsert(__Vfinal,"i", &(TOP.fetch_unit__DOT__rvcDecompressor_3__DOT__i), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,1 ,31,0);
        __Vscope_fetch_unit__rvcDecompressor_3.varInsert(__Vfinal,"jImm", &(TOP.fetch_unit__DOT__rvcDecompressor_3__DOT__jImm), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,1 ,20,0);
        __Vscope_fetch_unit__rvcDecompressor_3.varInsert(__Vfinal,"jalImm", &(TOP.fetch_unit__DOT__rvcDecompressor_3__DOT__jalImm), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,1 ,20,0);
        __Vscope_fetch_unit__rvcDecompressor_3.varInsert(__Vfinal,"ldImm", &(TOP.fetch_unit__DOT__rvcDecompressor_3__DOT__ldImm), false, VLVT_UINT16,VLVD_NODIR|VLVF_PUB_RW,1 ,11,0);
        __Vscope_fetch_unit__rvcDecompressor_3.varInsert(__Vfinal,"luiImm", &(TOP.fetch_unit__DOT__rvcDecompressor_3__DOT__luiImm), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,1 ,31,0);
        __Vscope_fetch_unit__rvcDecompressor_3.varInsert(__Vfinal,"lwImm", &(TOP.fetch_unit__DOT__rvcDecompressor_3__DOT__lwImm), false, VLVT_UINT16,VLVD_NODIR|VLVF_PUB_RW,1 ,11,0);
        __Vscope_fetch_unit__rvcDecompressor_3.varInsert(__Vfinal,"rch", &(TOP.fetch_unit__DOT__rvcDecompressor_3__DOT__rch), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,4,0);
        __Vscope_fetch_unit__rvcDecompressor_3.varInsert(__Vfinal,"rcl", &(TOP.fetch_unit__DOT__rvcDecompressor_3__DOT__rcl), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,4,0);
        __Vscope_fetch_unit__rvcDecompressor_3.varInsert(__Vfinal,"ret_illegal", &(TOP.fetch_unit__DOT__rvcDecompressor_3__DOT__ret_illegal), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_fetch_unit__rvcDecompressor_3.varInsert(__Vfinal,"ret_inst", &(TOP.fetch_unit__DOT__rvcDecompressor_3__DOT__ret_inst), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,1 ,31,0);
        __Vscope_fetch_unit__rvcDecompressor_3.varInsert(__Vfinal,"shiftImm", &(TOP.fetch_unit__DOT__rvcDecompressor_3__DOT__shiftImm), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,4,0);
        __Vscope_fetch_unit__rvcDecompressor_3.varInsert(__Vfinal,"tmp_addImm", &(TOP.fetch_unit__DOT__rvcDecompressor_3__DOT__tmp_addImm), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_fetch_unit__rvcDecompressor_3.varInsert(__Vfinal,"tmp_addi16spImm", &(TOP.fetch_unit__DOT__rvcDecompressor_3__DOT__tmp_addi16spImm), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_fetch_unit__rvcDecompressor_3.varInsert(__Vfinal,"tmp_addi16spImm_1", &(TOP.fetch_unit__DOT__rvcDecompressor_3__DOT__tmp_addi16spImm_1), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,2,0);
        __Vscope_fetch_unit__rvcDecompressor_3.varInsert(__Vfinal,"tmp_bImm", &(TOP.fetch_unit__DOT__rvcDecompressor_3__DOT__tmp_bImm), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_fetch_unit__rvcDecompressor_3.varInsert(__Vfinal,"tmp_bImm_1", &(TOP.fetch_unit__DOT__rvcDecompressor_3__DOT__tmp_bImm_1), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,4,0);
        __Vscope_fetch_unit__rvcDecompressor_3.varInsert(__Vfinal,"tmp_jImm", &(TOP.fetch_unit__DOT__rvcDecompressor_3__DOT__tmp_jImm), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_fetch_unit__rvcDecompressor_3.varInsert(__Vfinal,"tmp_jImm_1", &(TOP.fetch_unit__DOT__rvcDecompressor_3__DOT__tmp_jImm_1), false, VLVT_UINT16,VLVD_NODIR|VLVF_PUB_RW,1 ,9,0);
        __Vscope_fetch_unit__rvcDecompressor_3.varInsert(__Vfinal,"tmp_jalImm", &(TOP.fetch_unit__DOT__rvcDecompressor_3__DOT__tmp_jalImm), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_fetch_unit__rvcDecompressor_3.varInsert(__Vfinal,"tmp_jalImm_1", &(TOP.fetch_unit__DOT__rvcDecompressor_3__DOT__tmp_jalImm_1), false, VLVT_UINT16,VLVD_NODIR|VLVF_PUB_RW,1 ,9,0);
        __Vscope_fetch_unit__rvcDecompressor_3.varInsert(__Vfinal,"tmp_luiImm", &(TOP.fetch_unit__DOT__rvcDecompressor_3__DOT__tmp_luiImm), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_fetch_unit__rvcDecompressor_3.varInsert(__Vfinal,"tmp_luiImm_1", &(TOP.fetch_unit__DOT__rvcDecompressor_3__DOT__tmp_luiImm_1), false, VLVT_UINT16,VLVD_NODIR|VLVF_PUB_RW,1 ,14,0);
        __Vscope_fetch_unit__rvcDecompressor_3.varInsert(__Vfinal,"tmp_ret_inst", &(TOP.fetch_unit__DOT__rvcDecompressor_3__DOT__tmp_ret_inst), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,1 ,31,0);
        __Vscope_fetch_unit__rvcDecompressor_3.varInsert(__Vfinal,"tmp_ret_inst_1", &(TOP.fetch_unit__DOT__rvcDecompressor_3__DOT__tmp_ret_inst_1), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,1 ,31,0);
        __Vscope_fetch_unit__rvcDecompressor_3.varInsert(__Vfinal,"tmp_ret_inst_10", &(TOP.fetch_unit__DOT__rvcDecompressor_3__DOT__tmp_ret_inst_10), false, VLVT_UINT16,VLVD_NODIR|VLVF_PUB_RW,1 ,11,0);
        __Vscope_fetch_unit__rvcDecompressor_3.varInsert(__Vfinal,"tmp_ret_inst_2", &(TOP.fetch_unit__DOT__rvcDecompressor_3__DOT__tmp_ret_inst_2), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,1,0);
        __Vscope_fetch_unit__rvcDecompressor_3.varInsert(__Vfinal,"tmp_ret_inst_3", &(TOP.fetch_unit__DOT__rvcDecompressor_3__DOT__tmp_ret_inst_3), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,2,0);
        __Vscope_fetch_unit__rvcDecompressor_3.varInsert(__Vfinal,"tmp_ret_inst_4", &(TOP.fetch_unit__DOT__rvcDecompressor_3__DOT__tmp_ret_inst_4), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,2,0);
        __Vscope_fetch_unit__rvcDecompressor_3.varInsert(__Vfinal,"tmp_ret_inst_5", &(TOP.fetch_unit__DOT__rvcDecompressor_3__DOT__tmp_ret_inst_5), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,6,0);
        __Vscope_fetch_unit__rvcDecompressor_3.varInsert(__Vfinal,"tmp_ret_inst_6", &(TOP.fetch_unit__DOT__rvcDecompressor_3__DOT__tmp_ret_inst_6), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,4,0);
        __Vscope_fetch_unit__rvcDecompressor_3.varInsert(__Vfinal,"tmp_ret_inst_7", &(TOP.fetch_unit__DOT__rvcDecompressor_3__DOT__tmp_ret_inst_7), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_fetch_unit__rvcDecompressor_3.varInsert(__Vfinal,"tmp_ret_inst_8", &(TOP.fetch_unit__DOT__rvcDecompressor_3__DOT__tmp_ret_inst_8), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,4,0);
        __Vscope_fetch_unit__rvcDecompressor_3.varInsert(__Vfinal,"tmp_ret_inst_9", &(TOP.fetch_unit__DOT__rvcDecompressor_3__DOT__tmp_ret_inst_9), false, VLVT_UINT16,VLVD_NODIR|VLVF_PUB_RW,1 ,11,0);
        __Vscope_fetch_unit__rvcDecompressor_3.varInsert(__Vfinal,"tmp_tmp_ret_inst", &(TOP.fetch_unit__DOT__rvcDecompressor_3__DOT__tmp_tmp_ret_inst), false, VLVT_UINT16,VLVD_NODIR|VLVF_PUB_RW,1 ,11,0);
        __Vscope_fetch_unit__rvcDecompressor_3.varInsert(__Vfinal,"tmp_tmp_ret_inst_1", &(TOP.fetch_unit__DOT__rvcDecompressor_3__DOT__tmp_tmp_ret_inst_1), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,5,0);
        __Vscope_fetch_unit__rvcDecompressor_3.varInsert(__Vfinal,"x0", &(TOP.fetch_unit__DOT__rvcDecompressor_3__DOT__x0), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,4,0);
        __Vscope_fetch_unit__rvcDecompressor_3.varInsert(__Vfinal,"x1", &(TOP.fetch_unit__DOT__rvcDecompressor_3__DOT__x1), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,4,0);
        __Vscope_fetch_unit__rvcDecompressor_3.varInsert(__Vfinal,"x2", &(TOP.fetch_unit__DOT__rvcDecompressor_3__DOT__x2), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,4,0);
        __Vscope_fetch_unit__trailone_index_0.varInsert(__Vfinal,"cnt_out", &(TOP.fetch_unit__DOT__trailone_index_0__DOT__cnt_out), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,2,0);
        __Vscope_fetch_unit__trailone_index_0.varInsert(__Vfinal,"data_in", &(TOP.fetch_unit__DOT__trailone_index_0__DOT__data_in), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,3,0);
        __Vscope_fetch_unit__trailone_index_0.varInsert(__Vfinal,"data_s", &(TOP.fetch_unit__DOT__trailone_index_0__DOT__data_s), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,3,0);
        __Vscope_fetch_unit__trailone_index_0.varInsert(__Vfinal,"datain_reverse", &(TOP.fetch_unit__DOT__trailone_index_0__DOT__datain_reverse), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,3,0);
        __Vscope_fetch_unit__trailone_index_0.varInsert(__Vfinal,"empty", &(TOP.fetch_unit__DOT__trailone_index_0__DOT__empty), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_fetch_unit__trailone_index_0.varInsert(__Vfinal,"lead", &(TOP.fetch_unit__DOT__trailone_index_0__DOT__lead), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_fetch_unit__trailone_index_0.varInsert(__Vfinal,"mode", &(TOP.fetch_unit__DOT__trailone_index_0__DOT__mode), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_fetch_unit__trailone_index_0.varInsert(__Vfinal,"stage_index1_0", &(TOP.fetch_unit__DOT__trailone_index_0__DOT__stage_index1_0), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,1,0);
        __Vscope_fetch_unit__trailone_index_0.varInsert(__Vfinal,"stage_index1_1", &(TOP.fetch_unit__DOT__trailone_index_0__DOT__stage_index1_1), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,1,0);
        __Vscope_fetch_unit__trailone_index_0.varInsert(__Vfinal,"stage_index2_0", &(TOP.fetch_unit__DOT__trailone_index_0__DOT__stage_index2_0), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,1,0);
        __Vscope_fetch_unit__trailone_index_0.varInsert(__Vfinal,"stage_node_0", &(TOP.fetch_unit__DOT__trailone_index_0__DOT__stage_node_0), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,3,0);
        __Vscope_fetch_unit__trailone_index_0.varInsert(__Vfinal,"stage_node_1", &(TOP.fetch_unit__DOT__trailone_index_0__DOT__stage_node_1), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,1,0);
        __Vscope_fetch_unit__trailone_index_0.varInsert(__Vfinal,"tmp_cnt_out", &(TOP.fetch_unit__DOT__trailone_index_0__DOT__tmp_cnt_out), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,2,0);
        __Vscope_fetch_unit__trailone_index_0.varInsert(__Vfinal,"trail", &(TOP.fetch_unit__DOT__trailone_index_0__DOT__trail), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_fetch_unit__trailone_index_1.varInsert(__Vfinal,"cnt_out", &(TOP.fetch_unit__DOT__trailone_index_1__DOT__cnt_out), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,2,0);
        __Vscope_fetch_unit__trailone_index_1.varInsert(__Vfinal,"data_in", &(TOP.fetch_unit__DOT__trailone_index_1__DOT__data_in), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,3,0);
        __Vscope_fetch_unit__trailone_index_1.varInsert(__Vfinal,"data_s", &(TOP.fetch_unit__DOT__trailone_index_1__DOT__data_s), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,3,0);
        __Vscope_fetch_unit__trailone_index_1.varInsert(__Vfinal,"datain_reverse", &(TOP.fetch_unit__DOT__trailone_index_1__DOT__datain_reverse), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,3,0);
        __Vscope_fetch_unit__trailone_index_1.varInsert(__Vfinal,"empty", &(TOP.fetch_unit__DOT__trailone_index_1__DOT__empty), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_fetch_unit__trailone_index_1.varInsert(__Vfinal,"lead", &(TOP.fetch_unit__DOT__trailone_index_1__DOT__lead), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_fetch_unit__trailone_index_1.varInsert(__Vfinal,"mode", &(TOP.fetch_unit__DOT__trailone_index_1__DOT__mode), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_fetch_unit__trailone_index_1.varInsert(__Vfinal,"stage_index1_0", &(TOP.fetch_unit__DOT__trailone_index_1__DOT__stage_index1_0), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,1,0);
        __Vscope_fetch_unit__trailone_index_1.varInsert(__Vfinal,"stage_index1_1", &(TOP.fetch_unit__DOT__trailone_index_1__DOT__stage_index1_1), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,1,0);
        __Vscope_fetch_unit__trailone_index_1.varInsert(__Vfinal,"stage_index2_0", &(TOP.fetch_unit__DOT__trailone_index_1__DOT__stage_index2_0), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,1,0);
        __Vscope_fetch_unit__trailone_index_1.varInsert(__Vfinal,"stage_node_0", &(TOP.fetch_unit__DOT__trailone_index_1__DOT__stage_node_0), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,3,0);
        __Vscope_fetch_unit__trailone_index_1.varInsert(__Vfinal,"stage_node_1", &(TOP.fetch_unit__DOT__trailone_index_1__DOT__stage_node_1), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,1,0);
        __Vscope_fetch_unit__trailone_index_1.varInsert(__Vfinal,"tmp_cnt_out", &(TOP.fetch_unit__DOT__trailone_index_1__DOT__tmp_cnt_out), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,2,0);
        __Vscope_fetch_unit__trailone_index_1.varInsert(__Vfinal,"trail", &(TOP.fetch_unit__DOT__trailone_index_1__DOT__trail), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_fetch_unit__trailone_index_2.varInsert(__Vfinal,"cnt_out", &(TOP.fetch_unit__DOT__trailone_index_2__DOT__cnt_out), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,2,0);
        __Vscope_fetch_unit__trailone_index_2.varInsert(__Vfinal,"data_in", &(TOP.fetch_unit__DOT__trailone_index_2__DOT__data_in), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,3,0);
        __Vscope_fetch_unit__trailone_index_2.varInsert(__Vfinal,"data_s", &(TOP.fetch_unit__DOT__trailone_index_2__DOT__data_s), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,3,0);
        __Vscope_fetch_unit__trailone_index_2.varInsert(__Vfinal,"datain_reverse", &(TOP.fetch_unit__DOT__trailone_index_2__DOT__datain_reverse), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,3,0);
        __Vscope_fetch_unit__trailone_index_2.varInsert(__Vfinal,"empty", &(TOP.fetch_unit__DOT__trailone_index_2__DOT__empty), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_fetch_unit__trailone_index_2.varInsert(__Vfinal,"lead", &(TOP.fetch_unit__DOT__trailone_index_2__DOT__lead), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_fetch_unit__trailone_index_2.varInsert(__Vfinal,"mode", &(TOP.fetch_unit__DOT__trailone_index_2__DOT__mode), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_fetch_unit__trailone_index_2.varInsert(__Vfinal,"stage_index1_0", &(TOP.fetch_unit__DOT__trailone_index_2__DOT__stage_index1_0), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,1,0);
        __Vscope_fetch_unit__trailone_index_2.varInsert(__Vfinal,"stage_index1_1", &(TOP.fetch_unit__DOT__trailone_index_2__DOT__stage_index1_1), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,1,0);
        __Vscope_fetch_unit__trailone_index_2.varInsert(__Vfinal,"stage_index2_0", &(TOP.fetch_unit__DOT__trailone_index_2__DOT__stage_index2_0), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,1,0);
        __Vscope_fetch_unit__trailone_index_2.varInsert(__Vfinal,"stage_node_0", &(TOP.fetch_unit__DOT__trailone_index_2__DOT__stage_node_0), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,3,0);
        __Vscope_fetch_unit__trailone_index_2.varInsert(__Vfinal,"stage_node_1", &(TOP.fetch_unit__DOT__trailone_index_2__DOT__stage_node_1), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,1,0);
        __Vscope_fetch_unit__trailone_index_2.varInsert(__Vfinal,"tmp_cnt_out", &(TOP.fetch_unit__DOT__trailone_index_2__DOT__tmp_cnt_out), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,2,0);
        __Vscope_fetch_unit__trailone_index_2.varInsert(__Vfinal,"trail", &(TOP.fetch_unit__DOT__trailone_index_2__DOT__trail), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_fetch_unit__trailone_index_3.varInsert(__Vfinal,"cnt_out", &(TOP.fetch_unit__DOT__trailone_index_3__DOT__cnt_out), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,2,0);
        __Vscope_fetch_unit__trailone_index_3.varInsert(__Vfinal,"data_in", &(TOP.fetch_unit__DOT__trailone_index_3__DOT__data_in), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,3,0);
        __Vscope_fetch_unit__trailone_index_3.varInsert(__Vfinal,"data_s", &(TOP.fetch_unit__DOT__trailone_index_3__DOT__data_s), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,3,0);
        __Vscope_fetch_unit__trailone_index_3.varInsert(__Vfinal,"datain_reverse", &(TOP.fetch_unit__DOT__trailone_index_3__DOT__datain_reverse), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,3,0);
        __Vscope_fetch_unit__trailone_index_3.varInsert(__Vfinal,"empty", &(TOP.fetch_unit__DOT__trailone_index_3__DOT__empty), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_fetch_unit__trailone_index_3.varInsert(__Vfinal,"lead", &(TOP.fetch_unit__DOT__trailone_index_3__DOT__lead), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_fetch_unit__trailone_index_3.varInsert(__Vfinal,"mode", &(TOP.fetch_unit__DOT__trailone_index_3__DOT__mode), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_fetch_unit__trailone_index_3.varInsert(__Vfinal,"stage_index1_0", &(TOP.fetch_unit__DOT__trailone_index_3__DOT__stage_index1_0), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,1,0);
        __Vscope_fetch_unit__trailone_index_3.varInsert(__Vfinal,"stage_index1_1", &(TOP.fetch_unit__DOT__trailone_index_3__DOT__stage_index1_1), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,1,0);
        __Vscope_fetch_unit__trailone_index_3.varInsert(__Vfinal,"stage_index2_0", &(TOP.fetch_unit__DOT__trailone_index_3__DOT__stage_index2_0), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,1,0);
        __Vscope_fetch_unit__trailone_index_3.varInsert(__Vfinal,"stage_node_0", &(TOP.fetch_unit__DOT__trailone_index_3__DOT__stage_node_0), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,3,0);
        __Vscope_fetch_unit__trailone_index_3.varInsert(__Vfinal,"stage_node_1", &(TOP.fetch_unit__DOT__trailone_index_3__DOT__stage_node_1), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,1,0);
        __Vscope_fetch_unit__trailone_index_3.varInsert(__Vfinal,"tmp_cnt_out", &(TOP.fetch_unit__DOT__trailone_index_3__DOT__tmp_cnt_out), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,2,0);
        __Vscope_fetch_unit__trailone_index_3.varInsert(__Vfinal,"trail", &(TOP.fetch_unit__DOT__trailone_index_3__DOT__trail), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_fetch_unit__validNumFifo.varInsert(__Vfinal,"clk", &(TOP.fetch_unit__DOT__validNumFifo__DOT__clk), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_fetch_unit__validNumFifo.varInsert(__Vfinal,"empty", &(TOP.fetch_unit__DOT__validNumFifo__DOT__empty), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_fetch_unit__validNumFifo.varInsert(__Vfinal,"flush", &(TOP.fetch_unit__DOT__validNumFifo__DOT__flush), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_fetch_unit__validNumFifo.varInsert(__Vfinal,"full", &(TOP.fetch_unit__DOT__validNumFifo__DOT__full), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_fetch_unit__validNumFifo.varInsert(__Vfinal,"head", &(TOP.fetch_unit__DOT__validNumFifo__DOT__head), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,2,0);
        __Vscope_fetch_unit__validNumFifo.varInsert(__Vfinal,"occupancy", &(TOP.fetch_unit__DOT__validNumFifo__DOT__occupancy), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,2,0);
        __Vscope_fetch_unit__validNumFifo.varInsert(__Vfinal,"popPtrGlobal", &(TOP.fetch_unit__DOT__validNumFifo__DOT__popPtrGlobal), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,1,0);
        __Vscope_fetch_unit__validNumFifo.varInsert(__Vfinal,"pop_pop_out_data", &(TOP.fetch_unit__DOT__validNumFifo__DOT__pop_pop_out_data), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,2,0);
        __Vscope_fetch_unit__validNumFifo.varInsert(__Vfinal,"pop_pop_real", &(TOP.fetch_unit__DOT__validNumFifo__DOT__pop_pop_real), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_fetch_unit__validNumFifo.varInsert(__Vfinal,"pop_pop_req_num", &(TOP.fetch_unit__DOT__validNumFifo__DOT__pop_pop_req_num), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,2,0);
        __Vscope_fetch_unit__validNumFifo.varInsert(__Vfinal,"pop_ready", &(TOP.fetch_unit__DOT__validNumFifo__DOT__pop_ready), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_fetch_unit__validNumFifo.varInsert(__Vfinal,"pop_valid", &(TOP.fetch_unit__DOT__validNumFifo__DOT__pop_valid), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_fetch_unit__validNumFifo.varInsert(__Vfinal,"ptrDif", &(TOP.fetch_unit__DOT__validNumFifo__DOT__ptrDif), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,1,0);
        __Vscope_fetch_unit__validNumFifo.varInsert(__Vfinal,"ptrMatch", &(TOP.fetch_unit__DOT__validNumFifo__DOT__ptrMatch), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_fetch_unit__validNumFifo.varInsert(__Vfinal,"pushPtrGlobal", &(TOP.fetch_unit__DOT__validNumFifo__DOT__pushPtrGlobal), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,1,0);
        __Vscope_fetch_unit__validNumFifo.varInsert(__Vfinal,"push_payload", &(TOP.fetch_unit__DOT__validNumFifo__DOT__push_payload), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,2,0);
        __Vscope_fetch_unit__validNumFifo.varInsert(__Vfinal,"push_ready", &(TOP.fetch_unit__DOT__validNumFifo__DOT__push_ready), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_fetch_unit__validNumFifo.varInsert(__Vfinal,"push_valid", &(TOP.fetch_unit__DOT__validNumFifo__DOT__push_valid), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_fetch_unit__validNumFifo.varInsert(__Vfinal,"pushing", &(TOP.fetch_unit__DOT__validNumFifo__DOT__pushing), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_fetch_unit__validNumFifo.varInsert(__Vfinal,"resetn", &(TOP.fetch_unit__DOT__validNumFifo__DOT__resetn), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_fetch_unit__validNumFifo.varInsert(__Vfinal,"risingOccupancy", &(TOP.fetch_unit__DOT__validNumFifo__DOT__risingOccupancy), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0);
        __Vscope_fetch_unit__validNumFifo.varInsert(__Vfinal,"tmp_1", &(TOP.fetch_unit__DOT__validNumFifo__DOT__tmp_1), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,3,0);
        __Vscope_fetch_unit__validNumFifo.varInsert(__Vfinal,"tmp_2", &(TOP.fetch_unit__DOT__validNumFifo__DOT__tmp_2), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,3,0);
        __Vscope_fetch_unit__validNumFifo.varInsert(__Vfinal,"tmp_pop_pop_out_data", &(TOP.fetch_unit__DOT__validNumFifo__DOT__tmp_pop_pop_out_data), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,2,0);
        __Vscope_fetch_unit__validNumFifo.varInsert(__Vfinal,"tmp_tmp_pop_pop_out_data", &(TOP.fetch_unit__DOT__validNumFifo__DOT__tmp_tmp_pop_pop_out_data), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,2,0);
        __Vscope_fetch_unit__validNumFifo.varInsert(__Vfinal,"tmp_vec_0", &(TOP.fetch_unit__DOT__validNumFifo__DOT__tmp_vec_0), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,2,0);
        __Vscope_fetch_unit__validNumFifo.varInsert(__Vfinal,"vec_0", &(TOP.fetch_unit__DOT__validNumFifo__DOT__vec_0), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,2,0);
        __Vscope_fetch_unit__validNumFifo.varInsert(__Vfinal,"vec_1", &(TOP.fetch_unit__DOT__validNumFifo__DOT__vec_1), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,2,0);
        __Vscope_fetch_unit__validNumFifo.varInsert(__Vfinal,"vec_2", &(TOP.fetch_unit__DOT__validNumFifo__DOT__vec_2), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,2,0);
        __Vscope_fetch_unit__validNumFifo.varInsert(__Vfinal,"vec_3", &(TOP.fetch_unit__DOT__validNumFifo__DOT__vec_3), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,1 ,2,0);
    }
}
