// Verilated -*- C++ -*-
// DESCRIPTION: Verilator output: Tracing implementation internals
#include "verilated_fst_c.h"
#include "Vtop__Syms.h"


VL_ATTR_COLD void Vtop___024root__trace_init_sub__TOP__0(Vtop___024root* vlSelf, VerilatedFst* tracep) {
    if (false && vlSelf) {}  // Prevent unused
    Vtop__Syms* const __restrict vlSymsp VL_ATTR_UNUSED = vlSelf->vlSymsp;
    VL_DEBUG_IF(VL_DBG_MSGF("+    Vtop___024root__trace_init_sub__TOP__0\n"); );
    // Init
    const int c = vlSymsp->__Vm_baseCode;
    // Body
    tracep->declBit(c+1,"core_en",-1,FST_VD_INPUT,FST_VT_VCD_WIRE, false,-1);
    tracep->declBit(c+2,"ibus_cmd_valid",-1,FST_VD_OUTPUT,FST_VT_VCD_WIRE, false,-1);
    tracep->declBit(c+3,"ibus_cmd_ready",-1,FST_VD_INPUT,FST_VT_VCD_WIRE, false,-1);
    tracep->declBus(c+4,"ibus_cmd_payload_address",-1,FST_VD_OUTPUT,FST_VT_VCD_WIRE, false,-1, 31,0);
    tracep->declBit(c+5,"ibus_rsp_valid",-1,FST_VD_INPUT,FST_VT_VCD_WIRE, false,-1);
    tracep->declBit(c+6,"ibus_rsp_ready",-1,FST_VD_OUTPUT,FST_VT_VCD_WIRE, false,-1);
    tracep->declQuad(c+7,"ibus_rsp_payload_rdata",-1,FST_VD_INPUT,FST_VT_VCD_WIRE, false,-1, 63,0);
    tracep->declBus(c+9,"if2id_itf_0_instr_data",-1,FST_VD_OUTPUT,FST_VT_VCD_WIRE, false,-1, 31,0);
    tracep->declBus(c+10,"if2id_itf_0_instr_pc",-1,FST_VD_OUTPUT,FST_VT_VCD_WIRE, false,-1, 31,0);
    tracep->declBit(c+11,"if2id_itf_0_valid",-1,FST_VD_OUTPUT,FST_VT_VCD_WIRE, false,-1);
    tracep->declBus(c+12,"if2id_itf_1_instr_data",-1,FST_VD_OUTPUT,FST_VT_VCD_WIRE, false,-1, 31,0);
    tracep->declBus(c+13,"if2id_itf_1_instr_pc",-1,FST_VD_OUTPUT,FST_VT_VCD_WIRE, false,-1, 31,0);
    tracep->declBit(c+14,"if2id_itf_1_valid",-1,FST_VD_OUTPUT,FST_VT_VCD_WIRE, false,-1);
    tracep->declBit(c+15,"fetchStage_flush",-1,FST_VD_INPUT,FST_VT_VCD_WIRE, false,-1);
    tracep->declBit(c+16,"fetchStage_isDone",-1,FST_VD_INPUT,FST_VT_VCD_WIRE, false,-1);
    tracep->declBit(c+17,"fetchStage_isReady",-1,FST_VD_OUTPUT,FST_VT_VCD_WIRE, false,-1);
    tracep->declBit(c+18,"pcJumpTarget_valid",-1,FST_VD_INPUT,FST_VT_VCD_WIRE, false,-1);
    tracep->declBus(c+19,"pcJumpTarget_payload",-1,FST_VD_INPUT,FST_VT_VCD_WIRE, false,-1, 31,0);
    tracep->declBit(c+20,"pcPredicted_valid",-1,FST_VD_INPUT,FST_VT_VCD_WIRE, false,-1);
    tracep->declBus(c+21,"pcPredicted_payload",-1,FST_VD_INPUT,FST_VT_VCD_WIRE, false,-1, 31,0);
    tracep->declBit(c+22,"clk",-1,FST_VD_INPUT,FST_VT_VCD_WIRE, false,-1);
    tracep->declBit(c+23,"resetn",-1,FST_VD_INPUT,FST_VT_VCD_WIRE, false,-1);
    tracep->pushNamePrefix("fetch_unit ");
    tracep->declBit(c+24,"core_en",-1,FST_VD_INPUT,FST_VT_VCD_WIRE, false,-1);
    tracep->declBit(c+25,"ibus_cmd_valid",-1,FST_VD_OUTPUT,FST_VT_VCD_WIRE, false,-1);
    tracep->declBit(c+26,"ibus_cmd_ready",-1,FST_VD_INPUT,FST_VT_VCD_WIRE, false,-1);
    tracep->declBus(c+27,"ibus_cmd_payload_address",-1,FST_VD_OUTPUT,FST_VT_VCD_WIRE, false,-1, 31,0);
    tracep->declBit(c+28,"ibus_rsp_valid",-1,FST_VD_INPUT,FST_VT_VCD_WIRE, false,-1);
    tracep->declBit(c+29,"ibus_rsp_ready",-1,FST_VD_OUTPUT,FST_VT_VCD_WIRE, false,-1);
    tracep->declQuad(c+30,"ibus_rsp_payload_rdata",-1,FST_VD_INPUT,FST_VT_VCD_WIRE, false,-1, 63,0);
    tracep->declBus(c+32,"if2id_itf_0_instr_data",-1,FST_VD_OUTPUT,FST_VT_VCD_WIRE, false,-1, 31,0);
    tracep->declBus(c+33,"if2id_itf_0_instr_pc",-1,FST_VD_OUTPUT,FST_VT_VCD_WIRE, false,-1, 31,0);
    tracep->declBit(c+34,"if2id_itf_0_valid",-1,FST_VD_OUTPUT,FST_VT_VCD_WIRE, false,-1);
    tracep->declBus(c+35,"if2id_itf_1_instr_data",-1,FST_VD_OUTPUT,FST_VT_VCD_WIRE, false,-1, 31,0);
    tracep->declBus(c+36,"if2id_itf_1_instr_pc",-1,FST_VD_OUTPUT,FST_VT_VCD_WIRE, false,-1, 31,0);
    tracep->declBit(c+37,"if2id_itf_1_valid",-1,FST_VD_OUTPUT,FST_VT_VCD_WIRE, false,-1);
    tracep->declBit(c+38,"fetchStage_flush",-1,FST_VD_INPUT,FST_VT_VCD_WIRE, false,-1);
    tracep->declBit(c+39,"fetchStage_isDone",-1,FST_VD_INPUT,FST_VT_VCD_WIRE, false,-1);
    tracep->declBit(c+40,"fetchStage_isReady",-1,FST_VD_OUTPUT,FST_VT_VCD_WIRE, false,-1);
    tracep->declBit(c+41,"pcJumpTarget_valid",-1,FST_VD_INPUT,FST_VT_VCD_WIRE, false,-1);
    tracep->declBus(c+42,"pcJumpTarget_payload",-1,FST_VD_INPUT,FST_VT_VCD_WIRE, false,-1, 31,0);
    tracep->declBit(c+43,"pcPredicted_valid",-1,FST_VD_INPUT,FST_VT_VCD_WIRE, false,-1);
    tracep->declBus(c+44,"pcPredicted_payload",-1,FST_VD_INPUT,FST_VT_VCD_WIRE, false,-1, 31,0);
    tracep->declBit(c+45,"clk",-1,FST_VD_INPUT,FST_VT_VCD_WIRE, false,-1);
    tracep->declBit(c+46,"resetn",-1,FST_VD_INPUT,FST_VT_VCD_WIRE, false,-1);
    tracep->declBus(c+563,"RVL",-1, FST_VD_IMPLICIT,FST_VT_VCD_PARAMETER, false,-1, 1,0);
    tracep->declBus(c+564,"RVH",-1, FST_VD_IMPLICIT,FST_VT_VCD_PARAMETER, false,-1, 1,0);
    tracep->declBus(c+565,"RVC",-1, FST_VD_IMPLICIT,FST_VT_VCD_PARAMETER, false,-1, 1,0);
    tracep->declBus(c+566,"INVALID",-1, FST_VD_IMPLICIT,FST_VT_VCD_PARAMETER, false,-1, 1,0);
    tracep->declBit(c+47,"addressFifo_io_push_valid",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1);
    tracep->declBit(c+48,"addressFifo_io_pop_ready",-1, FST_VD_IMPLICIT,FST_VT_SV_LOGIC, false,-1);
    tracep->declBit(c+49,"addressFifo_io_flush",-1, FST_VD_IMPLICIT,FST_VT_SV_LOGIC, false,-1);
    tracep->declBit(c+50,"validNumFifo_push_valid",-1, FST_VD_IMPLICIT,FST_VT_SV_LOGIC, false,-1);
    tracep->declBus(c+51,"validNumFifo_push_payload",-1, FST_VD_IMPLICIT,FST_VT_SV_LOGIC, false,-1, 2,0);
    tracep->declBit(c+52,"validNumFifo_pop_valid",-1, FST_VD_IMPLICIT,FST_VT_SV_LOGIC, false,-1);
    tracep->declBus(c+53,"validNumFifo_pop_pop_req_num",-1, FST_VD_IMPLICIT,FST_VT_SV_LOGIC, false,-1, 2,0);
    tracep->declBit(c+54,"validNumFifo_flush",-1, FST_VD_IMPLICIT,FST_VT_SV_LOGIC, false,-1);
    tracep->declBit(c+55,"instrFifo_io_push_0_valid",-1, FST_VD_IMPLICIT,FST_VT_SV_LOGIC, false,-1);
    tracep->declQuad(c+56,"instrFifo_io_push_0_payload",-1, FST_VD_IMPLICIT,FST_VT_SV_LOGIC, false,-1, 32,0);
    tracep->declBit(c+58,"instrFifo_io_push_1_valid",-1, FST_VD_IMPLICIT,FST_VT_SV_LOGIC, false,-1);
    tracep->declQuad(c+59,"instrFifo_io_push_1_payload",-1, FST_VD_IMPLICIT,FST_VT_SV_LOGIC, false,-1, 32,0);
    tracep->declBit(c+61,"instrFifo_io_push_2_valid",-1, FST_VD_IMPLICIT,FST_VT_SV_LOGIC, false,-1);
    tracep->declQuad(c+62,"instrFifo_io_push_2_payload",-1, FST_VD_IMPLICIT,FST_VT_SV_LOGIC, false,-1, 32,0);
    tracep->declBit(c+64,"instrFifo_io_push_3_valid",-1, FST_VD_IMPLICIT,FST_VT_SV_LOGIC, false,-1);
    tracep->declQuad(c+65,"instrFifo_io_push_3_payload",-1, FST_VD_IMPLICIT,FST_VT_SV_LOGIC, false,-1, 32,0);
    tracep->declBit(c+67,"instrFifo_io_flush",-1, FST_VD_IMPLICIT,FST_VT_SV_LOGIC, false,-1);
    tracep->declBus(c+68,"rvcDecompressor_2_i",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1, 31,0);
    tracep->declBus(c+69,"rvcDecompressor_3_i",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1, 31,0);
    tracep->declBit(c+70,"addressFifo_io_push_ready",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1);
    tracep->declBit(c+71,"addressFifo_io_pop_valid",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1);
    tracep->declBus(c+72,"addressFifo_io_pop_payload",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1, 31,0);
    tracep->declBus(c+73,"addressFifo_io_head",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1, 31,0);
    tracep->declBus(c+74,"addressFifo_io_occupancy",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1, 2,0);
    tracep->declBit(c+75,"validNumFifo_push_ready",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1);
    tracep->declBit(c+76,"validNumFifo_pop_ready",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1);
    tracep->declBus(c+77,"validNumFifo_pop_pop_out_data",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1, 2,0);
    tracep->declBit(c+78,"validNumFifo_pop_pop_real",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1);
    tracep->declBus(c+79,"validNumFifo_head",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1, 2,0);
    tracep->declBus(c+80,"validNumFifo_occupancy",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1, 2,0);
    tracep->declBit(c+81,"instrFifo_io_push_0_ready",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1);
    tracep->declBit(c+82,"instrFifo_io_push_1_ready",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1);
    tracep->declBit(c+83,"instrFifo_io_push_2_ready",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1);
    tracep->declBit(c+84,"instrFifo_io_push_3_ready",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1);
    tracep->declBit(c+85,"instrFifo_io_pop_0_valid",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1);
    tracep->declQuad(c+86,"instrFifo_io_pop_0_payload",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1, 32,0);
    tracep->declBit(c+88,"instrFifo_io_pop_1_valid",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1);
    tracep->declQuad(c+89,"instrFifo_io_pop_1_payload",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1, 32,0);
    tracep->declBus(c+91,"instrFifo_io_occupancy",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1, 3,0);
    tracep->declBit(c+92,"instrFifo_io_ov_waterline",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1);
    tracep->declBus(c+93,"trailone_index_0_cnt_out",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1, 2,0);
    tracep->declBus(c+94,"trailone_index_1_cnt_out",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1, 2,0);
    tracep->declBus(c+95,"trailone_index_2_cnt_out",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1, 2,0);
    tracep->declBus(c+96,"trailone_index_3_cnt_out",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1, 2,0);
    tracep->declBus(c+97,"instr_push_valid_vec_popc_cnt_out",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1, 2,0);
    tracep->declBus(c+98,"instr_pop_valid_popc_cnt_out",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1, 1,0);
    tracep->declBus(c+99,"rvcDecompressor_2_decompInstr_inst",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1, 31,0);
    tracep->declBit(c+100,"rvcDecompressor_2_decompInstr_illegal",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1);
    tracep->declBus(c+101,"rvcDecompressor_3_decompInstr_inst",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1, 31,0);
    tracep->declBit(c+102,"rvcDecompressor_3_decompInstr_illegal",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1);
    tracep->declQuad(c+103,"tmp_io_push_0_payload",-1, FST_VD_IMPLICIT,FST_VT_SV_LOGIC, false,-1, 32,0);
    tracep->declBit(c+105,"tmp_io_push_0_valid",-1, FST_VD_IMPLICIT,FST_VT_SV_LOGIC, false,-1);
    tracep->declQuad(c+106,"tmp_io_push_1_payload",-1, FST_VD_IMPLICIT,FST_VT_SV_LOGIC, false,-1, 32,0);
    tracep->declBit(c+108,"tmp_io_push_1_valid",-1, FST_VD_IMPLICIT,FST_VT_SV_LOGIC, false,-1);
    tracep->declQuad(c+109,"tmp_io_push_2_payload",-1, FST_VD_IMPLICIT,FST_VT_SV_LOGIC, false,-1, 32,0);
    tracep->declBit(c+111,"tmp_io_push_2_valid",-1, FST_VD_IMPLICIT,FST_VT_SV_LOGIC, false,-1);
    tracep->declQuad(c+112,"tmp_io_push_3_payload",-1, FST_VD_IMPLICIT,FST_VT_SV_LOGIC, false,-1, 32,0);
    tracep->declBit(c+114,"tmp_io_push_3_valid",-1, FST_VD_IMPLICIT,FST_VT_SV_LOGIC, false,-1);
    tracep->declBus(c+115,"tmp_if2id_itf_0_instr_pc",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1, 31,0);
    tracep->declBus(c+116,"tmp_if2id_itf_0_instr_pc_1",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1, 31,0);
    tracep->declBus(c+117,"tmp_if2id_itf_1_instr_pc",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1, 31,0);
    tracep->declBus(c+118,"tmp_if2id_itf_1_instr_pc_1",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1, 31,0);
    tracep->declBus(c+119,"tmp_if2id_itf_1_instr_pc_2",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1, 31,0);
    tracep->declBus(c+120,"pc",-1, FST_VD_IMPLICIT,FST_VT_SV_LOGIC, false,-1, 31,0);
    tracep->declBus(c+121,"default_next_pc",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1, 31,0);
    tracep->declBit(c+122,"fetch_pending",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1);
    tracep->declBus(c+123,"addressOffset",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1, 1,0);
    tracep->declBit(c+124,"ibus_cmd_fire",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1);
    tracep->declBit(c+125,"valid_instr_slice_0",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1);
    tracep->declBit(c+126,"valid_instr_slice_1",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1);
    tracep->declBit(c+127,"valid_instr_slice_2",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1);
    tracep->declBit(c+128,"valid_instr_slice_3",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1);
    tracep->declBit(c+129,"instr_slices_0_valid",-1, FST_VD_IMPLICIT,FST_VT_SV_LOGIC, false,-1);
    tracep->declQuad(c+130,"instr_slices_0_payload",-1, FST_VD_IMPLICIT,FST_VT_SV_LOGIC, false,-1, 32,0);
    tracep->declBit(c+132,"instr_slices_1_valid",-1, FST_VD_IMPLICIT,FST_VT_SV_LOGIC, false,-1);
    tracep->declQuad(c+133,"instr_slices_1_payload",-1, FST_VD_IMPLICIT,FST_VT_SV_LOGIC, false,-1, 32,0);
    tracep->declBit(c+135,"instr_slices_2_valid",-1, FST_VD_IMPLICIT,FST_VT_SV_LOGIC, false,-1);
    tracep->declQuad(c+136,"instr_slices_2_payload",-1, FST_VD_IMPLICIT,FST_VT_SV_LOGIC, false,-1, 32,0);
    tracep->declBit(c+138,"instr_slices_3_valid",-1, FST_VD_IMPLICIT,FST_VT_SV_LOGIC, false,-1);
    tracep->declQuad(c+139,"instr_slices_3_payload",-1, FST_VD_IMPLICIT,FST_VT_SV_LOGIC, false,-1, 32,0);
    tracep->declBus(c+141,"tail_one_matrix_0",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1, 3,0);
    tracep->declBus(c+142,"tail_one_matrix_1",-1, FST_VD_IMPLICIT,FST_VT_SV_LOGIC, false,-1, 3,0);
    tracep->declBus(c+143,"tail_one_matrix_2",-1, FST_VD_IMPLICIT,FST_VT_SV_LOGIC, false,-1, 3,0);
    tracep->declBus(c+144,"tail_one_matrix_3",-1, FST_VD_IMPLICIT,FST_VT_SV_LOGIC, false,-1, 3,0);
    tracep->declBus(c+145,"tail_one_index_vec_0",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1, 1,0);
    tracep->declBus(c+146,"tail_one_index_vec_1",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1, 1,0);
    tracep->declBus(c+147,"tail_one_index_vec_2",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1, 1,0);
    tracep->declBus(c+148,"tail_one_index_vec_3",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1, 1,0);
    tracep->declBit(c+149,"tail_one_valid_vec_0",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1);
    tracep->declBit(c+150,"tail_one_valid_vec_1",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1);
    tracep->declBit(c+151,"tail_one_valid_vec_2",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1);
    tracep->declBit(c+152,"tail_one_valid_vec_3",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1);
    tracep->declBus(c+153,"slice_valid_vec_0",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1, 0,0);
    tracep->declBus(c+154,"slice_valid_vec_1",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1, 0,0);
    tracep->declBus(c+155,"slice_valid_vec_2",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1, 0,0);
    tracep->declBus(c+156,"slice_valid_vec_3",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1, 0,0);
    tracep->declBit(c+157,"tmp_1",-1, FST_VD_IMPLICIT,FST_VT_SV_LOGIC, false,-1);
    tracep->declBus(c+158,"tmp_instr_slices_0_payload",-1, FST_VD_IMPLICIT,FST_VT_SV_LOGIC, false,-1, 15,0);
    tracep->declBus(c+159,"tmp_2",-1, FST_VD_IMPLICIT,FST_VT_SV_LOGIC, false,-1, 1,0);
    tracep->declBus(c+160,"tmp_3",-1, FST_VD_IMPLICIT,FST_VT_SV_LOGIC, false,-1, 1,0);
    tracep->declBus(c+161,"tmp_4",-1, FST_VD_IMPLICIT,FST_VT_SV_LOGIC, false,-1, 1,0);
    tracep->declBus(c+162,"tmp_5",-1, FST_VD_IMPLICIT,FST_VT_SV_LOGIC, false,-1, 1,0);
    tracep->declBit(c+163,"ibus_rsp_fire",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1);
    tracep->declBus(c+164,"instr_push_valid_vec",-1, FST_VD_IMPLICIT,FST_VT_SV_LOGIC, false,-1, 3,0);
    tracep->declBit(c+165,"toplevel_instrFifo_io_push_0_fire",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1);
    tracep->declBus(c+166,"instr_pop_valid",-1, FST_VD_IMPLICIT,FST_VT_SV_LOGIC, false,-1, 1,0);
    tracep->declBit(c+167,"toplevel_instrFifo_io_pop_0_fire",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1);
    tracep->declBit(c+168,"toplevel_instrFifo_io_pop_1_fire",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1);
    tracep->declBus(c+169,"pc_pop_offset",-1, FST_VD_IMPLICIT,FST_VT_SV_LOGIC, false,-1, 2,0);
    tracep->declBus(c+170,"pc_step_all_1",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1, 2,0);
    tracep->declBus(c+171,"pc_step_all_2",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1, 2,0);
    tracep->declBus(c+172,"real_instr_0",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1, 31,0);
    tracep->declBus(c+173,"real_instr_1",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1, 31,0);
    tracep->declBus(c+174,"pc_step_0",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1, 2,0);
    tracep->declBus(c+175,"pc_step_1",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1, 2,0);
    tracep->declBit(c+176,"tmp_real_instr_0",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1);
    tracep->declBit(c+177,"tmp_real_instr_1",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1);
    tracep->declBit(c+178,"toplevel_addressFifo_io_pop_fire",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1);
    tracep->declQuad(c+179,"tmp_2_string",-1, FST_VD_IMPLICIT,FST_VT_SV_LOGIC, false,-1, 55,0);
    tracep->declQuad(c+181,"tmp_3_string",-1, FST_VD_IMPLICIT,FST_VT_SV_LOGIC, false,-1, 55,0);
    tracep->declQuad(c+183,"tmp_4_string",-1, FST_VD_IMPLICIT,FST_VT_SV_LOGIC, false,-1, 55,0);
    tracep->declQuad(c+185,"tmp_5_string",-1, FST_VD_IMPLICIT,FST_VT_SV_LOGIC, false,-1, 55,0);
    tracep->pushNamePrefix("addressFifo ");
    tracep->declBit(c+187,"io_push_valid",-1,FST_VD_INPUT,FST_VT_VCD_WIRE, false,-1);
    tracep->declBit(c+188,"io_push_ready",-1,FST_VD_OUTPUT,FST_VT_VCD_WIRE, false,-1);
    tracep->declBus(c+189,"io_push_payload",-1,FST_VD_INPUT,FST_VT_VCD_WIRE, false,-1, 31,0);
    tracep->declBit(c+190,"io_pop_valid",-1,FST_VD_OUTPUT,FST_VT_VCD_WIRE, false,-1);
    tracep->declBit(c+191,"io_pop_ready",-1,FST_VD_INPUT,FST_VT_VCD_WIRE, false,-1);
    tracep->declBus(c+192,"io_pop_payload",-1,FST_VD_OUTPUT,FST_VT_VCD_WIRE, false,-1, 31,0);
    tracep->declBus(c+193,"io_head",-1,FST_VD_OUTPUT,FST_VT_VCD_WIRE, false,-1, 31,0);
    tracep->declBit(c+194,"io_flush",-1,FST_VD_INPUT,FST_VT_VCD_WIRE, false,-1);
    tracep->declBus(c+195,"io_occupancy",-1,FST_VD_OUTPUT,FST_VT_VCD_WIRE, false,-1, 2,0);
    tracep->declBit(c+196,"clk",-1,FST_VD_INPUT,FST_VT_VCD_WIRE, false,-1);
    tracep->declBit(c+197,"resetn",-1,FST_VD_INPUT,FST_VT_VCD_WIRE, false,-1);
    tracep->declBus(c+198,"tmp_pushPtr_valueNext",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1, 2,0);
    tracep->declBus(c+199,"tmp_pushPtr_valueNext_1",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1, 0,0);
    tracep->declBus(c+200,"tmp_popPtr_valueNext",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1, 2,0);
    tracep->declBus(c+201,"tmp_popPtr_valueNext_1",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1, 0,0);
    tracep->declBus(c+202,"tmp_readed",-1, FST_VD_IMPLICIT,FST_VT_SV_LOGIC, false,-1, 31,0);
    tracep->declBus(c+203,"tmp_io_occupancy",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1, 2,0);
    tracep->declBus(c+204,"vec_0",-1, FST_VD_IMPLICIT,FST_VT_SV_LOGIC, false,-1, 31,0);
    tracep->declBus(c+205,"vec_1",-1, FST_VD_IMPLICIT,FST_VT_SV_LOGIC, false,-1, 31,0);
    tracep->declBus(c+206,"vec_2",-1, FST_VD_IMPLICIT,FST_VT_SV_LOGIC, false,-1, 31,0);
    tracep->declBus(c+207,"vec_3",-1, FST_VD_IMPLICIT,FST_VT_SV_LOGIC, false,-1, 31,0);
    tracep->declBus(c+208,"vec_4",-1, FST_VD_IMPLICIT,FST_VT_SV_LOGIC, false,-1, 31,0);
    tracep->declBus(c+209,"vec_5",-1, FST_VD_IMPLICIT,FST_VT_SV_LOGIC, false,-1, 31,0);
    tracep->declBit(c+210,"pushPtr_willIncrement",-1, FST_VD_IMPLICIT,FST_VT_SV_LOGIC, false,-1);
    tracep->declBit(c+211,"pushPtr_willClear",-1, FST_VD_IMPLICIT,FST_VT_SV_LOGIC, false,-1);
    tracep->declBus(c+212,"pushPtr_valueNext",-1, FST_VD_IMPLICIT,FST_VT_SV_LOGIC, false,-1, 2,0);
    tracep->declBus(c+213,"pushPtr_value",-1, FST_VD_IMPLICIT,FST_VT_SV_LOGIC, false,-1, 2,0);
    tracep->declBit(c+214,"pushPtr_willOverflowIfInc",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1);
    tracep->declBit(c+215,"pushPtr_willOverflow",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1);
    tracep->declBit(c+216,"popPtr_willIncrement",-1, FST_VD_IMPLICIT,FST_VT_SV_LOGIC, false,-1);
    tracep->declBit(c+217,"popPtr_willClear",-1, FST_VD_IMPLICIT,FST_VT_SV_LOGIC, false,-1);
    tracep->declBus(c+218,"popPtr_valueNext",-1, FST_VD_IMPLICIT,FST_VT_SV_LOGIC, false,-1, 2,0);
    tracep->declBus(c+219,"popPtr_value",-1, FST_VD_IMPLICIT,FST_VT_SV_LOGIC, false,-1, 2,0);
    tracep->declBit(c+220,"popPtr_willOverflowIfInc",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1);
    tracep->declBit(c+221,"popPtr_willOverflow",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1);
    tracep->declBit(c+222,"ptrMatch",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1);
    tracep->declBit(c+223,"risingOccupancy",-1, FST_VD_IMPLICIT,FST_VT_SV_LOGIC, false,-1);
    tracep->declBit(c+224,"empty",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1);
    tracep->declBit(c+225,"full",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1);
    tracep->declBit(c+226,"pushing",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1);
    tracep->declBit(c+227,"popping",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1);
    tracep->declBus(c+228,"readed",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1, 31,0);
    tracep->declBus(c+229,"tmp_1",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1, 7,0);
    tracep->declBus(c+230,"ptrDif",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1, 2,0);
    tracep->popNamePrefix(1);
    tracep->pushNamePrefix("instrFifo ");
    tracep->declBit(c+231,"io_push_0_valid",-1,FST_VD_INPUT,FST_VT_VCD_WIRE, false,-1);
    tracep->declBit(c+232,"io_push_0_ready",-1,FST_VD_OUTPUT,FST_VT_VCD_WIRE, false,-1);
    tracep->declQuad(c+233,"io_push_0_payload",-1,FST_VD_INPUT,FST_VT_VCD_WIRE, false,-1, 32,0);
    tracep->declBit(c+235,"io_push_1_valid",-1,FST_VD_INPUT,FST_VT_VCD_WIRE, false,-1);
    tracep->declBit(c+236,"io_push_1_ready",-1,FST_VD_OUTPUT,FST_VT_VCD_WIRE, false,-1);
    tracep->declQuad(c+237,"io_push_1_payload",-1,FST_VD_INPUT,FST_VT_VCD_WIRE, false,-1, 32,0);
    tracep->declBit(c+239,"io_push_2_valid",-1,FST_VD_INPUT,FST_VT_VCD_WIRE, false,-1);
    tracep->declBit(c+240,"io_push_2_ready",-1,FST_VD_OUTPUT,FST_VT_VCD_WIRE, false,-1);
    tracep->declQuad(c+241,"io_push_2_payload",-1,FST_VD_INPUT,FST_VT_VCD_WIRE, false,-1, 32,0);
    tracep->declBit(c+243,"io_push_3_valid",-1,FST_VD_INPUT,FST_VT_VCD_WIRE, false,-1);
    tracep->declBit(c+244,"io_push_3_ready",-1,FST_VD_OUTPUT,FST_VT_VCD_WIRE, false,-1);
    tracep->declQuad(c+245,"io_push_3_payload",-1,FST_VD_INPUT,FST_VT_VCD_WIRE, false,-1, 32,0);
    tracep->declBit(c+247,"io_pop_0_valid",-1,FST_VD_OUTPUT,FST_VT_VCD_WIRE, false,-1);
    tracep->declBit(c+248,"io_pop_0_ready",-1,FST_VD_INPUT,FST_VT_VCD_WIRE, false,-1);
    tracep->declQuad(c+249,"io_pop_0_payload",-1,FST_VD_OUTPUT,FST_VT_VCD_WIRE, false,-1, 32,0);
    tracep->declBit(c+251,"io_pop_1_valid",-1,FST_VD_OUTPUT,FST_VT_VCD_WIRE, false,-1);
    tracep->declBit(c+252,"io_pop_1_ready",-1,FST_VD_INPUT,FST_VT_VCD_WIRE, false,-1);
    tracep->declQuad(c+253,"io_pop_1_payload",-1,FST_VD_OUTPUT,FST_VT_VCD_WIRE, false,-1, 32,0);
    tracep->declBit(c+255,"io_flush",-1,FST_VD_INPUT,FST_VT_VCD_WIRE, false,-1);
    tracep->declBus(c+256,"io_occupancy",-1,FST_VD_OUTPUT,FST_VT_VCD_WIRE, false,-1, 3,0);
    tracep->declBit(c+257,"io_ov_waterline",-1,FST_VD_OUTPUT,FST_VT_VCD_WIRE, false,-1);
    tracep->declBit(c+258,"clk",-1,FST_VD_INPUT,FST_VT_VCD_WIRE, false,-1);
    tracep->declBit(c+259,"resetn",-1,FST_VD_INPUT,FST_VT_VCD_WIRE, false,-1);
    tracep->declBus(c+260,"tmp_inc_num_1",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1, 1,0);
    tracep->declBus(c+261,"tmp_inc_num_2",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1, 1,0);
    tracep->declBus(c+262,"tmp_inc_num_3",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1, 0,0);
    tracep->declBus(c+263,"tmp_inc_num_4",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1, 2,0);
    tracep->declBus(c+264,"tmp_inc_num_5",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1, 1,0);
    tracep->declBus(c+265,"tmp_inc_num_6",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1, 1,0);
    tracep->declBus(c+266,"tmp_inc_num_7",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1, 0,0);
    tracep->declBus(c+267,"tmp_dec_num_1",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1, 1,0);
    tracep->declBus(c+268,"tmp_dec_num_2",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1, 0,0);
    tracep->declBus(c+269,"tmp_io_push_0_ready",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1, 3,0);
    tracep->declBus(c+270,"tmp_io_push_1_ready",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1, 3,0);
    tracep->declBus(c+271,"tmp_io_push_2_ready",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1, 3,0);
    tracep->declBus(c+272,"tmp_io_push_3_ready",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1, 3,0);
    tracep->declBus(c+273,"tmp_pushPtrs_inc_0",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1, 4,0);
    tracep->declBus(c+274,"tmp_pushPtrs_inc_0_1",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1, 0,0);
    tracep->declBus(c+275,"tmp_pushPtrs_inc_1",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1, 4,0);
    tracep->declBus(c+276,"tmp_pushPtrs_inc_1_1",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1, 1,0);
    tracep->declBus(c+277,"tmp_pushPtrs_inc_2",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1, 4,0);
    tracep->declBus(c+278,"tmp_pushPtrs_inc_2_1",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1, 2,0);
    tracep->declBus(c+279,"tmp_pushPtrs_inc_3",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1, 4,0);
    tracep->declBus(c+280,"tmp_pushPtrs_inc_3_1",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1, 2,0);
    tracep->declBus(c+281,"tmp_popPtrs_inc_0",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1, 4,0);
    tracep->declBus(c+282,"tmp_popPtrs_inc_0_1",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1, 0,0);
    tracep->declBus(c+283,"tmp_popPtrs_inc_1",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1, 4,0);
    tracep->declBus(c+284,"tmp_popPtrs_inc_1_1",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1, 1,0);
    tracep->declQuad(c+285,"tmp_readedVec_0",-1, FST_VD_IMPLICIT,FST_VT_SV_LOGIC, false,-1, 32,0);
    tracep->declBus(c+287,"tmp_readedVec_0_1",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1, 3,0);
    tracep->declQuad(c+288,"tmp_readedVec_1",-1, FST_VD_IMPLICIT,FST_VT_SV_LOGIC, false,-1, 32,0);
    tracep->declBus(c+290,"tmp_readedVec_1_1",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1, 3,0);
    tracep->declBus(c+291,"tmp_when",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1, 2,0);
    tracep->declBus(c+292,"tmp_pushPtrGlobalInc",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1, 4,0);
    tracep->declBus(c+293,"tmp_pushPtrGlobalInc_1",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1, 3,0);
    tracep->declBus(c+294,"tmp_popPtrGlobalInc",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1, 4,0);
    tracep->declBus(c+295,"tmp_popPtrGlobalInc_1",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1, 2,0);
    tracep->declBus(c+296,"tmp_pushPtrGlobal",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1, 4,0);
    tracep->declBus(c+297,"tmp_popPtrGlobal",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1, 4,0);
    tracep->declBus(c+298,"tmp_io_occupancy",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1, 3,0);
    tracep->declQuad(c+299,"vec_0",-1, FST_VD_IMPLICIT,FST_VT_SV_LOGIC, false,-1, 32,0);
    tracep->declQuad(c+301,"vec_1",-1, FST_VD_IMPLICIT,FST_VT_SV_LOGIC, false,-1, 32,0);
    tracep->declQuad(c+303,"vec_2",-1, FST_VD_IMPLICIT,FST_VT_SV_LOGIC, false,-1, 32,0);
    tracep->declQuad(c+305,"vec_3",-1, FST_VD_IMPLICIT,FST_VT_SV_LOGIC, false,-1, 32,0);
    tracep->declQuad(c+307,"vec_4",-1, FST_VD_IMPLICIT,FST_VT_SV_LOGIC, false,-1, 32,0);
    tracep->declQuad(c+309,"vec_5",-1, FST_VD_IMPLICIT,FST_VT_SV_LOGIC, false,-1, 32,0);
    tracep->declQuad(c+311,"vec_6",-1, FST_VD_IMPLICIT,FST_VT_SV_LOGIC, false,-1, 32,0);
    tracep->declQuad(c+313,"vec_7",-1, FST_VD_IMPLICIT,FST_VT_SV_LOGIC, false,-1, 32,0);
    tracep->declQuad(c+315,"vec_8",-1, FST_VD_IMPLICIT,FST_VT_SV_LOGIC, false,-1, 32,0);
    tracep->declQuad(c+317,"vec_9",-1, FST_VD_IMPLICIT,FST_VT_SV_LOGIC, false,-1, 32,0);
    tracep->declQuad(c+319,"vec_10",-1, FST_VD_IMPLICIT,FST_VT_SV_LOGIC, false,-1, 32,0);
    tracep->declQuad(c+321,"vec_11",-1, FST_VD_IMPLICIT,FST_VT_SV_LOGIC, false,-1, 32,0);
    tracep->declQuad(c+323,"vec_12",-1, FST_VD_IMPLICIT,FST_VT_SV_LOGIC, false,-1, 32,0);
    tracep->declQuad(c+325,"vec_13",-1, FST_VD_IMPLICIT,FST_VT_SV_LOGIC, false,-1, 32,0);
    tracep->declBus(c+327,"pushPtrGlobal",-1, FST_VD_IMPLICIT,FST_VT_SV_LOGIC, false,-1, 3,0);
    tracep->declBus(c+328,"popPtrGlobal",-1, FST_VD_IMPLICIT,FST_VT_SV_LOGIC, false,-1, 3,0);
    tracep->declBit(c+329,"ptrMatch",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1);
    tracep->declBit(c+330,"risingOccupancy",-1, FST_VD_IMPLICIT,FST_VT_SV_LOGIC, false,-1);
    tracep->declBit(c+331,"empty",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1);
    tracep->declBit(c+332,"full",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1);
    tracep->declBit(c+333,"pushing_vec_0",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1);
    tracep->declBit(c+334,"pushing_vec_1",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1);
    tracep->declBit(c+335,"pushing_vec_2",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1);
    tracep->declBit(c+336,"pushing_vec_3",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1);
    tracep->declBit(c+337,"popping_vec_0",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1);
    tracep->declBit(c+338,"popping_vec_1",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1);
    tracep->declBit(c+339,"tmp_inc_num",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1);
    tracep->declBus(c+340,"inc_num",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1, 2,0);
    tracep->declBit(c+341,"tmp_dec_num",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1);
    tracep->declBus(c+342,"dec_num",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1, 1,0);
    tracep->declBus(c+343,"pushPtrs_0",-1, FST_VD_IMPLICIT,FST_VT_SV_LOGIC, false,-1, 4,0);
    tracep->declBus(c+344,"pushPtrs_1",-1, FST_VD_IMPLICIT,FST_VT_SV_LOGIC, false,-1, 4,0);
    tracep->declBus(c+345,"pushPtrs_2",-1, FST_VD_IMPLICIT,FST_VT_SV_LOGIC, false,-1, 4,0);
    tracep->declBus(c+346,"pushPtrs_3",-1, FST_VD_IMPLICIT,FST_VT_SV_LOGIC, false,-1, 4,0);
    tracep->declBus(c+347,"popPtrs_0",-1, FST_VD_IMPLICIT,FST_VT_SV_LOGIC, false,-1, 4,0);
    tracep->declBus(c+348,"popPtrs_1",-1, FST_VD_IMPLICIT,FST_VT_SV_LOGIC, false,-1, 4,0);
    tracep->declBus(c+349,"pushPtrs_inc_0",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1, 4,0);
    tracep->declBus(c+350,"pushPtrs_inc_1",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1, 4,0);
    tracep->declBus(c+351,"pushPtrs_inc_2",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1, 4,0);
    tracep->declBus(c+352,"pushPtrs_inc_3",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1, 4,0);
    tracep->declBus(c+353,"popPtrs_inc_0",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1, 4,0);
    tracep->declBus(c+354,"popPtrs_inc_1",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1, 4,0);
    tracep->declQuad(c+355,"readedVec_0",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1, 32,0);
    tracep->declQuad(c+357,"readedVec_1",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1, 32,0);
    tracep->declBus(c+359,"tmp_1",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1, 15,0);
    tracep->declBus(c+360,"tmp_2",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1, 15,0);
    tracep->declBus(c+361,"tmp_3",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1, 15,0);
    tracep->declBus(c+362,"tmp_4",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1, 15,0);
    tracep->declBus(c+363,"pushPtrGlobalInc",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1, 4,0);
    tracep->declBus(c+364,"popPtrGlobalInc",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1, 4,0);
    tracep->declBus(c+365,"ptrDif",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1, 3,0);
    tracep->popNamePrefix(1);
    tracep->pushNamePrefix("instr_pop_valid_popc ");
    tracep->declBit(c+366,"din_vld",-1,FST_VD_INPUT,FST_VT_VCD_WIRE, false,-1);
    tracep->declBus(c+367,"data_in",-1,FST_VD_INPUT,FST_VT_VCD_WIRE, false,-1, 1,0);
    tracep->declBus(c+368,"cnt_out",-1,FST_VD_OUTPUT,FST_VT_VCD_WIRE, false,-1, 1,0);
    tracep->declBus(c+369,"popsum_init_0",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1, 0,0);
    tracep->declBus(c+370,"popsum_init_1",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1, 0,0);
    tracep->declBus(c+371,"popsum_stage1_ele0",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1, 1,0);
    tracep->popNamePrefix(1);
    tracep->pushNamePrefix("instr_push_valid_vec_popc ");
    tracep->declBit(c+372,"din_vld",-1,FST_VD_INPUT,FST_VT_VCD_WIRE, false,-1);
    tracep->declBus(c+373,"data_in",-1,FST_VD_INPUT,FST_VT_VCD_WIRE, false,-1, 3,0);
    tracep->declBus(c+374,"cnt_out",-1,FST_VD_OUTPUT,FST_VT_VCD_WIRE, false,-1, 2,0);
    tracep->declBus(c+375,"popsum_init_0",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1, 0,0);
    tracep->declBus(c+376,"popsum_init_1",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1, 0,0);
    tracep->declBus(c+377,"popsum_init_2",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1, 0,0);
    tracep->declBus(c+378,"popsum_init_3",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1, 0,0);
    tracep->declBus(c+379,"popsum_stage1_ele0",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1, 1,0);
    tracep->declBus(c+380,"popsum_stage1_ele1",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1, 1,0);
    tracep->declBus(c+381,"popsum_stage2_ele0",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1, 2,0);
    tracep->popNamePrefix(1);
    tracep->pushNamePrefix("rvcDecompressor_2 ");
    tracep->declBus(c+382,"i",-1,FST_VD_INPUT,FST_VT_VCD_WIRE, false,-1, 31,0);
    tracep->declBus(c+383,"decompInstr_inst",-1,FST_VD_OUTPUT,FST_VT_VCD_WIRE, false,-1, 31,0);
    tracep->declBit(c+384,"decompInstr_illegal",-1,FST_VD_OUTPUT,FST_VT_VCD_WIRE, false,-1);
    tracep->declBus(c+385,"tmp_tmp_ret_inst",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1, 11,0);
    tracep->declBus(c+386,"tmp_tmp_ret_inst_1",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1, 5,0);
    tracep->declBus(c+387,"tmp_ret_inst_1",-1, FST_VD_IMPLICIT,FST_VT_SV_LOGIC, false,-1, 31,0);
    tracep->declBus(c+388,"tmp_ret_inst_2",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1, 1,0);
    tracep->declBus(c+389,"tmp_ret_inst_3",-1, FST_VD_IMPLICIT,FST_VT_SV_LOGIC, false,-1, 2,0);
    tracep->declBus(c+390,"tmp_ret_inst_4",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1, 2,0);
    tracep->declBus(c+391,"tmp_ret_inst_5",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1, 6,0);
    tracep->declBus(c+392,"tmp_ret_inst_6",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1, 4,0);
    tracep->declBit(c+393,"tmp_ret_inst_7",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1);
    tracep->declBus(c+394,"tmp_ret_inst_8",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1, 4,0);
    tracep->declBus(c+395,"tmp_ret_inst_9",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1, 11,0);
    tracep->declBus(c+396,"tmp_ret_inst_10",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1, 11,0);
    tracep->declBus(c+397,"ret_inst",-1, FST_VD_IMPLICIT,FST_VT_SV_LOGIC, false,-1, 31,0);
    tracep->declBit(c+398,"ret_illegal",-1, FST_VD_IMPLICIT,FST_VT_SV_LOGIC, false,-1);
    tracep->declBus(c+399,"rch",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1, 4,0);
    tracep->declBus(c+400,"rcl",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1, 4,0);
    tracep->declBus(c+401,"addi5spnImm",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1, 11,0);
    tracep->declBus(c+402,"lwImm",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1, 11,0);
    tracep->declBus(c+403,"ldImm",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1, 11,0);
    tracep->declBit(c+404,"tmp_addImm",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1);
    tracep->declBus(c+405,"addImm",-1, FST_VD_IMPLICIT,FST_VT_SV_LOGIC, false,-1, 11,0);
    tracep->declBit(c+406,"tmp_jalImm",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1);
    tracep->declBus(c+407,"tmp_jalImm_1",-1, FST_VD_IMPLICIT,FST_VT_SV_LOGIC, false,-1, 9,0);
    tracep->declBus(c+408,"jalImm",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1, 20,0);
    tracep->declBit(c+409,"tmp_luiImm",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1);
    tracep->declBus(c+410,"tmp_luiImm_1",-1, FST_VD_IMPLICIT,FST_VT_SV_LOGIC, false,-1, 14,0);
    tracep->declBus(c+411,"luiImm",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1, 31,0);
    tracep->declBus(c+412,"shiftImm",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1, 4,0);
    tracep->declBit(c+413,"tmp_addi16spImm",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1);
    tracep->declBus(c+414,"tmp_addi16spImm_1",-1, FST_VD_IMPLICIT,FST_VT_SV_LOGIC, false,-1, 2,0);
    tracep->declBus(c+415,"addi16spImm",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1, 11,0);
    tracep->declBit(c+416,"tmp_jImm",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1);
    tracep->declBus(c+417,"tmp_jImm_1",-1, FST_VD_IMPLICIT,FST_VT_SV_LOGIC, false,-1, 9,0);
    tracep->declBus(c+418,"jImm",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1, 20,0);
    tracep->declBit(c+419,"tmp_bImm",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1);
    tracep->declBus(c+420,"tmp_bImm_1",-1, FST_VD_IMPLICIT,FST_VT_SV_LOGIC, false,-1, 4,0);
    tracep->declBus(c+421,"bImm",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1, 12,0);
    tracep->declBus(c+422,"x0",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1, 4,0);
    tracep->declBus(c+423,"x1",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1, 4,0);
    tracep->declBus(c+424,"x2",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1, 4,0);
    tracep->declBus(c+425,"tmp_ret_inst",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1, 31,0);
    tracep->popNamePrefix(1);
    tracep->pushNamePrefix("rvcDecompressor_3 ");
    tracep->declBus(c+426,"i",-1,FST_VD_INPUT,FST_VT_VCD_WIRE, false,-1, 31,0);
    tracep->declBus(c+427,"decompInstr_inst",-1,FST_VD_OUTPUT,FST_VT_VCD_WIRE, false,-1, 31,0);
    tracep->declBit(c+428,"decompInstr_illegal",-1,FST_VD_OUTPUT,FST_VT_VCD_WIRE, false,-1);
    tracep->declBus(c+429,"tmp_tmp_ret_inst",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1, 11,0);
    tracep->declBus(c+430,"tmp_tmp_ret_inst_1",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1, 5,0);
    tracep->declBus(c+431,"tmp_ret_inst_1",-1, FST_VD_IMPLICIT,FST_VT_SV_LOGIC, false,-1, 31,0);
    tracep->declBus(c+432,"tmp_ret_inst_2",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1, 1,0);
    tracep->declBus(c+433,"tmp_ret_inst_3",-1, FST_VD_IMPLICIT,FST_VT_SV_LOGIC, false,-1, 2,0);
    tracep->declBus(c+434,"tmp_ret_inst_4",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1, 2,0);
    tracep->declBus(c+435,"tmp_ret_inst_5",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1, 6,0);
    tracep->declBus(c+436,"tmp_ret_inst_6",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1, 4,0);
    tracep->declBit(c+437,"tmp_ret_inst_7",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1);
    tracep->declBus(c+438,"tmp_ret_inst_8",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1, 4,0);
    tracep->declBus(c+439,"tmp_ret_inst_9",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1, 11,0);
    tracep->declBus(c+440,"tmp_ret_inst_10",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1, 11,0);
    tracep->declBus(c+441,"ret_inst",-1, FST_VD_IMPLICIT,FST_VT_SV_LOGIC, false,-1, 31,0);
    tracep->declBit(c+442,"ret_illegal",-1, FST_VD_IMPLICIT,FST_VT_SV_LOGIC, false,-1);
    tracep->declBus(c+443,"rch",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1, 4,0);
    tracep->declBus(c+444,"rcl",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1, 4,0);
    tracep->declBus(c+445,"addi5spnImm",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1, 11,0);
    tracep->declBus(c+446,"lwImm",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1, 11,0);
    tracep->declBus(c+447,"ldImm",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1, 11,0);
    tracep->declBit(c+448,"tmp_addImm",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1);
    tracep->declBus(c+449,"addImm",-1, FST_VD_IMPLICIT,FST_VT_SV_LOGIC, false,-1, 11,0);
    tracep->declBit(c+450,"tmp_jalImm",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1);
    tracep->declBus(c+451,"tmp_jalImm_1",-1, FST_VD_IMPLICIT,FST_VT_SV_LOGIC, false,-1, 9,0);
    tracep->declBus(c+452,"jalImm",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1, 20,0);
    tracep->declBit(c+453,"tmp_luiImm",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1);
    tracep->declBus(c+454,"tmp_luiImm_1",-1, FST_VD_IMPLICIT,FST_VT_SV_LOGIC, false,-1, 14,0);
    tracep->declBus(c+455,"luiImm",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1, 31,0);
    tracep->declBus(c+456,"shiftImm",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1, 4,0);
    tracep->declBit(c+457,"tmp_addi16spImm",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1);
    tracep->declBus(c+458,"tmp_addi16spImm_1",-1, FST_VD_IMPLICIT,FST_VT_SV_LOGIC, false,-1, 2,0);
    tracep->declBus(c+459,"addi16spImm",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1, 11,0);
    tracep->declBit(c+460,"tmp_jImm",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1);
    tracep->declBus(c+461,"tmp_jImm_1",-1, FST_VD_IMPLICIT,FST_VT_SV_LOGIC, false,-1, 9,0);
    tracep->declBus(c+462,"jImm",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1, 20,0);
    tracep->declBit(c+463,"tmp_bImm",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1);
    tracep->declBus(c+464,"tmp_bImm_1",-1, FST_VD_IMPLICIT,FST_VT_SV_LOGIC, false,-1, 4,0);
    tracep->declBus(c+465,"bImm",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1, 12,0);
    tracep->declBus(c+466,"x0",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1, 4,0);
    tracep->declBus(c+467,"x1",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1, 4,0);
    tracep->declBus(c+468,"x2",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1, 4,0);
    tracep->declBus(c+469,"tmp_ret_inst",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1, 31,0);
    tracep->popNamePrefix(1);
    tracep->pushNamePrefix("trailone_index_0 ");
    tracep->declBit(c+470,"mode",-1,FST_VD_INPUT,FST_VT_VCD_WIRE, false,-1);
    tracep->declBit(c+471,"lead",-1,FST_VD_INPUT,FST_VT_VCD_WIRE, false,-1);
    tracep->declBit(c+472,"trail",-1,FST_VD_INPUT,FST_VT_VCD_WIRE, false,-1);
    tracep->declBus(c+473,"data_in",-1,FST_VD_INPUT,FST_VT_VCD_WIRE, false,-1, 3,0);
    tracep->declBus(c+474,"cnt_out",-1,FST_VD_OUTPUT,FST_VT_VCD_WIRE, false,-1, 2,0);
    tracep->declBus(c+475,"tmp_cnt_out",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1, 2,0);
    tracep->declBus(c+476,"data_s",-1, FST_VD_IMPLICIT,FST_VT_SV_LOGIC, false,-1, 3,0);
    tracep->declBus(c+477,"datain_reverse",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1, 3,0);
    tracep->declBus(c+478,"stage_node_0",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1, 3,0);
    tracep->declBus(c+479,"stage_node_1",-1, FST_VD_IMPLICIT,FST_VT_SV_LOGIC, false,-1, 1,0);
    tracep->declBus(c+480,"stage_index1_0",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1, 1,0);
    tracep->declBus(c+481,"stage_index1_1",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1, 1,0);
    tracep->declBus(c+482,"stage_index2_0",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1, 1,0);
    tracep->declBit(c+483,"empty",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1);
    tracep->declBus(c+484,"out_remap",-1, FST_VD_IMPLICIT,FST_VT_SV_LOGIC, false,-1, 1,0);
    tracep->popNamePrefix(1);
    tracep->pushNamePrefix("trailone_index_1 ");
    tracep->declBit(c+485,"mode",-1,FST_VD_INPUT,FST_VT_VCD_WIRE, false,-1);
    tracep->declBit(c+486,"lead",-1,FST_VD_INPUT,FST_VT_VCD_WIRE, false,-1);
    tracep->declBit(c+487,"trail",-1,FST_VD_INPUT,FST_VT_VCD_WIRE, false,-1);
    tracep->declBus(c+488,"data_in",-1,FST_VD_INPUT,FST_VT_VCD_WIRE, false,-1, 3,0);
    tracep->declBus(c+489,"cnt_out",-1,FST_VD_OUTPUT,FST_VT_VCD_WIRE, false,-1, 2,0);
    tracep->declBus(c+490,"tmp_cnt_out",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1, 2,0);
    tracep->declBus(c+491,"data_s",-1, FST_VD_IMPLICIT,FST_VT_SV_LOGIC, false,-1, 3,0);
    tracep->declBus(c+492,"datain_reverse",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1, 3,0);
    tracep->declBus(c+493,"stage_node_0",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1, 3,0);
    tracep->declBus(c+494,"stage_node_1",-1, FST_VD_IMPLICIT,FST_VT_SV_LOGIC, false,-1, 1,0);
    tracep->declBus(c+495,"stage_index1_0",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1, 1,0);
    tracep->declBus(c+496,"stage_index1_1",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1, 1,0);
    tracep->declBus(c+497,"stage_index2_0",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1, 1,0);
    tracep->declBit(c+498,"empty",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1);
    tracep->declBus(c+499,"out_remap",-1, FST_VD_IMPLICIT,FST_VT_SV_LOGIC, false,-1, 1,0);
    tracep->popNamePrefix(1);
    tracep->pushNamePrefix("trailone_index_2 ");
    tracep->declBit(c+500,"mode",-1,FST_VD_INPUT,FST_VT_VCD_WIRE, false,-1);
    tracep->declBit(c+501,"lead",-1,FST_VD_INPUT,FST_VT_VCD_WIRE, false,-1);
    tracep->declBit(c+502,"trail",-1,FST_VD_INPUT,FST_VT_VCD_WIRE, false,-1);
    tracep->declBus(c+503,"data_in",-1,FST_VD_INPUT,FST_VT_VCD_WIRE, false,-1, 3,0);
    tracep->declBus(c+504,"cnt_out",-1,FST_VD_OUTPUT,FST_VT_VCD_WIRE, false,-1, 2,0);
    tracep->declBus(c+505,"tmp_cnt_out",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1, 2,0);
    tracep->declBus(c+506,"data_s",-1, FST_VD_IMPLICIT,FST_VT_SV_LOGIC, false,-1, 3,0);
    tracep->declBus(c+507,"datain_reverse",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1, 3,0);
    tracep->declBus(c+508,"stage_node_0",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1, 3,0);
    tracep->declBus(c+509,"stage_node_1",-1, FST_VD_IMPLICIT,FST_VT_SV_LOGIC, false,-1, 1,0);
    tracep->declBus(c+510,"stage_index1_0",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1, 1,0);
    tracep->declBus(c+511,"stage_index1_1",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1, 1,0);
    tracep->declBus(c+512,"stage_index2_0",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1, 1,0);
    tracep->declBit(c+513,"empty",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1);
    tracep->declBus(c+514,"out_remap",-1, FST_VD_IMPLICIT,FST_VT_SV_LOGIC, false,-1, 1,0);
    tracep->popNamePrefix(1);
    tracep->pushNamePrefix("trailone_index_3 ");
    tracep->declBit(c+515,"mode",-1,FST_VD_INPUT,FST_VT_VCD_WIRE, false,-1);
    tracep->declBit(c+516,"lead",-1,FST_VD_INPUT,FST_VT_VCD_WIRE, false,-1);
    tracep->declBit(c+517,"trail",-1,FST_VD_INPUT,FST_VT_VCD_WIRE, false,-1);
    tracep->declBus(c+518,"data_in",-1,FST_VD_INPUT,FST_VT_VCD_WIRE, false,-1, 3,0);
    tracep->declBus(c+519,"cnt_out",-1,FST_VD_OUTPUT,FST_VT_VCD_WIRE, false,-1, 2,0);
    tracep->declBus(c+520,"tmp_cnt_out",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1, 2,0);
    tracep->declBus(c+521,"data_s",-1, FST_VD_IMPLICIT,FST_VT_SV_LOGIC, false,-1, 3,0);
    tracep->declBus(c+522,"datain_reverse",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1, 3,0);
    tracep->declBus(c+523,"stage_node_0",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1, 3,0);
    tracep->declBus(c+524,"stage_node_1",-1, FST_VD_IMPLICIT,FST_VT_SV_LOGIC, false,-1, 1,0);
    tracep->declBus(c+525,"stage_index1_0",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1, 1,0);
    tracep->declBus(c+526,"stage_index1_1",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1, 1,0);
    tracep->declBus(c+527,"stage_index2_0",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1, 1,0);
    tracep->declBit(c+528,"empty",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1);
    tracep->declBus(c+529,"out_remap",-1, FST_VD_IMPLICIT,FST_VT_SV_LOGIC, false,-1, 1,0);
    tracep->popNamePrefix(1);
    tracep->pushNamePrefix("validNumFifo ");
    tracep->declBit(c+530,"push_valid",-1,FST_VD_INPUT,FST_VT_VCD_WIRE, false,-1);
    tracep->declBit(c+531,"push_ready",-1,FST_VD_OUTPUT,FST_VT_VCD_WIRE, false,-1);
    tracep->declBus(c+532,"push_payload",-1,FST_VD_INPUT,FST_VT_VCD_WIRE, false,-1, 2,0);
    tracep->declBit(c+533,"pop_valid",-1,FST_VD_INPUT,FST_VT_VCD_WIRE, false,-1);
    tracep->declBit(c+534,"pop_ready",-1,FST_VD_OUTPUT,FST_VT_VCD_WIRE, false,-1);
    tracep->declBus(c+535,"pop_pop_req_num",-1,FST_VD_INPUT,FST_VT_VCD_WIRE, false,-1, 2,0);
    tracep->declBus(c+536,"pop_pop_out_data",-1,FST_VD_OUTPUT,FST_VT_VCD_WIRE, false,-1, 2,0);
    tracep->declBit(c+537,"pop_pop_real",-1,FST_VD_OUTPUT,FST_VT_VCD_WIRE, false,-1);
    tracep->declBus(c+538,"head",-1,FST_VD_OUTPUT,FST_VT_VCD_WIRE, false,-1, 2,0);
    tracep->declBit(c+539,"flush",-1,FST_VD_INPUT,FST_VT_VCD_WIRE, false,-1);
    tracep->declBus(c+540,"occupancy",-1,FST_VD_OUTPUT,FST_VT_VCD_WIRE, false,-1, 2,0);
    tracep->declBit(c+541,"clk",-1,FST_VD_INPUT,FST_VT_VCD_WIRE, false,-1);
    tracep->declBit(c+542,"resetn",-1,FST_VD_INPUT,FST_VT_VCD_WIRE, false,-1);
    tracep->declBus(c+543,"tmp_tmp_pop_pop_out_data",-1, FST_VD_IMPLICIT,FST_VT_SV_LOGIC, false,-1, 2,0);
    tracep->declBus(c+544,"tmp_occupancy",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1, 2,0);
    tracep->declBus(c+545,"vec_0",-1, FST_VD_IMPLICIT,FST_VT_SV_LOGIC, false,-1, 2,0);
    tracep->declBus(c+546,"vec_1",-1, FST_VD_IMPLICIT,FST_VT_SV_LOGIC, false,-1, 2,0);
    tracep->declBus(c+547,"vec_2",-1, FST_VD_IMPLICIT,FST_VT_SV_LOGIC, false,-1, 2,0);
    tracep->declBus(c+548,"vec_3",-1, FST_VD_IMPLICIT,FST_VT_SV_LOGIC, false,-1, 2,0);
    tracep->declBus(c+549,"vec_4",-1, FST_VD_IMPLICIT,FST_VT_SV_LOGIC, false,-1, 2,0);
    tracep->declBus(c+550,"vec_5",-1, FST_VD_IMPLICIT,FST_VT_SV_LOGIC, false,-1, 2,0);
    tracep->declBus(c+551,"pushPtrGlobal",-1, FST_VD_IMPLICIT,FST_VT_SV_LOGIC, false,-1, 2,0);
    tracep->declBus(c+552,"popPtrGlobal",-1, FST_VD_IMPLICIT,FST_VT_SV_LOGIC, false,-1, 2,0);
    tracep->declBit(c+553,"ptrMatch",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1);
    tracep->declBit(c+554,"risingOccupancy",-1, FST_VD_IMPLICIT,FST_VT_SV_LOGIC, false,-1);
    tracep->declBit(c+555,"empty",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1);
    tracep->declBit(c+556,"full",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1);
    tracep->declBit(c+557,"pushing",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1);
    tracep->declBus(c+558,"tmp_pop_pop_out_data",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1, 2,0);
    tracep->declBus(c+559,"tmp_1",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1, 7,0);
    tracep->declBus(c+560,"tmp_vec_0",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1, 2,0);
    tracep->declBus(c+561,"tmp_2",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1, 7,0);
    tracep->declBus(c+562,"ptrDif",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1, 2,0);
    tracep->popNamePrefix(2);
}

VL_ATTR_COLD void Vtop___024root__trace_init_top(Vtop___024root* vlSelf, VerilatedFst* tracep) {
    if (false && vlSelf) {}  // Prevent unused
    Vtop__Syms* const __restrict vlSymsp VL_ATTR_UNUSED = vlSelf->vlSymsp;
    VL_DEBUG_IF(VL_DBG_MSGF("+    Vtop___024root__trace_init_top\n"); );
    // Body
    Vtop___024root__trace_init_sub__TOP__0(vlSelf, tracep);
}

VL_ATTR_COLD void Vtop___024root__trace_full_top_0(void* voidSelf, VerilatedFst::Buffer* bufp);
void Vtop___024root__trace_chg_top_0(void* voidSelf, VerilatedFst::Buffer* bufp);
void Vtop___024root__trace_cleanup(void* voidSelf, VerilatedFst* /*unused*/);

VL_ATTR_COLD void Vtop___024root__trace_register(Vtop___024root* vlSelf, VerilatedFst* tracep) {
    if (false && vlSelf) {}  // Prevent unused
    Vtop__Syms* const __restrict vlSymsp VL_ATTR_UNUSED = vlSelf->vlSymsp;
    VL_DEBUG_IF(VL_DBG_MSGF("+    Vtop___024root__trace_register\n"); );
    // Body
    tracep->addFullCb(&Vtop___024root__trace_full_top_0, vlSelf);
    tracep->addChgCb(&Vtop___024root__trace_chg_top_0, vlSelf);
    tracep->addCleanupCb(&Vtop___024root__trace_cleanup, vlSelf);
}

VL_ATTR_COLD void Vtop___024root__trace_full_sub_0(Vtop___024root* vlSelf, VerilatedFst::Buffer* bufp);

VL_ATTR_COLD void Vtop___024root__trace_full_top_0(void* voidSelf, VerilatedFst::Buffer* bufp) {
    VL_DEBUG_IF(VL_DBG_MSGF("+    Vtop___024root__trace_full_top_0\n"); );
    // Init
    Vtop___024root* const __restrict vlSelf VL_ATTR_UNUSED = static_cast<Vtop___024root*>(voidSelf);
    Vtop__Syms* const __restrict vlSymsp VL_ATTR_UNUSED = vlSelf->vlSymsp;
    // Body
    Vtop___024root__trace_full_sub_0((&vlSymsp->TOP), bufp);
}

VL_ATTR_COLD void Vtop___024root__trace_full_sub_0(Vtop___024root* vlSelf, VerilatedFst::Buffer* bufp) {
    if (false && vlSelf) {}  // Prevent unused
    Vtop__Syms* const __restrict vlSymsp VL_ATTR_UNUSED = vlSelf->vlSymsp;
    VL_DEBUG_IF(VL_DBG_MSGF("+    Vtop___024root__trace_full_sub_0\n"); );
    // Init
    uint32_t* const oldp VL_ATTR_UNUSED = bufp->oldp(vlSymsp->__Vm_baseCode);
    // Body
    bufp->fullBit(oldp+1,(vlSelf->core_en));
    bufp->fullBit(oldp+2,(vlSelf->ibus_cmd_valid));
    bufp->fullBit(oldp+3,(vlSelf->ibus_cmd_ready));
    bufp->fullIData(oldp+4,(vlSelf->ibus_cmd_payload_address),32);
    bufp->fullBit(oldp+5,(vlSelf->ibus_rsp_valid));
    bufp->fullBit(oldp+6,(vlSelf->ibus_rsp_ready));
    bufp->fullQData(oldp+7,(vlSelf->ibus_rsp_payload_rdata),64);
    bufp->fullIData(oldp+9,(vlSelf->if2id_itf_0_instr_data),32);
    bufp->fullIData(oldp+10,(vlSelf->if2id_itf_0_instr_pc),32);
    bufp->fullBit(oldp+11,(vlSelf->if2id_itf_0_valid));
    bufp->fullIData(oldp+12,(vlSelf->if2id_itf_1_instr_data),32);
    bufp->fullIData(oldp+13,(vlSelf->if2id_itf_1_instr_pc),32);
    bufp->fullBit(oldp+14,(vlSelf->if2id_itf_1_valid));
    bufp->fullBit(oldp+15,(vlSelf->fetchStage_flush));
    bufp->fullBit(oldp+16,(vlSelf->fetchStage_isDone));
    bufp->fullBit(oldp+17,(vlSelf->fetchStage_isReady));
    bufp->fullBit(oldp+18,(vlSelf->pcJumpTarget_valid));
    bufp->fullIData(oldp+19,(vlSelf->pcJumpTarget_payload),32);
    bufp->fullBit(oldp+20,(vlSelf->pcPredicted_valid));
    bufp->fullIData(oldp+21,(vlSelf->pcPredicted_payload),32);
    bufp->fullBit(oldp+22,(vlSelf->clk));
    bufp->fullBit(oldp+23,(vlSelf->resetn));
    bufp->fullBit(oldp+24,(vlSelf->fetch_unit__DOT__core_en));
    bufp->fullBit(oldp+25,(vlSelf->fetch_unit__DOT__ibus_cmd_valid));
    bufp->fullBit(oldp+26,(vlSelf->fetch_unit__DOT__ibus_cmd_ready));
    bufp->fullIData(oldp+27,(vlSelf->fetch_unit__DOT__ibus_cmd_payload_address),32);
    bufp->fullBit(oldp+28,(vlSelf->fetch_unit__DOT__ibus_rsp_valid));
    bufp->fullBit(oldp+29,(vlSelf->fetch_unit__DOT__ibus_rsp_ready));
    bufp->fullQData(oldp+30,(vlSelf->fetch_unit__DOT__ibus_rsp_payload_rdata),64);
    bufp->fullIData(oldp+32,(vlSelf->fetch_unit__DOT__if2id_itf_0_instr_data),32);
    bufp->fullIData(oldp+33,(vlSelf->fetch_unit__DOT__if2id_itf_0_instr_pc),32);
    bufp->fullBit(oldp+34,(vlSelf->fetch_unit__DOT__if2id_itf_0_valid));
    bufp->fullIData(oldp+35,(vlSelf->fetch_unit__DOT__if2id_itf_1_instr_data),32);
    bufp->fullIData(oldp+36,(vlSelf->fetch_unit__DOT__if2id_itf_1_instr_pc),32);
    bufp->fullBit(oldp+37,(vlSelf->fetch_unit__DOT__if2id_itf_1_valid));
    bufp->fullBit(oldp+38,(vlSelf->fetch_unit__DOT__fetchStage_flush));
    bufp->fullBit(oldp+39,(vlSelf->fetch_unit__DOT__fetchStage_isDone));
    bufp->fullBit(oldp+40,(vlSelf->fetch_unit__DOT__fetchStage_isReady));
    bufp->fullBit(oldp+41,(vlSelf->fetch_unit__DOT__pcJumpTarget_valid));
    bufp->fullIData(oldp+42,(vlSelf->fetch_unit__DOT__pcJumpTarget_payload),32);
    bufp->fullBit(oldp+43,(vlSelf->fetch_unit__DOT__pcPredicted_valid));
    bufp->fullIData(oldp+44,(vlSelf->fetch_unit__DOT__pcPredicted_payload),32);
    bufp->fullBit(oldp+45,(vlSelf->fetch_unit__DOT__clk));
    bufp->fullBit(oldp+46,(vlSelf->fetch_unit__DOT__resetn));
    bufp->fullBit(oldp+47,(vlSelf->fetch_unit__DOT__addressFifo_io_push_valid));
    bufp->fullBit(oldp+48,(vlSelf->fetch_unit__DOT__addressFifo_io_pop_ready));
    bufp->fullBit(oldp+49,(vlSelf->fetch_unit__DOT__addressFifo_io_flush));
    bufp->fullBit(oldp+50,(vlSelf->fetch_unit__DOT__validNumFifo_push_valid));
    bufp->fullCData(oldp+51,(vlSelf->fetch_unit__DOT__validNumFifo_push_payload),3);
    bufp->fullBit(oldp+52,(vlSelf->fetch_unit__DOT__validNumFifo_pop_valid));
    bufp->fullCData(oldp+53,(vlSelf->fetch_unit__DOT__validNumFifo_pop_pop_req_num),3);
    bufp->fullBit(oldp+54,(vlSelf->fetch_unit__DOT__validNumFifo_flush));
    bufp->fullBit(oldp+55,(vlSelf->fetch_unit__DOT__instrFifo_io_push_0_valid));
    bufp->fullQData(oldp+56,(vlSelf->fetch_unit__DOT__instrFifo_io_push_0_payload),33);
    bufp->fullBit(oldp+58,(vlSelf->fetch_unit__DOT__instrFifo_io_push_1_valid));
    bufp->fullQData(oldp+59,(vlSelf->fetch_unit__DOT__instrFifo_io_push_1_payload),33);
    bufp->fullBit(oldp+61,(vlSelf->fetch_unit__DOT__instrFifo_io_push_2_valid));
    bufp->fullQData(oldp+62,(vlSelf->fetch_unit__DOT__instrFifo_io_push_2_payload),33);
    bufp->fullBit(oldp+64,(vlSelf->fetch_unit__DOT__instrFifo_io_push_3_valid));
    bufp->fullQData(oldp+65,(vlSelf->fetch_unit__DOT__instrFifo_io_push_3_payload),33);
    bufp->fullBit(oldp+67,(vlSelf->fetch_unit__DOT__instrFifo_io_flush));
    bufp->fullIData(oldp+68,(vlSelf->fetch_unit__DOT__rvcDecompressor_2_i),32);
    bufp->fullIData(oldp+69,(vlSelf->fetch_unit__DOT__rvcDecompressor_3_i),32);
    bufp->fullBit(oldp+70,(vlSelf->fetch_unit__DOT__addressFifo_io_push_ready));
    bufp->fullBit(oldp+71,(vlSelf->fetch_unit__DOT__addressFifo_io_pop_valid));
    bufp->fullIData(oldp+72,(vlSelf->fetch_unit__DOT__addressFifo_io_pop_payload),32);
    bufp->fullIData(oldp+73,(vlSelf->fetch_unit__DOT__addressFifo_io_head),32);
    bufp->fullCData(oldp+74,(vlSelf->fetch_unit__DOT__addressFifo_io_occupancy),3);
    bufp->fullBit(oldp+75,(vlSelf->fetch_unit__DOT__validNumFifo_push_ready));
    bufp->fullBit(oldp+76,(vlSelf->fetch_unit__DOT__validNumFifo_pop_ready));
    bufp->fullCData(oldp+77,(vlSelf->fetch_unit__DOT__validNumFifo_pop_pop_out_data),3);
    bufp->fullBit(oldp+78,(vlSelf->fetch_unit__DOT__validNumFifo_pop_pop_real));
    bufp->fullCData(oldp+79,(vlSelf->fetch_unit__DOT__validNumFifo_head),3);
    bufp->fullCData(oldp+80,(vlSelf->fetch_unit__DOT__validNumFifo_occupancy),3);
    bufp->fullBit(oldp+81,(vlSelf->fetch_unit__DOT__instrFifo_io_push_0_ready));
    bufp->fullBit(oldp+82,(vlSelf->fetch_unit__DOT__instrFifo_io_push_1_ready));
    bufp->fullBit(oldp+83,(vlSelf->fetch_unit__DOT__instrFifo_io_push_2_ready));
    bufp->fullBit(oldp+84,(vlSelf->fetch_unit__DOT__instrFifo_io_push_3_ready));
    bufp->fullBit(oldp+85,(vlSelf->fetch_unit__DOT__instrFifo_io_pop_0_valid));
    bufp->fullQData(oldp+86,(vlSelf->fetch_unit__DOT__instrFifo_io_pop_0_payload),33);
    bufp->fullBit(oldp+88,(vlSelf->fetch_unit__DOT__instrFifo_io_pop_1_valid));
    bufp->fullQData(oldp+89,(vlSelf->fetch_unit__DOT__instrFifo_io_pop_1_payload),33);
    bufp->fullCData(oldp+91,(vlSelf->fetch_unit__DOT__instrFifo_io_occupancy),4);
    bufp->fullBit(oldp+92,(vlSelf->fetch_unit__DOT__instrFifo_io_ov_waterline));
    bufp->fullCData(oldp+93,(vlSelf->fetch_unit__DOT__trailone_index_0_cnt_out),3);
    bufp->fullCData(oldp+94,(vlSelf->fetch_unit__DOT__trailone_index_1_cnt_out),3);
    bufp->fullCData(oldp+95,(vlSelf->fetch_unit__DOT__trailone_index_2_cnt_out),3);
    bufp->fullCData(oldp+96,(vlSelf->fetch_unit__DOT__trailone_index_3_cnt_out),3);
    bufp->fullCData(oldp+97,(vlSelf->fetch_unit__DOT__instr_push_valid_vec_popc_cnt_out),3);
    bufp->fullCData(oldp+98,(vlSelf->fetch_unit__DOT__instr_pop_valid_popc_cnt_out),2);
    bufp->fullIData(oldp+99,(vlSelf->fetch_unit__DOT__rvcDecompressor_2_decompInstr_inst),32);
    bufp->fullBit(oldp+100,(vlSelf->fetch_unit__DOT__rvcDecompressor_2_decompInstr_illegal));
    bufp->fullIData(oldp+101,(vlSelf->fetch_unit__DOT__rvcDecompressor_3_decompInstr_inst),32);
    bufp->fullBit(oldp+102,(vlSelf->fetch_unit__DOT__rvcDecompressor_3_decompInstr_illegal));
    bufp->fullQData(oldp+103,(vlSelf->fetch_unit__DOT__tmp_io_push_0_payload),33);
    bufp->fullBit(oldp+105,(vlSelf->fetch_unit__DOT__tmp_io_push_0_valid));
    bufp->fullQData(oldp+106,(vlSelf->fetch_unit__DOT__tmp_io_push_1_payload),33);
    bufp->fullBit(oldp+108,(vlSelf->fetch_unit__DOT__tmp_io_push_1_valid));
    bufp->fullQData(oldp+109,(vlSelf->fetch_unit__DOT__tmp_io_push_2_payload),33);
    bufp->fullBit(oldp+111,(vlSelf->fetch_unit__DOT__tmp_io_push_2_valid));
    bufp->fullQData(oldp+112,(vlSelf->fetch_unit__DOT__tmp_io_push_3_payload),33);
    bufp->fullBit(oldp+114,(vlSelf->fetch_unit__DOT__tmp_io_push_3_valid));
    bufp->fullIData(oldp+115,(vlSelf->fetch_unit__DOT__tmp_if2id_itf_0_instr_pc),32);
    bufp->fullIData(oldp+116,(vlSelf->fetch_unit__DOT__tmp_if2id_itf_0_instr_pc_1),32);
    bufp->fullIData(oldp+117,(vlSelf->fetch_unit__DOT__tmp_if2id_itf_1_instr_pc),32);
    bufp->fullIData(oldp+118,(vlSelf->fetch_unit__DOT__tmp_if2id_itf_1_instr_pc_1),32);
    bufp->fullIData(oldp+119,(vlSelf->fetch_unit__DOT__tmp_if2id_itf_1_instr_pc_2),32);
    bufp->fullIData(oldp+120,(vlSelf->fetch_unit__DOT__pc),32);
    bufp->fullIData(oldp+121,(vlSelf->fetch_unit__DOT__default_next_pc),32);
    bufp->fullBit(oldp+122,(vlSelf->fetch_unit__DOT__fetch_pending));
    bufp->fullCData(oldp+123,(vlSelf->fetch_unit__DOT__addressOffset),2);
    bufp->fullBit(oldp+124,(vlSelf->fetch_unit__DOT__ibus_cmd_fire));
    bufp->fullBit(oldp+125,(vlSelf->fetch_unit__DOT__valid_instr_slice_0));
    bufp->fullBit(oldp+126,(vlSelf->fetch_unit__DOT__valid_instr_slice_1));
    bufp->fullBit(oldp+127,(vlSelf->fetch_unit__DOT__valid_instr_slice_2));
    bufp->fullBit(oldp+128,(vlSelf->fetch_unit__DOT__valid_instr_slice_3));
    bufp->fullBit(oldp+129,(vlSelf->fetch_unit__DOT__instr_slices_0_valid));
    bufp->fullQData(oldp+130,(vlSelf->fetch_unit__DOT__instr_slices_0_payload),33);
    bufp->fullBit(oldp+132,(vlSelf->fetch_unit__DOT__instr_slices_1_valid));
    bufp->fullQData(oldp+133,(vlSelf->fetch_unit__DOT__instr_slices_1_payload),33);
    bufp->fullBit(oldp+135,(vlSelf->fetch_unit__DOT__instr_slices_2_valid));
    bufp->fullQData(oldp+136,(vlSelf->fetch_unit__DOT__instr_slices_2_payload),33);
    bufp->fullBit(oldp+138,(vlSelf->fetch_unit__DOT__instr_slices_3_valid));
    bufp->fullQData(oldp+139,(vlSelf->fetch_unit__DOT__instr_slices_3_payload),33);
    bufp->fullCData(oldp+141,(vlSelf->fetch_unit__DOT__tail_one_matrix_0),4);
    bufp->fullCData(oldp+142,(vlSelf->fetch_unit__DOT__tail_one_matrix_1),4);
    bufp->fullCData(oldp+143,(vlSelf->fetch_unit__DOT__tail_one_matrix_2),4);
    bufp->fullCData(oldp+144,(vlSelf->fetch_unit__DOT__tail_one_matrix_3),4);
    bufp->fullCData(oldp+145,(vlSelf->fetch_unit__DOT__tail_one_index_vec_0),2);
    bufp->fullCData(oldp+146,(vlSelf->fetch_unit__DOT__tail_one_index_vec_1),2);
    bufp->fullCData(oldp+147,(vlSelf->fetch_unit__DOT__tail_one_index_vec_2),2);
    bufp->fullCData(oldp+148,(vlSelf->fetch_unit__DOT__tail_one_index_vec_3),2);
    bufp->fullBit(oldp+149,(vlSelf->fetch_unit__DOT__tail_one_valid_vec_0));
    bufp->fullBit(oldp+150,(vlSelf->fetch_unit__DOT__tail_one_valid_vec_1));
    bufp->fullBit(oldp+151,(vlSelf->fetch_unit__DOT__tail_one_valid_vec_2));
    bufp->fullBit(oldp+152,(vlSelf->fetch_unit__DOT__tail_one_valid_vec_3));
    bufp->fullBit(oldp+153,(vlSelf->fetch_unit__DOT__slice_valid_vec_0));
    bufp->fullBit(oldp+154,(vlSelf->fetch_unit__DOT__slice_valid_vec_1));
    bufp->fullBit(oldp+155,(vlSelf->fetch_unit__DOT__slice_valid_vec_2));
    bufp->fullBit(oldp+156,(vlSelf->fetch_unit__DOT__slice_valid_vec_3));
    bufp->fullBit(oldp+157,(vlSelf->fetch_unit__DOT__tmp_1));
    bufp->fullSData(oldp+158,(vlSelf->fetch_unit__DOT__tmp_instr_slices_0_payload),16);
    bufp->fullCData(oldp+159,(vlSelf->fetch_unit__DOT__tmp_2),2);
    bufp->fullCData(oldp+160,(vlSelf->fetch_unit__DOT__tmp_3),2);
    bufp->fullCData(oldp+161,(vlSelf->fetch_unit__DOT__tmp_4),2);
    bufp->fullCData(oldp+162,(vlSelf->fetch_unit__DOT__tmp_5),2);
    bufp->fullBit(oldp+163,(vlSelf->fetch_unit__DOT__ibus_rsp_fire));
    bufp->fullCData(oldp+164,(vlSelf->fetch_unit__DOT__instr_push_valid_vec),4);
    bufp->fullBit(oldp+165,(vlSelf->fetch_unit__DOT__toplevel_instrFifo_io_push_0_fire));
    bufp->fullCData(oldp+166,(vlSelf->fetch_unit__DOT__instr_pop_valid),2);
    bufp->fullBit(oldp+167,(vlSelf->fetch_unit__DOT__toplevel_instrFifo_io_pop_0_fire));
    bufp->fullBit(oldp+168,(vlSelf->fetch_unit__DOT__toplevel_instrFifo_io_pop_1_fire));
    bufp->fullCData(oldp+169,(vlSelf->fetch_unit__DOT__pc_pop_offset),3);
    bufp->fullCData(oldp+170,(vlSelf->fetch_unit__DOT__pc_step_all_1),3);
    bufp->fullCData(oldp+171,(vlSelf->fetch_unit__DOT__pc_step_all_2),3);
    bufp->fullIData(oldp+172,(vlSelf->fetch_unit__DOT__real_instr_0),32);
    bufp->fullIData(oldp+173,(vlSelf->fetch_unit__DOT__real_instr_1),32);
    bufp->fullCData(oldp+174,(vlSelf->fetch_unit__DOT__pc_step_0),3);
    bufp->fullCData(oldp+175,(vlSelf->fetch_unit__DOT__pc_step_1),3);
    bufp->fullBit(oldp+176,(vlSelf->fetch_unit__DOT__tmp_real_instr_0));
    bufp->fullBit(oldp+177,(vlSelf->fetch_unit__DOT__tmp_real_instr_1));
    bufp->fullBit(oldp+178,(vlSelf->fetch_unit__DOT__toplevel_addressFifo_io_pop_fire));
    bufp->fullQData(oldp+179,(vlSelf->fetch_unit__DOT__tmp_2_string),56);
    bufp->fullQData(oldp+181,(vlSelf->fetch_unit__DOT__tmp_3_string),56);
    bufp->fullQData(oldp+183,(vlSelf->fetch_unit__DOT__tmp_4_string),56);
    bufp->fullQData(oldp+185,(vlSelf->fetch_unit__DOT__tmp_5_string),56);
    bufp->fullBit(oldp+187,(vlSelf->fetch_unit__DOT__addressFifo__DOT__io_push_valid));
    bufp->fullBit(oldp+188,(vlSelf->fetch_unit__DOT__addressFifo__DOT__io_push_ready));
    bufp->fullIData(oldp+189,(vlSelf->fetch_unit__DOT__addressFifo__DOT__io_push_payload),32);
    bufp->fullBit(oldp+190,(vlSelf->fetch_unit__DOT__addressFifo__DOT__io_pop_valid));
    bufp->fullBit(oldp+191,(vlSelf->fetch_unit__DOT__addressFifo__DOT__io_pop_ready));
    bufp->fullIData(oldp+192,(vlSelf->fetch_unit__DOT__addressFifo__DOT__io_pop_payload),32);
    bufp->fullIData(oldp+193,(vlSelf->fetch_unit__DOT__addressFifo__DOT__io_head),32);
    bufp->fullBit(oldp+194,(vlSelf->fetch_unit__DOT__addressFifo__DOT__io_flush));
    bufp->fullCData(oldp+195,(vlSelf->fetch_unit__DOT__addressFifo__DOT__io_occupancy),3);
    bufp->fullBit(oldp+196,(vlSelf->fetch_unit__DOT__addressFifo__DOT__clk));
    bufp->fullBit(oldp+197,(vlSelf->fetch_unit__DOT__addressFifo__DOT__resetn));
    bufp->fullCData(oldp+198,(vlSelf->fetch_unit__DOT__addressFifo__DOT__tmp_pushPtr_valueNext),3);
    bufp->fullBit(oldp+199,(vlSelf->fetch_unit__DOT__addressFifo__DOT__tmp_pushPtr_valueNext_1));
    bufp->fullCData(oldp+200,(vlSelf->fetch_unit__DOT__addressFifo__DOT__tmp_popPtr_valueNext),3);
    bufp->fullBit(oldp+201,(vlSelf->fetch_unit__DOT__addressFifo__DOT__tmp_popPtr_valueNext_1));
    bufp->fullIData(oldp+202,(vlSelf->fetch_unit__DOT__addressFifo__DOT__tmp_readed),32);
    bufp->fullCData(oldp+203,(vlSelf->fetch_unit__DOT__addressFifo__DOT__tmp_io_occupancy),3);
    bufp->fullIData(oldp+204,(vlSelf->fetch_unit__DOT__addressFifo__DOT__vec_0),32);
    bufp->fullIData(oldp+205,(vlSelf->fetch_unit__DOT__addressFifo__DOT__vec_1),32);
    bufp->fullIData(oldp+206,(vlSelf->fetch_unit__DOT__addressFifo__DOT__vec_2),32);
    bufp->fullIData(oldp+207,(vlSelf->fetch_unit__DOT__addressFifo__DOT__vec_3),32);
    bufp->fullIData(oldp+208,(vlSelf->fetch_unit__DOT__addressFifo__DOT__vec_4),32);
    bufp->fullIData(oldp+209,(vlSelf->fetch_unit__DOT__addressFifo__DOT__vec_5),32);
    bufp->fullBit(oldp+210,(vlSelf->fetch_unit__DOT__addressFifo__DOT__pushPtr_willIncrement));
    bufp->fullBit(oldp+211,(vlSelf->fetch_unit__DOT__addressFifo__DOT__pushPtr_willClear));
    bufp->fullCData(oldp+212,(vlSelf->fetch_unit__DOT__addressFifo__DOT__pushPtr_valueNext),3);
    bufp->fullCData(oldp+213,(vlSelf->fetch_unit__DOT__addressFifo__DOT__pushPtr_value),3);
    bufp->fullBit(oldp+214,(vlSelf->fetch_unit__DOT__addressFifo__DOT__pushPtr_willOverflowIfInc));
    bufp->fullBit(oldp+215,(vlSelf->fetch_unit__DOT__addressFifo__DOT__pushPtr_willOverflow));
    bufp->fullBit(oldp+216,(vlSelf->fetch_unit__DOT__addressFifo__DOT__popPtr_willIncrement));
    bufp->fullBit(oldp+217,(vlSelf->fetch_unit__DOT__addressFifo__DOT__popPtr_willClear));
    bufp->fullCData(oldp+218,(vlSelf->fetch_unit__DOT__addressFifo__DOT__popPtr_valueNext),3);
    bufp->fullCData(oldp+219,(vlSelf->fetch_unit__DOT__addressFifo__DOT__popPtr_value),3);
    bufp->fullBit(oldp+220,(vlSelf->fetch_unit__DOT__addressFifo__DOT__popPtr_willOverflowIfInc));
    bufp->fullBit(oldp+221,(vlSelf->fetch_unit__DOT__addressFifo__DOT__popPtr_willOverflow));
    bufp->fullBit(oldp+222,(vlSelf->fetch_unit__DOT__addressFifo__DOT__ptrMatch));
    bufp->fullBit(oldp+223,(vlSelf->fetch_unit__DOT__addressFifo__DOT__risingOccupancy));
    bufp->fullBit(oldp+224,(vlSelf->fetch_unit__DOT__addressFifo__DOT__empty));
    bufp->fullBit(oldp+225,(vlSelf->fetch_unit__DOT__addressFifo__DOT__full));
    bufp->fullBit(oldp+226,(vlSelf->fetch_unit__DOT__addressFifo__DOT__pushing));
    bufp->fullBit(oldp+227,(vlSelf->fetch_unit__DOT__addressFifo__DOT__popping));
    bufp->fullIData(oldp+228,(vlSelf->fetch_unit__DOT__addressFifo__DOT__readed),32);
    bufp->fullCData(oldp+229,(vlSelf->fetch_unit__DOT__addressFifo__DOT__tmp_1),8);
    bufp->fullCData(oldp+230,(vlSelf->fetch_unit__DOT__addressFifo__DOT__ptrDif),3);
    bufp->fullBit(oldp+231,(vlSelf->fetch_unit__DOT__instrFifo__DOT__io_push_0_valid));
    bufp->fullBit(oldp+232,(vlSelf->fetch_unit__DOT__instrFifo__DOT__io_push_0_ready));
    bufp->fullQData(oldp+233,(vlSelf->fetch_unit__DOT__instrFifo__DOT__io_push_0_payload),33);
    bufp->fullBit(oldp+235,(vlSelf->fetch_unit__DOT__instrFifo__DOT__io_push_1_valid));
    bufp->fullBit(oldp+236,(vlSelf->fetch_unit__DOT__instrFifo__DOT__io_push_1_ready));
    bufp->fullQData(oldp+237,(vlSelf->fetch_unit__DOT__instrFifo__DOT__io_push_1_payload),33);
    bufp->fullBit(oldp+239,(vlSelf->fetch_unit__DOT__instrFifo__DOT__io_push_2_valid));
    bufp->fullBit(oldp+240,(vlSelf->fetch_unit__DOT__instrFifo__DOT__io_push_2_ready));
    bufp->fullQData(oldp+241,(vlSelf->fetch_unit__DOT__instrFifo__DOT__io_push_2_payload),33);
    bufp->fullBit(oldp+243,(vlSelf->fetch_unit__DOT__instrFifo__DOT__io_push_3_valid));
    bufp->fullBit(oldp+244,(vlSelf->fetch_unit__DOT__instrFifo__DOT__io_push_3_ready));
    bufp->fullQData(oldp+245,(vlSelf->fetch_unit__DOT__instrFifo__DOT__io_push_3_payload),33);
    bufp->fullBit(oldp+247,(vlSelf->fetch_unit__DOT__instrFifo__DOT__io_pop_0_valid));
    bufp->fullBit(oldp+248,(vlSelf->fetch_unit__DOT__instrFifo__DOT__io_pop_0_ready));
    bufp->fullQData(oldp+249,(vlSelf->fetch_unit__DOT__instrFifo__DOT__io_pop_0_payload),33);
    bufp->fullBit(oldp+251,(vlSelf->fetch_unit__DOT__instrFifo__DOT__io_pop_1_valid));
    bufp->fullBit(oldp+252,(vlSelf->fetch_unit__DOT__instrFifo__DOT__io_pop_1_ready));
    bufp->fullQData(oldp+253,(vlSelf->fetch_unit__DOT__instrFifo__DOT__io_pop_1_payload),33);
    bufp->fullBit(oldp+255,(vlSelf->fetch_unit__DOT__instrFifo__DOT__io_flush));
    bufp->fullCData(oldp+256,(vlSelf->fetch_unit__DOT__instrFifo__DOT__io_occupancy),4);
    bufp->fullBit(oldp+257,(vlSelf->fetch_unit__DOT__instrFifo__DOT__io_ov_waterline));
    bufp->fullBit(oldp+258,(vlSelf->fetch_unit__DOT__instrFifo__DOT__clk));
    bufp->fullBit(oldp+259,(vlSelf->fetch_unit__DOT__instrFifo__DOT__resetn));
    bufp->fullCData(oldp+260,(vlSelf->fetch_unit__DOT__instrFifo__DOT__tmp_inc_num_1),2);
    bufp->fullCData(oldp+261,(vlSelf->fetch_unit__DOT__instrFifo__DOT__tmp_inc_num_2),2);
    bufp->fullBit(oldp+262,(vlSelf->fetch_unit__DOT__instrFifo__DOT__tmp_inc_num_3));
    bufp->fullCData(oldp+263,(vlSelf->fetch_unit__DOT__instrFifo__DOT__tmp_inc_num_4),3);
    bufp->fullCData(oldp+264,(vlSelf->fetch_unit__DOT__instrFifo__DOT__tmp_inc_num_5),2);
    bufp->fullCData(oldp+265,(vlSelf->fetch_unit__DOT__instrFifo__DOT__tmp_inc_num_6),2);
    bufp->fullBit(oldp+266,(vlSelf->fetch_unit__DOT__instrFifo__DOT__tmp_inc_num_7));
    bufp->fullCData(oldp+267,(vlSelf->fetch_unit__DOT__instrFifo__DOT__tmp_dec_num_1),2);
    bufp->fullBit(oldp+268,(vlSelf->fetch_unit__DOT__instrFifo__DOT__tmp_dec_num_2));
    bufp->fullCData(oldp+269,(vlSelf->fetch_unit__DOT__instrFifo__DOT__tmp_io_push_0_ready),4);
    bufp->fullCData(oldp+270,(vlSelf->fetch_unit__DOT__instrFifo__DOT__tmp_io_push_1_ready),4);
    bufp->fullCData(oldp+271,(vlSelf->fetch_unit__DOT__instrFifo__DOT__tmp_io_push_2_ready),4);
    bufp->fullCData(oldp+272,(vlSelf->fetch_unit__DOT__instrFifo__DOT__tmp_io_push_3_ready),4);
    bufp->fullCData(oldp+273,(vlSelf->fetch_unit__DOT__instrFifo__DOT__tmp_pushPtrs_inc_0),5);
    bufp->fullBit(oldp+274,(vlSelf->fetch_unit__DOT__instrFifo__DOT__tmp_pushPtrs_inc_0_1));
    bufp->fullCData(oldp+275,(vlSelf->fetch_unit__DOT__instrFifo__DOT__tmp_pushPtrs_inc_1),5);
    bufp->fullCData(oldp+276,(vlSelf->fetch_unit__DOT__instrFifo__DOT__tmp_pushPtrs_inc_1_1),2);
    bufp->fullCData(oldp+277,(vlSelf->fetch_unit__DOT__instrFifo__DOT__tmp_pushPtrs_inc_2),5);
    bufp->fullCData(oldp+278,(vlSelf->fetch_unit__DOT__instrFifo__DOT__tmp_pushPtrs_inc_2_1),3);
    bufp->fullCData(oldp+279,(vlSelf->fetch_unit__DOT__instrFifo__DOT__tmp_pushPtrs_inc_3),5);
    bufp->fullCData(oldp+280,(vlSelf->fetch_unit__DOT__instrFifo__DOT__tmp_pushPtrs_inc_3_1),3);
    bufp->fullCData(oldp+281,(vlSelf->fetch_unit__DOT__instrFifo__DOT__tmp_popPtrs_inc_0),5);
    bufp->fullBit(oldp+282,(vlSelf->fetch_unit__DOT__instrFifo__DOT__tmp_popPtrs_inc_0_1));
    bufp->fullCData(oldp+283,(vlSelf->fetch_unit__DOT__instrFifo__DOT__tmp_popPtrs_inc_1),5);
    bufp->fullCData(oldp+284,(vlSelf->fetch_unit__DOT__instrFifo__DOT__tmp_popPtrs_inc_1_1),2);
    bufp->fullQData(oldp+285,(vlSelf->fetch_unit__DOT__instrFifo__DOT__tmp_readedVec_0),33);
    bufp->fullCData(oldp+287,(vlSelf->fetch_unit__DOT__instrFifo__DOT__tmp_readedVec_0_1),4);
    bufp->fullQData(oldp+288,(vlSelf->fetch_unit__DOT__instrFifo__DOT__tmp_readedVec_1),33);
    bufp->fullCData(oldp+290,(vlSelf->fetch_unit__DOT__instrFifo__DOT__tmp_readedVec_1_1),4);
    bufp->fullCData(oldp+291,(vlSelf->fetch_unit__DOT__instrFifo__DOT__tmp_when),3);
    bufp->fullCData(oldp+292,(vlSelf->fetch_unit__DOT__instrFifo__DOT__tmp_pushPtrGlobalInc),5);
    bufp->fullCData(oldp+293,(vlSelf->fetch_unit__DOT__instrFifo__DOT__tmp_pushPtrGlobalInc_1),4);
    bufp->fullCData(oldp+294,(vlSelf->fetch_unit__DOT__instrFifo__DOT__tmp_popPtrGlobalInc),5);
    bufp->fullCData(oldp+295,(vlSelf->fetch_unit__DOT__instrFifo__DOT__tmp_popPtrGlobalInc_1),3);
    bufp->fullCData(oldp+296,(vlSelf->fetch_unit__DOT__instrFifo__DOT__tmp_pushPtrGlobal),5);
    bufp->fullCData(oldp+297,(vlSelf->fetch_unit__DOT__instrFifo__DOT__tmp_popPtrGlobal),5);
    bufp->fullCData(oldp+298,(vlSelf->fetch_unit__DOT__instrFifo__DOT__tmp_io_occupancy),4);
    bufp->fullQData(oldp+299,(vlSelf->fetch_unit__DOT__instrFifo__DOT__vec_0),33);
    bufp->fullQData(oldp+301,(vlSelf->fetch_unit__DOT__instrFifo__DOT__vec_1),33);
    bufp->fullQData(oldp+303,(vlSelf->fetch_unit__DOT__instrFifo__DOT__vec_2),33);
    bufp->fullQData(oldp+305,(vlSelf->fetch_unit__DOT__instrFifo__DOT__vec_3),33);
    bufp->fullQData(oldp+307,(vlSelf->fetch_unit__DOT__instrFifo__DOT__vec_4),33);
    bufp->fullQData(oldp+309,(vlSelf->fetch_unit__DOT__instrFifo__DOT__vec_5),33);
    bufp->fullQData(oldp+311,(vlSelf->fetch_unit__DOT__instrFifo__DOT__vec_6),33);
    bufp->fullQData(oldp+313,(vlSelf->fetch_unit__DOT__instrFifo__DOT__vec_7),33);
    bufp->fullQData(oldp+315,(vlSelf->fetch_unit__DOT__instrFifo__DOT__vec_8),33);
    bufp->fullQData(oldp+317,(vlSelf->fetch_unit__DOT__instrFifo__DOT__vec_9),33);
    bufp->fullQData(oldp+319,(vlSelf->fetch_unit__DOT__instrFifo__DOT__vec_10),33);
    bufp->fullQData(oldp+321,(vlSelf->fetch_unit__DOT__instrFifo__DOT__vec_11),33);
    bufp->fullQData(oldp+323,(vlSelf->fetch_unit__DOT__instrFifo__DOT__vec_12),33);
    bufp->fullQData(oldp+325,(vlSelf->fetch_unit__DOT__instrFifo__DOT__vec_13),33);
    bufp->fullCData(oldp+327,(vlSelf->fetch_unit__DOT__instrFifo__DOT__pushPtrGlobal),4);
    bufp->fullCData(oldp+328,(vlSelf->fetch_unit__DOT__instrFifo__DOT__popPtrGlobal),4);
    bufp->fullBit(oldp+329,(vlSelf->fetch_unit__DOT__instrFifo__DOT__ptrMatch));
    bufp->fullBit(oldp+330,(vlSelf->fetch_unit__DOT__instrFifo__DOT__risingOccupancy));
    bufp->fullBit(oldp+331,(vlSelf->fetch_unit__DOT__instrFifo__DOT__empty));
    bufp->fullBit(oldp+332,(vlSelf->fetch_unit__DOT__instrFifo__DOT__full));
    bufp->fullBit(oldp+333,(vlSelf->fetch_unit__DOT__instrFifo__DOT__pushing_vec_0));
    bufp->fullBit(oldp+334,(vlSelf->fetch_unit__DOT__instrFifo__DOT__pushing_vec_1));
    bufp->fullBit(oldp+335,(vlSelf->fetch_unit__DOT__instrFifo__DOT__pushing_vec_2));
    bufp->fullBit(oldp+336,(vlSelf->fetch_unit__DOT__instrFifo__DOT__pushing_vec_3));
    bufp->fullBit(oldp+337,(vlSelf->fetch_unit__DOT__instrFifo__DOT__popping_vec_0));
    bufp->fullBit(oldp+338,(vlSelf->fetch_unit__DOT__instrFifo__DOT__popping_vec_1));
    bufp->fullBit(oldp+339,(vlSelf->fetch_unit__DOT__instrFifo__DOT__tmp_inc_num));
    bufp->fullCData(oldp+340,(vlSelf->fetch_unit__DOT__instrFifo__DOT__inc_num),3);
    bufp->fullBit(oldp+341,(vlSelf->fetch_unit__DOT__instrFifo__DOT__tmp_dec_num));
    bufp->fullCData(oldp+342,(vlSelf->fetch_unit__DOT__instrFifo__DOT__dec_num),2);
    bufp->fullCData(oldp+343,(vlSelf->fetch_unit__DOT__instrFifo__DOT__pushPtrs_0),5);
    bufp->fullCData(oldp+344,(vlSelf->fetch_unit__DOT__instrFifo__DOT__pushPtrs_1),5);
    bufp->fullCData(oldp+345,(vlSelf->fetch_unit__DOT__instrFifo__DOT__pushPtrs_2),5);
    bufp->fullCData(oldp+346,(vlSelf->fetch_unit__DOT__instrFifo__DOT__pushPtrs_3),5);
    bufp->fullCData(oldp+347,(vlSelf->fetch_unit__DOT__instrFifo__DOT__popPtrs_0),5);
    bufp->fullCData(oldp+348,(vlSelf->fetch_unit__DOT__instrFifo__DOT__popPtrs_1),5);
    bufp->fullCData(oldp+349,(vlSelf->fetch_unit__DOT__instrFifo__DOT__pushPtrs_inc_0),5);
    bufp->fullCData(oldp+350,(vlSelf->fetch_unit__DOT__instrFifo__DOT__pushPtrs_inc_1),5);
    bufp->fullCData(oldp+351,(vlSelf->fetch_unit__DOT__instrFifo__DOT__pushPtrs_inc_2),5);
    bufp->fullCData(oldp+352,(vlSelf->fetch_unit__DOT__instrFifo__DOT__pushPtrs_inc_3),5);
    bufp->fullCData(oldp+353,(vlSelf->fetch_unit__DOT__instrFifo__DOT__popPtrs_inc_0),5);
    bufp->fullCData(oldp+354,(vlSelf->fetch_unit__DOT__instrFifo__DOT__popPtrs_inc_1),5);
    bufp->fullQData(oldp+355,(vlSelf->fetch_unit__DOT__instrFifo__DOT__readedVec_0),33);
    bufp->fullQData(oldp+357,(vlSelf->fetch_unit__DOT__instrFifo__DOT__readedVec_1),33);
    bufp->fullSData(oldp+359,(vlSelf->fetch_unit__DOT__instrFifo__DOT__tmp_1),16);
    bufp->fullSData(oldp+360,(vlSelf->fetch_unit__DOT__instrFifo__DOT__tmp_2),16);
    bufp->fullSData(oldp+361,(vlSelf->fetch_unit__DOT__instrFifo__DOT__tmp_3),16);
    bufp->fullSData(oldp+362,(vlSelf->fetch_unit__DOT__instrFifo__DOT__tmp_4),16);
    bufp->fullCData(oldp+363,(vlSelf->fetch_unit__DOT__instrFifo__DOT__pushPtrGlobalInc),5);
    bufp->fullCData(oldp+364,(vlSelf->fetch_unit__DOT__instrFifo__DOT__popPtrGlobalInc),5);
    bufp->fullCData(oldp+365,(vlSelf->fetch_unit__DOT__instrFifo__DOT__ptrDif),4);
    bufp->fullBit(oldp+366,(vlSelf->fetch_unit__DOT__instr_pop_valid_popc__DOT__din_vld));
    bufp->fullCData(oldp+367,(vlSelf->fetch_unit__DOT__instr_pop_valid_popc__DOT__data_in),2);
    bufp->fullCData(oldp+368,(vlSelf->fetch_unit__DOT__instr_pop_valid_popc__DOT__cnt_out),2);
    bufp->fullBit(oldp+369,(vlSelf->fetch_unit__DOT__instr_pop_valid_popc__DOT__popsum_init_0));
    bufp->fullBit(oldp+370,(vlSelf->fetch_unit__DOT__instr_pop_valid_popc__DOT__popsum_init_1));
    bufp->fullCData(oldp+371,(vlSelf->fetch_unit__DOT__instr_pop_valid_popc__DOT__popsum_stage1_ele0),2);
    bufp->fullBit(oldp+372,(vlSelf->fetch_unit__DOT__instr_push_valid_vec_popc__DOT__din_vld));
    bufp->fullCData(oldp+373,(vlSelf->fetch_unit__DOT__instr_push_valid_vec_popc__DOT__data_in),4);
    bufp->fullCData(oldp+374,(vlSelf->fetch_unit__DOT__instr_push_valid_vec_popc__DOT__cnt_out),3);
    bufp->fullBit(oldp+375,(vlSelf->fetch_unit__DOT__instr_push_valid_vec_popc__DOT__popsum_init_0));
    bufp->fullBit(oldp+376,(vlSelf->fetch_unit__DOT__instr_push_valid_vec_popc__DOT__popsum_init_1));
    bufp->fullBit(oldp+377,(vlSelf->fetch_unit__DOT__instr_push_valid_vec_popc__DOT__popsum_init_2));
    bufp->fullBit(oldp+378,(vlSelf->fetch_unit__DOT__instr_push_valid_vec_popc__DOT__popsum_init_3));
    bufp->fullCData(oldp+379,(vlSelf->fetch_unit__DOT__instr_push_valid_vec_popc__DOT__popsum_stage1_ele0),2);
    bufp->fullCData(oldp+380,(vlSelf->fetch_unit__DOT__instr_push_valid_vec_popc__DOT__popsum_stage1_ele1),2);
    bufp->fullCData(oldp+381,(vlSelf->fetch_unit__DOT__instr_push_valid_vec_popc__DOT__popsum_stage2_ele0),3);
    bufp->fullIData(oldp+382,(vlSelf->fetch_unit__DOT__rvcDecompressor_2__DOT__i),32);
    bufp->fullIData(oldp+383,(vlSelf->fetch_unit__DOT__rvcDecompressor_2__DOT__decompInstr_inst),32);
    bufp->fullBit(oldp+384,(vlSelf->fetch_unit__DOT__rvcDecompressor_2__DOT__decompInstr_illegal));
    bufp->fullSData(oldp+385,(vlSelf->fetch_unit__DOT__rvcDecompressor_2__DOT__tmp_tmp_ret_inst),12);
    bufp->fullCData(oldp+386,(vlSelf->fetch_unit__DOT__rvcDecompressor_2__DOT__tmp_tmp_ret_inst_1),6);
    bufp->fullIData(oldp+387,(vlSelf->fetch_unit__DOT__rvcDecompressor_2__DOT__tmp_ret_inst_1),32);
    bufp->fullCData(oldp+388,(vlSelf->fetch_unit__DOT__rvcDecompressor_2__DOT__tmp_ret_inst_2),2);
    bufp->fullCData(oldp+389,(vlSelf->fetch_unit__DOT__rvcDecompressor_2__DOT__tmp_ret_inst_3),3);
    bufp->fullCData(oldp+390,(vlSelf->fetch_unit__DOT__rvcDecompressor_2__DOT__tmp_ret_inst_4),3);
    bufp->fullCData(oldp+391,(vlSelf->fetch_unit__DOT__rvcDecompressor_2__DOT__tmp_ret_inst_5),7);
    bufp->fullCData(oldp+392,(vlSelf->fetch_unit__DOT__rvcDecompressor_2__DOT__tmp_ret_inst_6),5);
    bufp->fullBit(oldp+393,(vlSelf->fetch_unit__DOT__rvcDecompressor_2__DOT__tmp_ret_inst_7));
    bufp->fullCData(oldp+394,(vlSelf->fetch_unit__DOT__rvcDecompressor_2__DOT__tmp_ret_inst_8),5);
    bufp->fullSData(oldp+395,(vlSelf->fetch_unit__DOT__rvcDecompressor_2__DOT__tmp_ret_inst_9),12);
    bufp->fullSData(oldp+396,(vlSelf->fetch_unit__DOT__rvcDecompressor_2__DOT__tmp_ret_inst_10),12);
    bufp->fullIData(oldp+397,(vlSelf->fetch_unit__DOT__rvcDecompressor_2__DOT__ret_inst),32);
    bufp->fullBit(oldp+398,(vlSelf->fetch_unit__DOT__rvcDecompressor_2__DOT__ret_illegal));
    bufp->fullCData(oldp+399,(vlSelf->fetch_unit__DOT__rvcDecompressor_2__DOT__rch),5);
    bufp->fullCData(oldp+400,(vlSelf->fetch_unit__DOT__rvcDecompressor_2__DOT__rcl),5);
    bufp->fullSData(oldp+401,(vlSelf->fetch_unit__DOT__rvcDecompressor_2__DOT__addi5spnImm),12);
    bufp->fullSData(oldp+402,(vlSelf->fetch_unit__DOT__rvcDecompressor_2__DOT__lwImm),12);
    bufp->fullSData(oldp+403,(vlSelf->fetch_unit__DOT__rvcDecompressor_2__DOT__ldImm),12);
    bufp->fullBit(oldp+404,(vlSelf->fetch_unit__DOT__rvcDecompressor_2__DOT__tmp_addImm));
    bufp->fullSData(oldp+405,(vlSelf->fetch_unit__DOT__rvcDecompressor_2__DOT__addImm),12);
    bufp->fullBit(oldp+406,(vlSelf->fetch_unit__DOT__rvcDecompressor_2__DOT__tmp_jalImm));
    bufp->fullSData(oldp+407,(vlSelf->fetch_unit__DOT__rvcDecompressor_2__DOT__tmp_jalImm_1),10);
    bufp->fullIData(oldp+408,(vlSelf->fetch_unit__DOT__rvcDecompressor_2__DOT__jalImm),21);
    bufp->fullBit(oldp+409,(vlSelf->fetch_unit__DOT__rvcDecompressor_2__DOT__tmp_luiImm));
    bufp->fullSData(oldp+410,(vlSelf->fetch_unit__DOT__rvcDecompressor_2__DOT__tmp_luiImm_1),15);
    bufp->fullIData(oldp+411,(vlSelf->fetch_unit__DOT__rvcDecompressor_2__DOT__luiImm),32);
    bufp->fullCData(oldp+412,(vlSelf->fetch_unit__DOT__rvcDecompressor_2__DOT__shiftImm),5);
    bufp->fullBit(oldp+413,(vlSelf->fetch_unit__DOT__rvcDecompressor_2__DOT__tmp_addi16spImm));
    bufp->fullCData(oldp+414,(vlSelf->fetch_unit__DOT__rvcDecompressor_2__DOT__tmp_addi16spImm_1),3);
    bufp->fullSData(oldp+415,(vlSelf->fetch_unit__DOT__rvcDecompressor_2__DOT__addi16spImm),12);
    bufp->fullBit(oldp+416,(vlSelf->fetch_unit__DOT__rvcDecompressor_2__DOT__tmp_jImm));
    bufp->fullSData(oldp+417,(vlSelf->fetch_unit__DOT__rvcDecompressor_2__DOT__tmp_jImm_1),10);
    bufp->fullIData(oldp+418,(vlSelf->fetch_unit__DOT__rvcDecompressor_2__DOT__jImm),21);
    bufp->fullBit(oldp+419,(vlSelf->fetch_unit__DOT__rvcDecompressor_2__DOT__tmp_bImm));
    bufp->fullCData(oldp+420,(vlSelf->fetch_unit__DOT__rvcDecompressor_2__DOT__tmp_bImm_1),5);
    bufp->fullSData(oldp+421,(vlSelf->fetch_unit__DOT__rvcDecompressor_2__DOT__bImm),13);
    bufp->fullCData(oldp+422,(vlSelf->fetch_unit__DOT__rvcDecompressor_2__DOT__x0),5);
    bufp->fullCData(oldp+423,(vlSelf->fetch_unit__DOT__rvcDecompressor_2__DOT__x1),5);
    bufp->fullCData(oldp+424,(vlSelf->fetch_unit__DOT__rvcDecompressor_2__DOT__x2),5);
    bufp->fullIData(oldp+425,(vlSelf->fetch_unit__DOT__rvcDecompressor_2__DOT__tmp_ret_inst),32);
    bufp->fullIData(oldp+426,(vlSelf->fetch_unit__DOT__rvcDecompressor_3__DOT__i),32);
    bufp->fullIData(oldp+427,(vlSelf->fetch_unit__DOT__rvcDecompressor_3__DOT__decompInstr_inst),32);
    bufp->fullBit(oldp+428,(vlSelf->fetch_unit__DOT__rvcDecompressor_3__DOT__decompInstr_illegal));
    bufp->fullSData(oldp+429,(vlSelf->fetch_unit__DOT__rvcDecompressor_3__DOT__tmp_tmp_ret_inst),12);
    bufp->fullCData(oldp+430,(vlSelf->fetch_unit__DOT__rvcDecompressor_3__DOT__tmp_tmp_ret_inst_1),6);
    bufp->fullIData(oldp+431,(vlSelf->fetch_unit__DOT__rvcDecompressor_3__DOT__tmp_ret_inst_1),32);
    bufp->fullCData(oldp+432,(vlSelf->fetch_unit__DOT__rvcDecompressor_3__DOT__tmp_ret_inst_2),2);
    bufp->fullCData(oldp+433,(vlSelf->fetch_unit__DOT__rvcDecompressor_3__DOT__tmp_ret_inst_3),3);
    bufp->fullCData(oldp+434,(vlSelf->fetch_unit__DOT__rvcDecompressor_3__DOT__tmp_ret_inst_4),3);
    bufp->fullCData(oldp+435,(vlSelf->fetch_unit__DOT__rvcDecompressor_3__DOT__tmp_ret_inst_5),7);
    bufp->fullCData(oldp+436,(vlSelf->fetch_unit__DOT__rvcDecompressor_3__DOT__tmp_ret_inst_6),5);
    bufp->fullBit(oldp+437,(vlSelf->fetch_unit__DOT__rvcDecompressor_3__DOT__tmp_ret_inst_7));
    bufp->fullCData(oldp+438,(vlSelf->fetch_unit__DOT__rvcDecompressor_3__DOT__tmp_ret_inst_8),5);
    bufp->fullSData(oldp+439,(vlSelf->fetch_unit__DOT__rvcDecompressor_3__DOT__tmp_ret_inst_9),12);
    bufp->fullSData(oldp+440,(vlSelf->fetch_unit__DOT__rvcDecompressor_3__DOT__tmp_ret_inst_10),12);
    bufp->fullIData(oldp+441,(vlSelf->fetch_unit__DOT__rvcDecompressor_3__DOT__ret_inst),32);
    bufp->fullBit(oldp+442,(vlSelf->fetch_unit__DOT__rvcDecompressor_3__DOT__ret_illegal));
    bufp->fullCData(oldp+443,(vlSelf->fetch_unit__DOT__rvcDecompressor_3__DOT__rch),5);
    bufp->fullCData(oldp+444,(vlSelf->fetch_unit__DOT__rvcDecompressor_3__DOT__rcl),5);
    bufp->fullSData(oldp+445,(vlSelf->fetch_unit__DOT__rvcDecompressor_3__DOT__addi5spnImm),12);
    bufp->fullSData(oldp+446,(vlSelf->fetch_unit__DOT__rvcDecompressor_3__DOT__lwImm),12);
    bufp->fullSData(oldp+447,(vlSelf->fetch_unit__DOT__rvcDecompressor_3__DOT__ldImm),12);
    bufp->fullBit(oldp+448,(vlSelf->fetch_unit__DOT__rvcDecompressor_3__DOT__tmp_addImm));
    bufp->fullSData(oldp+449,(vlSelf->fetch_unit__DOT__rvcDecompressor_3__DOT__addImm),12);
    bufp->fullBit(oldp+450,(vlSelf->fetch_unit__DOT__rvcDecompressor_3__DOT__tmp_jalImm));
    bufp->fullSData(oldp+451,(vlSelf->fetch_unit__DOT__rvcDecompressor_3__DOT__tmp_jalImm_1),10);
    bufp->fullIData(oldp+452,(vlSelf->fetch_unit__DOT__rvcDecompressor_3__DOT__jalImm),21);
    bufp->fullBit(oldp+453,(vlSelf->fetch_unit__DOT__rvcDecompressor_3__DOT__tmp_luiImm));
    bufp->fullSData(oldp+454,(vlSelf->fetch_unit__DOT__rvcDecompressor_3__DOT__tmp_luiImm_1),15);
    bufp->fullIData(oldp+455,(vlSelf->fetch_unit__DOT__rvcDecompressor_3__DOT__luiImm),32);
    bufp->fullCData(oldp+456,(vlSelf->fetch_unit__DOT__rvcDecompressor_3__DOT__shiftImm),5);
    bufp->fullBit(oldp+457,(vlSelf->fetch_unit__DOT__rvcDecompressor_3__DOT__tmp_addi16spImm));
    bufp->fullCData(oldp+458,(vlSelf->fetch_unit__DOT__rvcDecompressor_3__DOT__tmp_addi16spImm_1),3);
    bufp->fullSData(oldp+459,(vlSelf->fetch_unit__DOT__rvcDecompressor_3__DOT__addi16spImm),12);
    bufp->fullBit(oldp+460,(vlSelf->fetch_unit__DOT__rvcDecompressor_3__DOT__tmp_jImm));
    bufp->fullSData(oldp+461,(vlSelf->fetch_unit__DOT__rvcDecompressor_3__DOT__tmp_jImm_1),10);
    bufp->fullIData(oldp+462,(vlSelf->fetch_unit__DOT__rvcDecompressor_3__DOT__jImm),21);
    bufp->fullBit(oldp+463,(vlSelf->fetch_unit__DOT__rvcDecompressor_3__DOT__tmp_bImm));
    bufp->fullCData(oldp+464,(vlSelf->fetch_unit__DOT__rvcDecompressor_3__DOT__tmp_bImm_1),5);
    bufp->fullSData(oldp+465,(vlSelf->fetch_unit__DOT__rvcDecompressor_3__DOT__bImm),13);
    bufp->fullCData(oldp+466,(vlSelf->fetch_unit__DOT__rvcDecompressor_3__DOT__x0),5);
    bufp->fullCData(oldp+467,(vlSelf->fetch_unit__DOT__rvcDecompressor_3__DOT__x1),5);
    bufp->fullCData(oldp+468,(vlSelf->fetch_unit__DOT__rvcDecompressor_3__DOT__x2),5);
    bufp->fullIData(oldp+469,(vlSelf->fetch_unit__DOT__rvcDecompressor_3__DOT__tmp_ret_inst),32);
    bufp->fullBit(oldp+470,(vlSelf->fetch_unit__DOT__trailone_index_0__DOT__mode));
    bufp->fullBit(oldp+471,(vlSelf->fetch_unit__DOT__trailone_index_0__DOT__lead));
    bufp->fullBit(oldp+472,(vlSelf->fetch_unit__DOT__trailone_index_0__DOT__trail));
    bufp->fullCData(oldp+473,(vlSelf->fetch_unit__DOT__trailone_index_0__DOT__data_in),4);
    bufp->fullCData(oldp+474,(vlSelf->fetch_unit__DOT__trailone_index_0__DOT__cnt_out),3);
    bufp->fullCData(oldp+475,(vlSelf->fetch_unit__DOT__trailone_index_0__DOT__tmp_cnt_out),3);
    bufp->fullCData(oldp+476,(vlSelf->fetch_unit__DOT__trailone_index_0__DOT__data_s),4);
    bufp->fullCData(oldp+477,(vlSelf->fetch_unit__DOT__trailone_index_0__DOT__datain_reverse),4);
    bufp->fullCData(oldp+478,(vlSelf->fetch_unit__DOT__trailone_index_0__DOT__stage_node_0),4);
    bufp->fullCData(oldp+479,(vlSelf->fetch_unit__DOT__trailone_index_0__DOT__stage_node_1),2);
    bufp->fullCData(oldp+480,(vlSelf->fetch_unit__DOT__trailone_index_0__DOT__stage_index1_0),2);
    bufp->fullCData(oldp+481,(vlSelf->fetch_unit__DOT__trailone_index_0__DOT__stage_index1_1),2);
    bufp->fullCData(oldp+482,(vlSelf->fetch_unit__DOT__trailone_index_0__DOT__stage_index2_0),2);
    bufp->fullBit(oldp+483,(vlSelf->fetch_unit__DOT__trailone_index_0__DOT__empty));
    bufp->fullCData(oldp+484,(vlSelf->fetch_unit__DOT__trailone_index_0__DOT__out_remap),2);
    bufp->fullBit(oldp+485,(vlSelf->fetch_unit__DOT__trailone_index_1__DOT__mode));
    bufp->fullBit(oldp+486,(vlSelf->fetch_unit__DOT__trailone_index_1__DOT__lead));
    bufp->fullBit(oldp+487,(vlSelf->fetch_unit__DOT__trailone_index_1__DOT__trail));
    bufp->fullCData(oldp+488,(vlSelf->fetch_unit__DOT__trailone_index_1__DOT__data_in),4);
    bufp->fullCData(oldp+489,(vlSelf->fetch_unit__DOT__trailone_index_1__DOT__cnt_out),3);
    bufp->fullCData(oldp+490,(vlSelf->fetch_unit__DOT__trailone_index_1__DOT__tmp_cnt_out),3);
    bufp->fullCData(oldp+491,(vlSelf->fetch_unit__DOT__trailone_index_1__DOT__data_s),4);
    bufp->fullCData(oldp+492,(vlSelf->fetch_unit__DOT__trailone_index_1__DOT__datain_reverse),4);
    bufp->fullCData(oldp+493,(vlSelf->fetch_unit__DOT__trailone_index_1__DOT__stage_node_0),4);
    bufp->fullCData(oldp+494,(vlSelf->fetch_unit__DOT__trailone_index_1__DOT__stage_node_1),2);
    bufp->fullCData(oldp+495,(vlSelf->fetch_unit__DOT__trailone_index_1__DOT__stage_index1_0),2);
    bufp->fullCData(oldp+496,(vlSelf->fetch_unit__DOT__trailone_index_1__DOT__stage_index1_1),2);
    bufp->fullCData(oldp+497,(vlSelf->fetch_unit__DOT__trailone_index_1__DOT__stage_index2_0),2);
    bufp->fullBit(oldp+498,(vlSelf->fetch_unit__DOT__trailone_index_1__DOT__empty));
    bufp->fullCData(oldp+499,(vlSelf->fetch_unit__DOT__trailone_index_1__DOT__out_remap),2);
    bufp->fullBit(oldp+500,(vlSelf->fetch_unit__DOT__trailone_index_2__DOT__mode));
    bufp->fullBit(oldp+501,(vlSelf->fetch_unit__DOT__trailone_index_2__DOT__lead));
    bufp->fullBit(oldp+502,(vlSelf->fetch_unit__DOT__trailone_index_2__DOT__trail));
    bufp->fullCData(oldp+503,(vlSelf->fetch_unit__DOT__trailone_index_2__DOT__data_in),4);
    bufp->fullCData(oldp+504,(vlSelf->fetch_unit__DOT__trailone_index_2__DOT__cnt_out),3);
    bufp->fullCData(oldp+505,(vlSelf->fetch_unit__DOT__trailone_index_2__DOT__tmp_cnt_out),3);
    bufp->fullCData(oldp+506,(vlSelf->fetch_unit__DOT__trailone_index_2__DOT__data_s),4);
    bufp->fullCData(oldp+507,(vlSelf->fetch_unit__DOT__trailone_index_2__DOT__datain_reverse),4);
    bufp->fullCData(oldp+508,(vlSelf->fetch_unit__DOT__trailone_index_2__DOT__stage_node_0),4);
    bufp->fullCData(oldp+509,(vlSelf->fetch_unit__DOT__trailone_index_2__DOT__stage_node_1),2);
    bufp->fullCData(oldp+510,(vlSelf->fetch_unit__DOT__trailone_index_2__DOT__stage_index1_0),2);
    bufp->fullCData(oldp+511,(vlSelf->fetch_unit__DOT__trailone_index_2__DOT__stage_index1_1),2);
    bufp->fullCData(oldp+512,(vlSelf->fetch_unit__DOT__trailone_index_2__DOT__stage_index2_0),2);
    bufp->fullBit(oldp+513,(vlSelf->fetch_unit__DOT__trailone_index_2__DOT__empty));
    bufp->fullCData(oldp+514,(vlSelf->fetch_unit__DOT__trailone_index_2__DOT__out_remap),2);
    bufp->fullBit(oldp+515,(vlSelf->fetch_unit__DOT__trailone_index_3__DOT__mode));
    bufp->fullBit(oldp+516,(vlSelf->fetch_unit__DOT__trailone_index_3__DOT__lead));
    bufp->fullBit(oldp+517,(vlSelf->fetch_unit__DOT__trailone_index_3__DOT__trail));
    bufp->fullCData(oldp+518,(vlSelf->fetch_unit__DOT__trailone_index_3__DOT__data_in),4);
    bufp->fullCData(oldp+519,(vlSelf->fetch_unit__DOT__trailone_index_3__DOT__cnt_out),3);
    bufp->fullCData(oldp+520,(vlSelf->fetch_unit__DOT__trailone_index_3__DOT__tmp_cnt_out),3);
    bufp->fullCData(oldp+521,(vlSelf->fetch_unit__DOT__trailone_index_3__DOT__data_s),4);
    bufp->fullCData(oldp+522,(vlSelf->fetch_unit__DOT__trailone_index_3__DOT__datain_reverse),4);
    bufp->fullCData(oldp+523,(vlSelf->fetch_unit__DOT__trailone_index_3__DOT__stage_node_0),4);
    bufp->fullCData(oldp+524,(vlSelf->fetch_unit__DOT__trailone_index_3__DOT__stage_node_1),2);
    bufp->fullCData(oldp+525,(vlSelf->fetch_unit__DOT__trailone_index_3__DOT__stage_index1_0),2);
    bufp->fullCData(oldp+526,(vlSelf->fetch_unit__DOT__trailone_index_3__DOT__stage_index1_1),2);
    bufp->fullCData(oldp+527,(vlSelf->fetch_unit__DOT__trailone_index_3__DOT__stage_index2_0),2);
    bufp->fullBit(oldp+528,(vlSelf->fetch_unit__DOT__trailone_index_3__DOT__empty));
    bufp->fullCData(oldp+529,(vlSelf->fetch_unit__DOT__trailone_index_3__DOT__out_remap),2);
    bufp->fullBit(oldp+530,(vlSelf->fetch_unit__DOT__validNumFifo__DOT__push_valid));
    bufp->fullBit(oldp+531,(vlSelf->fetch_unit__DOT__validNumFifo__DOT__push_ready));
    bufp->fullCData(oldp+532,(vlSelf->fetch_unit__DOT__validNumFifo__DOT__push_payload),3);
    bufp->fullBit(oldp+533,(vlSelf->fetch_unit__DOT__validNumFifo__DOT__pop_valid));
    bufp->fullBit(oldp+534,(vlSelf->fetch_unit__DOT__validNumFifo__DOT__pop_ready));
    bufp->fullCData(oldp+535,(vlSelf->fetch_unit__DOT__validNumFifo__DOT__pop_pop_req_num),3);
    bufp->fullCData(oldp+536,(vlSelf->fetch_unit__DOT__validNumFifo__DOT__pop_pop_out_data),3);
    bufp->fullBit(oldp+537,(vlSelf->fetch_unit__DOT__validNumFifo__DOT__pop_pop_real));
    bufp->fullCData(oldp+538,(vlSelf->fetch_unit__DOT__validNumFifo__DOT__head),3);
    bufp->fullBit(oldp+539,(vlSelf->fetch_unit__DOT__validNumFifo__DOT__flush));
    bufp->fullCData(oldp+540,(vlSelf->fetch_unit__DOT__validNumFifo__DOT__occupancy),3);
    bufp->fullBit(oldp+541,(vlSelf->fetch_unit__DOT__validNumFifo__DOT__clk));
    bufp->fullBit(oldp+542,(vlSelf->fetch_unit__DOT__validNumFifo__DOT__resetn));
    bufp->fullCData(oldp+543,(vlSelf->fetch_unit__DOT__validNumFifo__DOT__tmp_tmp_pop_pop_out_data),3);
    bufp->fullCData(oldp+544,(vlSelf->fetch_unit__DOT__validNumFifo__DOT__tmp_occupancy),3);
    bufp->fullCData(oldp+545,(vlSelf->fetch_unit__DOT__validNumFifo__DOT__vec_0),3);
    bufp->fullCData(oldp+546,(vlSelf->fetch_unit__DOT__validNumFifo__DOT__vec_1),3);
    bufp->fullCData(oldp+547,(vlSelf->fetch_unit__DOT__validNumFifo__DOT__vec_2),3);
    bufp->fullCData(oldp+548,(vlSelf->fetch_unit__DOT__validNumFifo__DOT__vec_3),3);
    bufp->fullCData(oldp+549,(vlSelf->fetch_unit__DOT__validNumFifo__DOT__vec_4),3);
    bufp->fullCData(oldp+550,(vlSelf->fetch_unit__DOT__validNumFifo__DOT__vec_5),3);
    bufp->fullCData(oldp+551,(vlSelf->fetch_unit__DOT__validNumFifo__DOT__pushPtrGlobal),3);
    bufp->fullCData(oldp+552,(vlSelf->fetch_unit__DOT__validNumFifo__DOT__popPtrGlobal),3);
    bufp->fullBit(oldp+553,(vlSelf->fetch_unit__DOT__validNumFifo__DOT__ptrMatch));
    bufp->fullBit(oldp+554,(vlSelf->fetch_unit__DOT__validNumFifo__DOT__risingOccupancy));
    bufp->fullBit(oldp+555,(vlSelf->fetch_unit__DOT__validNumFifo__DOT__empty));
    bufp->fullBit(oldp+556,(vlSelf->fetch_unit__DOT__validNumFifo__DOT__full));
    bufp->fullBit(oldp+557,(vlSelf->fetch_unit__DOT__validNumFifo__DOT__pushing));
    bufp->fullCData(oldp+558,(vlSelf->fetch_unit__DOT__validNumFifo__DOT__tmp_pop_pop_out_data),3);
    bufp->fullCData(oldp+559,(vlSelf->fetch_unit__DOT__validNumFifo__DOT__tmp_1),8);
    bufp->fullCData(oldp+560,(vlSelf->fetch_unit__DOT__validNumFifo__DOT__tmp_vec_0),3);
    bufp->fullCData(oldp+561,(vlSelf->fetch_unit__DOT__validNumFifo__DOT__tmp_2),8);
    bufp->fullCData(oldp+562,(vlSelf->fetch_unit__DOT__validNumFifo__DOT__ptrDif),3);
    bufp->fullCData(oldp+563,(0U),2);
    bufp->fullCData(oldp+564,(1U),2);
    bufp->fullCData(oldp+565,(2U),2);
    bufp->fullCData(oldp+566,(3U),2);
}
