// Verilated -*- C++ -*-
// DESCRIPTION: Verilator output: Tracing implementation internals
#include "verilated_fst_c.h"
#include "Vtop__Syms.h"


VL_ATTR_COLD void Vtop___024root__trace_init_sub__TOP__0(Vtop___024root* vlSelf, VerilatedFst* tracep) {
    if (false && vlSelf) {}  // Prevent unused
    Vtop__Syms* const __restrict vlSymsp VL_ATTR_UNUSED = vlSelf->vlSymsp;
    VL_DEBUG_IF(VL_DBG_MSGF("+    Vtop___024root__trace_init_sub__TOP__0\n"); );
    // Init
    const int c = vlSymsp->__Vm_baseCode;
    // Body
    tracep->declBit(c+1,"core_en",-1,FST_VD_INPUT,FST_VT_VCD_WIRE, false,-1);
    tracep->declBit(c+2,"ibus_cmd_valid",-1,FST_VD_OUTPUT,FST_VT_VCD_WIRE, false,-1);
    tracep->declBit(c+3,"ibus_cmd_ready",-1,FST_VD_INPUT,FST_VT_VCD_WIRE, false,-1);
    tracep->declBus(c+4,"ibus_cmd_payload_address",-1,FST_VD_OUTPUT,FST_VT_VCD_WIRE, false,-1, 31,0);
    tracep->declBit(c+5,"ibus_rsp_valid",-1,FST_VD_INPUT,FST_VT_VCD_WIRE, false,-1);
    tracep->declBit(c+6,"ibus_rsp_ready",-1,FST_VD_OUTPUT,FST_VT_VCD_WIRE, false,-1);
    tracep->declQuad(c+7,"ibus_rsp_payload_rdata",-1,FST_VD_INPUT,FST_VT_VCD_WIRE, false,-1, 63,0);
    tracep->declBus(c+9,"if2id_itf_0_instr_data",-1,FST_VD_OUTPUT,FST_VT_VCD_WIRE, false,-1, 31,0);
    tracep->declBus(c+10,"if2id_itf_0_instr_pc",-1,FST_VD_OUTPUT,FST_VT_VCD_WIRE, false,-1, 31,0);
    tracep->declBit(c+11,"if2id_itf_0_valid",-1,FST_VD_OUTPUT,FST_VT_VCD_WIRE, false,-1);
    tracep->declBus(c+12,"if2id_itf_1_instr_data",-1,FST_VD_OUTPUT,FST_VT_VCD_WIRE, false,-1, 31,0);
    tracep->declBus(c+13,"if2id_itf_1_instr_pc",-1,FST_VD_OUTPUT,FST_VT_VCD_WIRE, false,-1, 31,0);
    tracep->declBit(c+14,"if2id_itf_1_valid",-1,FST_VD_OUTPUT,FST_VT_VCD_WIRE, false,-1);
    tracep->declBit(c+15,"fetchStage_flush",-1,FST_VD_INPUT,FST_VT_VCD_WIRE, false,-1);
    tracep->declBit(c+16,"fetchStage_isDone",-1,FST_VD_INPUT,FST_VT_VCD_WIRE, false,-1);
    tracep->declBit(c+17,"fetchStage_isReady",-1,FST_VD_OUTPUT,FST_VT_VCD_WIRE, false,-1);
    tracep->declBit(c+18,"pcJumpTarget_valid",-1,FST_VD_INPUT,FST_VT_VCD_WIRE, false,-1);
    tracep->declBus(c+19,"pcJumpTarget_payload",-1,FST_VD_INPUT,FST_VT_VCD_WIRE, false,-1, 31,0);
    tracep->declBit(c+20,"pcPredicted_valid",-1,FST_VD_INPUT,FST_VT_VCD_WIRE, false,-1);
    tracep->declBus(c+21,"pcPredicted_payload",-1,FST_VD_INPUT,FST_VT_VCD_WIRE, false,-1, 31,0);
    tracep->declBit(c+22,"clk",-1,FST_VD_INPUT,FST_VT_VCD_WIRE, false,-1);
    tracep->declBit(c+23,"resetn",-1,FST_VD_INPUT,FST_VT_VCD_WIRE, false,-1);
    tracep->pushNamePrefix("fetch_unit ");
    tracep->declBit(c+24,"core_en",-1,FST_VD_INPUT,FST_VT_VCD_WIRE, false,-1);
    tracep->declBit(c+25,"ibus_cmd_valid",-1,FST_VD_OUTPUT,FST_VT_VCD_WIRE, false,-1);
    tracep->declBit(c+26,"ibus_cmd_ready",-1,FST_VD_INPUT,FST_VT_VCD_WIRE, false,-1);
    tracep->declBus(c+27,"ibus_cmd_payload_address",-1,FST_VD_OUTPUT,FST_VT_VCD_WIRE, false,-1, 31,0);
    tracep->declBit(c+28,"ibus_rsp_valid",-1,FST_VD_INPUT,FST_VT_VCD_WIRE, false,-1);
    tracep->declBit(c+29,"ibus_rsp_ready",-1,FST_VD_OUTPUT,FST_VT_VCD_WIRE, false,-1);
    tracep->declQuad(c+30,"ibus_rsp_payload_rdata",-1,FST_VD_INPUT,FST_VT_VCD_WIRE, false,-1, 63,0);
    tracep->declBus(c+32,"if2id_itf_0_instr_data",-1,FST_VD_OUTPUT,FST_VT_VCD_WIRE, false,-1, 31,0);
    tracep->declBus(c+33,"if2id_itf_0_instr_pc",-1,FST_VD_OUTPUT,FST_VT_VCD_WIRE, false,-1, 31,0);
    tracep->declBit(c+34,"if2id_itf_0_valid",-1,FST_VD_OUTPUT,FST_VT_VCD_WIRE, false,-1);
    tracep->declBus(c+35,"if2id_itf_1_instr_data",-1,FST_VD_OUTPUT,FST_VT_VCD_WIRE, false,-1, 31,0);
    tracep->declBus(c+36,"if2id_itf_1_instr_pc",-1,FST_VD_OUTPUT,FST_VT_VCD_WIRE, false,-1, 31,0);
    tracep->declBit(c+37,"if2id_itf_1_valid",-1,FST_VD_OUTPUT,FST_VT_VCD_WIRE, false,-1);
    tracep->declBit(c+38,"fetchStage_flush",-1,FST_VD_INPUT,FST_VT_VCD_WIRE, false,-1);
    tracep->declBit(c+39,"fetchStage_isDone",-1,FST_VD_INPUT,FST_VT_VCD_WIRE, false,-1);
    tracep->declBit(c+40,"fetchStage_isReady",-1,FST_VD_OUTPUT,FST_VT_VCD_WIRE, false,-1);
    tracep->declBit(c+41,"pcJumpTarget_valid",-1,FST_VD_INPUT,FST_VT_VCD_WIRE, false,-1);
    tracep->declBus(c+42,"pcJumpTarget_payload",-1,FST_VD_INPUT,FST_VT_VCD_WIRE, false,-1, 31,0);
    tracep->declBit(c+43,"pcPredicted_valid",-1,FST_VD_INPUT,FST_VT_VCD_WIRE, false,-1);
    tracep->declBus(c+44,"pcPredicted_payload",-1,FST_VD_INPUT,FST_VT_VCD_WIRE, false,-1, 31,0);
    tracep->declBit(c+45,"clk",-1,FST_VD_INPUT,FST_VT_VCD_WIRE, false,-1);
    tracep->declBit(c+46,"resetn",-1,FST_VD_INPUT,FST_VT_VCD_WIRE, false,-1);
    tracep->declBus(c+530,"RVL",-1, FST_VD_IMPLICIT,FST_VT_VCD_PARAMETER, false,-1, 1,0);
    tracep->declBus(c+531,"RVH",-1, FST_VD_IMPLICIT,FST_VT_VCD_PARAMETER, false,-1, 1,0);
    tracep->declBus(c+532,"RVC",-1, FST_VD_IMPLICIT,FST_VT_VCD_PARAMETER, false,-1, 1,0);
    tracep->declBus(c+533,"INVALID",-1, FST_VD_IMPLICIT,FST_VT_VCD_PARAMETER, false,-1, 1,0);
    tracep->declBit(c+47,"addressFifo_io_push_valid",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1);
    tracep->declBit(c+48,"addressFifo_io_pop_ready",-1, FST_VD_IMPLICIT,FST_VT_SV_LOGIC, false,-1);
    tracep->declBit(c+49,"addressFifo_io_flush",-1, FST_VD_IMPLICIT,FST_VT_SV_LOGIC, false,-1);
    tracep->declBit(c+50,"validNumFifo_push_valid",-1, FST_VD_IMPLICIT,FST_VT_SV_LOGIC, false,-1);
    tracep->declBus(c+51,"validNumFifo_push_payload",-1, FST_VD_IMPLICIT,FST_VT_SV_LOGIC, false,-1, 2,0);
    tracep->declBit(c+52,"validNumFifo_pop_valid",-1, FST_VD_IMPLICIT,FST_VT_SV_LOGIC, false,-1);
    tracep->declBus(c+53,"validNumFifo_pop_pop_req_num",-1, FST_VD_IMPLICIT,FST_VT_SV_LOGIC, false,-1, 2,0);
    tracep->declBit(c+54,"validNumFifo_flush",-1, FST_VD_IMPLICIT,FST_VT_SV_LOGIC, false,-1);
    tracep->declBit(c+55,"instrFifo_io_push_0_valid",-1, FST_VD_IMPLICIT,FST_VT_SV_LOGIC, false,-1);
    tracep->declQuad(c+56,"instrFifo_io_push_0_payload",-1, FST_VD_IMPLICIT,FST_VT_SV_LOGIC, false,-1, 32,0);
    tracep->declBit(c+58,"instrFifo_io_push_1_valid",-1, FST_VD_IMPLICIT,FST_VT_SV_LOGIC, false,-1);
    tracep->declQuad(c+59,"instrFifo_io_push_1_payload",-1, FST_VD_IMPLICIT,FST_VT_SV_LOGIC, false,-1, 32,0);
    tracep->declBit(c+61,"instrFifo_io_push_2_valid",-1, FST_VD_IMPLICIT,FST_VT_SV_LOGIC, false,-1);
    tracep->declQuad(c+62,"instrFifo_io_push_2_payload",-1, FST_VD_IMPLICIT,FST_VT_SV_LOGIC, false,-1, 32,0);
    tracep->declBit(c+64,"instrFifo_io_push_3_valid",-1, FST_VD_IMPLICIT,FST_VT_SV_LOGIC, false,-1);
    tracep->declQuad(c+65,"instrFifo_io_push_3_payload",-1, FST_VD_IMPLICIT,FST_VT_SV_LOGIC, false,-1, 32,0);
    tracep->declBit(c+67,"instrFifo_io_flush",-1, FST_VD_IMPLICIT,FST_VT_SV_LOGIC, false,-1);
    tracep->declBus(c+68,"rvcDecompressor_2_i",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1, 31,0);
    tracep->declBus(c+69,"rvcDecompressor_3_i",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1, 31,0);
    tracep->declBit(c+70,"addressFifo_io_push_ready",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1);
    tracep->declBit(c+71,"addressFifo_io_pop_valid",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1);
    tracep->declBus(c+72,"addressFifo_io_pop_payload",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1, 31,0);
    tracep->declBus(c+73,"addressFifo_io_head",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1, 31,0);
    tracep->declBus(c+74,"addressFifo_io_occupancy",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1, 2,0);
    tracep->declBit(c+75,"validNumFifo_push_ready",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1);
    tracep->declBit(c+76,"validNumFifo_pop_ready",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1);
    tracep->declBus(c+77,"validNumFifo_pop_pop_out_data",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1, 2,0);
    tracep->declBit(c+78,"validNumFifo_pop_pop_real",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1);
    tracep->declBus(c+79,"validNumFifo_head",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1, 2,0);
    tracep->declBus(c+80,"validNumFifo_occupancy",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1, 2,0);
    tracep->declBit(c+81,"instrFifo_io_push_0_ready",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1);
    tracep->declBit(c+82,"instrFifo_io_push_1_ready",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1);
    tracep->declBit(c+83,"instrFifo_io_push_2_ready",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1);
    tracep->declBit(c+84,"instrFifo_io_push_3_ready",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1);
    tracep->declBit(c+85,"instrFifo_io_pop_0_valid",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1);
    tracep->declQuad(c+86,"instrFifo_io_pop_0_payload",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1, 32,0);
    tracep->declBit(c+88,"instrFifo_io_pop_1_valid",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1);
    tracep->declQuad(c+89,"instrFifo_io_pop_1_payload",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1, 32,0);
    tracep->declBus(c+91,"instrFifo_io_occupancy",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1, 3,0);
    tracep->declBit(c+92,"instrFifo_io_ov_waterline",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1);
    tracep->declBus(c+93,"trailone_index_0_cnt_out",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1, 2,0);
    tracep->declBus(c+94,"trailone_index_1_cnt_out",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1, 2,0);
    tracep->declBus(c+95,"trailone_index_2_cnt_out",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1, 2,0);
    tracep->declBus(c+96,"trailone_index_3_cnt_out",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1, 2,0);
    tracep->declBus(c+97,"instr_push_valid_vec_popc_cnt_out",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1, 2,0);
    tracep->declBus(c+98,"instr_pop_valid_popc_cnt_out",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1, 1,0);
    tracep->declBus(c+99,"rvcDecompressor_2_decompInstr_inst",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1, 31,0);
    tracep->declBit(c+100,"rvcDecompressor_2_decompInstr_illegal",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1);
    tracep->declBus(c+101,"rvcDecompressor_3_decompInstr_inst",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1, 31,0);
    tracep->declBit(c+102,"rvcDecompressor_3_decompInstr_illegal",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1);
    tracep->declQuad(c+103,"tmp_io_push_0_payload",-1, FST_VD_IMPLICIT,FST_VT_SV_LOGIC, false,-1, 32,0);
    tracep->declBit(c+105,"tmp_io_push_0_valid",-1, FST_VD_IMPLICIT,FST_VT_SV_LOGIC, false,-1);
    tracep->declQuad(c+106,"tmp_io_push_1_payload",-1, FST_VD_IMPLICIT,FST_VT_SV_LOGIC, false,-1, 32,0);
    tracep->declBit(c+108,"tmp_io_push_1_valid",-1, FST_VD_IMPLICIT,FST_VT_SV_LOGIC, false,-1);
    tracep->declQuad(c+109,"tmp_io_push_2_payload",-1, FST_VD_IMPLICIT,FST_VT_SV_LOGIC, false,-1, 32,0);
    tracep->declBit(c+111,"tmp_io_push_2_valid",-1, FST_VD_IMPLICIT,FST_VT_SV_LOGIC, false,-1);
    tracep->declQuad(c+112,"tmp_io_push_3_payload",-1, FST_VD_IMPLICIT,FST_VT_SV_LOGIC, false,-1, 32,0);
    tracep->declBit(c+114,"tmp_io_push_3_valid",-1, FST_VD_IMPLICIT,FST_VT_SV_LOGIC, false,-1);
    tracep->declBus(c+115,"tmp_if2id_itf_0_instr_pc",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1, 31,0);
    tracep->declBus(c+116,"tmp_if2id_itf_0_instr_pc_1",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1, 31,0);
    tracep->declBus(c+117,"tmp_if2id_itf_1_instr_pc",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1, 31,0);
    tracep->declBus(c+118,"tmp_if2id_itf_1_instr_pc_1",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1, 31,0);
    tracep->declBus(c+119,"tmp_if2id_itf_1_instr_pc_2",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1, 31,0);
    tracep->declBus(c+120,"pc",-1, FST_VD_IMPLICIT,FST_VT_SV_LOGIC, false,-1, 31,0);
    tracep->declBus(c+121,"default_next_pc",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1, 31,0);
    tracep->declBit(c+122,"fetch_pending",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1);
    tracep->declBus(c+123,"addressOffset",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1, 1,0);
    tracep->declBit(c+124,"ibus_cmd_fire",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1);
    tracep->declBit(c+125,"valid_instr_slice_0",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1);
    tracep->declBit(c+126,"valid_instr_slice_1",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1);
    tracep->declBit(c+127,"valid_instr_slice_2",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1);
    tracep->declBit(c+128,"valid_instr_slice_3",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1);
    tracep->declBit(c+129,"instr_slices_0_valid",-1, FST_VD_IMPLICIT,FST_VT_SV_LOGIC, false,-1);
    tracep->declQuad(c+130,"instr_slices_0_payload",-1, FST_VD_IMPLICIT,FST_VT_SV_LOGIC, false,-1, 32,0);
    tracep->declBit(c+132,"instr_slices_1_valid",-1, FST_VD_IMPLICIT,FST_VT_SV_LOGIC, false,-1);
    tracep->declQuad(c+133,"instr_slices_1_payload",-1, FST_VD_IMPLICIT,FST_VT_SV_LOGIC, false,-1, 32,0);
    tracep->declBit(c+135,"instr_slices_2_valid",-1, FST_VD_IMPLICIT,FST_VT_SV_LOGIC, false,-1);
    tracep->declQuad(c+136,"instr_slices_2_payload",-1, FST_VD_IMPLICIT,FST_VT_SV_LOGIC, false,-1, 32,0);
    tracep->declBit(c+138,"instr_slices_3_valid",-1, FST_VD_IMPLICIT,FST_VT_SV_LOGIC, false,-1);
    tracep->declQuad(c+139,"instr_slices_3_payload",-1, FST_VD_IMPLICIT,FST_VT_SV_LOGIC, false,-1, 32,0);
    tracep->declBus(c+141,"tail_one_matrix_0",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1, 3,0);
    tracep->declBus(c+142,"tail_one_matrix_1",-1, FST_VD_IMPLICIT,FST_VT_SV_LOGIC, false,-1, 3,0);
    tracep->declBus(c+143,"tail_one_matrix_2",-1, FST_VD_IMPLICIT,FST_VT_SV_LOGIC, false,-1, 3,0);
    tracep->declBus(c+144,"tail_one_matrix_3",-1, FST_VD_IMPLICIT,FST_VT_SV_LOGIC, false,-1, 3,0);
    tracep->declBus(c+145,"tail_one_index_vec_0",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1, 1,0);
    tracep->declBus(c+146,"tail_one_index_vec_1",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1, 1,0);
    tracep->declBus(c+147,"tail_one_index_vec_2",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1, 1,0);
    tracep->declBus(c+148,"tail_one_index_vec_3",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1, 1,0);
    tracep->declBit(c+149,"tail_one_valid_vec_0",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1);
    tracep->declBit(c+150,"tail_one_valid_vec_1",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1);
    tracep->declBit(c+151,"tail_one_valid_vec_2",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1);
    tracep->declBit(c+152,"tail_one_valid_vec_3",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1);
    tracep->declBus(c+153,"slice_valid_vec_0",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1, 0,0);
    tracep->declBus(c+154,"slice_valid_vec_1",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1, 0,0);
    tracep->declBus(c+155,"slice_valid_vec_2",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1, 0,0);
    tracep->declBus(c+156,"slice_valid_vec_3",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1, 0,0);
    tracep->declBit(c+157,"tmp_1",-1, FST_VD_IMPLICIT,FST_VT_SV_LOGIC, false,-1);
    tracep->declBus(c+158,"tmp_instr_slices_0_payload",-1, FST_VD_IMPLICIT,FST_VT_SV_LOGIC, false,-1, 15,0);
    tracep->declBus(c+159,"tmp_2",-1, FST_VD_IMPLICIT,FST_VT_SV_LOGIC, false,-1, 1,0);
    tracep->declBus(c+160,"tmp_3",-1, FST_VD_IMPLICIT,FST_VT_SV_LOGIC, false,-1, 1,0);
    tracep->declBus(c+161,"tmp_4",-1, FST_VD_IMPLICIT,FST_VT_SV_LOGIC, false,-1, 1,0);
    tracep->declBus(c+162,"tmp_5",-1, FST_VD_IMPLICIT,FST_VT_SV_LOGIC, false,-1, 1,0);
    tracep->declBit(c+163,"ibus_rsp_fire",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1);
    tracep->declBus(c+164,"instr_push_valid_vec",-1, FST_VD_IMPLICIT,FST_VT_SV_LOGIC, false,-1, 3,0);
    tracep->declBit(c+165,"toplevel_instrFifo_io_push_0_fire",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1);
    tracep->declBus(c+166,"instr_pop_valid",-1, FST_VD_IMPLICIT,FST_VT_SV_LOGIC, false,-1, 1,0);
    tracep->declBit(c+167,"toplevel_instrFifo_io_pop_0_fire",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1);
    tracep->declBit(c+168,"toplevel_instrFifo_io_pop_1_fire",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1);
    tracep->declBus(c+169,"pc_pop_offset",-1, FST_VD_IMPLICIT,FST_VT_SV_LOGIC, false,-1, 2,0);
    tracep->declBus(c+170,"pc_step_all_1",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1, 2,0);
    tracep->declBus(c+171,"pc_step_all_2",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1, 2,0);
    tracep->declBus(c+172,"real_instr_0",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1, 31,0);
    tracep->declBus(c+173,"real_instr_1",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1, 31,0);
    tracep->declBit(c+174,"tmp_pc_step_all_1",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1);
    tracep->declBit(c+175,"tmp_pc_step_all_2",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1);
    tracep->declQuad(c+176,"tmp_2_string",-1, FST_VD_IMPLICIT,FST_VT_SV_LOGIC, false,-1, 55,0);
    tracep->declQuad(c+178,"tmp_3_string",-1, FST_VD_IMPLICIT,FST_VT_SV_LOGIC, false,-1, 55,0);
    tracep->declQuad(c+180,"tmp_4_string",-1, FST_VD_IMPLICIT,FST_VT_SV_LOGIC, false,-1, 55,0);
    tracep->declQuad(c+182,"tmp_5_string",-1, FST_VD_IMPLICIT,FST_VT_SV_LOGIC, false,-1, 55,0);
    tracep->pushNamePrefix("addressFifo ");
    tracep->declBit(c+184,"io_push_valid",-1,FST_VD_INPUT,FST_VT_VCD_WIRE, false,-1);
    tracep->declBit(c+185,"io_push_ready",-1,FST_VD_OUTPUT,FST_VT_VCD_WIRE, false,-1);
    tracep->declBus(c+186,"io_push_payload",-1,FST_VD_INPUT,FST_VT_VCD_WIRE, false,-1, 31,0);
    tracep->declBit(c+187,"io_pop_valid",-1,FST_VD_OUTPUT,FST_VT_VCD_WIRE, false,-1);
    tracep->declBit(c+188,"io_pop_ready",-1,FST_VD_INPUT,FST_VT_VCD_WIRE, false,-1);
    tracep->declBus(c+189,"io_pop_payload",-1,FST_VD_OUTPUT,FST_VT_VCD_WIRE, false,-1, 31,0);
    tracep->declBus(c+190,"io_head",-1,FST_VD_OUTPUT,FST_VT_VCD_WIRE, false,-1, 31,0);
    tracep->declBit(c+191,"io_flush",-1,FST_VD_INPUT,FST_VT_VCD_WIRE, false,-1);
    tracep->declBus(c+192,"io_occupancy",-1,FST_VD_OUTPUT,FST_VT_VCD_WIRE, false,-1, 2,0);
    tracep->declBit(c+193,"clk",-1,FST_VD_INPUT,FST_VT_VCD_WIRE, false,-1);
    tracep->declBit(c+194,"resetn",-1,FST_VD_INPUT,FST_VT_VCD_WIRE, false,-1);
    tracep->declBus(c+195,"tmp_pushPtr_valueNext",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1, 1,0);
    tracep->declBus(c+196,"tmp_pushPtr_valueNext_1",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1, 0,0);
    tracep->declBus(c+197,"tmp_popPtr_valueNext",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1, 1,0);
    tracep->declBus(c+198,"tmp_popPtr_valueNext_1",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1, 0,0);
    tracep->declBus(c+199,"tmp_readed",-1, FST_VD_IMPLICIT,FST_VT_SV_LOGIC, false,-1, 31,0);
    tracep->declBus(c+200,"vec_0",-1, FST_VD_IMPLICIT,FST_VT_SV_LOGIC, false,-1, 31,0);
    tracep->declBus(c+201,"vec_1",-1, FST_VD_IMPLICIT,FST_VT_SV_LOGIC, false,-1, 31,0);
    tracep->declBus(c+202,"vec_2",-1, FST_VD_IMPLICIT,FST_VT_SV_LOGIC, false,-1, 31,0);
    tracep->declBus(c+203,"vec_3",-1, FST_VD_IMPLICIT,FST_VT_SV_LOGIC, false,-1, 31,0);
    tracep->declBit(c+204,"pushPtr_willIncrement",-1, FST_VD_IMPLICIT,FST_VT_SV_LOGIC, false,-1);
    tracep->declBit(c+205,"pushPtr_willClear",-1, FST_VD_IMPLICIT,FST_VT_SV_LOGIC, false,-1);
    tracep->declBus(c+206,"pushPtr_valueNext",-1, FST_VD_IMPLICIT,FST_VT_SV_LOGIC, false,-1, 1,0);
    tracep->declBus(c+207,"pushPtr_value",-1, FST_VD_IMPLICIT,FST_VT_SV_LOGIC, false,-1, 1,0);
    tracep->declBit(c+208,"pushPtr_willOverflowIfInc",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1);
    tracep->declBit(c+209,"pushPtr_willOverflow",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1);
    tracep->declBit(c+210,"popPtr_willIncrement",-1, FST_VD_IMPLICIT,FST_VT_SV_LOGIC, false,-1);
    tracep->declBit(c+211,"popPtr_willClear",-1, FST_VD_IMPLICIT,FST_VT_SV_LOGIC, false,-1);
    tracep->declBus(c+212,"popPtr_valueNext",-1, FST_VD_IMPLICIT,FST_VT_SV_LOGIC, false,-1, 1,0);
    tracep->declBus(c+213,"popPtr_value",-1, FST_VD_IMPLICIT,FST_VT_SV_LOGIC, false,-1, 1,0);
    tracep->declBit(c+214,"popPtr_willOverflowIfInc",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1);
    tracep->declBit(c+215,"popPtr_willOverflow",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1);
    tracep->declBit(c+216,"ptrMatch",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1);
    tracep->declBit(c+217,"risingOccupancy",-1, FST_VD_IMPLICIT,FST_VT_SV_LOGIC, false,-1);
    tracep->declBit(c+218,"empty",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1);
    tracep->declBit(c+219,"full",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1);
    tracep->declBit(c+220,"pushing",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1);
    tracep->declBit(c+221,"popping",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1);
    tracep->declBus(c+222,"readed",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1, 31,0);
    tracep->declBus(c+223,"tmp_1",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1, 3,0);
    tracep->declBus(c+224,"ptrDif",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1, 1,0);
    tracep->popNamePrefix(1);
    tracep->pushNamePrefix("instrFifo ");
    tracep->declBit(c+225,"io_push_0_valid",-1,FST_VD_INPUT,FST_VT_VCD_WIRE, false,-1);
    tracep->declBit(c+226,"io_push_0_ready",-1,FST_VD_OUTPUT,FST_VT_VCD_WIRE, false,-1);
    tracep->declQuad(c+227,"io_push_0_payload",-1,FST_VD_INPUT,FST_VT_VCD_WIRE, false,-1, 32,0);
    tracep->declBit(c+229,"io_push_1_valid",-1,FST_VD_INPUT,FST_VT_VCD_WIRE, false,-1);
    tracep->declBit(c+230,"io_push_1_ready",-1,FST_VD_OUTPUT,FST_VT_VCD_WIRE, false,-1);
    tracep->declQuad(c+231,"io_push_1_payload",-1,FST_VD_INPUT,FST_VT_VCD_WIRE, false,-1, 32,0);
    tracep->declBit(c+233,"io_push_2_valid",-1,FST_VD_INPUT,FST_VT_VCD_WIRE, false,-1);
    tracep->declBit(c+234,"io_push_2_ready",-1,FST_VD_OUTPUT,FST_VT_VCD_WIRE, false,-1);
    tracep->declQuad(c+235,"io_push_2_payload",-1,FST_VD_INPUT,FST_VT_VCD_WIRE, false,-1, 32,0);
    tracep->declBit(c+237,"io_push_3_valid",-1,FST_VD_INPUT,FST_VT_VCD_WIRE, false,-1);
    tracep->declBit(c+238,"io_push_3_ready",-1,FST_VD_OUTPUT,FST_VT_VCD_WIRE, false,-1);
    tracep->declQuad(c+239,"io_push_3_payload",-1,FST_VD_INPUT,FST_VT_VCD_WIRE, false,-1, 32,0);
    tracep->declBit(c+241,"io_pop_0_valid",-1,FST_VD_OUTPUT,FST_VT_VCD_WIRE, false,-1);
    tracep->declBit(c+242,"io_pop_0_ready",-1,FST_VD_INPUT,FST_VT_VCD_WIRE, false,-1);
    tracep->declQuad(c+243,"io_pop_0_payload",-1,FST_VD_OUTPUT,FST_VT_VCD_WIRE, false,-1, 32,0);
    tracep->declBit(c+245,"io_pop_1_valid",-1,FST_VD_OUTPUT,FST_VT_VCD_WIRE, false,-1);
    tracep->declBit(c+246,"io_pop_1_ready",-1,FST_VD_INPUT,FST_VT_VCD_WIRE, false,-1);
    tracep->declQuad(c+247,"io_pop_1_payload",-1,FST_VD_OUTPUT,FST_VT_VCD_WIRE, false,-1, 32,0);
    tracep->declBit(c+249,"io_flush",-1,FST_VD_INPUT,FST_VT_VCD_WIRE, false,-1);
    tracep->declBus(c+250,"io_occupancy",-1,FST_VD_OUTPUT,FST_VT_VCD_WIRE, false,-1, 3,0);
    tracep->declBit(c+251,"io_ov_waterline",-1,FST_VD_OUTPUT,FST_VT_VCD_WIRE, false,-1);
    tracep->declBit(c+252,"clk",-1,FST_VD_INPUT,FST_VT_VCD_WIRE, false,-1);
    tracep->declBit(c+253,"resetn",-1,FST_VD_INPUT,FST_VT_VCD_WIRE, false,-1);
    tracep->declBus(c+254,"tmp_inc_num_1",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1, 1,0);
    tracep->declBus(c+255,"tmp_inc_num_2",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1, 1,0);
    tracep->declBus(c+256,"tmp_inc_num_3",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1, 0,0);
    tracep->declBus(c+257,"tmp_inc_num_4",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1, 2,0);
    tracep->declBus(c+258,"tmp_inc_num_5",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1, 1,0);
    tracep->declBus(c+259,"tmp_inc_num_6",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1, 1,0);
    tracep->declBus(c+260,"tmp_inc_num_7",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1, 0,0);
    tracep->declBus(c+261,"tmp_dec_num_1",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1, 1,0);
    tracep->declBus(c+262,"tmp_dec_num_2",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1, 0,0);
    tracep->declBus(c+263,"tmp_io_push_0_ready",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1, 3,0);
    tracep->declBus(c+264,"tmp_io_push_1_ready",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1, 3,0);
    tracep->declBus(c+265,"tmp_io_push_2_ready",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1, 3,0);
    tracep->declBus(c+266,"tmp_io_push_3_ready",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1, 3,0);
    tracep->declBus(c+267,"tmp_when",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1, 3,0);
    tracep->declBus(c+268,"tmp_when_1",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1, 3,0);
    tracep->declBus(c+269,"tmp_when_2",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1, 3,0);
    tracep->declBus(c+270,"tmp_when_3",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1, 3,0);
    tracep->declBus(c+271,"tmp_when_4",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1, 3,0);
    tracep->declBus(c+272,"tmp_when_5",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1, 3,0);
    tracep->declQuad(c+273,"tmp_readedVec_0",-1, FST_VD_IMPLICIT,FST_VT_SV_LOGIC, false,-1, 32,0);
    tracep->declBus(c+275,"tmp_readedVec_0_1",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1, 3,0);
    tracep->declQuad(c+276,"tmp_readedVec_1",-1, FST_VD_IMPLICIT,FST_VT_SV_LOGIC, false,-1, 32,0);
    tracep->declBus(c+278,"tmp_readedVec_1_1",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1, 3,0);
    tracep->declBus(c+279,"tmp_when_6",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1, 2,0);
    tracep->declBus(c+280,"tmp_pushPtrGlobalInc",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1, 3,0);
    tracep->declBus(c+281,"tmp_popPtrGlobalInc",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1, 3,0);
    tracep->declBus(c+282,"tmp_io_occupancy",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1, 3,0);
    tracep->declQuad(c+283,"vec_0",-1, FST_VD_IMPLICIT,FST_VT_SV_LOGIC, false,-1, 32,0);
    tracep->declQuad(c+285,"vec_1",-1, FST_VD_IMPLICIT,FST_VT_SV_LOGIC, false,-1, 32,0);
    tracep->declQuad(c+287,"vec_2",-1, FST_VD_IMPLICIT,FST_VT_SV_LOGIC, false,-1, 32,0);
    tracep->declQuad(c+289,"vec_3",-1, FST_VD_IMPLICIT,FST_VT_SV_LOGIC, false,-1, 32,0);
    tracep->declQuad(c+291,"vec_4",-1, FST_VD_IMPLICIT,FST_VT_SV_LOGIC, false,-1, 32,0);
    tracep->declQuad(c+293,"vec_5",-1, FST_VD_IMPLICIT,FST_VT_SV_LOGIC, false,-1, 32,0);
    tracep->declQuad(c+295,"vec_6",-1, FST_VD_IMPLICIT,FST_VT_SV_LOGIC, false,-1, 32,0);
    tracep->declQuad(c+297,"vec_7",-1, FST_VD_IMPLICIT,FST_VT_SV_LOGIC, false,-1, 32,0);
    tracep->declQuad(c+299,"vec_8",-1, FST_VD_IMPLICIT,FST_VT_SV_LOGIC, false,-1, 32,0);
    tracep->declQuad(c+301,"vec_9",-1, FST_VD_IMPLICIT,FST_VT_SV_LOGIC, false,-1, 32,0);
    tracep->declQuad(c+303,"vec_10",-1, FST_VD_IMPLICIT,FST_VT_SV_LOGIC, false,-1, 32,0);
    tracep->declQuad(c+305,"vec_11",-1, FST_VD_IMPLICIT,FST_VT_SV_LOGIC, false,-1, 32,0);
    tracep->declBus(c+307,"pushPtrGlobal",-1, FST_VD_IMPLICIT,FST_VT_SV_LOGIC, false,-1, 3,0);
    tracep->declBus(c+308,"popPtrGlobal",-1, FST_VD_IMPLICIT,FST_VT_SV_LOGIC, false,-1, 3,0);
    tracep->declBit(c+309,"ptrMatch",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1);
    tracep->declBit(c+310,"risingOccupancy",-1, FST_VD_IMPLICIT,FST_VT_SV_LOGIC, false,-1);
    tracep->declBit(c+311,"empty",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1);
    tracep->declBit(c+312,"full",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1);
    tracep->declBit(c+313,"pushing_vec_0",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1);
    tracep->declBit(c+314,"pushing_vec_1",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1);
    tracep->declBit(c+315,"pushing_vec_2",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1);
    tracep->declBit(c+316,"pushing_vec_3",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1);
    tracep->declBit(c+317,"popping_vec_0",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1);
    tracep->declBit(c+318,"popping_vec_1",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1);
    tracep->declBit(c+319,"tmp_inc_num",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1);
    tracep->declBus(c+320,"inc_num",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1, 2,0);
    tracep->declBit(c+321,"tmp_dec_num",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1);
    tracep->declBus(c+322,"dec_num",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1, 1,0);
    tracep->declBus(c+323,"pushPtrs_0",-1, FST_VD_IMPLICIT,FST_VT_SV_LOGIC, false,-1, 3,0);
    tracep->declBus(c+324,"pushPtrs_1",-1, FST_VD_IMPLICIT,FST_VT_SV_LOGIC, false,-1, 3,0);
    tracep->declBus(c+325,"pushPtrs_2",-1, FST_VD_IMPLICIT,FST_VT_SV_LOGIC, false,-1, 3,0);
    tracep->declBus(c+326,"pushPtrs_3",-1, FST_VD_IMPLICIT,FST_VT_SV_LOGIC, false,-1, 3,0);
    tracep->declBus(c+327,"popPtrs_0",-1, FST_VD_IMPLICIT,FST_VT_SV_LOGIC, false,-1, 3,0);
    tracep->declBus(c+328,"popPtrs_1",-1, FST_VD_IMPLICIT,FST_VT_SV_LOGIC, false,-1, 3,0);
    tracep->declQuad(c+329,"readedVec_0",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1, 32,0);
    tracep->declQuad(c+331,"readedVec_1",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1, 32,0);
    tracep->declBus(c+333,"tmp_1",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1, 15,0);
    tracep->declBus(c+334,"tmp_2",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1, 15,0);
    tracep->declBus(c+335,"tmp_3",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1, 15,0);
    tracep->declBus(c+336,"tmp_4",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1, 15,0);
    tracep->declBus(c+337,"pushPtrGlobalInc",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1, 3,0);
    tracep->declBus(c+338,"popPtrGlobalInc",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1, 3,0);
    tracep->declBus(c+339,"ptrDif",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1, 3,0);
    tracep->popNamePrefix(1);
    tracep->pushNamePrefix("instr_pop_valid_popc ");
    tracep->declBit(c+340,"din_vld",-1,FST_VD_INPUT,FST_VT_VCD_WIRE, false,-1);
    tracep->declBus(c+341,"data_in",-1,FST_VD_INPUT,FST_VT_VCD_WIRE, false,-1, 1,0);
    tracep->declBus(c+342,"cnt_out",-1,FST_VD_OUTPUT,FST_VT_VCD_WIRE, false,-1, 1,0);
    tracep->declBus(c+343,"popsum_init_0",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1, 0,0);
    tracep->declBus(c+344,"popsum_init_1",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1, 0,0);
    tracep->declBus(c+345,"popsum_stage1_ele0",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1, 1,0);
    tracep->popNamePrefix(1);
    tracep->pushNamePrefix("instr_push_valid_vec_popc ");
    tracep->declBit(c+346,"din_vld",-1,FST_VD_INPUT,FST_VT_VCD_WIRE, false,-1);
    tracep->declBus(c+347,"data_in",-1,FST_VD_INPUT,FST_VT_VCD_WIRE, false,-1, 3,0);
    tracep->declBus(c+348,"cnt_out",-1,FST_VD_OUTPUT,FST_VT_VCD_WIRE, false,-1, 2,0);
    tracep->declBus(c+349,"popsum_init_0",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1, 0,0);
    tracep->declBus(c+350,"popsum_init_1",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1, 0,0);
    tracep->declBus(c+351,"popsum_init_2",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1, 0,0);
    tracep->declBus(c+352,"popsum_init_3",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1, 0,0);
    tracep->declBus(c+353,"popsum_stage1_ele0",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1, 1,0);
    tracep->declBus(c+354,"popsum_stage1_ele1",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1, 1,0);
    tracep->declBus(c+355,"popsum_stage2_ele0",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1, 2,0);
    tracep->popNamePrefix(1);
    tracep->pushNamePrefix("rvcDecompressor_2 ");
    tracep->declBus(c+356,"i",-1,FST_VD_INPUT,FST_VT_VCD_WIRE, false,-1, 31,0);
    tracep->declBus(c+357,"decompInstr_inst",-1,FST_VD_OUTPUT,FST_VT_VCD_WIRE, false,-1, 31,0);
    tracep->declBit(c+358,"decompInstr_illegal",-1,FST_VD_OUTPUT,FST_VT_VCD_WIRE, false,-1);
    tracep->declBus(c+359,"tmp_tmp_ret_inst",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1, 11,0);
    tracep->declBus(c+360,"tmp_tmp_ret_inst_1",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1, 5,0);
    tracep->declBus(c+361,"tmp_ret_inst_1",-1, FST_VD_IMPLICIT,FST_VT_SV_LOGIC, false,-1, 31,0);
    tracep->declBus(c+362,"tmp_ret_inst_2",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1, 1,0);
    tracep->declBus(c+363,"tmp_ret_inst_3",-1, FST_VD_IMPLICIT,FST_VT_SV_LOGIC, false,-1, 2,0);
    tracep->declBus(c+364,"tmp_ret_inst_4",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1, 2,0);
    tracep->declBus(c+365,"tmp_ret_inst_5",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1, 6,0);
    tracep->declBus(c+366,"tmp_ret_inst_6",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1, 4,0);
    tracep->declBit(c+367,"tmp_ret_inst_7",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1);
    tracep->declBus(c+368,"tmp_ret_inst_8",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1, 4,0);
    tracep->declBus(c+369,"tmp_ret_inst_9",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1, 11,0);
    tracep->declBus(c+370,"tmp_ret_inst_10",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1, 11,0);
    tracep->declBus(c+371,"ret_inst",-1, FST_VD_IMPLICIT,FST_VT_SV_LOGIC, false,-1, 31,0);
    tracep->declBit(c+372,"ret_illegal",-1, FST_VD_IMPLICIT,FST_VT_SV_LOGIC, false,-1);
    tracep->declBus(c+373,"rch",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1, 4,0);
    tracep->declBus(c+374,"rcl",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1, 4,0);
    tracep->declBus(c+375,"addi5spnImm",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1, 11,0);
    tracep->declBus(c+376,"lwImm",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1, 11,0);
    tracep->declBus(c+377,"ldImm",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1, 11,0);
    tracep->declBit(c+378,"tmp_addImm",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1);
    tracep->declBus(c+379,"addImm",-1, FST_VD_IMPLICIT,FST_VT_SV_LOGIC, false,-1, 11,0);
    tracep->declBit(c+380,"tmp_jalImm",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1);
    tracep->declBus(c+381,"tmp_jalImm_1",-1, FST_VD_IMPLICIT,FST_VT_SV_LOGIC, false,-1, 9,0);
    tracep->declBus(c+382,"jalImm",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1, 20,0);
    tracep->declBit(c+383,"tmp_luiImm",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1);
    tracep->declBus(c+384,"tmp_luiImm_1",-1, FST_VD_IMPLICIT,FST_VT_SV_LOGIC, false,-1, 14,0);
    tracep->declBus(c+385,"luiImm",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1, 31,0);
    tracep->declBus(c+386,"shiftImm",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1, 4,0);
    tracep->declBit(c+387,"tmp_addi16spImm",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1);
    tracep->declBus(c+388,"tmp_addi16spImm_1",-1, FST_VD_IMPLICIT,FST_VT_SV_LOGIC, false,-1, 2,0);
    tracep->declBus(c+389,"addi16spImm",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1, 11,0);
    tracep->declBit(c+390,"tmp_jImm",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1);
    tracep->declBus(c+391,"tmp_jImm_1",-1, FST_VD_IMPLICIT,FST_VT_SV_LOGIC, false,-1, 9,0);
    tracep->declBus(c+392,"jImm",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1, 20,0);
    tracep->declBit(c+393,"tmp_bImm",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1);
    tracep->declBus(c+394,"tmp_bImm_1",-1, FST_VD_IMPLICIT,FST_VT_SV_LOGIC, false,-1, 4,0);
    tracep->declBus(c+395,"bImm",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1, 12,0);
    tracep->declBus(c+396,"x0",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1, 4,0);
    tracep->declBus(c+397,"x1",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1, 4,0);
    tracep->declBus(c+398,"x2",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1, 4,0);
    tracep->declBus(c+399,"tmp_ret_inst",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1, 31,0);
    tracep->popNamePrefix(1);
    tracep->pushNamePrefix("rvcDecompressor_3 ");
    tracep->declBus(c+400,"i",-1,FST_VD_INPUT,FST_VT_VCD_WIRE, false,-1, 31,0);
    tracep->declBus(c+401,"decompInstr_inst",-1,FST_VD_OUTPUT,FST_VT_VCD_WIRE, false,-1, 31,0);
    tracep->declBit(c+402,"decompInstr_illegal",-1,FST_VD_OUTPUT,FST_VT_VCD_WIRE, false,-1);
    tracep->declBus(c+403,"tmp_tmp_ret_inst",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1, 11,0);
    tracep->declBus(c+404,"tmp_tmp_ret_inst_1",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1, 5,0);
    tracep->declBus(c+405,"tmp_ret_inst_1",-1, FST_VD_IMPLICIT,FST_VT_SV_LOGIC, false,-1, 31,0);
    tracep->declBus(c+406,"tmp_ret_inst_2",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1, 1,0);
    tracep->declBus(c+407,"tmp_ret_inst_3",-1, FST_VD_IMPLICIT,FST_VT_SV_LOGIC, false,-1, 2,0);
    tracep->declBus(c+408,"tmp_ret_inst_4",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1, 2,0);
    tracep->declBus(c+409,"tmp_ret_inst_5",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1, 6,0);
    tracep->declBus(c+410,"tmp_ret_inst_6",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1, 4,0);
    tracep->declBit(c+411,"tmp_ret_inst_7",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1);
    tracep->declBus(c+412,"tmp_ret_inst_8",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1, 4,0);
    tracep->declBus(c+413,"tmp_ret_inst_9",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1, 11,0);
    tracep->declBus(c+414,"tmp_ret_inst_10",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1, 11,0);
    tracep->declBus(c+415,"ret_inst",-1, FST_VD_IMPLICIT,FST_VT_SV_LOGIC, false,-1, 31,0);
    tracep->declBit(c+416,"ret_illegal",-1, FST_VD_IMPLICIT,FST_VT_SV_LOGIC, false,-1);
    tracep->declBus(c+417,"rch",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1, 4,0);
    tracep->declBus(c+418,"rcl",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1, 4,0);
    tracep->declBus(c+419,"addi5spnImm",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1, 11,0);
    tracep->declBus(c+420,"lwImm",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1, 11,0);
    tracep->declBus(c+421,"ldImm",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1, 11,0);
    tracep->declBit(c+422,"tmp_addImm",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1);
    tracep->declBus(c+423,"addImm",-1, FST_VD_IMPLICIT,FST_VT_SV_LOGIC, false,-1, 11,0);
    tracep->declBit(c+424,"tmp_jalImm",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1);
    tracep->declBus(c+425,"tmp_jalImm_1",-1, FST_VD_IMPLICIT,FST_VT_SV_LOGIC, false,-1, 9,0);
    tracep->declBus(c+426,"jalImm",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1, 20,0);
    tracep->declBit(c+427,"tmp_luiImm",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1);
    tracep->declBus(c+428,"tmp_luiImm_1",-1, FST_VD_IMPLICIT,FST_VT_SV_LOGIC, false,-1, 14,0);
    tracep->declBus(c+429,"luiImm",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1, 31,0);
    tracep->declBus(c+430,"shiftImm",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1, 4,0);
    tracep->declBit(c+431,"tmp_addi16spImm",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1);
    tracep->declBus(c+432,"tmp_addi16spImm_1",-1, FST_VD_IMPLICIT,FST_VT_SV_LOGIC, false,-1, 2,0);
    tracep->declBus(c+433,"addi16spImm",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1, 11,0);
    tracep->declBit(c+434,"tmp_jImm",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1);
    tracep->declBus(c+435,"tmp_jImm_1",-1, FST_VD_IMPLICIT,FST_VT_SV_LOGIC, false,-1, 9,0);
    tracep->declBus(c+436,"jImm",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1, 20,0);
    tracep->declBit(c+437,"tmp_bImm",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1);
    tracep->declBus(c+438,"tmp_bImm_1",-1, FST_VD_IMPLICIT,FST_VT_SV_LOGIC, false,-1, 4,0);
    tracep->declBus(c+439,"bImm",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1, 12,0);
    tracep->declBus(c+440,"x0",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1, 4,0);
    tracep->declBus(c+441,"x1",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1, 4,0);
    tracep->declBus(c+442,"x2",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1, 4,0);
    tracep->declBus(c+443,"tmp_ret_inst",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1, 31,0);
    tracep->popNamePrefix(1);
    tracep->pushNamePrefix("trailone_index_0 ");
    tracep->declBit(c+444,"mode",-1,FST_VD_INPUT,FST_VT_VCD_WIRE, false,-1);
    tracep->declBit(c+445,"lead",-1,FST_VD_INPUT,FST_VT_VCD_WIRE, false,-1);
    tracep->declBit(c+446,"trail",-1,FST_VD_INPUT,FST_VT_VCD_WIRE, false,-1);
    tracep->declBus(c+447,"data_in",-1,FST_VD_INPUT,FST_VT_VCD_WIRE, false,-1, 3,0);
    tracep->declBus(c+448,"cnt_out",-1,FST_VD_OUTPUT,FST_VT_VCD_WIRE, false,-1, 2,0);
    tracep->declBus(c+449,"tmp_cnt_out",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1, 2,0);
    tracep->declBus(c+450,"data_s",-1, FST_VD_IMPLICIT,FST_VT_SV_LOGIC, false,-1, 3,0);
    tracep->declBus(c+451,"datain_reverse",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1, 3,0);
    tracep->declBus(c+452,"stage_node_0",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1, 3,0);
    tracep->declBus(c+453,"stage_node_1",-1, FST_VD_IMPLICIT,FST_VT_SV_LOGIC, false,-1, 1,0);
    tracep->declBus(c+454,"stage_index1_0",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1, 1,0);
    tracep->declBus(c+455,"stage_index1_1",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1, 1,0);
    tracep->declBus(c+456,"stage_index2_0",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1, 1,0);
    tracep->declBit(c+457,"empty",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1);
    tracep->popNamePrefix(1);
    tracep->pushNamePrefix("trailone_index_1 ");
    tracep->declBit(c+458,"mode",-1,FST_VD_INPUT,FST_VT_VCD_WIRE, false,-1);
    tracep->declBit(c+459,"lead",-1,FST_VD_INPUT,FST_VT_VCD_WIRE, false,-1);
    tracep->declBit(c+460,"trail",-1,FST_VD_INPUT,FST_VT_VCD_WIRE, false,-1);
    tracep->declBus(c+461,"data_in",-1,FST_VD_INPUT,FST_VT_VCD_WIRE, false,-1, 3,0);
    tracep->declBus(c+462,"cnt_out",-1,FST_VD_OUTPUT,FST_VT_VCD_WIRE, false,-1, 2,0);
    tracep->declBus(c+463,"tmp_cnt_out",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1, 2,0);
    tracep->declBus(c+464,"data_s",-1, FST_VD_IMPLICIT,FST_VT_SV_LOGIC, false,-1, 3,0);
    tracep->declBus(c+465,"datain_reverse",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1, 3,0);
    tracep->declBus(c+466,"stage_node_0",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1, 3,0);
    tracep->declBus(c+467,"stage_node_1",-1, FST_VD_IMPLICIT,FST_VT_SV_LOGIC, false,-1, 1,0);
    tracep->declBus(c+468,"stage_index1_0",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1, 1,0);
    tracep->declBus(c+469,"stage_index1_1",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1, 1,0);
    tracep->declBus(c+470,"stage_index2_0",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1, 1,0);
    tracep->declBit(c+471,"empty",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1);
    tracep->popNamePrefix(1);
    tracep->pushNamePrefix("trailone_index_2 ");
    tracep->declBit(c+472,"mode",-1,FST_VD_INPUT,FST_VT_VCD_WIRE, false,-1);
    tracep->declBit(c+473,"lead",-1,FST_VD_INPUT,FST_VT_VCD_WIRE, false,-1);
    tracep->declBit(c+474,"trail",-1,FST_VD_INPUT,FST_VT_VCD_WIRE, false,-1);
    tracep->declBus(c+475,"data_in",-1,FST_VD_INPUT,FST_VT_VCD_WIRE, false,-1, 3,0);
    tracep->declBus(c+476,"cnt_out",-1,FST_VD_OUTPUT,FST_VT_VCD_WIRE, false,-1, 2,0);
    tracep->declBus(c+477,"tmp_cnt_out",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1, 2,0);
    tracep->declBus(c+478,"data_s",-1, FST_VD_IMPLICIT,FST_VT_SV_LOGIC, false,-1, 3,0);
    tracep->declBus(c+479,"datain_reverse",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1, 3,0);
    tracep->declBus(c+480,"stage_node_0",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1, 3,0);
    tracep->declBus(c+481,"stage_node_1",-1, FST_VD_IMPLICIT,FST_VT_SV_LOGIC, false,-1, 1,0);
    tracep->declBus(c+482,"stage_index1_0",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1, 1,0);
    tracep->declBus(c+483,"stage_index1_1",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1, 1,0);
    tracep->declBus(c+484,"stage_index2_0",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1, 1,0);
    tracep->declBit(c+485,"empty",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1);
    tracep->popNamePrefix(1);
    tracep->pushNamePrefix("trailone_index_3 ");
    tracep->declBit(c+486,"mode",-1,FST_VD_INPUT,FST_VT_VCD_WIRE, false,-1);
    tracep->declBit(c+487,"lead",-1,FST_VD_INPUT,FST_VT_VCD_WIRE, false,-1);
    tracep->declBit(c+488,"trail",-1,FST_VD_INPUT,FST_VT_VCD_WIRE, false,-1);
    tracep->declBus(c+489,"data_in",-1,FST_VD_INPUT,FST_VT_VCD_WIRE, false,-1, 3,0);
    tracep->declBus(c+490,"cnt_out",-1,FST_VD_OUTPUT,FST_VT_VCD_WIRE, false,-1, 2,0);
    tracep->declBus(c+491,"tmp_cnt_out",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1, 2,0);
    tracep->declBus(c+492,"data_s",-1, FST_VD_IMPLICIT,FST_VT_SV_LOGIC, false,-1, 3,0);
    tracep->declBus(c+493,"datain_reverse",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1, 3,0);
    tracep->declBus(c+494,"stage_node_0",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1, 3,0);
    tracep->declBus(c+495,"stage_node_1",-1, FST_VD_IMPLICIT,FST_VT_SV_LOGIC, false,-1, 1,0);
    tracep->declBus(c+496,"stage_index1_0",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1, 1,0);
    tracep->declBus(c+497,"stage_index1_1",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1, 1,0);
    tracep->declBus(c+498,"stage_index2_0",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1, 1,0);
    tracep->declBit(c+499,"empty",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1);
    tracep->popNamePrefix(1);
    tracep->pushNamePrefix("validNumFifo ");
    tracep->declBit(c+500,"push_valid",-1,FST_VD_INPUT,FST_VT_VCD_WIRE, false,-1);
    tracep->declBit(c+501,"push_ready",-1,FST_VD_OUTPUT,FST_VT_VCD_WIRE, false,-1);
    tracep->declBus(c+502,"push_payload",-1,FST_VD_INPUT,FST_VT_VCD_WIRE, false,-1, 2,0);
    tracep->declBit(c+503,"pop_valid",-1,FST_VD_INPUT,FST_VT_VCD_WIRE, false,-1);
    tracep->declBit(c+504,"pop_ready",-1,FST_VD_OUTPUT,FST_VT_VCD_WIRE, false,-1);
    tracep->declBus(c+505,"pop_pop_req_num",-1,FST_VD_INPUT,FST_VT_VCD_WIRE, false,-1, 2,0);
    tracep->declBus(c+506,"pop_pop_out_data",-1,FST_VD_OUTPUT,FST_VT_VCD_WIRE, false,-1, 2,0);
    tracep->declBit(c+507,"pop_pop_real",-1,FST_VD_OUTPUT,FST_VT_VCD_WIRE, false,-1);
    tracep->declBus(c+508,"head",-1,FST_VD_OUTPUT,FST_VT_VCD_WIRE, false,-1, 2,0);
    tracep->declBit(c+509,"flush",-1,FST_VD_INPUT,FST_VT_VCD_WIRE, false,-1);
    tracep->declBus(c+510,"occupancy",-1,FST_VD_OUTPUT,FST_VT_VCD_WIRE, false,-1, 2,0);
    tracep->declBit(c+511,"clk",-1,FST_VD_INPUT,FST_VT_VCD_WIRE, false,-1);
    tracep->declBit(c+512,"resetn",-1,FST_VD_INPUT,FST_VT_VCD_WIRE, false,-1);
    tracep->declBus(c+513,"tmp_tmp_pop_pop_out_data",-1, FST_VD_IMPLICIT,FST_VT_SV_LOGIC, false,-1, 2,0);
    tracep->declBus(c+514,"vec_0",-1, FST_VD_IMPLICIT,FST_VT_SV_LOGIC, false,-1, 2,0);
    tracep->declBus(c+515,"vec_1",-1, FST_VD_IMPLICIT,FST_VT_SV_LOGIC, false,-1, 2,0);
    tracep->declBus(c+516,"vec_2",-1, FST_VD_IMPLICIT,FST_VT_SV_LOGIC, false,-1, 2,0);
    tracep->declBus(c+517,"vec_3",-1, FST_VD_IMPLICIT,FST_VT_SV_LOGIC, false,-1, 2,0);
    tracep->declBus(c+518,"pushPtrGlobal",-1, FST_VD_IMPLICIT,FST_VT_SV_LOGIC, false,-1, 1,0);
    tracep->declBus(c+519,"popPtrGlobal",-1, FST_VD_IMPLICIT,FST_VT_SV_LOGIC, false,-1, 1,0);
    tracep->declBit(c+520,"ptrMatch",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1);
    tracep->declBit(c+521,"risingOccupancy",-1, FST_VD_IMPLICIT,FST_VT_SV_LOGIC, false,-1);
    tracep->declBit(c+522,"empty",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1);
    tracep->declBit(c+523,"full",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1);
    tracep->declBit(c+524,"pushing",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1);
    tracep->declBus(c+525,"tmp_pop_pop_out_data",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1, 2,0);
    tracep->declBus(c+526,"tmp_1",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1, 3,0);
    tracep->declBus(c+527,"tmp_vec_0",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1, 2,0);
    tracep->declBus(c+528,"tmp_2",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1, 3,0);
    tracep->declBus(c+529,"ptrDif",-1, FST_VD_IMPLICIT,FST_VT_VCD_WIRE, false,-1, 1,0);
    tracep->popNamePrefix(2);
}

VL_ATTR_COLD void Vtop___024root__trace_init_top(Vtop___024root* vlSelf, VerilatedFst* tracep) {
    if (false && vlSelf) {}  // Prevent unused
    Vtop__Syms* const __restrict vlSymsp VL_ATTR_UNUSED = vlSelf->vlSymsp;
    VL_DEBUG_IF(VL_DBG_MSGF("+    Vtop___024root__trace_init_top\n"); );
    // Body
    Vtop___024root__trace_init_sub__TOP__0(vlSelf, tracep);
}

VL_ATTR_COLD void Vtop___024root__trace_full_top_0(void* voidSelf, VerilatedFst::Buffer* bufp);
void Vtop___024root__trace_chg_top_0(void* voidSelf, VerilatedFst::Buffer* bufp);
void Vtop___024root__trace_cleanup(void* voidSelf, VerilatedFst* /*unused*/);

VL_ATTR_COLD void Vtop___024root__trace_register(Vtop___024root* vlSelf, VerilatedFst* tracep) {
    if (false && vlSelf) {}  // Prevent unused
    Vtop__Syms* const __restrict vlSymsp VL_ATTR_UNUSED = vlSelf->vlSymsp;
    VL_DEBUG_IF(VL_DBG_MSGF("+    Vtop___024root__trace_register\n"); );
    // Body
    tracep->addFullCb(&Vtop___024root__trace_full_top_0, vlSelf);
    tracep->addChgCb(&Vtop___024root__trace_chg_top_0, vlSelf);
    tracep->addCleanupCb(&Vtop___024root__trace_cleanup, vlSelf);
}

VL_ATTR_COLD void Vtop___024root__trace_full_sub_0(Vtop___024root* vlSelf, VerilatedFst::Buffer* bufp);

VL_ATTR_COLD void Vtop___024root__trace_full_top_0(void* voidSelf, VerilatedFst::Buffer* bufp) {
    VL_DEBUG_IF(VL_DBG_MSGF("+    Vtop___024root__trace_full_top_0\n"); );
    // Init
    Vtop___024root* const __restrict vlSelf VL_ATTR_UNUSED = static_cast<Vtop___024root*>(voidSelf);
    Vtop__Syms* const __restrict vlSymsp VL_ATTR_UNUSED = vlSelf->vlSymsp;
    // Body
    Vtop___024root__trace_full_sub_0((&vlSymsp->TOP), bufp);
}

VL_ATTR_COLD void Vtop___024root__trace_full_sub_0(Vtop___024root* vlSelf, VerilatedFst::Buffer* bufp) {
    if (false && vlSelf) {}  // Prevent unused
    Vtop__Syms* const __restrict vlSymsp VL_ATTR_UNUSED = vlSelf->vlSymsp;
    VL_DEBUG_IF(VL_DBG_MSGF("+    Vtop___024root__trace_full_sub_0\n"); );
    // Init
    uint32_t* const oldp VL_ATTR_UNUSED = bufp->oldp(vlSymsp->__Vm_baseCode);
    // Body
    bufp->fullBit(oldp+1,(vlSelf->core_en));
    bufp->fullBit(oldp+2,(vlSelf->ibus_cmd_valid));
    bufp->fullBit(oldp+3,(vlSelf->ibus_cmd_ready));
    bufp->fullIData(oldp+4,(vlSelf->ibus_cmd_payload_address),32);
    bufp->fullBit(oldp+5,(vlSelf->ibus_rsp_valid));
    bufp->fullBit(oldp+6,(vlSelf->ibus_rsp_ready));
    bufp->fullQData(oldp+7,(vlSelf->ibus_rsp_payload_rdata),64);
    bufp->fullIData(oldp+9,(vlSelf->if2id_itf_0_instr_data),32);
    bufp->fullIData(oldp+10,(vlSelf->if2id_itf_0_instr_pc),32);
    bufp->fullBit(oldp+11,(vlSelf->if2id_itf_0_valid));
    bufp->fullIData(oldp+12,(vlSelf->if2id_itf_1_instr_data),32);
    bufp->fullIData(oldp+13,(vlSelf->if2id_itf_1_instr_pc),32);
    bufp->fullBit(oldp+14,(vlSelf->if2id_itf_1_valid));
    bufp->fullBit(oldp+15,(vlSelf->fetchStage_flush));
    bufp->fullBit(oldp+16,(vlSelf->fetchStage_isDone));
    bufp->fullBit(oldp+17,(vlSelf->fetchStage_isReady));
    bufp->fullBit(oldp+18,(vlSelf->pcJumpTarget_valid));
    bufp->fullIData(oldp+19,(vlSelf->pcJumpTarget_payload),32);
    bufp->fullBit(oldp+20,(vlSelf->pcPredicted_valid));
    bufp->fullIData(oldp+21,(vlSelf->pcPredicted_payload),32);
    bufp->fullBit(oldp+22,(vlSelf->clk));
    bufp->fullBit(oldp+23,(vlSelf->resetn));
    bufp->fullBit(oldp+24,(vlSelf->fetch_unit__DOT__core_en));
    bufp->fullBit(oldp+25,(vlSelf->fetch_unit__DOT__ibus_cmd_valid));
    bufp->fullBit(oldp+26,(vlSelf->fetch_unit__DOT__ibus_cmd_ready));
    bufp->fullIData(oldp+27,(vlSelf->fetch_unit__DOT__ibus_cmd_payload_address),32);
    bufp->fullBit(oldp+28,(vlSelf->fetch_unit__DOT__ibus_rsp_valid));
    bufp->fullBit(oldp+29,(vlSelf->fetch_unit__DOT__ibus_rsp_ready));
    bufp->fullQData(oldp+30,(vlSelf->fetch_unit__DOT__ibus_rsp_payload_rdata),64);
    bufp->fullIData(oldp+32,(vlSelf->fetch_unit__DOT__if2id_itf_0_instr_data),32);
    bufp->fullIData(oldp+33,(vlSelf->fetch_unit__DOT__if2id_itf_0_instr_pc),32);
    bufp->fullBit(oldp+34,(vlSelf->fetch_unit__DOT__if2id_itf_0_valid));
    bufp->fullIData(oldp+35,(vlSelf->fetch_unit__DOT__if2id_itf_1_instr_data),32);
    bufp->fullIData(oldp+36,(vlSelf->fetch_unit__DOT__if2id_itf_1_instr_pc),32);
    bufp->fullBit(oldp+37,(vlSelf->fetch_unit__DOT__if2id_itf_1_valid));
    bufp->fullBit(oldp+38,(vlSelf->fetch_unit__DOT__fetchStage_flush));
    bufp->fullBit(oldp+39,(vlSelf->fetch_unit__DOT__fetchStage_isDone));
    bufp->fullBit(oldp+40,(vlSelf->fetch_unit__DOT__fetchStage_isReady));
    bufp->fullBit(oldp+41,(vlSelf->fetch_unit__DOT__pcJumpTarget_valid));
    bufp->fullIData(oldp+42,(vlSelf->fetch_unit__DOT__pcJumpTarget_payload),32);
    bufp->fullBit(oldp+43,(vlSelf->fetch_unit__DOT__pcPredicted_valid));
    bufp->fullIData(oldp+44,(vlSelf->fetch_unit__DOT__pcPredicted_payload),32);
    bufp->fullBit(oldp+45,(vlSelf->fetch_unit__DOT__clk));
    bufp->fullBit(oldp+46,(vlSelf->fetch_unit__DOT__resetn));
    bufp->fullBit(oldp+47,(vlSelf->fetch_unit__DOT__addressFifo_io_push_valid));
    bufp->fullBit(oldp+48,(vlSelf->fetch_unit__DOT__addressFifo_io_pop_ready));
    bufp->fullBit(oldp+49,(vlSelf->fetch_unit__DOT__addressFifo_io_flush));
    bufp->fullBit(oldp+50,(vlSelf->fetch_unit__DOT__validNumFifo_push_valid));
    bufp->fullCData(oldp+51,(vlSelf->fetch_unit__DOT__validNumFifo_push_payload),3);
    bufp->fullBit(oldp+52,(vlSelf->fetch_unit__DOT__validNumFifo_pop_valid));
    bufp->fullCData(oldp+53,(vlSelf->fetch_unit__DOT__validNumFifo_pop_pop_req_num),3);
    bufp->fullBit(oldp+54,(vlSelf->fetch_unit__DOT__validNumFifo_flush));
    bufp->fullBit(oldp+55,(vlSelf->fetch_unit__DOT__instrFifo_io_push_0_valid));
    bufp->fullQData(oldp+56,(vlSelf->fetch_unit__DOT__instrFifo_io_push_0_payload),33);
    bufp->fullBit(oldp+58,(vlSelf->fetch_unit__DOT__instrFifo_io_push_1_valid));
    bufp->fullQData(oldp+59,(vlSelf->fetch_unit__DOT__instrFifo_io_push_1_payload),33);
    bufp->fullBit(oldp+61,(vlSelf->fetch_unit__DOT__instrFifo_io_push_2_valid));
    bufp->fullQData(oldp+62,(vlSelf->fetch_unit__DOT__instrFifo_io_push_2_payload),33);
    bufp->fullBit(oldp+64,(vlSelf->fetch_unit__DOT__instrFifo_io_push_3_valid));
    bufp->fullQData(oldp+65,(vlSelf->fetch_unit__DOT__instrFifo_io_push_3_payload),33);
    bufp->fullBit(oldp+67,(vlSelf->fetch_unit__DOT__instrFifo_io_flush));
    bufp->fullIData(oldp+68,(vlSelf->fetch_unit__DOT__rvcDecompressor_2_i),32);
    bufp->fullIData(oldp+69,(vlSelf->fetch_unit__DOT__rvcDecompressor_3_i),32);
    bufp->fullBit(oldp+70,(vlSelf->fetch_unit__DOT__addressFifo_io_push_ready));
    bufp->fullBit(oldp+71,(vlSelf->fetch_unit__DOT__addressFifo_io_pop_valid));
    bufp->fullIData(oldp+72,(vlSelf->fetch_unit__DOT__addressFifo_io_pop_payload),32);
    bufp->fullIData(oldp+73,(vlSelf->fetch_unit__DOT__addressFifo_io_head),32);
    bufp->fullCData(oldp+74,(vlSelf->fetch_unit__DOT__addressFifo_io_occupancy),3);
    bufp->fullBit(oldp+75,(vlSelf->fetch_unit__DOT__validNumFifo_push_ready));
    bufp->fullBit(oldp+76,(vlSelf->fetch_unit__DOT__validNumFifo_pop_ready));
    bufp->fullCData(oldp+77,(vlSelf->fetch_unit__DOT__validNumFifo_pop_pop_out_data),3);
    bufp->fullBit(oldp+78,(vlSelf->fetch_unit__DOT__validNumFifo_pop_pop_real));
    bufp->fullCData(oldp+79,(vlSelf->fetch_unit__DOT__validNumFifo_head),3);
    bufp->fullCData(oldp+80,(vlSelf->fetch_unit__DOT__validNumFifo_occupancy),3);
    bufp->fullBit(oldp+81,(vlSelf->fetch_unit__DOT__instrFifo_io_push_0_ready));
    bufp->fullBit(oldp+82,(vlSelf->fetch_unit__DOT__instrFifo_io_push_1_ready));
    bufp->fullBit(oldp+83,(vlSelf->fetch_unit__DOT__instrFifo_io_push_2_ready));
    bufp->fullBit(oldp+84,(vlSelf->fetch_unit__DOT__instrFifo_io_push_3_ready));
    bufp->fullBit(oldp+85,(vlSelf->fetch_unit__DOT__instrFifo_io_pop_0_valid));
    bufp->fullQData(oldp+86,(vlSelf->fetch_unit__DOT__instrFifo_io_pop_0_payload),33);
    bufp->fullBit(oldp+88,(vlSelf->fetch_unit__DOT__instrFifo_io_pop_1_valid));
    bufp->fullQData(oldp+89,(vlSelf->fetch_unit__DOT__instrFifo_io_pop_1_payload),33);
    bufp->fullCData(oldp+91,(vlSelf->fetch_unit__DOT__instrFifo_io_occupancy),4);
    bufp->fullBit(oldp+92,(vlSelf->fetch_unit__DOT__instrFifo_io_ov_waterline));
    bufp->fullCData(oldp+93,(vlSelf->fetch_unit__DOT__trailone_index_0_cnt_out),3);
    bufp->fullCData(oldp+94,(vlSelf->fetch_unit__DOT__trailone_index_1_cnt_out),3);
    bufp->fullCData(oldp+95,(vlSelf->fetch_unit__DOT__trailone_index_2_cnt_out),3);
    bufp->fullCData(oldp+96,(vlSelf->fetch_unit__DOT__trailone_index_3_cnt_out),3);
    bufp->fullCData(oldp+97,(vlSelf->fetch_unit__DOT__instr_push_valid_vec_popc_cnt_out),3);
    bufp->fullCData(oldp+98,(vlSelf->fetch_unit__DOT__instr_pop_valid_popc_cnt_out),2);
    bufp->fullIData(oldp+99,(vlSelf->fetch_unit__DOT__rvcDecompressor_2_decompInstr_inst),32);
    bufp->fullBit(oldp+100,(vlSelf->fetch_unit__DOT__rvcDecompressor_2_decompInstr_illegal));
    bufp->fullIData(oldp+101,(vlSelf->fetch_unit__DOT__rvcDecompressor_3_decompInstr_inst),32);
    bufp->fullBit(oldp+102,(vlSelf->fetch_unit__DOT__rvcDecompressor_3_decompInstr_illegal));
    bufp->fullQData(oldp+103,(vlSelf->fetch_unit__DOT__tmp_io_push_0_payload),33);
    bufp->fullBit(oldp+105,(vlSelf->fetch_unit__DOT__tmp_io_push_0_valid));
    bufp->fullQData(oldp+106,(vlSelf->fetch_unit__DOT__tmp_io_push_1_payload),33);
    bufp->fullBit(oldp+108,(vlSelf->fetch_unit__DOT__tmp_io_push_1_valid));
    bufp->fullQData(oldp+109,(vlSelf->fetch_unit__DOT__tmp_io_push_2_payload),33);
    bufp->fullBit(oldp+111,(vlSelf->fetch_unit__DOT__tmp_io_push_2_valid));
    bufp->fullQData(oldp+112,(vlSelf->fetch_unit__DOT__tmp_io_push_3_payload),33);
    bufp->fullBit(oldp+114,(vlSelf->fetch_unit__DOT__tmp_io_push_3_valid));
    bufp->fullIData(oldp+115,(vlSelf->fetch_unit__DOT__tmp_if2id_itf_0_instr_pc),32);
    bufp->fullIData(oldp+116,(vlSelf->fetch_unit__DOT__tmp_if2id_itf_0_instr_pc_1),32);
    bufp->fullIData(oldp+117,(vlSelf->fetch_unit__DOT__tmp_if2id_itf_1_instr_pc),32);
    bufp->fullIData(oldp+118,(vlSelf->fetch_unit__DOT__tmp_if2id_itf_1_instr_pc_1),32);
    bufp->fullIData(oldp+119,(vlSelf->fetch_unit__DOT__tmp_if2id_itf_1_instr_pc_2),32);
    bufp->fullIData(oldp+120,(vlSelf->fetch_unit__DOT__pc),32);
    bufp->fullIData(oldp+121,(vlSelf->fetch_unit__DOT__default_next_pc),32);
    bufp->fullBit(oldp+122,(vlSelf->fetch_unit__DOT__fetch_pending));
    bufp->fullCData(oldp+123,(vlSelf->fetch_unit__DOT__addressOffset),2);
    bufp->fullBit(oldp+124,(vlSelf->fetch_unit__DOT__ibus_cmd_fire));
    bufp->fullBit(oldp+125,(vlSelf->fetch_unit__DOT__valid_instr_slice_0));
    bufp->fullBit(oldp+126,(vlSelf->fetch_unit__DOT__valid_instr_slice_1));
    bufp->fullBit(oldp+127,(vlSelf->fetch_unit__DOT__valid_instr_slice_2));
    bufp->fullBit(oldp+128,(vlSelf->fetch_unit__DOT__valid_instr_slice_3));
    bufp->fullBit(oldp+129,(vlSelf->fetch_unit__DOT__instr_slices_0_valid));
    bufp->fullQData(oldp+130,(vlSelf->fetch_unit__DOT__instr_slices_0_payload),33);
    bufp->fullBit(oldp+132,(vlSelf->fetch_unit__DOT__instr_slices_1_valid));
    bufp->fullQData(oldp+133,(vlSelf->fetch_unit__DOT__instr_slices_1_payload),33);
    bufp->fullBit(oldp+135,(vlSelf->fetch_unit__DOT__instr_slices_2_valid));
    bufp->fullQData(oldp+136,(vlSelf->fetch_unit__DOT__instr_slices_2_payload),33);
    bufp->fullBit(oldp+138,(vlSelf->fetch_unit__DOT__instr_slices_3_valid));
    bufp->fullQData(oldp+139,(vlSelf->fetch_unit__DOT__instr_slices_3_payload),33);
    bufp->fullCData(oldp+141,(vlSelf->fetch_unit__DOT__tail_one_matrix_0),4);
    bufp->fullCData(oldp+142,(vlSelf->fetch_unit__DOT__tail_one_matrix_1),4);
    bufp->fullCData(oldp+143,(vlSelf->fetch_unit__DOT__tail_one_matrix_2),4);
    bufp->fullCData(oldp+144,(vlSelf->fetch_unit__DOT__tail_one_matrix_3),4);
    bufp->fullCData(oldp+145,(vlSelf->fetch_unit__DOT__tail_one_index_vec_0),2);
    bufp->fullCData(oldp+146,(vlSelf->fetch_unit__DOT__tail_one_index_vec_1),2);
    bufp->fullCData(oldp+147,(vlSelf->fetch_unit__DOT__tail_one_index_vec_2),2);
    bufp->fullCData(oldp+148,(vlSelf->fetch_unit__DOT__tail_one_index_vec_3),2);
    bufp->fullBit(oldp+149,(vlSelf->fetch_unit__DOT__tail_one_valid_vec_0));
    bufp->fullBit(oldp+150,(vlSelf->fetch_unit__DOT__tail_one_valid_vec_1));
    bufp->fullBit(oldp+151,(vlSelf->fetch_unit__DOT__tail_one_valid_vec_2));
    bufp->fullBit(oldp+152,(vlSelf->fetch_unit__DOT__tail_one_valid_vec_3));
    bufp->fullBit(oldp+153,(vlSelf->fetch_unit__DOT__slice_valid_vec_0));
    bufp->fullBit(oldp+154,(vlSelf->fetch_unit__DOT__slice_valid_vec_1));
    bufp->fullBit(oldp+155,(vlSelf->fetch_unit__DOT__slice_valid_vec_2));
    bufp->fullBit(oldp+156,(vlSelf->fetch_unit__DOT__slice_valid_vec_3));
    bufp->fullBit(oldp+157,(vlSelf->fetch_unit__DOT__tmp_1));
    bufp->fullSData(oldp+158,(vlSelf->fetch_unit__DOT__tmp_instr_slices_0_payload),16);
    bufp->fullCData(oldp+159,(vlSelf->fetch_unit__DOT__tmp_2),2);
    bufp->fullCData(oldp+160,(vlSelf->fetch_unit__DOT__tmp_3),2);
    bufp->fullCData(oldp+161,(vlSelf->fetch_unit__DOT__tmp_4),2);
    bufp->fullCData(oldp+162,(vlSelf->fetch_unit__DOT__tmp_5),2);
    bufp->fullBit(oldp+163,(vlSelf->fetch_unit__DOT__ibus_rsp_fire));
    bufp->fullCData(oldp+164,(vlSelf->fetch_unit__DOT__instr_push_valid_vec),4);
    bufp->fullBit(oldp+165,(vlSelf->fetch_unit__DOT__toplevel_instrFifo_io_push_0_fire));
    bufp->fullCData(oldp+166,(vlSelf->fetch_unit__DOT__instr_pop_valid),2);
    bufp->fullBit(oldp+167,(vlSelf->fetch_unit__DOT__toplevel_instrFifo_io_pop_0_fire));
    bufp->fullBit(oldp+168,(vlSelf->fetch_unit__DOT__toplevel_instrFifo_io_pop_1_fire));
    bufp->fullCData(oldp+169,(vlSelf->fetch_unit__DOT__pc_pop_offset),3);
    bufp->fullCData(oldp+170,(vlSelf->fetch_unit__DOT__pc_step_all_1),3);
    bufp->fullCData(oldp+171,(vlSelf->fetch_unit__DOT__pc_step_all_2),3);
    bufp->fullIData(oldp+172,(vlSelf->fetch_unit__DOT__real_instr_0),32);
    bufp->fullIData(oldp+173,(vlSelf->fetch_unit__DOT__real_instr_1),32);
    bufp->fullBit(oldp+174,(vlSelf->fetch_unit__DOT__tmp_pc_step_all_1));
    bufp->fullBit(oldp+175,(vlSelf->fetch_unit__DOT__tmp_pc_step_all_2));
    bufp->fullQData(oldp+176,(vlSelf->fetch_unit__DOT__tmp_2_string),56);
    bufp->fullQData(oldp+178,(vlSelf->fetch_unit__DOT__tmp_3_string),56);
    bufp->fullQData(oldp+180,(vlSelf->fetch_unit__DOT__tmp_4_string),56);
    bufp->fullQData(oldp+182,(vlSelf->fetch_unit__DOT__tmp_5_string),56);
    bufp->fullBit(oldp+184,(vlSelf->fetch_unit__DOT__addressFifo__DOT__io_push_valid));
    bufp->fullBit(oldp+185,(vlSelf->fetch_unit__DOT__addressFifo__DOT__io_push_ready));
    bufp->fullIData(oldp+186,(vlSelf->fetch_unit__DOT__addressFifo__DOT__io_push_payload),32);
    bufp->fullBit(oldp+187,(vlSelf->fetch_unit__DOT__addressFifo__DOT__io_pop_valid));
    bufp->fullBit(oldp+188,(vlSelf->fetch_unit__DOT__addressFifo__DOT__io_pop_ready));
    bufp->fullIData(oldp+189,(vlSelf->fetch_unit__DOT__addressFifo__DOT__io_pop_payload),32);
    bufp->fullIData(oldp+190,(vlSelf->fetch_unit__DOT__addressFifo__DOT__io_head),32);
    bufp->fullBit(oldp+191,(vlSelf->fetch_unit__DOT__addressFifo__DOT__io_flush));
    bufp->fullCData(oldp+192,(vlSelf->fetch_unit__DOT__addressFifo__DOT__io_occupancy),3);
    bufp->fullBit(oldp+193,(vlSelf->fetch_unit__DOT__addressFifo__DOT__clk));
    bufp->fullBit(oldp+194,(vlSelf->fetch_unit__DOT__addressFifo__DOT__resetn));
    bufp->fullCData(oldp+195,(vlSelf->fetch_unit__DOT__addressFifo__DOT__tmp_pushPtr_valueNext),2);
    bufp->fullBit(oldp+196,(vlSelf->fetch_unit__DOT__addressFifo__DOT__tmp_pushPtr_valueNext_1));
    bufp->fullCData(oldp+197,(vlSelf->fetch_unit__DOT__addressFifo__DOT__tmp_popPtr_valueNext),2);
    bufp->fullBit(oldp+198,(vlSelf->fetch_unit__DOT__addressFifo__DOT__tmp_popPtr_valueNext_1));
    bufp->fullIData(oldp+199,(vlSelf->fetch_unit__DOT__addressFifo__DOT__tmp_readed),32);
    bufp->fullIData(oldp+200,(vlSelf->fetch_unit__DOT__addressFifo__DOT__vec_0),32);
    bufp->fullIData(oldp+201,(vlSelf->fetch_unit__DOT__addressFifo__DOT__vec_1),32);
    bufp->fullIData(oldp+202,(vlSelf->fetch_unit__DOT__addressFifo__DOT__vec_2),32);
    bufp->fullIData(oldp+203,(vlSelf->fetch_unit__DOT__addressFifo__DOT__vec_3),32);
    bufp->fullBit(oldp+204,(vlSelf->fetch_unit__DOT__addressFifo__DOT__pushPtr_willIncrement));
    bufp->fullBit(oldp+205,(vlSelf->fetch_unit__DOT__addressFifo__DOT__pushPtr_willClear));
    bufp->fullCData(oldp+206,(vlSelf->fetch_unit__DOT__addressFifo__DOT__pushPtr_valueNext),2);
    bufp->fullCData(oldp+207,(vlSelf->fetch_unit__DOT__addressFifo__DOT__pushPtr_value),2);
    bufp->fullBit(oldp+208,(vlSelf->fetch_unit__DOT__addressFifo__DOT__pushPtr_willOverflowIfInc));
    bufp->fullBit(oldp+209,(vlSelf->fetch_unit__DOT__addressFifo__DOT__pushPtr_willOverflow));
    bufp->fullBit(oldp+210,(vlSelf->fetch_unit__DOT__addressFifo__DOT__popPtr_willIncrement));
    bufp->fullBit(oldp+211,(vlSelf->fetch_unit__DOT__addressFifo__DOT__popPtr_willClear));
    bufp->fullCData(oldp+212,(vlSelf->fetch_unit__DOT__addressFifo__DOT__popPtr_valueNext),2);
    bufp->fullCData(oldp+213,(vlSelf->fetch_unit__DOT__addressFifo__DOT__popPtr_value),2);
    bufp->fullBit(oldp+214,(vlSelf->fetch_unit__DOT__addressFifo__DOT__popPtr_willOverflowIfInc));
    bufp->fullBit(oldp+215,(vlSelf->fetch_unit__DOT__addressFifo__DOT__popPtr_willOverflow));
    bufp->fullBit(oldp+216,(vlSelf->fetch_unit__DOT__addressFifo__DOT__ptrMatch));
    bufp->fullBit(oldp+217,(vlSelf->fetch_unit__DOT__addressFifo__DOT__risingOccupancy));
    bufp->fullBit(oldp+218,(vlSelf->fetch_unit__DOT__addressFifo__DOT__empty));
    bufp->fullBit(oldp+219,(vlSelf->fetch_unit__DOT__addressFifo__DOT__full));
    bufp->fullBit(oldp+220,(vlSelf->fetch_unit__DOT__addressFifo__DOT__pushing));
    bufp->fullBit(oldp+221,(vlSelf->fetch_unit__DOT__addressFifo__DOT__popping));
    bufp->fullIData(oldp+222,(vlSelf->fetch_unit__DOT__addressFifo__DOT__readed),32);
    bufp->fullCData(oldp+223,(vlSelf->fetch_unit__DOT__addressFifo__DOT__tmp_1),4);
    bufp->fullCData(oldp+224,(vlSelf->fetch_unit__DOT__addressFifo__DOT__ptrDif),2);
    bufp->fullBit(oldp+225,(vlSelf->fetch_unit__DOT__instrFifo__DOT__io_push_0_valid));
    bufp->fullBit(oldp+226,(vlSelf->fetch_unit__DOT__instrFifo__DOT__io_push_0_ready));
    bufp->fullQData(oldp+227,(vlSelf->fetch_unit__DOT__instrFifo__DOT__io_push_0_payload),33);
    bufp->fullBit(oldp+229,(vlSelf->fetch_unit__DOT__instrFifo__DOT__io_push_1_valid));
    bufp->fullBit(oldp+230,(vlSelf->fetch_unit__DOT__instrFifo__DOT__io_push_1_ready));
    bufp->fullQData(oldp+231,(vlSelf->fetch_unit__DOT__instrFifo__DOT__io_push_1_payload),33);
    bufp->fullBit(oldp+233,(vlSelf->fetch_unit__DOT__instrFifo__DOT__io_push_2_valid));
    bufp->fullBit(oldp+234,(vlSelf->fetch_unit__DOT__instrFifo__DOT__io_push_2_ready));
    bufp->fullQData(oldp+235,(vlSelf->fetch_unit__DOT__instrFifo__DOT__io_push_2_payload),33);
    bufp->fullBit(oldp+237,(vlSelf->fetch_unit__DOT__instrFifo__DOT__io_push_3_valid));
    bufp->fullBit(oldp+238,(vlSelf->fetch_unit__DOT__instrFifo__DOT__io_push_3_ready));
    bufp->fullQData(oldp+239,(vlSelf->fetch_unit__DOT__instrFifo__DOT__io_push_3_payload),33);
    bufp->fullBit(oldp+241,(vlSelf->fetch_unit__DOT__instrFifo__DOT__io_pop_0_valid));
    bufp->fullBit(oldp+242,(vlSelf->fetch_unit__DOT__instrFifo__DOT__io_pop_0_ready));
    bufp->fullQData(oldp+243,(vlSelf->fetch_unit__DOT__instrFifo__DOT__io_pop_0_payload),33);
    bufp->fullBit(oldp+245,(vlSelf->fetch_unit__DOT__instrFifo__DOT__io_pop_1_valid));
    bufp->fullBit(oldp+246,(vlSelf->fetch_unit__DOT__instrFifo__DOT__io_pop_1_ready));
    bufp->fullQData(oldp+247,(vlSelf->fetch_unit__DOT__instrFifo__DOT__io_pop_1_payload),33);
    bufp->fullBit(oldp+249,(vlSelf->fetch_unit__DOT__instrFifo__DOT__io_flush));
    bufp->fullCData(oldp+250,(vlSelf->fetch_unit__DOT__instrFifo__DOT__io_occupancy),4);
    bufp->fullBit(oldp+251,(vlSelf->fetch_unit__DOT__instrFifo__DOT__io_ov_waterline));
    bufp->fullBit(oldp+252,(vlSelf->fetch_unit__DOT__instrFifo__DOT__clk));
    bufp->fullBit(oldp+253,(vlSelf->fetch_unit__DOT__instrFifo__DOT__resetn));
    bufp->fullCData(oldp+254,(vlSelf->fetch_unit__DOT__instrFifo__DOT__tmp_inc_num_1),2);
    bufp->fullCData(oldp+255,(vlSelf->fetch_unit__DOT__instrFifo__DOT__tmp_inc_num_2),2);
    bufp->fullBit(oldp+256,(vlSelf->fetch_unit__DOT__instrFifo__DOT__tmp_inc_num_3));
    bufp->fullCData(oldp+257,(vlSelf->fetch_unit__DOT__instrFifo__DOT__tmp_inc_num_4),3);
    bufp->fullCData(oldp+258,(vlSelf->fetch_unit__DOT__instrFifo__DOT__tmp_inc_num_5),2);
    bufp->fullCData(oldp+259,(vlSelf->fetch_unit__DOT__instrFifo__DOT__tmp_inc_num_6),2);
    bufp->fullBit(oldp+260,(vlSelf->fetch_unit__DOT__instrFifo__DOT__tmp_inc_num_7));
    bufp->fullCData(oldp+261,(vlSelf->fetch_unit__DOT__instrFifo__DOT__tmp_dec_num_1),2);
    bufp->fullBit(oldp+262,(vlSelf->fetch_unit__DOT__instrFifo__DOT__tmp_dec_num_2));
    bufp->fullCData(oldp+263,(vlSelf->fetch_unit__DOT__instrFifo__DOT__tmp_io_push_0_ready),4);
    bufp->fullCData(oldp+264,(vlSelf->fetch_unit__DOT__instrFifo__DOT__tmp_io_push_1_ready),4);
    bufp->fullCData(oldp+265,(vlSelf->fetch_unit__DOT__instrFifo__DOT__tmp_io_push_2_ready),4);
    bufp->fullCData(oldp+266,(vlSelf->fetch_unit__DOT__instrFifo__DOT__tmp_io_push_3_ready),4);
    bufp->fullCData(oldp+267,(vlSelf->fetch_unit__DOT__instrFifo__DOT__tmp_when),4);
    bufp->fullCData(oldp+268,(vlSelf->fetch_unit__DOT__instrFifo__DOT__tmp_when_1),4);
    bufp->fullCData(oldp+269,(vlSelf->fetch_unit__DOT__instrFifo__DOT__tmp_when_2),4);
    bufp->fullCData(oldp+270,(vlSelf->fetch_unit__DOT__instrFifo__DOT__tmp_when_3),4);
    bufp->fullCData(oldp+271,(vlSelf->fetch_unit__DOT__instrFifo__DOT__tmp_when_4),4);
    bufp->fullCData(oldp+272,(vlSelf->fetch_unit__DOT__instrFifo__DOT__tmp_when_5),4);
    bufp->fullQData(oldp+273,(vlSelf->fetch_unit__DOT__instrFifo__DOT__tmp_readedVec_0),33);
    bufp->fullCData(oldp+275,(vlSelf->fetch_unit__DOT__instrFifo__DOT__tmp_readedVec_0_1),4);
    bufp->fullQData(oldp+276,(vlSelf->fetch_unit__DOT__instrFifo__DOT__tmp_readedVec_1),33);
    bufp->fullCData(oldp+278,(vlSelf->fetch_unit__DOT__instrFifo__DOT__tmp_readedVec_1_1),4);
    bufp->fullCData(oldp+279,(vlSelf->fetch_unit__DOT__instrFifo__DOT__tmp_when_6),3);
    bufp->fullCData(oldp+280,(vlSelf->fetch_unit__DOT__instrFifo__DOT__tmp_pushPtrGlobalInc),4);
    bufp->fullCData(oldp+281,(vlSelf->fetch_unit__DOT__instrFifo__DOT__tmp_popPtrGlobalInc),4);
    bufp->fullCData(oldp+282,(vlSelf->fetch_unit__DOT__instrFifo__DOT__tmp_io_occupancy),4);
    bufp->fullQData(oldp+283,(vlSelf->fetch_unit__DOT__instrFifo__DOT__vec_0),33);
    bufp->fullQData(oldp+285,(vlSelf->fetch_unit__DOT__instrFifo__DOT__vec_1),33);
    bufp->fullQData(oldp+287,(vlSelf->fetch_unit__DOT__instrFifo__DOT__vec_2),33);
    bufp->fullQData(oldp+289,(vlSelf->fetch_unit__DOT__instrFifo__DOT__vec_3),33);
    bufp->fullQData(oldp+291,(vlSelf->fetch_unit__DOT__instrFifo__DOT__vec_4),33);
    bufp->fullQData(oldp+293,(vlSelf->fetch_unit__DOT__instrFifo__DOT__vec_5),33);
    bufp->fullQData(oldp+295,(vlSelf->fetch_unit__DOT__instrFifo__DOT__vec_6),33);
    bufp->fullQData(oldp+297,(vlSelf->fetch_unit__DOT__instrFifo__DOT__vec_7),33);
    bufp->fullQData(oldp+299,(vlSelf->fetch_unit__DOT__instrFifo__DOT__vec_8),33);
    bufp->fullQData(oldp+301,(vlSelf->fetch_unit__DOT__instrFifo__DOT__vec_9),33);
    bufp->fullQData(oldp+303,(vlSelf->fetch_unit__DOT__instrFifo__DOT__vec_10),33);
    bufp->fullQData(oldp+305,(vlSelf->fetch_unit__DOT__instrFifo__DOT__vec_11),33);
    bufp->fullCData(oldp+307,(vlSelf->fetch_unit__DOT__instrFifo__DOT__pushPtrGlobal),4);
    bufp->fullCData(oldp+308,(vlSelf->fetch_unit__DOT__instrFifo__DOT__popPtrGlobal),4);
    bufp->fullBit(oldp+309,(vlSelf->fetch_unit__DOT__instrFifo__DOT__ptrMatch));
    bufp->fullBit(oldp+310,(vlSelf->fetch_unit__DOT__instrFifo__DOT__risingOccupancy));
    bufp->fullBit(oldp+311,(vlSelf->fetch_unit__DOT__instrFifo__DOT__empty));
    bufp->fullBit(oldp+312,(vlSelf->fetch_unit__DOT__instrFifo__DOT__full));
    bufp->fullBit(oldp+313,(vlSelf->fetch_unit__DOT__instrFifo__DOT__pushing_vec_0));
    bufp->fullBit(oldp+314,(vlSelf->fetch_unit__DOT__instrFifo__DOT__pushing_vec_1));
    bufp->fullBit(oldp+315,(vlSelf->fetch_unit__DOT__instrFifo__DOT__pushing_vec_2));
    bufp->fullBit(oldp+316,(vlSelf->fetch_unit__DOT__instrFifo__DOT__pushing_vec_3));
    bufp->fullBit(oldp+317,(vlSelf->fetch_unit__DOT__instrFifo__DOT__popping_vec_0));
    bufp->fullBit(oldp+318,(vlSelf->fetch_unit__DOT__instrFifo__DOT__popping_vec_1));
    bufp->fullBit(oldp+319,(vlSelf->fetch_unit__DOT__instrFifo__DOT__tmp_inc_num));
    bufp->fullCData(oldp+320,(vlSelf->fetch_unit__DOT__instrFifo__DOT__inc_num),3);
    bufp->fullBit(oldp+321,(vlSelf->fetch_unit__DOT__instrFifo__DOT__tmp_dec_num));
    bufp->fullCData(oldp+322,(vlSelf->fetch_unit__DOT__instrFifo__DOT__dec_num),2);
    bufp->fullCData(oldp+323,(vlSelf->fetch_unit__DOT__instrFifo__DOT__pushPtrs_0),4);
    bufp->fullCData(oldp+324,(vlSelf->fetch_unit__DOT__instrFifo__DOT__pushPtrs_1),4);
    bufp->fullCData(oldp+325,(vlSelf->fetch_unit__DOT__instrFifo__DOT__pushPtrs_2),4);
    bufp->fullCData(oldp+326,(vlSelf->fetch_unit__DOT__instrFifo__DOT__pushPtrs_3),4);
    bufp->fullCData(oldp+327,(vlSelf->fetch_unit__DOT__instrFifo__DOT__popPtrs_0),4);
    bufp->fullCData(oldp+328,(vlSelf->fetch_unit__DOT__instrFifo__DOT__popPtrs_1),4);
    bufp->fullQData(oldp+329,(vlSelf->fetch_unit__DOT__instrFifo__DOT__readedVec_0),33);
    bufp->fullQData(oldp+331,(vlSelf->fetch_unit__DOT__instrFifo__DOT__readedVec_1),33);
    bufp->fullSData(oldp+333,(vlSelf->fetch_unit__DOT__instrFifo__DOT__tmp_1),16);
    bufp->fullSData(oldp+334,(vlSelf->fetch_unit__DOT__instrFifo__DOT__tmp_2),16);
    bufp->fullSData(oldp+335,(vlSelf->fetch_unit__DOT__instrFifo__DOT__tmp_3),16);
    bufp->fullSData(oldp+336,(vlSelf->fetch_unit__DOT__instrFifo__DOT__tmp_4),16);
    bufp->fullCData(oldp+337,(vlSelf->fetch_unit__DOT__instrFifo__DOT__pushPtrGlobalInc),4);
    bufp->fullCData(oldp+338,(vlSelf->fetch_unit__DOT__instrFifo__DOT__popPtrGlobalInc),4);
    bufp->fullCData(oldp+339,(vlSelf->fetch_unit__DOT__instrFifo__DOT__ptrDif),4);
    bufp->fullBit(oldp+340,(vlSelf->fetch_unit__DOT__instr_pop_valid_popc__DOT__din_vld));
    bufp->fullCData(oldp+341,(vlSelf->fetch_unit__DOT__instr_pop_valid_popc__DOT__data_in),2);
    bufp->fullCData(oldp+342,(vlSelf->fetch_unit__DOT__instr_pop_valid_popc__DOT__cnt_out),2);
    bufp->fullBit(oldp+343,(vlSelf->fetch_unit__DOT__instr_pop_valid_popc__DOT__popsum_init_0));
    bufp->fullBit(oldp+344,(vlSelf->fetch_unit__DOT__instr_pop_valid_popc__DOT__popsum_init_1));
    bufp->fullCData(oldp+345,(vlSelf->fetch_unit__DOT__instr_pop_valid_popc__DOT__popsum_stage1_ele0),2);
    bufp->fullBit(oldp+346,(vlSelf->fetch_unit__DOT__instr_push_valid_vec_popc__DOT__din_vld));
    bufp->fullCData(oldp+347,(vlSelf->fetch_unit__DOT__instr_push_valid_vec_popc__DOT__data_in),4);
    bufp->fullCData(oldp+348,(vlSelf->fetch_unit__DOT__instr_push_valid_vec_popc__DOT__cnt_out),3);
    bufp->fullBit(oldp+349,(vlSelf->fetch_unit__DOT__instr_push_valid_vec_popc__DOT__popsum_init_0));
    bufp->fullBit(oldp+350,(vlSelf->fetch_unit__DOT__instr_push_valid_vec_popc__DOT__popsum_init_1));
    bufp->fullBit(oldp+351,(vlSelf->fetch_unit__DOT__instr_push_valid_vec_popc__DOT__popsum_init_2));
    bufp->fullBit(oldp+352,(vlSelf->fetch_unit__DOT__instr_push_valid_vec_popc__DOT__popsum_init_3));
    bufp->fullCData(oldp+353,(vlSelf->fetch_unit__DOT__instr_push_valid_vec_popc__DOT__popsum_stage1_ele0),2);
    bufp->fullCData(oldp+354,(vlSelf->fetch_unit__DOT__instr_push_valid_vec_popc__DOT__popsum_stage1_ele1),2);
    bufp->fullCData(oldp+355,(vlSelf->fetch_unit__DOT__instr_push_valid_vec_popc__DOT__popsum_stage2_ele0),3);
    bufp->fullIData(oldp+356,(vlSelf->fetch_unit__DOT__rvcDecompressor_2__DOT__i),32);
    bufp->fullIData(oldp+357,(vlSelf->fetch_unit__DOT__rvcDecompressor_2__DOT__decompInstr_inst),32);
    bufp->fullBit(oldp+358,(vlSelf->fetch_unit__DOT__rvcDecompressor_2__DOT__decompInstr_illegal));
    bufp->fullSData(oldp+359,(vlSelf->fetch_unit__DOT__rvcDecompressor_2__DOT__tmp_tmp_ret_inst),12);
    bufp->fullCData(oldp+360,(vlSelf->fetch_unit__DOT__rvcDecompressor_2__DOT__tmp_tmp_ret_inst_1),6);
    bufp->fullIData(oldp+361,(vlSelf->fetch_unit__DOT__rvcDecompressor_2__DOT__tmp_ret_inst_1),32);
    bufp->fullCData(oldp+362,(vlSelf->fetch_unit__DOT__rvcDecompressor_2__DOT__tmp_ret_inst_2),2);
    bufp->fullCData(oldp+363,(vlSelf->fetch_unit__DOT__rvcDecompressor_2__DOT__tmp_ret_inst_3),3);
    bufp->fullCData(oldp+364,(vlSelf->fetch_unit__DOT__rvcDecompressor_2__DOT__tmp_ret_inst_4),3);
    bufp->fullCData(oldp+365,(vlSelf->fetch_unit__DOT__rvcDecompressor_2__DOT__tmp_ret_inst_5),7);
    bufp->fullCData(oldp+366,(vlSelf->fetch_unit__DOT__rvcDecompressor_2__DOT__tmp_ret_inst_6),5);
    bufp->fullBit(oldp+367,(vlSelf->fetch_unit__DOT__rvcDecompressor_2__DOT__tmp_ret_inst_7));
    bufp->fullCData(oldp+368,(vlSelf->fetch_unit__DOT__rvcDecompressor_2__DOT__tmp_ret_inst_8),5);
    bufp->fullSData(oldp+369,(vlSelf->fetch_unit__DOT__rvcDecompressor_2__DOT__tmp_ret_inst_9),12);
    bufp->fullSData(oldp+370,(vlSelf->fetch_unit__DOT__rvcDecompressor_2__DOT__tmp_ret_inst_10),12);
    bufp->fullIData(oldp+371,(vlSelf->fetch_unit__DOT__rvcDecompressor_2__DOT__ret_inst),32);
    bufp->fullBit(oldp+372,(vlSelf->fetch_unit__DOT__rvcDecompressor_2__DOT__ret_illegal));
    bufp->fullCData(oldp+373,(vlSelf->fetch_unit__DOT__rvcDecompressor_2__DOT__rch),5);
    bufp->fullCData(oldp+374,(vlSelf->fetch_unit__DOT__rvcDecompressor_2__DOT__rcl),5);
    bufp->fullSData(oldp+375,(vlSelf->fetch_unit__DOT__rvcDecompressor_2__DOT__addi5spnImm),12);
    bufp->fullSData(oldp+376,(vlSelf->fetch_unit__DOT__rvcDecompressor_2__DOT__lwImm),12);
    bufp->fullSData(oldp+377,(vlSelf->fetch_unit__DOT__rvcDecompressor_2__DOT__ldImm),12);
    bufp->fullBit(oldp+378,(vlSelf->fetch_unit__DOT__rvcDecompressor_2__DOT__tmp_addImm));
    bufp->fullSData(oldp+379,(vlSelf->fetch_unit__DOT__rvcDecompressor_2__DOT__addImm),12);
    bufp->fullBit(oldp+380,(vlSelf->fetch_unit__DOT__rvcDecompressor_2__DOT__tmp_jalImm));
    bufp->fullSData(oldp+381,(vlSelf->fetch_unit__DOT__rvcDecompressor_2__DOT__tmp_jalImm_1),10);
    bufp->fullIData(oldp+382,(vlSelf->fetch_unit__DOT__rvcDecompressor_2__DOT__jalImm),21);
    bufp->fullBit(oldp+383,(vlSelf->fetch_unit__DOT__rvcDecompressor_2__DOT__tmp_luiImm));
    bufp->fullSData(oldp+384,(vlSelf->fetch_unit__DOT__rvcDecompressor_2__DOT__tmp_luiImm_1),15);
    bufp->fullIData(oldp+385,(vlSelf->fetch_unit__DOT__rvcDecompressor_2__DOT__luiImm),32);
    bufp->fullCData(oldp+386,(vlSelf->fetch_unit__DOT__rvcDecompressor_2__DOT__shiftImm),5);
    bufp->fullBit(oldp+387,(vlSelf->fetch_unit__DOT__rvcDecompressor_2__DOT__tmp_addi16spImm));
    bufp->fullCData(oldp+388,(vlSelf->fetch_unit__DOT__rvcDecompressor_2__DOT__tmp_addi16spImm_1),3);
    bufp->fullSData(oldp+389,(vlSelf->fetch_unit__DOT__rvcDecompressor_2__DOT__addi16spImm),12);
    bufp->fullBit(oldp+390,(vlSelf->fetch_unit__DOT__rvcDecompressor_2__DOT__tmp_jImm));
    bufp->fullSData(oldp+391,(vlSelf->fetch_unit__DOT__rvcDecompressor_2__DOT__tmp_jImm_1),10);
    bufp->fullIData(oldp+392,(vlSelf->fetch_unit__DOT__rvcDecompressor_2__DOT__jImm),21);
    bufp->fullBit(oldp+393,(vlSelf->fetch_unit__DOT__rvcDecompressor_2__DOT__tmp_bImm));
    bufp->fullCData(oldp+394,(vlSelf->fetch_unit__DOT__rvcDecompressor_2__DOT__tmp_bImm_1),5);
    bufp->fullSData(oldp+395,(vlSelf->fetch_unit__DOT__rvcDecompressor_2__DOT__bImm),13);
    bufp->fullCData(oldp+396,(vlSelf->fetch_unit__DOT__rvcDecompressor_2__DOT__x0),5);
    bufp->fullCData(oldp+397,(vlSelf->fetch_unit__DOT__rvcDecompressor_2__DOT__x1),5);
    bufp->fullCData(oldp+398,(vlSelf->fetch_unit__DOT__rvcDecompressor_2__DOT__x2),5);
    bufp->fullIData(oldp+399,(vlSelf->fetch_unit__DOT__rvcDecompressor_2__DOT__tmp_ret_inst),32);
    bufp->fullIData(oldp+400,(vlSelf->fetch_unit__DOT__rvcDecompressor_3__DOT__i),32);
    bufp->fullIData(oldp+401,(vlSelf->fetch_unit__DOT__rvcDecompressor_3__DOT__decompInstr_inst),32);
    bufp->fullBit(oldp+402,(vlSelf->fetch_unit__DOT__rvcDecompressor_3__DOT__decompInstr_illegal));
    bufp->fullSData(oldp+403,(vlSelf->fetch_unit__DOT__rvcDecompressor_3__DOT__tmp_tmp_ret_inst),12);
    bufp->fullCData(oldp+404,(vlSelf->fetch_unit__DOT__rvcDecompressor_3__DOT__tmp_tmp_ret_inst_1),6);
    bufp->fullIData(oldp+405,(vlSelf->fetch_unit__DOT__rvcDecompressor_3__DOT__tmp_ret_inst_1),32);
    bufp->fullCData(oldp+406,(vlSelf->fetch_unit__DOT__rvcDecompressor_3__DOT__tmp_ret_inst_2),2);
    bufp->fullCData(oldp+407,(vlSelf->fetch_unit__DOT__rvcDecompressor_3__DOT__tmp_ret_inst_3),3);
    bufp->fullCData(oldp+408,(vlSelf->fetch_unit__DOT__rvcDecompressor_3__DOT__tmp_ret_inst_4),3);
    bufp->fullCData(oldp+409,(vlSelf->fetch_unit__DOT__rvcDecompressor_3__DOT__tmp_ret_inst_5),7);
    bufp->fullCData(oldp+410,(vlSelf->fetch_unit__DOT__rvcDecompressor_3__DOT__tmp_ret_inst_6),5);
    bufp->fullBit(oldp+411,(vlSelf->fetch_unit__DOT__rvcDecompressor_3__DOT__tmp_ret_inst_7));
    bufp->fullCData(oldp+412,(vlSelf->fetch_unit__DOT__rvcDecompressor_3__DOT__tmp_ret_inst_8),5);
    bufp->fullSData(oldp+413,(vlSelf->fetch_unit__DOT__rvcDecompressor_3__DOT__tmp_ret_inst_9),12);
    bufp->fullSData(oldp+414,(vlSelf->fetch_unit__DOT__rvcDecompressor_3__DOT__tmp_ret_inst_10),12);
    bufp->fullIData(oldp+415,(vlSelf->fetch_unit__DOT__rvcDecompressor_3__DOT__ret_inst),32);
    bufp->fullBit(oldp+416,(vlSelf->fetch_unit__DOT__rvcDecompressor_3__DOT__ret_illegal));
    bufp->fullCData(oldp+417,(vlSelf->fetch_unit__DOT__rvcDecompressor_3__DOT__rch),5);
    bufp->fullCData(oldp+418,(vlSelf->fetch_unit__DOT__rvcDecompressor_3__DOT__rcl),5);
    bufp->fullSData(oldp+419,(vlSelf->fetch_unit__DOT__rvcDecompressor_3__DOT__addi5spnImm),12);
    bufp->fullSData(oldp+420,(vlSelf->fetch_unit__DOT__rvcDecompressor_3__DOT__lwImm),12);
    bufp->fullSData(oldp+421,(vlSelf->fetch_unit__DOT__rvcDecompressor_3__DOT__ldImm),12);
    bufp->fullBit(oldp+422,(vlSelf->fetch_unit__DOT__rvcDecompressor_3__DOT__tmp_addImm));
    bufp->fullSData(oldp+423,(vlSelf->fetch_unit__DOT__rvcDecompressor_3__DOT__addImm),12);
    bufp->fullBit(oldp+424,(vlSelf->fetch_unit__DOT__rvcDecompressor_3__DOT__tmp_jalImm));
    bufp->fullSData(oldp+425,(vlSelf->fetch_unit__DOT__rvcDecompressor_3__DOT__tmp_jalImm_1),10);
    bufp->fullIData(oldp+426,(vlSelf->fetch_unit__DOT__rvcDecompressor_3__DOT__jalImm),21);
    bufp->fullBit(oldp+427,(vlSelf->fetch_unit__DOT__rvcDecompressor_3__DOT__tmp_luiImm));
    bufp->fullSData(oldp+428,(vlSelf->fetch_unit__DOT__rvcDecompressor_3__DOT__tmp_luiImm_1),15);
    bufp->fullIData(oldp+429,(vlSelf->fetch_unit__DOT__rvcDecompressor_3__DOT__luiImm),32);
    bufp->fullCData(oldp+430,(vlSelf->fetch_unit__DOT__rvcDecompressor_3__DOT__shiftImm),5);
    bufp->fullBit(oldp+431,(vlSelf->fetch_unit__DOT__rvcDecompressor_3__DOT__tmp_addi16spImm));
    bufp->fullCData(oldp+432,(vlSelf->fetch_unit__DOT__rvcDecompressor_3__DOT__tmp_addi16spImm_1),3);
    bufp->fullSData(oldp+433,(vlSelf->fetch_unit__DOT__rvcDecompressor_3__DOT__addi16spImm),12);
    bufp->fullBit(oldp+434,(vlSelf->fetch_unit__DOT__rvcDecompressor_3__DOT__tmp_jImm));
    bufp->fullSData(oldp+435,(vlSelf->fetch_unit__DOT__rvcDecompressor_3__DOT__tmp_jImm_1),10);
    bufp->fullIData(oldp+436,(vlSelf->fetch_unit__DOT__rvcDecompressor_3__DOT__jImm),21);
    bufp->fullBit(oldp+437,(vlSelf->fetch_unit__DOT__rvcDecompressor_3__DOT__tmp_bImm));
    bufp->fullCData(oldp+438,(vlSelf->fetch_unit__DOT__rvcDecompressor_3__DOT__tmp_bImm_1),5);
    bufp->fullSData(oldp+439,(vlSelf->fetch_unit__DOT__rvcDecompressor_3__DOT__bImm),13);
    bufp->fullCData(oldp+440,(vlSelf->fetch_unit__DOT__rvcDecompressor_3__DOT__x0),5);
    bufp->fullCData(oldp+441,(vlSelf->fetch_unit__DOT__rvcDecompressor_3__DOT__x1),5);
    bufp->fullCData(oldp+442,(vlSelf->fetch_unit__DOT__rvcDecompressor_3__DOT__x2),5);
    bufp->fullIData(oldp+443,(vlSelf->fetch_unit__DOT__rvcDecompressor_3__DOT__tmp_ret_inst),32);
    bufp->fullBit(oldp+444,(vlSelf->fetch_unit__DOT__trailone_index_0__DOT__mode));
    bufp->fullBit(oldp+445,(vlSelf->fetch_unit__DOT__trailone_index_0__DOT__lead));
    bufp->fullBit(oldp+446,(vlSelf->fetch_unit__DOT__trailone_index_0__DOT__trail));
    bufp->fullCData(oldp+447,(vlSelf->fetch_unit__DOT__trailone_index_0__DOT__data_in),4);
    bufp->fullCData(oldp+448,(vlSelf->fetch_unit__DOT__trailone_index_0__DOT__cnt_out),3);
    bufp->fullCData(oldp+449,(vlSelf->fetch_unit__DOT__trailone_index_0__DOT__tmp_cnt_out),3);
    bufp->fullCData(oldp+450,(vlSelf->fetch_unit__DOT__trailone_index_0__DOT__data_s),4);
    bufp->fullCData(oldp+451,(vlSelf->fetch_unit__DOT__trailone_index_0__DOT__datain_reverse),4);
    bufp->fullCData(oldp+452,(vlSelf->fetch_unit__DOT__trailone_index_0__DOT__stage_node_0),4);
    bufp->fullCData(oldp+453,(vlSelf->fetch_unit__DOT__trailone_index_0__DOT__stage_node_1),2);
    bufp->fullCData(oldp+454,(vlSelf->fetch_unit__DOT__trailone_index_0__DOT__stage_index1_0),2);
    bufp->fullCData(oldp+455,(vlSelf->fetch_unit__DOT__trailone_index_0__DOT__stage_index1_1),2);
    bufp->fullCData(oldp+456,(vlSelf->fetch_unit__DOT__trailone_index_0__DOT__stage_index2_0),2);
    bufp->fullBit(oldp+457,(vlSelf->fetch_unit__DOT__trailone_index_0__DOT__empty));
    bufp->fullBit(oldp+458,(vlSelf->fetch_unit__DOT__trailone_index_1__DOT__mode));
    bufp->fullBit(oldp+459,(vlSelf->fetch_unit__DOT__trailone_index_1__DOT__lead));
    bufp->fullBit(oldp+460,(vlSelf->fetch_unit__DOT__trailone_index_1__DOT__trail));
    bufp->fullCData(oldp+461,(vlSelf->fetch_unit__DOT__trailone_index_1__DOT__data_in),4);
    bufp->fullCData(oldp+462,(vlSelf->fetch_unit__DOT__trailone_index_1__DOT__cnt_out),3);
    bufp->fullCData(oldp+463,(vlSelf->fetch_unit__DOT__trailone_index_1__DOT__tmp_cnt_out),3);
    bufp->fullCData(oldp+464,(vlSelf->fetch_unit__DOT__trailone_index_1__DOT__data_s),4);
    bufp->fullCData(oldp+465,(vlSelf->fetch_unit__DOT__trailone_index_1__DOT__datain_reverse),4);
    bufp->fullCData(oldp+466,(vlSelf->fetch_unit__DOT__trailone_index_1__DOT__stage_node_0),4);
    bufp->fullCData(oldp+467,(vlSelf->fetch_unit__DOT__trailone_index_1__DOT__stage_node_1),2);
    bufp->fullCData(oldp+468,(vlSelf->fetch_unit__DOT__trailone_index_1__DOT__stage_index1_0),2);
    bufp->fullCData(oldp+469,(vlSelf->fetch_unit__DOT__trailone_index_1__DOT__stage_index1_1),2);
    bufp->fullCData(oldp+470,(vlSelf->fetch_unit__DOT__trailone_index_1__DOT__stage_index2_0),2);
    bufp->fullBit(oldp+471,(vlSelf->fetch_unit__DOT__trailone_index_1__DOT__empty));
    bufp->fullBit(oldp+472,(vlSelf->fetch_unit__DOT__trailone_index_2__DOT__mode));
    bufp->fullBit(oldp+473,(vlSelf->fetch_unit__DOT__trailone_index_2__DOT__lead));
    bufp->fullBit(oldp+474,(vlSelf->fetch_unit__DOT__trailone_index_2__DOT__trail));
    bufp->fullCData(oldp+475,(vlSelf->fetch_unit__DOT__trailone_index_2__DOT__data_in),4);
    bufp->fullCData(oldp+476,(vlSelf->fetch_unit__DOT__trailone_index_2__DOT__cnt_out),3);
    bufp->fullCData(oldp+477,(vlSelf->fetch_unit__DOT__trailone_index_2__DOT__tmp_cnt_out),3);
    bufp->fullCData(oldp+478,(vlSelf->fetch_unit__DOT__trailone_index_2__DOT__data_s),4);
    bufp->fullCData(oldp+479,(vlSelf->fetch_unit__DOT__trailone_index_2__DOT__datain_reverse),4);
    bufp->fullCData(oldp+480,(vlSelf->fetch_unit__DOT__trailone_index_2__DOT__stage_node_0),4);
    bufp->fullCData(oldp+481,(vlSelf->fetch_unit__DOT__trailone_index_2__DOT__stage_node_1),2);
    bufp->fullCData(oldp+482,(vlSelf->fetch_unit__DOT__trailone_index_2__DOT__stage_index1_0),2);
    bufp->fullCData(oldp+483,(vlSelf->fetch_unit__DOT__trailone_index_2__DOT__stage_index1_1),2);
    bufp->fullCData(oldp+484,(vlSelf->fetch_unit__DOT__trailone_index_2__DOT__stage_index2_0),2);
    bufp->fullBit(oldp+485,(vlSelf->fetch_unit__DOT__trailone_index_2__DOT__empty));
    bufp->fullBit(oldp+486,(vlSelf->fetch_unit__DOT__trailone_index_3__DOT__mode));
    bufp->fullBit(oldp+487,(vlSelf->fetch_unit__DOT__trailone_index_3__DOT__lead));
    bufp->fullBit(oldp+488,(vlSelf->fetch_unit__DOT__trailone_index_3__DOT__trail));
    bufp->fullCData(oldp+489,(vlSelf->fetch_unit__DOT__trailone_index_3__DOT__data_in),4);
    bufp->fullCData(oldp+490,(vlSelf->fetch_unit__DOT__trailone_index_3__DOT__cnt_out),3);
    bufp->fullCData(oldp+491,(vlSelf->fetch_unit__DOT__trailone_index_3__DOT__tmp_cnt_out),3);
    bufp->fullCData(oldp+492,(vlSelf->fetch_unit__DOT__trailone_index_3__DOT__data_s),4);
    bufp->fullCData(oldp+493,(vlSelf->fetch_unit__DOT__trailone_index_3__DOT__datain_reverse),4);
    bufp->fullCData(oldp+494,(vlSelf->fetch_unit__DOT__trailone_index_3__DOT__stage_node_0),4);
    bufp->fullCData(oldp+495,(vlSelf->fetch_unit__DOT__trailone_index_3__DOT__stage_node_1),2);
    bufp->fullCData(oldp+496,(vlSelf->fetch_unit__DOT__trailone_index_3__DOT__stage_index1_0),2);
    bufp->fullCData(oldp+497,(vlSelf->fetch_unit__DOT__trailone_index_3__DOT__stage_index1_1),2);
    bufp->fullCData(oldp+498,(vlSelf->fetch_unit__DOT__trailone_index_3__DOT__stage_index2_0),2);
    bufp->fullBit(oldp+499,(vlSelf->fetch_unit__DOT__trailone_index_3__DOT__empty));
    bufp->fullBit(oldp+500,(vlSelf->fetch_unit__DOT__validNumFifo__DOT__push_valid));
    bufp->fullBit(oldp+501,(vlSelf->fetch_unit__DOT__validNumFifo__DOT__push_ready));
    bufp->fullCData(oldp+502,(vlSelf->fetch_unit__DOT__validNumFifo__DOT__push_payload),3);
    bufp->fullBit(oldp+503,(vlSelf->fetch_unit__DOT__validNumFifo__DOT__pop_valid));
    bufp->fullBit(oldp+504,(vlSelf->fetch_unit__DOT__validNumFifo__DOT__pop_ready));
    bufp->fullCData(oldp+505,(vlSelf->fetch_unit__DOT__validNumFifo__DOT__pop_pop_req_num),3);
    bufp->fullCData(oldp+506,(vlSelf->fetch_unit__DOT__validNumFifo__DOT__pop_pop_out_data),3);
    bufp->fullBit(oldp+507,(vlSelf->fetch_unit__DOT__validNumFifo__DOT__pop_pop_real));
    bufp->fullCData(oldp+508,(vlSelf->fetch_unit__DOT__validNumFifo__DOT__head),3);
    bufp->fullBit(oldp+509,(vlSelf->fetch_unit__DOT__validNumFifo__DOT__flush));
    bufp->fullCData(oldp+510,(vlSelf->fetch_unit__DOT__validNumFifo__DOT__occupancy),3);
    bufp->fullBit(oldp+511,(vlSelf->fetch_unit__DOT__validNumFifo__DOT__clk));
    bufp->fullBit(oldp+512,(vlSelf->fetch_unit__DOT__validNumFifo__DOT__resetn));
    bufp->fullCData(oldp+513,(vlSelf->fetch_unit__DOT__validNumFifo__DOT__tmp_tmp_pop_pop_out_data),3);
    bufp->fullCData(oldp+514,(vlSelf->fetch_unit__DOT__validNumFifo__DOT__vec_0),3);
    bufp->fullCData(oldp+515,(vlSelf->fetch_unit__DOT__validNumFifo__DOT__vec_1),3);
    bufp->fullCData(oldp+516,(vlSelf->fetch_unit__DOT__validNumFifo__DOT__vec_2),3);
    bufp->fullCData(oldp+517,(vlSelf->fetch_unit__DOT__validNumFifo__DOT__vec_3),3);
    bufp->fullCData(oldp+518,(vlSelf->fetch_unit__DOT__validNumFifo__DOT__pushPtrGlobal),2);
    bufp->fullCData(oldp+519,(vlSelf->fetch_unit__DOT__validNumFifo__DOT__popPtrGlobal),2);
    bufp->fullBit(oldp+520,(vlSelf->fetch_unit__DOT__validNumFifo__DOT__ptrMatch));
    bufp->fullBit(oldp+521,(vlSelf->fetch_unit__DOT__validNumFifo__DOT__risingOccupancy));
    bufp->fullBit(oldp+522,(vlSelf->fetch_unit__DOT__validNumFifo__DOT__empty));
    bufp->fullBit(oldp+523,(vlSelf->fetch_unit__DOT__validNumFifo__DOT__full));
    bufp->fullBit(oldp+524,(vlSelf->fetch_unit__DOT__validNumFifo__DOT__pushing));
    bufp->fullCData(oldp+525,(vlSelf->fetch_unit__DOT__validNumFifo__DOT__tmp_pop_pop_out_data),3);
    bufp->fullCData(oldp+526,(vlSelf->fetch_unit__DOT__validNumFifo__DOT__tmp_1),4);
    bufp->fullCData(oldp+527,(vlSelf->fetch_unit__DOT__validNumFifo__DOT__tmp_vec_0),3);
    bufp->fullCData(oldp+528,(vlSelf->fetch_unit__DOT__validNumFifo__DOT__tmp_2),4);
    bufp->fullCData(oldp+529,(vlSelf->fetch_unit__DOT__validNumFifo__DOT__ptrDif),2);
    bufp->fullCData(oldp+530,(0U),2);
    bufp->fullCData(oldp+531,(1U),2);
    bufp->fullCData(oldp+532,(2U),2);
    bufp->fullCData(oldp+533,(3U),2);
}
