// Verilated -*- C++ -*-
// DESCRIPTION: Verilator output: Design internal header
// See Vtop.h for the primary calling header

#ifndef VERILATED_VTOP___024ROOT_H_
#define VERILATED_VTOP___024ROOT_H_  // guard

#include "verilated.h"

class Vtop__Syms;

class Vtop___024root final : public VerilatedModule {
  public:

    // DESIGN SPECIFIC STATE
    // Anonymous structures to workaround compiler member-count bugs
    struct {
        VL_IN8(clk,0,0);
        VL_IN8(resetn,0,0);
        VL_IN8(core_en,0,0);
        VL_OUT8(ibus_cmd_valid,0,0);
        VL_IN8(ibus_cmd_ready,0,0);
        VL_IN8(ibus_rsp_valid,0,0);
        VL_OUT8(ibus_rsp_ready,0,0);
        VL_OUT8(if2id_itf_0_valid,0,0);
        VL_OUT8(if2id_itf_1_valid,0,0);
        VL_IN8(fetchStage_flush,0,0);
        VL_IN8(fetchStage_isDone,0,0);
        VL_OUT8(fetchStage_isReady,0,0);
        VL_IN8(pcJumpTarget_valid,0,0);
        VL_IN8(pcPredicted_valid,0,0);
        CData/*0:0*/ fetch_unit__DOT__core_en;
        CData/*0:0*/ fetch_unit__DOT__ibus_cmd_valid;
        CData/*0:0*/ fetch_unit__DOT__ibus_cmd_ready;
        CData/*0:0*/ fetch_unit__DOT__ibus_rsp_valid;
        CData/*0:0*/ fetch_unit__DOT__ibus_rsp_ready;
        CData/*0:0*/ fetch_unit__DOT__if2id_itf_0_valid;
        CData/*0:0*/ fetch_unit__DOT__if2id_itf_1_valid;
        CData/*0:0*/ fetch_unit__DOT__fetchStage_flush;
        CData/*0:0*/ fetch_unit__DOT__fetchStage_isDone;
        CData/*0:0*/ fetch_unit__DOT__fetchStage_isReady;
        CData/*0:0*/ fetch_unit__DOT__pcJumpTarget_valid;
        CData/*0:0*/ fetch_unit__DOT__pcPredicted_valid;
        CData/*0:0*/ fetch_unit__DOT__clk;
        CData/*0:0*/ fetch_unit__DOT__resetn;
        CData/*0:0*/ fetch_unit__DOT__addressFifo_io_push_valid;
        CData/*0:0*/ fetch_unit__DOT__addressFifo_io_pop_ready;
        CData/*0:0*/ fetch_unit__DOT__addressFifo_io_flush;
        CData/*0:0*/ fetch_unit__DOT__validNumFifo_push_valid;
        CData/*2:0*/ fetch_unit__DOT__validNumFifo_push_payload;
        CData/*0:0*/ fetch_unit__DOT__validNumFifo_pop_valid;
        CData/*2:0*/ fetch_unit__DOT__validNumFifo_pop_pop_req_num;
        CData/*0:0*/ fetch_unit__DOT__validNumFifo_flush;
        CData/*0:0*/ fetch_unit__DOT__instrFifo_io_push_0_valid;
        CData/*0:0*/ fetch_unit__DOT__instrFifo_io_push_1_valid;
        CData/*0:0*/ fetch_unit__DOT__instrFifo_io_push_2_valid;
        CData/*0:0*/ fetch_unit__DOT__instrFifo_io_push_3_valid;
        CData/*0:0*/ fetch_unit__DOT__instrFifo_io_flush;
        CData/*0:0*/ fetch_unit__DOT__addressFifo_io_push_ready;
        CData/*0:0*/ fetch_unit__DOT__addressFifo_io_pop_valid;
        CData/*2:0*/ fetch_unit__DOT__addressFifo_io_occupancy;
        CData/*0:0*/ fetch_unit__DOT__validNumFifo_push_ready;
        CData/*0:0*/ fetch_unit__DOT__validNumFifo_pop_ready;
        CData/*2:0*/ fetch_unit__DOT__validNumFifo_pop_pop_out_data;
        CData/*0:0*/ fetch_unit__DOT__validNumFifo_pop_pop_real;
        CData/*2:0*/ fetch_unit__DOT__validNumFifo_head;
        CData/*2:0*/ fetch_unit__DOT__validNumFifo_occupancy;
        CData/*0:0*/ fetch_unit__DOT__instrFifo_io_push_0_ready;
        CData/*0:0*/ fetch_unit__DOT__instrFifo_io_push_1_ready;
        CData/*0:0*/ fetch_unit__DOT__instrFifo_io_push_2_ready;
        CData/*0:0*/ fetch_unit__DOT__instrFifo_io_push_3_ready;
        CData/*0:0*/ fetch_unit__DOT__instrFifo_io_pop_0_valid;
        CData/*0:0*/ fetch_unit__DOT__instrFifo_io_pop_1_valid;
        CData/*3:0*/ fetch_unit__DOT__instrFifo_io_occupancy;
        CData/*0:0*/ fetch_unit__DOT__instrFifo_io_ov_waterline;
        CData/*2:0*/ fetch_unit__DOT__trailone_index_0_cnt_out;
        CData/*2:0*/ fetch_unit__DOT__trailone_index_1_cnt_out;
        CData/*2:0*/ fetch_unit__DOT__trailone_index_2_cnt_out;
        CData/*2:0*/ fetch_unit__DOT__trailone_index_3_cnt_out;
        CData/*2:0*/ fetch_unit__DOT__instr_push_valid_vec_popc_cnt_out;
        CData/*1:0*/ fetch_unit__DOT__instr_pop_valid_popc_cnt_out;
    };
    struct {
        CData/*0:0*/ fetch_unit__DOT__rvcDecompressor_2_decompInstr_illegal;
        CData/*0:0*/ fetch_unit__DOT__rvcDecompressor_3_decompInstr_illegal;
        CData/*0:0*/ fetch_unit__DOT__tmp_io_push_0_valid;
        CData/*0:0*/ fetch_unit__DOT__tmp_io_push_1_valid;
        CData/*0:0*/ fetch_unit__DOT__tmp_io_push_2_valid;
        CData/*0:0*/ fetch_unit__DOT__tmp_io_push_3_valid;
        CData/*0:0*/ fetch_unit__DOT__fetch_pending;
        CData/*1:0*/ fetch_unit__DOT__addressOffset;
        CData/*0:0*/ fetch_unit__DOT__ibus_cmd_fire;
        CData/*0:0*/ fetch_unit__DOT__valid_instr_slice_0;
        CData/*0:0*/ fetch_unit__DOT__valid_instr_slice_1;
        CData/*0:0*/ fetch_unit__DOT__valid_instr_slice_2;
        CData/*0:0*/ fetch_unit__DOT__valid_instr_slice_3;
        CData/*0:0*/ fetch_unit__DOT__instr_slices_0_valid;
        CData/*0:0*/ fetch_unit__DOT__instr_slices_1_valid;
        CData/*0:0*/ fetch_unit__DOT__instr_slices_2_valid;
        CData/*0:0*/ fetch_unit__DOT__instr_slices_3_valid;
        CData/*3:0*/ fetch_unit__DOT__tail_one_matrix_0;
        CData/*3:0*/ fetch_unit__DOT__tail_one_matrix_1;
        CData/*3:0*/ fetch_unit__DOT__tail_one_matrix_2;
        CData/*3:0*/ fetch_unit__DOT__tail_one_matrix_3;
        CData/*1:0*/ fetch_unit__DOT__tail_one_index_vec_0;
        CData/*1:0*/ fetch_unit__DOT__tail_one_index_vec_1;
        CData/*1:0*/ fetch_unit__DOT__tail_one_index_vec_2;
        CData/*1:0*/ fetch_unit__DOT__tail_one_index_vec_3;
        CData/*0:0*/ fetch_unit__DOT__tail_one_valid_vec_0;
        CData/*0:0*/ fetch_unit__DOT__tail_one_valid_vec_1;
        CData/*0:0*/ fetch_unit__DOT__tail_one_valid_vec_2;
        CData/*0:0*/ fetch_unit__DOT__tail_one_valid_vec_3;
        CData/*0:0*/ fetch_unit__DOT__slice_valid_vec_0;
        CData/*0:0*/ fetch_unit__DOT__slice_valid_vec_1;
        CData/*0:0*/ fetch_unit__DOT__slice_valid_vec_2;
        CData/*0:0*/ fetch_unit__DOT__slice_valid_vec_3;
        CData/*0:0*/ fetch_unit__DOT__tmp_1;
        CData/*1:0*/ fetch_unit__DOT__tmp_2;
        CData/*1:0*/ fetch_unit__DOT__tmp_3;
        CData/*1:0*/ fetch_unit__DOT__tmp_4;
        CData/*1:0*/ fetch_unit__DOT__tmp_5;
        CData/*0:0*/ fetch_unit__DOT__ibus_rsp_fire;
        CData/*3:0*/ fetch_unit__DOT__instr_push_valid_vec;
        CData/*0:0*/ fetch_unit__DOT__toplevel_instrFifo_io_push_0_fire;
        CData/*1:0*/ fetch_unit__DOT__instr_pop_valid;
        CData/*0:0*/ fetch_unit__DOT__toplevel_instrFifo_io_pop_0_fire;
        CData/*0:0*/ fetch_unit__DOT__toplevel_instrFifo_io_pop_1_fire;
        CData/*2:0*/ fetch_unit__DOT__pc_pop_offset;
        CData/*2:0*/ fetch_unit__DOT__pc_step_all_1;
        CData/*2:0*/ fetch_unit__DOT__pc_step_all_2;
        CData/*2:0*/ fetch_unit__DOT__pc_step_0;
        CData/*2:0*/ fetch_unit__DOT__pc_step_1;
        CData/*0:0*/ fetch_unit__DOT__tmp_real_instr_0;
        CData/*0:0*/ fetch_unit__DOT__tmp_real_instr_1;
        CData/*0:0*/ fetch_unit__DOT__toplevel_addressFifo_io_pop_fire;
        CData/*0:0*/ fetch_unit__DOT__addressFifo__DOT__io_push_valid;
        CData/*0:0*/ fetch_unit__DOT__addressFifo__DOT__io_push_ready;
        CData/*0:0*/ fetch_unit__DOT__addressFifo__DOT__io_pop_valid;
        CData/*0:0*/ fetch_unit__DOT__addressFifo__DOT__io_pop_ready;
        CData/*0:0*/ fetch_unit__DOT__addressFifo__DOT__io_flush;
        CData/*2:0*/ fetch_unit__DOT__addressFifo__DOT__io_occupancy;
        CData/*0:0*/ fetch_unit__DOT__addressFifo__DOT__clk;
        CData/*0:0*/ fetch_unit__DOT__addressFifo__DOT__resetn;
        CData/*2:0*/ fetch_unit__DOT__addressFifo__DOT__tmp_pushPtr_valueNext;
        CData/*0:0*/ fetch_unit__DOT__addressFifo__DOT__tmp_pushPtr_valueNext_1;
        CData/*2:0*/ fetch_unit__DOT__addressFifo__DOT__tmp_popPtr_valueNext;
        CData/*0:0*/ fetch_unit__DOT__addressFifo__DOT__tmp_popPtr_valueNext_1;
    };
    struct {
        CData/*2:0*/ fetch_unit__DOT__addressFifo__DOT__tmp_io_occupancy;
        CData/*0:0*/ fetch_unit__DOT__addressFifo__DOT__pushPtr_willIncrement;
        CData/*0:0*/ fetch_unit__DOT__addressFifo__DOT__pushPtr_willClear;
        CData/*2:0*/ fetch_unit__DOT__addressFifo__DOT__pushPtr_valueNext;
        CData/*2:0*/ fetch_unit__DOT__addressFifo__DOT__pushPtr_value;
        CData/*0:0*/ fetch_unit__DOT__addressFifo__DOT__pushPtr_willOverflowIfInc;
        CData/*0:0*/ fetch_unit__DOT__addressFifo__DOT__pushPtr_willOverflow;
        CData/*0:0*/ fetch_unit__DOT__addressFifo__DOT__popPtr_willIncrement;
        CData/*0:0*/ fetch_unit__DOT__addressFifo__DOT__popPtr_willClear;
        CData/*2:0*/ fetch_unit__DOT__addressFifo__DOT__popPtr_valueNext;
        CData/*2:0*/ fetch_unit__DOT__addressFifo__DOT__popPtr_value;
        CData/*0:0*/ fetch_unit__DOT__addressFifo__DOT__popPtr_willOverflowIfInc;
        CData/*0:0*/ fetch_unit__DOT__addressFifo__DOT__popPtr_willOverflow;
        CData/*0:0*/ fetch_unit__DOT__addressFifo__DOT__ptrMatch;
        CData/*0:0*/ fetch_unit__DOT__addressFifo__DOT__risingOccupancy;
        CData/*0:0*/ fetch_unit__DOT__addressFifo__DOT__empty;
        CData/*0:0*/ fetch_unit__DOT__addressFifo__DOT__full;
        CData/*0:0*/ fetch_unit__DOT__addressFifo__DOT__pushing;
        CData/*0:0*/ fetch_unit__DOT__addressFifo__DOT__popping;
        CData/*7:0*/ fetch_unit__DOT__addressFifo__DOT__tmp_1;
        CData/*2:0*/ fetch_unit__DOT__addressFifo__DOT__ptrDif;
        CData/*0:0*/ fetch_unit__DOT__validNumFifo__DOT__push_valid;
        CData/*0:0*/ fetch_unit__DOT__validNumFifo__DOT__push_ready;
        CData/*2:0*/ fetch_unit__DOT__validNumFifo__DOT__push_payload;
        CData/*0:0*/ fetch_unit__DOT__validNumFifo__DOT__pop_valid;
        CData/*0:0*/ fetch_unit__DOT__validNumFifo__DOT__pop_ready;
        CData/*2:0*/ fetch_unit__DOT__validNumFifo__DOT__pop_pop_req_num;
        CData/*2:0*/ fetch_unit__DOT__validNumFifo__DOT__pop_pop_out_data;
        CData/*0:0*/ fetch_unit__DOT__validNumFifo__DOT__pop_pop_real;
        CData/*2:0*/ fetch_unit__DOT__validNumFifo__DOT__head;
        CData/*0:0*/ fetch_unit__DOT__validNumFifo__DOT__flush;
        CData/*2:0*/ fetch_unit__DOT__validNumFifo__DOT__occupancy;
        CData/*0:0*/ fetch_unit__DOT__validNumFifo__DOT__clk;
        CData/*0:0*/ fetch_unit__DOT__validNumFifo__DOT__resetn;
        CData/*2:0*/ fetch_unit__DOT__validNumFifo__DOT__tmp_tmp_pop_pop_out_data;
        CData/*2:0*/ fetch_unit__DOT__validNumFifo__DOT__tmp_occupancy;
        CData/*2:0*/ fetch_unit__DOT__validNumFifo__DOT__vec_0;
        CData/*2:0*/ fetch_unit__DOT__validNumFifo__DOT__vec_1;
        CData/*2:0*/ fetch_unit__DOT__validNumFifo__DOT__vec_2;
        CData/*2:0*/ fetch_unit__DOT__validNumFifo__DOT__vec_3;
        CData/*2:0*/ fetch_unit__DOT__validNumFifo__DOT__vec_4;
        CData/*2:0*/ fetch_unit__DOT__validNumFifo__DOT__vec_5;
        CData/*2:0*/ fetch_unit__DOT__validNumFifo__DOT__pushPtrGlobal;
        CData/*2:0*/ fetch_unit__DOT__validNumFifo__DOT__popPtrGlobal;
        CData/*0:0*/ fetch_unit__DOT__validNumFifo__DOT__ptrMatch;
        CData/*0:0*/ fetch_unit__DOT__validNumFifo__DOT__risingOccupancy;
        CData/*0:0*/ fetch_unit__DOT__validNumFifo__DOT__empty;
        CData/*0:0*/ fetch_unit__DOT__validNumFifo__DOT__full;
        CData/*0:0*/ fetch_unit__DOT__validNumFifo__DOT__pushing;
        CData/*2:0*/ fetch_unit__DOT__validNumFifo__DOT__tmp_pop_pop_out_data;
        CData/*7:0*/ fetch_unit__DOT__validNumFifo__DOT__tmp_1;
        CData/*2:0*/ fetch_unit__DOT__validNumFifo__DOT__tmp_vec_0;
        CData/*7:0*/ fetch_unit__DOT__validNumFifo__DOT__tmp_2;
        CData/*2:0*/ fetch_unit__DOT__validNumFifo__DOT__ptrDif;
        CData/*0:0*/ fetch_unit__DOT__instrFifo__DOT__io_push_0_valid;
        CData/*0:0*/ fetch_unit__DOT__instrFifo__DOT__io_push_0_ready;
        CData/*0:0*/ fetch_unit__DOT__instrFifo__DOT__io_push_1_valid;
        CData/*0:0*/ fetch_unit__DOT__instrFifo__DOT__io_push_1_ready;
        CData/*0:0*/ fetch_unit__DOT__instrFifo__DOT__io_push_2_valid;
        CData/*0:0*/ fetch_unit__DOT__instrFifo__DOT__io_push_2_ready;
        CData/*0:0*/ fetch_unit__DOT__instrFifo__DOT__io_push_3_valid;
        CData/*0:0*/ fetch_unit__DOT__instrFifo__DOT__io_push_3_ready;
        CData/*0:0*/ fetch_unit__DOT__instrFifo__DOT__io_pop_0_valid;
        CData/*0:0*/ fetch_unit__DOT__instrFifo__DOT__io_pop_0_ready;
    };
    struct {
        CData/*0:0*/ fetch_unit__DOT__instrFifo__DOT__io_pop_1_valid;
        CData/*0:0*/ fetch_unit__DOT__instrFifo__DOT__io_pop_1_ready;
        CData/*0:0*/ fetch_unit__DOT__instrFifo__DOT__io_flush;
        CData/*3:0*/ fetch_unit__DOT__instrFifo__DOT__io_occupancy;
        CData/*0:0*/ fetch_unit__DOT__instrFifo__DOT__io_ov_waterline;
        CData/*0:0*/ fetch_unit__DOT__instrFifo__DOT__clk;
        CData/*0:0*/ fetch_unit__DOT__instrFifo__DOT__resetn;
        CData/*1:0*/ fetch_unit__DOT__instrFifo__DOT__tmp_inc_num_1;
        CData/*1:0*/ fetch_unit__DOT__instrFifo__DOT__tmp_inc_num_2;
        CData/*0:0*/ fetch_unit__DOT__instrFifo__DOT__tmp_inc_num_3;
        CData/*2:0*/ fetch_unit__DOT__instrFifo__DOT__tmp_inc_num_4;
        CData/*1:0*/ fetch_unit__DOT__instrFifo__DOT__tmp_inc_num_5;
        CData/*1:0*/ fetch_unit__DOT__instrFifo__DOT__tmp_inc_num_6;
        CData/*0:0*/ fetch_unit__DOT__instrFifo__DOT__tmp_inc_num_7;
        CData/*1:0*/ fetch_unit__DOT__instrFifo__DOT__tmp_dec_num_1;
        CData/*0:0*/ fetch_unit__DOT__instrFifo__DOT__tmp_dec_num_2;
        CData/*3:0*/ fetch_unit__DOT__instrFifo__DOT__tmp_io_push_0_ready;
        CData/*3:0*/ fetch_unit__DOT__instrFifo__DOT__tmp_io_push_1_ready;
        CData/*3:0*/ fetch_unit__DOT__instrFifo__DOT__tmp_io_push_2_ready;
        CData/*3:0*/ fetch_unit__DOT__instrFifo__DOT__tmp_io_push_3_ready;
        CData/*4:0*/ fetch_unit__DOT__instrFifo__DOT__tmp_pushPtrs_inc_0;
        CData/*0:0*/ fetch_unit__DOT__instrFifo__DOT__tmp_pushPtrs_inc_0_1;
        CData/*4:0*/ fetch_unit__DOT__instrFifo__DOT__tmp_pushPtrs_inc_1;
        CData/*1:0*/ fetch_unit__DOT__instrFifo__DOT__tmp_pushPtrs_inc_1_1;
        CData/*4:0*/ fetch_unit__DOT__instrFifo__DOT__tmp_pushPtrs_inc_2;
        CData/*2:0*/ fetch_unit__DOT__instrFifo__DOT__tmp_pushPtrs_inc_2_1;
        CData/*4:0*/ fetch_unit__DOT__instrFifo__DOT__tmp_pushPtrs_inc_3;
        CData/*2:0*/ fetch_unit__DOT__instrFifo__DOT__tmp_pushPtrs_inc_3_1;
        CData/*4:0*/ fetch_unit__DOT__instrFifo__DOT__tmp_popPtrs_inc_0;
        CData/*0:0*/ fetch_unit__DOT__instrFifo__DOT__tmp_popPtrs_inc_0_1;
        CData/*4:0*/ fetch_unit__DOT__instrFifo__DOT__tmp_popPtrs_inc_1;
        CData/*1:0*/ fetch_unit__DOT__instrFifo__DOT__tmp_popPtrs_inc_1_1;
        CData/*3:0*/ fetch_unit__DOT__instrFifo__DOT__tmp_readedVec_0_1;
        CData/*3:0*/ fetch_unit__DOT__instrFifo__DOT__tmp_readedVec_1_1;
        CData/*2:0*/ fetch_unit__DOT__instrFifo__DOT__tmp_when;
        CData/*4:0*/ fetch_unit__DOT__instrFifo__DOT__tmp_pushPtrGlobalInc;
        CData/*3:0*/ fetch_unit__DOT__instrFifo__DOT__tmp_pushPtrGlobalInc_1;
        CData/*4:0*/ fetch_unit__DOT__instrFifo__DOT__tmp_popPtrGlobalInc;
        CData/*2:0*/ fetch_unit__DOT__instrFifo__DOT__tmp_popPtrGlobalInc_1;
        CData/*4:0*/ fetch_unit__DOT__instrFifo__DOT__tmp_pushPtrGlobal;
        CData/*4:0*/ fetch_unit__DOT__instrFifo__DOT__tmp_popPtrGlobal;
        CData/*3:0*/ fetch_unit__DOT__instrFifo__DOT__tmp_io_occupancy;
        CData/*3:0*/ fetch_unit__DOT__instrFifo__DOT__pushPtrGlobal;
        CData/*3:0*/ fetch_unit__DOT__instrFifo__DOT__popPtrGlobal;
        CData/*0:0*/ fetch_unit__DOT__instrFifo__DOT__ptrMatch;
        CData/*0:0*/ fetch_unit__DOT__instrFifo__DOT__risingOccupancy;
        CData/*0:0*/ fetch_unit__DOT__instrFifo__DOT__empty;
        CData/*0:0*/ fetch_unit__DOT__instrFifo__DOT__full;
        CData/*0:0*/ fetch_unit__DOT__instrFifo__DOT__pushing_vec_0;
        CData/*0:0*/ fetch_unit__DOT__instrFifo__DOT__pushing_vec_1;
        CData/*0:0*/ fetch_unit__DOT__instrFifo__DOT__pushing_vec_2;
        CData/*0:0*/ fetch_unit__DOT__instrFifo__DOT__pushing_vec_3;
        CData/*0:0*/ fetch_unit__DOT__instrFifo__DOT__popping_vec_0;
        CData/*0:0*/ fetch_unit__DOT__instrFifo__DOT__popping_vec_1;
        CData/*0:0*/ fetch_unit__DOT__instrFifo__DOT__tmp_inc_num;
        CData/*2:0*/ fetch_unit__DOT__instrFifo__DOT__inc_num;
        CData/*0:0*/ fetch_unit__DOT__instrFifo__DOT__tmp_dec_num;
        CData/*1:0*/ fetch_unit__DOT__instrFifo__DOT__dec_num;
        CData/*4:0*/ fetch_unit__DOT__instrFifo__DOT__pushPtrs_0;
        CData/*4:0*/ fetch_unit__DOT__instrFifo__DOT__pushPtrs_1;
        CData/*4:0*/ fetch_unit__DOT__instrFifo__DOT__pushPtrs_2;
        CData/*4:0*/ fetch_unit__DOT__instrFifo__DOT__pushPtrs_3;
        CData/*4:0*/ fetch_unit__DOT__instrFifo__DOT__popPtrs_0;
        CData/*4:0*/ fetch_unit__DOT__instrFifo__DOT__popPtrs_1;
    };
    struct {
        CData/*4:0*/ fetch_unit__DOT__instrFifo__DOT__pushPtrs_inc_0;
        CData/*4:0*/ fetch_unit__DOT__instrFifo__DOT__pushPtrs_inc_1;
        CData/*4:0*/ fetch_unit__DOT__instrFifo__DOT__pushPtrs_inc_2;
        CData/*4:0*/ fetch_unit__DOT__instrFifo__DOT__pushPtrs_inc_3;
        CData/*4:0*/ fetch_unit__DOT__instrFifo__DOT__popPtrs_inc_0;
        CData/*4:0*/ fetch_unit__DOT__instrFifo__DOT__popPtrs_inc_1;
        CData/*4:0*/ fetch_unit__DOT__instrFifo__DOT__pushPtrGlobalInc;
        CData/*4:0*/ fetch_unit__DOT__instrFifo__DOT__popPtrGlobalInc;
        CData/*3:0*/ fetch_unit__DOT__instrFifo__DOT__ptrDif;
        CData/*0:0*/ fetch_unit__DOT__trailone_index_0__DOT__mode;
        CData/*0:0*/ fetch_unit__DOT__trailone_index_0__DOT__lead;
        CData/*0:0*/ fetch_unit__DOT__trailone_index_0__DOT__trail;
        CData/*3:0*/ fetch_unit__DOT__trailone_index_0__DOT__data_in;
        CData/*2:0*/ fetch_unit__DOT__trailone_index_0__DOT__cnt_out;
        CData/*2:0*/ fetch_unit__DOT__trailone_index_0__DOT__tmp_cnt_out;
        CData/*3:0*/ fetch_unit__DOT__trailone_index_0__DOT__data_s;
        CData/*3:0*/ fetch_unit__DOT__trailone_index_0__DOT__datain_reverse;
        CData/*3:0*/ fetch_unit__DOT__trailone_index_0__DOT__stage_node_0;
        CData/*1:0*/ fetch_unit__DOT__trailone_index_0__DOT__stage_node_1;
        CData/*1:0*/ fetch_unit__DOT__trailone_index_0__DOT__stage_index1_0;
        CData/*1:0*/ fetch_unit__DOT__trailone_index_0__DOT__stage_index1_1;
        CData/*1:0*/ fetch_unit__DOT__trailone_index_0__DOT__stage_index2_0;
        CData/*0:0*/ fetch_unit__DOT__trailone_index_0__DOT__empty;
        CData/*1:0*/ fetch_unit__DOT__trailone_index_0__DOT__out_remap;
        CData/*0:0*/ fetch_unit__DOT__trailone_index_1__DOT__mode;
        CData/*0:0*/ fetch_unit__DOT__trailone_index_1__DOT__lead;
        CData/*0:0*/ fetch_unit__DOT__trailone_index_1__DOT__trail;
        CData/*3:0*/ fetch_unit__DOT__trailone_index_1__DOT__data_in;
        CData/*2:0*/ fetch_unit__DOT__trailone_index_1__DOT__cnt_out;
        CData/*2:0*/ fetch_unit__DOT__trailone_index_1__DOT__tmp_cnt_out;
        CData/*3:0*/ fetch_unit__DOT__trailone_index_1__DOT__data_s;
        CData/*3:0*/ fetch_unit__DOT__trailone_index_1__DOT__datain_reverse;
        CData/*3:0*/ fetch_unit__DOT__trailone_index_1__DOT__stage_node_0;
        CData/*1:0*/ fetch_unit__DOT__trailone_index_1__DOT__stage_node_1;
        CData/*1:0*/ fetch_unit__DOT__trailone_index_1__DOT__stage_index1_0;
        CData/*1:0*/ fetch_unit__DOT__trailone_index_1__DOT__stage_index1_1;
        CData/*1:0*/ fetch_unit__DOT__trailone_index_1__DOT__stage_index2_0;
        CData/*0:0*/ fetch_unit__DOT__trailone_index_1__DOT__empty;
        CData/*1:0*/ fetch_unit__DOT__trailone_index_1__DOT__out_remap;
        CData/*0:0*/ fetch_unit__DOT__trailone_index_2__DOT__mode;
        CData/*0:0*/ fetch_unit__DOT__trailone_index_2__DOT__lead;
        CData/*0:0*/ fetch_unit__DOT__trailone_index_2__DOT__trail;
        CData/*3:0*/ fetch_unit__DOT__trailone_index_2__DOT__data_in;
        CData/*2:0*/ fetch_unit__DOT__trailone_index_2__DOT__cnt_out;
        CData/*2:0*/ fetch_unit__DOT__trailone_index_2__DOT__tmp_cnt_out;
        CData/*3:0*/ fetch_unit__DOT__trailone_index_2__DOT__data_s;
        CData/*3:0*/ fetch_unit__DOT__trailone_index_2__DOT__datain_reverse;
        CData/*3:0*/ fetch_unit__DOT__trailone_index_2__DOT__stage_node_0;
        CData/*1:0*/ fetch_unit__DOT__trailone_index_2__DOT__stage_node_1;
        CData/*1:0*/ fetch_unit__DOT__trailone_index_2__DOT__stage_index1_0;
        CData/*1:0*/ fetch_unit__DOT__trailone_index_2__DOT__stage_index1_1;
        CData/*1:0*/ fetch_unit__DOT__trailone_index_2__DOT__stage_index2_0;
        CData/*0:0*/ fetch_unit__DOT__trailone_index_2__DOT__empty;
        CData/*1:0*/ fetch_unit__DOT__trailone_index_2__DOT__out_remap;
        CData/*0:0*/ fetch_unit__DOT__trailone_index_3__DOT__mode;
        CData/*0:0*/ fetch_unit__DOT__trailone_index_3__DOT__lead;
        CData/*0:0*/ fetch_unit__DOT__trailone_index_3__DOT__trail;
        CData/*3:0*/ fetch_unit__DOT__trailone_index_3__DOT__data_in;
        CData/*2:0*/ fetch_unit__DOT__trailone_index_3__DOT__cnt_out;
        CData/*2:0*/ fetch_unit__DOT__trailone_index_3__DOT__tmp_cnt_out;
        CData/*3:0*/ fetch_unit__DOT__trailone_index_3__DOT__data_s;
        CData/*3:0*/ fetch_unit__DOT__trailone_index_3__DOT__datain_reverse;
        CData/*3:0*/ fetch_unit__DOT__trailone_index_3__DOT__stage_node_0;
        CData/*1:0*/ fetch_unit__DOT__trailone_index_3__DOT__stage_node_1;
    };
    struct {
        CData/*1:0*/ fetch_unit__DOT__trailone_index_3__DOT__stage_index1_0;
        CData/*1:0*/ fetch_unit__DOT__trailone_index_3__DOT__stage_index1_1;
        CData/*1:0*/ fetch_unit__DOT__trailone_index_3__DOT__stage_index2_0;
        CData/*0:0*/ fetch_unit__DOT__trailone_index_3__DOT__empty;
        CData/*1:0*/ fetch_unit__DOT__trailone_index_3__DOT__out_remap;
        CData/*0:0*/ fetch_unit__DOT__instr_push_valid_vec_popc__DOT__din_vld;
        CData/*3:0*/ fetch_unit__DOT__instr_push_valid_vec_popc__DOT__data_in;
        CData/*2:0*/ fetch_unit__DOT__instr_push_valid_vec_popc__DOT__cnt_out;
        CData/*0:0*/ fetch_unit__DOT__instr_push_valid_vec_popc__DOT__popsum_init_0;
        CData/*0:0*/ fetch_unit__DOT__instr_push_valid_vec_popc__DOT__popsum_init_1;
        CData/*0:0*/ fetch_unit__DOT__instr_push_valid_vec_popc__DOT__popsum_init_2;
        CData/*0:0*/ fetch_unit__DOT__instr_push_valid_vec_popc__DOT__popsum_init_3;
        CData/*1:0*/ fetch_unit__DOT__instr_push_valid_vec_popc__DOT__popsum_stage1_ele0;
        CData/*1:0*/ fetch_unit__DOT__instr_push_valid_vec_popc__DOT__popsum_stage1_ele1;
        CData/*2:0*/ fetch_unit__DOT__instr_push_valid_vec_popc__DOT__popsum_stage2_ele0;
        CData/*0:0*/ fetch_unit__DOT__instr_pop_valid_popc__DOT__din_vld;
        CData/*1:0*/ fetch_unit__DOT__instr_pop_valid_popc__DOT__data_in;
        CData/*1:0*/ fetch_unit__DOT__instr_pop_valid_popc__DOT__cnt_out;
        CData/*0:0*/ fetch_unit__DOT__instr_pop_valid_popc__DOT__popsum_init_0;
        CData/*0:0*/ fetch_unit__DOT__instr_pop_valid_popc__DOT__popsum_init_1;
        CData/*1:0*/ fetch_unit__DOT__instr_pop_valid_popc__DOT__popsum_stage1_ele0;
        CData/*0:0*/ fetch_unit__DOT__rvcDecompressor_2__DOT__decompInstr_illegal;
        CData/*5:0*/ fetch_unit__DOT__rvcDecompressor_2__DOT__tmp_tmp_ret_inst_1;
        CData/*1:0*/ fetch_unit__DOT__rvcDecompressor_2__DOT__tmp_ret_inst_2;
        CData/*2:0*/ fetch_unit__DOT__rvcDecompressor_2__DOT__tmp_ret_inst_3;
        CData/*2:0*/ fetch_unit__DOT__rvcDecompressor_2__DOT__tmp_ret_inst_4;
        CData/*6:0*/ fetch_unit__DOT__rvcDecompressor_2__DOT__tmp_ret_inst_5;
        CData/*4:0*/ fetch_unit__DOT__rvcDecompressor_2__DOT__tmp_ret_inst_6;
        CData/*0:0*/ fetch_unit__DOT__rvcDecompressor_2__DOT__tmp_ret_inst_7;
        CData/*4:0*/ fetch_unit__DOT__rvcDecompressor_2__DOT__tmp_ret_inst_8;
        CData/*0:0*/ fetch_unit__DOT__rvcDecompressor_2__DOT__ret_illegal;
        CData/*4:0*/ fetch_unit__DOT__rvcDecompressor_2__DOT__rch;
        CData/*4:0*/ fetch_unit__DOT__rvcDecompressor_2__DOT__rcl;
        CData/*0:0*/ fetch_unit__DOT__rvcDecompressor_2__DOT__tmp_addImm;
        CData/*0:0*/ fetch_unit__DOT__rvcDecompressor_2__DOT__tmp_jalImm;
        CData/*0:0*/ fetch_unit__DOT__rvcDecompressor_2__DOT__tmp_luiImm;
        CData/*4:0*/ fetch_unit__DOT__rvcDecompressor_2__DOT__shiftImm;
        CData/*0:0*/ fetch_unit__DOT__rvcDecompressor_2__DOT__tmp_addi16spImm;
        CData/*2:0*/ fetch_unit__DOT__rvcDecompressor_2__DOT__tmp_addi16spImm_1;
        CData/*0:0*/ fetch_unit__DOT__rvcDecompressor_2__DOT__tmp_jImm;
        CData/*0:0*/ fetch_unit__DOT__rvcDecompressor_2__DOT__tmp_bImm;
        CData/*4:0*/ fetch_unit__DOT__rvcDecompressor_2__DOT__tmp_bImm_1;
        CData/*4:0*/ fetch_unit__DOT__rvcDecompressor_2__DOT__x0;
        CData/*4:0*/ fetch_unit__DOT__rvcDecompressor_2__DOT__x1;
        CData/*4:0*/ fetch_unit__DOT__rvcDecompressor_2__DOT__x2;
        CData/*0:0*/ fetch_unit__DOT__rvcDecompressor_3__DOT__decompInstr_illegal;
        CData/*5:0*/ fetch_unit__DOT__rvcDecompressor_3__DOT__tmp_tmp_ret_inst_1;
        CData/*1:0*/ fetch_unit__DOT__rvcDecompressor_3__DOT__tmp_ret_inst_2;
        CData/*2:0*/ fetch_unit__DOT__rvcDecompressor_3__DOT__tmp_ret_inst_3;
        CData/*2:0*/ fetch_unit__DOT__rvcDecompressor_3__DOT__tmp_ret_inst_4;
        CData/*6:0*/ fetch_unit__DOT__rvcDecompressor_3__DOT__tmp_ret_inst_5;
        CData/*4:0*/ fetch_unit__DOT__rvcDecompressor_3__DOT__tmp_ret_inst_6;
        CData/*0:0*/ fetch_unit__DOT__rvcDecompressor_3__DOT__tmp_ret_inst_7;
        CData/*4:0*/ fetch_unit__DOT__rvcDecompressor_3__DOT__tmp_ret_inst_8;
        CData/*0:0*/ fetch_unit__DOT__rvcDecompressor_3__DOT__ret_illegal;
        CData/*4:0*/ fetch_unit__DOT__rvcDecompressor_3__DOT__rch;
        CData/*4:0*/ fetch_unit__DOT__rvcDecompressor_3__DOT__rcl;
        CData/*0:0*/ fetch_unit__DOT__rvcDecompressor_3__DOT__tmp_addImm;
        CData/*0:0*/ fetch_unit__DOT__rvcDecompressor_3__DOT__tmp_jalImm;
        CData/*0:0*/ fetch_unit__DOT__rvcDecompressor_3__DOT__tmp_luiImm;
        CData/*4:0*/ fetch_unit__DOT__rvcDecompressor_3__DOT__shiftImm;
        CData/*0:0*/ fetch_unit__DOT__rvcDecompressor_3__DOT__tmp_addi16spImm;
        CData/*2:0*/ fetch_unit__DOT__rvcDecompressor_3__DOT__tmp_addi16spImm_1;
        CData/*0:0*/ fetch_unit__DOT__rvcDecompressor_3__DOT__tmp_jImm;
    };
    struct {
        CData/*0:0*/ fetch_unit__DOT__rvcDecompressor_3__DOT__tmp_bImm;
        CData/*4:0*/ fetch_unit__DOT__rvcDecompressor_3__DOT__tmp_bImm_1;
        CData/*4:0*/ fetch_unit__DOT__rvcDecompressor_3__DOT__x0;
        CData/*4:0*/ fetch_unit__DOT__rvcDecompressor_3__DOT__x1;
        CData/*4:0*/ fetch_unit__DOT__rvcDecompressor_3__DOT__x2;
        CData/*0:0*/ __Vtrigrprev__TOP__clk;
        CData/*0:0*/ __Vtrigrprev__TOP__resetn;
        CData/*0:0*/ __VactContinue;
        SData/*15:0*/ fetch_unit__DOT__tmp_instr_slices_0_payload;
        SData/*15:0*/ fetch_unit__DOT__instrFifo__DOT__tmp_1;
        SData/*15:0*/ fetch_unit__DOT__instrFifo__DOT__tmp_2;
        SData/*15:0*/ fetch_unit__DOT__instrFifo__DOT__tmp_3;
        SData/*15:0*/ fetch_unit__DOT__instrFifo__DOT__tmp_4;
        SData/*11:0*/ fetch_unit__DOT__rvcDecompressor_2__DOT__tmp_tmp_ret_inst;
        SData/*11:0*/ fetch_unit__DOT__rvcDecompressor_2__DOT__tmp_ret_inst_9;
        SData/*11:0*/ fetch_unit__DOT__rvcDecompressor_2__DOT__tmp_ret_inst_10;
        SData/*11:0*/ fetch_unit__DOT__rvcDecompressor_2__DOT__addi5spnImm;
        SData/*11:0*/ fetch_unit__DOT__rvcDecompressor_2__DOT__lwImm;
        SData/*11:0*/ fetch_unit__DOT__rvcDecompressor_2__DOT__ldImm;
        SData/*11:0*/ fetch_unit__DOT__rvcDecompressor_2__DOT__addImm;
        SData/*9:0*/ fetch_unit__DOT__rvcDecompressor_2__DOT__tmp_jalImm_1;
        SData/*14:0*/ fetch_unit__DOT__rvcDecompressor_2__DOT__tmp_luiImm_1;
        SData/*11:0*/ fetch_unit__DOT__rvcDecompressor_2__DOT__addi16spImm;
        SData/*9:0*/ fetch_unit__DOT__rvcDecompressor_2__DOT__tmp_jImm_1;
        SData/*12:0*/ fetch_unit__DOT__rvcDecompressor_2__DOT__bImm;
        SData/*11:0*/ fetch_unit__DOT__rvcDecompressor_3__DOT__tmp_tmp_ret_inst;
        SData/*11:0*/ fetch_unit__DOT__rvcDecompressor_3__DOT__tmp_ret_inst_9;
        SData/*11:0*/ fetch_unit__DOT__rvcDecompressor_3__DOT__tmp_ret_inst_10;
        SData/*11:0*/ fetch_unit__DOT__rvcDecompressor_3__DOT__addi5spnImm;
        SData/*11:0*/ fetch_unit__DOT__rvcDecompressor_3__DOT__lwImm;
        SData/*11:0*/ fetch_unit__DOT__rvcDecompressor_3__DOT__ldImm;
        SData/*11:0*/ fetch_unit__DOT__rvcDecompressor_3__DOT__addImm;
        SData/*9:0*/ fetch_unit__DOT__rvcDecompressor_3__DOT__tmp_jalImm_1;
        SData/*14:0*/ fetch_unit__DOT__rvcDecompressor_3__DOT__tmp_luiImm_1;
        SData/*11:0*/ fetch_unit__DOT__rvcDecompressor_3__DOT__addi16spImm;
        SData/*9:0*/ fetch_unit__DOT__rvcDecompressor_3__DOT__tmp_jImm_1;
        SData/*12:0*/ fetch_unit__DOT__rvcDecompressor_3__DOT__bImm;
        VL_OUT(ibus_cmd_payload_address,31,0);
        VL_OUT(if2id_itf_0_instr_data,31,0);
        VL_OUT(if2id_itf_0_instr_pc,31,0);
        VL_OUT(if2id_itf_1_instr_data,31,0);
        VL_OUT(if2id_itf_1_instr_pc,31,0);
        VL_IN(pcJumpTarget_payload,31,0);
        VL_IN(pcPredicted_payload,31,0);
        IData/*31:0*/ fetch_unit__DOT__ibus_cmd_payload_address;
        IData/*31:0*/ fetch_unit__DOT__if2id_itf_0_instr_data;
        IData/*31:0*/ fetch_unit__DOT__if2id_itf_0_instr_pc;
        IData/*31:0*/ fetch_unit__DOT__if2id_itf_1_instr_data;
        IData/*31:0*/ fetch_unit__DOT__if2id_itf_1_instr_pc;
        IData/*31:0*/ fetch_unit__DOT__pcJumpTarget_payload;
        IData/*31:0*/ fetch_unit__DOT__pcPredicted_payload;
        IData/*31:0*/ fetch_unit__DOT__rvcDecompressor_2_i;
        IData/*31:0*/ fetch_unit__DOT__rvcDecompressor_3_i;
        IData/*31:0*/ fetch_unit__DOT__addressFifo_io_pop_payload;
        IData/*31:0*/ fetch_unit__DOT__addressFifo_io_head;
        IData/*31:0*/ fetch_unit__DOT__rvcDecompressor_2_decompInstr_inst;
        IData/*31:0*/ fetch_unit__DOT__rvcDecompressor_3_decompInstr_inst;
        IData/*31:0*/ fetch_unit__DOT__tmp_if2id_itf_0_instr_pc;
        IData/*31:0*/ fetch_unit__DOT__tmp_if2id_itf_0_instr_pc_1;
        IData/*31:0*/ fetch_unit__DOT__tmp_if2id_itf_1_instr_pc;
        IData/*31:0*/ fetch_unit__DOT__tmp_if2id_itf_1_instr_pc_1;
        IData/*31:0*/ fetch_unit__DOT__tmp_if2id_itf_1_instr_pc_2;
        IData/*31:0*/ fetch_unit__DOT__pc;
        IData/*31:0*/ fetch_unit__DOT__default_next_pc;
    };
    struct {
        IData/*31:0*/ fetch_unit__DOT__real_instr_0;
        IData/*31:0*/ fetch_unit__DOT__real_instr_1;
        IData/*31:0*/ fetch_unit__DOT__addressFifo__DOT__io_push_payload;
        IData/*31:0*/ fetch_unit__DOT__addressFifo__DOT__io_pop_payload;
        IData/*31:0*/ fetch_unit__DOT__addressFifo__DOT__io_head;
        IData/*31:0*/ fetch_unit__DOT__addressFifo__DOT__tmp_readed;
        IData/*31:0*/ fetch_unit__DOT__addressFifo__DOT__vec_0;
        IData/*31:0*/ fetch_unit__DOT__addressFifo__DOT__vec_1;
        IData/*31:0*/ fetch_unit__DOT__addressFifo__DOT__vec_2;
        IData/*31:0*/ fetch_unit__DOT__addressFifo__DOT__vec_3;
        IData/*31:0*/ fetch_unit__DOT__addressFifo__DOT__vec_4;
        IData/*31:0*/ fetch_unit__DOT__addressFifo__DOT__vec_5;
        IData/*31:0*/ fetch_unit__DOT__addressFifo__DOT__readed;
        IData/*31:0*/ fetch_unit__DOT__rvcDecompressor_2__DOT__i;
        IData/*31:0*/ fetch_unit__DOT__rvcDecompressor_2__DOT__decompInstr_inst;
        IData/*31:0*/ fetch_unit__DOT__rvcDecompressor_2__DOT__tmp_ret_inst_1;
        IData/*31:0*/ fetch_unit__DOT__rvcDecompressor_2__DOT__ret_inst;
        IData/*20:0*/ fetch_unit__DOT__rvcDecompressor_2__DOT__jalImm;
        IData/*31:0*/ fetch_unit__DOT__rvcDecompressor_2__DOT__luiImm;
        IData/*20:0*/ fetch_unit__DOT__rvcDecompressor_2__DOT__jImm;
        IData/*31:0*/ fetch_unit__DOT__rvcDecompressor_2__DOT__tmp_ret_inst;
        IData/*31:0*/ fetch_unit__DOT__rvcDecompressor_3__DOT__i;
        IData/*31:0*/ fetch_unit__DOT__rvcDecompressor_3__DOT__decompInstr_inst;
        IData/*31:0*/ fetch_unit__DOT__rvcDecompressor_3__DOT__tmp_ret_inst_1;
        IData/*31:0*/ fetch_unit__DOT__rvcDecompressor_3__DOT__ret_inst;
        IData/*20:0*/ fetch_unit__DOT__rvcDecompressor_3__DOT__jalImm;
        IData/*31:0*/ fetch_unit__DOT__rvcDecompressor_3__DOT__luiImm;
        IData/*20:0*/ fetch_unit__DOT__rvcDecompressor_3__DOT__jImm;
        IData/*31:0*/ fetch_unit__DOT__rvcDecompressor_3__DOT__tmp_ret_inst;
        IData/*31:0*/ __VstlIterCount;
        IData/*31:0*/ __VicoIterCount;
        IData/*31:0*/ __VactIterCount;
        VL_IN64(ibus_rsp_payload_rdata,63,0);
        QData/*63:0*/ fetch_unit__DOT__ibus_rsp_payload_rdata;
        QData/*32:0*/ fetch_unit__DOT__instrFifo_io_push_0_payload;
        QData/*32:0*/ fetch_unit__DOT__instrFifo_io_push_1_payload;
        QData/*32:0*/ fetch_unit__DOT__instrFifo_io_push_2_payload;
        QData/*32:0*/ fetch_unit__DOT__instrFifo_io_push_3_payload;
        QData/*32:0*/ fetch_unit__DOT__instrFifo_io_pop_0_payload;
        QData/*32:0*/ fetch_unit__DOT__instrFifo_io_pop_1_payload;
        QData/*32:0*/ fetch_unit__DOT__tmp_io_push_0_payload;
        QData/*32:0*/ fetch_unit__DOT__tmp_io_push_1_payload;
        QData/*32:0*/ fetch_unit__DOT__tmp_io_push_2_payload;
        QData/*32:0*/ fetch_unit__DOT__tmp_io_push_3_payload;
        QData/*32:0*/ fetch_unit__DOT__instr_slices_0_payload;
        QData/*32:0*/ fetch_unit__DOT__instr_slices_1_payload;
        QData/*32:0*/ fetch_unit__DOT__instr_slices_2_payload;
        QData/*32:0*/ fetch_unit__DOT__instr_slices_3_payload;
        QData/*55:0*/ fetch_unit__DOT__tmp_2_string;
        QData/*55:0*/ fetch_unit__DOT__tmp_3_string;
        QData/*55:0*/ fetch_unit__DOT__tmp_4_string;
        QData/*55:0*/ fetch_unit__DOT__tmp_5_string;
        QData/*32:0*/ fetch_unit__DOT__instrFifo__DOT__io_push_0_payload;
        QData/*32:0*/ fetch_unit__DOT__instrFifo__DOT__io_push_1_payload;
        QData/*32:0*/ fetch_unit__DOT__instrFifo__DOT__io_push_2_payload;
        QData/*32:0*/ fetch_unit__DOT__instrFifo__DOT__io_push_3_payload;
        QData/*32:0*/ fetch_unit__DOT__instrFifo__DOT__io_pop_0_payload;
        QData/*32:0*/ fetch_unit__DOT__instrFifo__DOT__io_pop_1_payload;
        QData/*32:0*/ fetch_unit__DOT__instrFifo__DOT__tmp_readedVec_0;
        QData/*32:0*/ fetch_unit__DOT__instrFifo__DOT__tmp_readedVec_1;
        QData/*32:0*/ fetch_unit__DOT__instrFifo__DOT__vec_0;
        QData/*32:0*/ fetch_unit__DOT__instrFifo__DOT__vec_1;
        QData/*32:0*/ fetch_unit__DOT__instrFifo__DOT__vec_2;
        QData/*32:0*/ fetch_unit__DOT__instrFifo__DOT__vec_3;
    };
    struct {
        QData/*32:0*/ fetch_unit__DOT__instrFifo__DOT__vec_4;
        QData/*32:0*/ fetch_unit__DOT__instrFifo__DOT__vec_5;
        QData/*32:0*/ fetch_unit__DOT__instrFifo__DOT__vec_6;
        QData/*32:0*/ fetch_unit__DOT__instrFifo__DOT__vec_7;
        QData/*32:0*/ fetch_unit__DOT__instrFifo__DOT__vec_8;
        QData/*32:0*/ fetch_unit__DOT__instrFifo__DOT__vec_9;
        QData/*32:0*/ fetch_unit__DOT__instrFifo__DOT__vec_10;
        QData/*32:0*/ fetch_unit__DOT__instrFifo__DOT__vec_11;
        QData/*32:0*/ fetch_unit__DOT__instrFifo__DOT__vec_12;
        QData/*32:0*/ fetch_unit__DOT__instrFifo__DOT__vec_13;
        QData/*32:0*/ fetch_unit__DOT__instrFifo__DOT__readedVec_0;
        QData/*32:0*/ fetch_unit__DOT__instrFifo__DOT__readedVec_1;
    };
    VlTriggerVec<1> __VstlTriggered;
    VlTriggerVec<1> __VicoTriggered;
    VlTriggerVec<2> __VactTriggered;
    VlTriggerVec<2> __VnbaTriggered;

    // INTERNAL VARIABLES
    Vtop__Syms* const vlSymsp;

    // PARAMETERS
    static constexpr CData/*1:0*/ fetch_unit__DOT__RVL = 0U;
    static constexpr CData/*1:0*/ fetch_unit__DOT__RVH = 1U;
    static constexpr CData/*1:0*/ fetch_unit__DOT__RVC = 2U;
    static constexpr CData/*1:0*/ fetch_unit__DOT__INVALID = 3U;

    // CONSTRUCTORS
    Vtop___024root(Vtop__Syms* symsp, const char* v__name);
    ~Vtop___024root();
    VL_UNCOPYABLE(Vtop___024root);

    // INTERNAL METHODS
    void __Vconfigure(bool first);
} VL_ATTR_ALIGNED(VL_CACHE_LINE_BYTES);


#endif  // guard
